### ISSUE TITLE
<importOrder><order> is ignored

### ISSUE THREAD

**Issue by iNikem** [diffplug/spotless#1000]
Here is a demo project demonstrating my problem: https://github.com/iNikem/spotless

It seems like `<importOrder><order>` configuration is ignored. I have configured a specific order, but when I run `mvn spotless:check` or `mvn spotless:apply` I get a behaviour like default alphabetical order is requested.

```
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 11.0.12, vendor: BellSoft, runtime: /Users/nsalnikovtarnovski/.sdkman/candidates/java/11.0.12-librca
Default locale: en_EE, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
```

Spotless version 2.17.4

**Comment by nedtwigg** [comment]
Try swapping the order of `google-java-format` vs `importOrder`. Spotless is a series of steps, probably the GJF step is wiping out the results of the importOrder.
