### ISSUE TITLE
Task 'ide' not found in root project 'spotless'

### ISSUE THREAD

**Issue by korthout** [diffplug/spotless#1007]
Hi all 👋  I'm new here and would love to start contributing, but I ran into the following while setting up the IDE for development.

The [CONTRIBUTING.md](https://github.com/diffplug/spotless/blob/main/CONTRIBUTING.md#contributing-to-spotless) guide mentions twice to run `gradlew ide` to setup the Eclipse IDE for development. But this results in the following error message:

```
./gradlew ide

FAILURE: Build failed with an exception.

* What went wrong:
Task 'ide' not found in root project 'spotless'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 589ms
```

Perhaps the guide is out of date, but I'd like to know how to get started. Generally, I code in IntelliJ-IDEA, but I don't mind having to switch to Eclipse for this. I'm also not used to using gradle (only maven), so perhaps I just do something wrong 😄 

## Context
- macOS 12.0.1
- Gradle 6.6
- db06b285822ee036289a3db1def5216c76891846

**Comment by nedtwigg** [comment]
Thanks for noticing this! We removed the `ide` task in #981 but I forgot to update the contributing guide. Maybe that can be your first PR 😉 .  I am now developing Spotless using IntelliJ, importing as a Gradle project.

**Comment by korthout** [comment]
Thanks for the quick reply @nedtwigg. 

>Maybe that can be your first PR 

Sounds great. Should I just remove the references to the `ide` task or should I nudge users towards IntelliJ?

I actually have a bigger topic I'd like to add. Should I open a new issue for it, to discuss it there or just open a pull request?

**Comment by nedtwigg** [comment]
Oh, and re: new markdown formatter:

- if your plan is simple, e.g. compatibility shims for FooFormatter, then I would just open a PR
- if your plan is complicated, e.g. write a new markdown formatter that lives inside the Spotless repository, then I would discuss the plan in an issue first

**Comment by korthout** [comment]
@nedtwigg Thanks for the replies. I've opened #1008 regarding the CONTRIBUTING guide 🎉 

I'll also open a PR for the new formatter which is mostly just compatibility code. We can discuss details in the upcoming PR 👍
