### ISSUE TITLE
6.0.2 -> 6.0.4: Not building project

### ISSUE THREAD

**Issue by SteinerOk** [diffplug/spotless#1026]
If you are submitting a **bug**, please include the following:

After updating the plug-in from version 6.0.2 to version 6.0.4, I get the following error, when I get drunk, build an android application:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot change attributes of dependency configuration ':app:kapt' after it has been resolved
```
No more changes were made, and when rolled back to 6.0.2, everything is going to be fine.
- [ ] Gradle 7.3.1, AGP 7.0.4
- [ ] Updating 6.0.2 to 6.0.4
- [ ] MacOS 12.0.1 (21A559)

**Comment by nedtwigg** [comment]
Interesting! This seems similar to #1024, where a change in when Spotless resolves dependencies is trickling through to other tasks unrelated to Spotless...

**Comment by nedtwigg** [comment]
Should be fixed in `6.1.0`, please reopen if the issue persists.

**Comment by LloydBlv** [comment]
I'm still running into this issue, with spotless 6.8.0 and ktlint 0.46.1, gradle: 7.2.1

**Comment by ininmm** [comment]
Still have the issue when I upgrade spotless from `5.8.2` to `6.11.0` and ktlint from `0.40.0` to `0.45.2`.
Current gradle is `7.4` with kotlin `1.7.10`.
