### ISSUE TITLE
Spotless configuration on Angular Project

### ISSUE THREAD

**Issue by samirsahoo** [diffplug/spotless#1029]
Hi

I would like to configure Spotless for an Angular Project (Checking the code format for TypeScript & HTML / CSS)
No maven or gradle project. With the npm build I should able to verify and fix the code format issue.

Could you please let me know how I can do this using Spotless.

Thanks in advance for your help & support !

Regards,
Samir

**Comment by nedtwigg** [comment]
You're going to need either Gradle or Maven in order to run Spotless. Here's a good example using Gradle.

https://github.com/mytakedotorg/mtdo/blob/50edf1a2e52e274fff1b798e15cb55c22adf73a6/client/build.gradle#L4-L21
