### ISSUE TITLE
Gradle feature request: API to run spotless on a single file

### ISSUE THREAD

**Issue by skissane** [diffplug/spotless#1033]
I have a Gradle build which includes some custom tasks. These tasks are written in Groovy (the Groovy code for them is embedded in the build script), and they generate output files which are checked into git. I'd like to invoke `spotlessApply`, just on those files, using the project's Spotless configuration.

At first I tried making `spotlessApply` a `finalizedBy` task of my custom task, but it was slow (because it was processing all the files instead of just the file I modified), plus it would pointlessly run even if my custom task failed. 

I think the ideal solution would be if the `SpotlessExtension` class had a method `public void applyFile(File file)`. And then my custom Gradle task could just do `project.spotless.applyFile(file)` to effectively run `spotlessApply` on that file. I think being able to invoke spotlessApply from within the code of my custom task, instead of as a separate task, would make things simpler.

Since that doesn't exist, I created a horrible evil hack to do the same thing:
```
import java.lang.reflect.Method
import java.lang.reflect.Field
import java.lang.reflect.InvocationTargetException
import org.gradle.internal.extensibility.DefaultExtraPropertiesExtension

rootProject.ext.spotlessFile = { File file -> 
    ClassLoader cldr = rootProject.buildscript.classLoader
    Class spotlessTask = cldr.loadClass("com.diffplug.gradle.spotless.SpotlessTask")
    long start = System.currentTimeMillis()

    rootProject.ext.spotlessIdeHook = file.absolutePath

    PrintStream ignored = new PrintStream(new ByteArrayOutputStream())
    OutputStream savedOut = System.out
    OutputStream savedErr = System.err
    System.setOut(ignored)
    System.setErr(ignored)
    try {
        Class clsIdeHook = cldr.loadClass("com.diffplug.gradle.spotless.IdeHook")
        Method performHook = clsIdeHook.getDeclaredMethod("performHook", spotlessTask)
        performHook.accessible = true
        rootProject.tasks.findAll { spotlessTask.isInstance(it) }.each {
            try { performHook.invoke(null, [it].toArray()) }
            catch (InvocationTargetException ex) { throw ex.getCause() }
        }

        Field storageField = DefaultExtraPropertiesExtension.getDeclaredField("storage")
        storageField.accessible = true
        Map storage = storageField.get(rootProject.ext)
        storage.remove("spotlessIdeHook")
    } finally {
        System.setOut(savedOut)
        System.setErr(savedErr)
    }
}
```

Obviously this is really bad, in that it depends on internals of both Gradle and Spotless which could change at any time. (Maybe the bit at the end in which I remove the project extension property isn't really necessary, but I was worried that leaving `spotlessIdeHook` set, even if just to `null`, might break something later in the build, and Gradle has no public API to delete an extension property.)

But, putting that badness aside, it allows me to just do `rootProject.ext.spotlessApply(project.file("my/generated/file.json"))`

**Comment by nedtwigg** [comment]
We have an existing feature (not well-documented) along these lines:

https://github.com/diffplug/spotless/blob/27820f00d58eef87cea8df8ac388a0881d46ab95/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L781-L808

And here is an example of it in operation:

https://github.com/diffplug/blowdryer-diffplug/blob/c7c8b3d0025a3da4032c9743ea2432c5c654ab5e/src/main/resources/spotless/freshmark.gradle#L42-L51

Do you think this could work for your use-case?

I see the appeal of "ignore performance, just call the method". But supporting that means that we have to give up autonomy over when we resolve formatter dependencies (currently we don't need to resolve them until task execution time, and we have full control over that). We've got quite a few outstanding issue related to "when is it okay to resolve these deps", so I'm wary to add more constraints to our ability to solve that problem.

**Comment by nedtwigg** [comment]
Happy to discuss further now or in the future, I'll reopen if we can establish a clear need for a new API which is unmet by the existing `createIndependentApplyTask`.
