### ISSUE TITLE
eclipse formatting issue

### ISSUE THREAD

**Issue by guai** [diffplug/spotless#104]
Hi guys
This isn't actually a spotless issue. I just need help
I've found a formatter issue in eclipse [here it is](https://bugs.eclipse.org/bugs/show_bug.cgi?id=510431)
Eclipse formatter does not indent nested ifs right when braces omitted.
And noone reacted for 3 monthes there
Maybe someone here is in contact with eclipse team or knows how to hurry them up...
I'm writing here cause it affects spotless quality too...

**Comment by nedtwigg** [comment]
Sorry, we don't have any special connection to the Eclipse formatter team.

I can say that your bug in the eclipse bugtracker needs to include the formatter config file that you are using.  The easier it is for the eclipse team to duplicate, the  better your chances of it getting fixed.

One way to make a reproducible testcase is to make something like this on github, and link to it in your bug report.

```
gradlew
build.gradle (just the spotless plugin, with just the eclipse formatter)
src/main/java/formatterbug/YourExample.java
formatterProps.xml
```
