### ISSUE TITLE
Spotless Gradle v6.0.3 causes SonarQube analysis to stop progressing

### ISSUE THREAD

**Issue by jamietanna** [diffplug/spotless#1042]
GitHub Actions does not seem to be happy when running Spotless Gradle v6.0.3 and SonarQube 3.3, and leads to the build timing out.

| Spotless Gradle | GitHub Actions | Commit | Success | 
| ---|---|---|---|
| v6.0.1 | https://github.com/co-cddo/federated-api-model/actions/runs/1588436514 | https://github.com/co-cddo/federated-api-model/commit/09e82435056a6d35b1902b2d8fcf63f9b6de09d8 | :heavy_check_mark:  |
| v6.0.2 | https://github.com/co-cddo/federated-api-model/actions/runs/1588482224 | https://github.com/co-cddo/federated-api-model/commit/4b949746eca16683be00fa5514c2286243adbc82 | :heavy_check_mark: |
| v6.0.3 | https://github.com/co-cddo/federated-api-model/actions/runs/1588491781 | https://github.com/co-cddo/federated-api-model/commit/c6fca4af3dded85012ea4e01ce231a489d53999a |  ❌ |
| v6.0.5 | https://github.com/co-cddo/federated-api-model/actions/runs/1591121636 | | ❌ |

[See `--info` logs for v6.0.3's `./gradlew sonarqube`](https://github.com/co-cddo/federated-api-model/actions/runs/1588576394)

**Comment by nedtwigg** [comment]
I believe this will be fixed by #1039 to be released later in `6.1.0`.

**Comment by nedtwigg** [comment]
Should be fixed in `6.1.0`, please reopen if the issue persists.

**Comment by jamietanna** [comment]
Thanks Ned, that solved it https://github.com/co-cddo/federated-api-model/pull/45
