### ISSUE TITLE
Add `group = "verification"` to all Gradle tasks

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [diffplug/spotless#1050]
Some Spotless tasks belong to `other`, I think some of them (or all) should belong to `verification`. For example, all Kotlin spotless tasks are under `other` (`spotlessKotlinApply/Check/Diagnose`).

**Comment by nedtwigg** [comment]
Good call! PR's welcome.

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle 6.5.0`.
