### ISSUE TITLE
Using spotless in an offline gradle build

### ISSUE THREAD

**Issue by jmini** [diffplug/spotless#1067]
I am not sure if my problem is specific to spotless or if I am not using Gradle correctly

I have a Gradle build where the Spotless plugin is configured.

Now I am working on a setup where I pre-fetch all my dependencies in order to run it later without internet access.

Gradle version: 7.3.1
Spotless version: 6.1.0

In order to work offline, my approach is to create a Gradle cache by resolving all configurations of all projects defined in my build. Next I use `./gradlew build` in a context where I do not have internet access. I can add the (`--offline` flag so that Gradle even does not try to connect to the internet, but this is not necessary)

My build is failing, because the task `spotlessJava` can not find the dependency `com.google.googlejavaformat:google-java-format:1.7`.

```
> Task :spotlessJava FAILED
You need to add a repository containing the '[com.google.googlejavaformat:google-java-format:1.7]' artifact in 'build.gradle'.
E.g.: 'repositories { mavenCentral() }'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessJava'.
> Cannot add a configuration with name 'spotless1972418317' as a configuration with that name already exists.
```

Complete log:
[log.txt](https://github.com/diffplug/spotless/files/7813077/log.txt)

I can probably modify my script that creates the cache to add the missing dependency, but I was wondering if there is a way to let the spotless plugin fetch the dependencies in advance.

**Comment by nedtwigg** [comment]
> I can probably modify my script that creates the cache to add the missing dependency

As long as you call either `spotlessApply` or `spotlessCheck` while you have an internet connection, then your cache will have all the deps you need.

For the purpose of your script, the problem with `apply` is that it might change your working tree, and the problem with `check` is it might fail...

Your best option is probably `spotlessDiagnose`. That task is only used for diagnosing [idempotence problems](https://github.com/diffplug/spotless/blob/main/PADDEDCELL.md), but it will still download all required deps.
