### ISSUE TITLE
new line difference between linux and windows breaks spotlessCheck

### ISSUE THREAD

**Issue by regrog** [diffplug/spotless#107]
I have this simple configuration:

```
	spotless {
		format 'misc', {
			target '**/*.gradle

			trimTrailingWhitespace()
			indentWithTabs()
		}
		encoding 'UTF-8'
	}
```

I'm using linux and when I execute spotlessApply it eventually changes every new line in gradle files.
The same happens when a colleague that use windows 10 executes the task.
We have a jenkins installed in a linux server that executes builds and when my colleague delivers any gradle file modified by spotless, the build fails.
In linux the new line separator is 'LF' while in windows it's composed by 'CR' and 'LF'. We are aware of that but the task spotlessApply has different behavior in windows and linux that breaks the build during spotlessCheck in different OS environment.

Thanks for the help!

**Comment by jbduncan** [comment]
Have you tried switching `trimTrailingWhitespace()` and `indentWithTabs()`?

What might be happening is that due to the order of those statements, Spotless is trimming whitespace before it converts spaces to tabs, which may be causing funny things to happen.

**Comment by jbduncan** [comment]
Can you provide a minimal, complete and verifiable example? (https://stackoverflow.com/help/mcve)

**Comment by regrog** [comment]
Damn!
My source control considered the file as binary and not as plain text with Platform separator, I figured it out because I was unable to create a verifiable example an that was the cause!
Someone delivered something wrong!
Sorry for that, and thanks anyway :D

**Comment by jbduncan** [comment]
No problem! Glad you're managed to find the source of the error. :)
