### ISSUE TITLE
`indentWithTabs` ought to preserve C-style multiline comments

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#1070]
As noted [here](https://github.com/diffplug/spotless/issues/81#issuecomment-1002952352), our `indentWithTabs` space has some surprising behavior when used with C-style multiline comments, for example:

```groovy
/**
 * A simple greeting task.
 */
abstract class GreetingTask extends DefaultTask {}
```

Gets errored out because Spotless dumps the leading spaces

```diff
/**
-·*·A·simple·greeting·task.
-·*/
+*·A·simple·greeting·task.
+*/
```

A hard limitation is that the `indentWithTabs` step can't know what language it is indenting. But it is pretty easy to detect that the leading whitespace of a line was terminated by a `*`, and then note that the indentation had one more space than expected, and just preserve that space.

You would detect that the first non-whitespace character is a `*` here to set `boolean mightBeMultilineComment = true/false`.

https://github.com/diffplug/spotless/blob/b3a6e369245bb6b10ef2db89e54294a5cdb59f49/lib/src/main/java/com/diffplug/spotless/generic/IndentStep.java#L88-L102

And then do some remainder math here to add an extra space if necessary.

https://github.com/diffplug/spotless/blob/b3a6e369245bb6b10ef2db89e54294a5cdb59f49/lib/src/main/java/com/diffplug/spotless/generic/IndentStep.java#L111-L115

I don't plan to implement this, but I'm happy to merge a PR for this (current test is [here](https://github.com/diffplug/spotless/blob/main/testlib/src/test/java/com/diffplug/spotless/generic/IndentStepTest.java)).

**Comment by nedtwigg** [comment]
@sormuras was nice enough to contribute something similar to this back in #82, but I rejected it at that time as a breaking change. The key change in scope that I believe makes this a `### Fixed` rather than a `**BREAKING CHANGE**` is:

- detects that first non-whitespace characters is `*`
- then and only then it will permit a *single* extra space character to persist

**Comment by vpavic** [comment]
I opened #1072 to address this.

The proposed solution does this:

> * detects that first non-whitespace characters is `*`
> * then and only then it will permit a _single_ extra space character to persist

While also handling the case with the missing leading space on a multi-line comment, so something like this:

```java
/**
* test
 * test
  * test
   * test
 */
class MyClass {
	/**
	* test
	 * test
	  * test
	   * test
	 */
	void myMethod() {}
}
```

Should end up properly formatted to:

```java
/**
 * test
 * test
 * test
 * test
 */
class MyClass {
	/**
	 * test
	 * test
	 * test
	 * test
	 */
	void myMethod() {}
}
```
