### ISSUE TITLE
Removed Used import

### ISSUE THREAD

**Issue by kjayachandra2000** [diffplug/spotless#1085]
Hi Team,
When trying to execute `./gradlew clean spotlessApply`, it's removing one of the used imports.

The project is on Java 8, but my local machine is on Java 11.
when executed spotlessApply
Removed `import lombok.var;`

if I change my local JAVA version to 8, then spotless works fine. can someone please help me here to force spotless to run only on java 8 or exclude `import lombok.var` from the unused import.

**Version**
Spotless: 6.0.5
Gradle: 6.8.3
Java: 8

**Comment by nedtwigg** [comment]
This is probably a bug in GoogleJavaFormat, and which version of that is being used depends on what JVM you are running for the formatter:

https://github.com/diffplug/spotless/blob/bb27596ed33d3029202c94940943926bba0e4229/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java#L96

You could do something [along these lines](https://docs.gradle.org/current/javadoc/org/gradle/api/JavaVersion.html?_ga=2.143110709.1412523459.1641842398-1295944823.1627561556):

```gradle
spotless {
  java {
    if (JavaVersion.current().isJava8()) {
      removeUnusedImports()
    }
    ...
```

**Comment by kjayachandra2000** [comment]
Thanks @nedtwigg, this was very helpful
but I have used the below snippet to enforce spotless to run on `java 8` regardless of local JDK version
```
spotless {
    java {
        if (JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_1_8)) {
            importOrder()
            indentWithSpaces(4)
            endWithNewline()
            trimTrailingWhitespace()
            custom 'trim extra newlines', { it.replace('\n\n\n', '\n\n') }
        }
    }
}
```
