### ISSUE TITLE
Gradle ecosystem is down because of jcenter / bintray

### ISSUE THREAD

**Issue by four2five** [diffplug/spotless#1088]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] gradle or maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

When running a build of our project that uses spotless (which we love), I occasionally see this error come up:
`   > Could not resolve org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r.
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.2 > com.diffplug.spotless:spotless-plugin-gradle:6.1.2
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.2 > com.diffplug.spotless:spotless-plugin-gradle:6.1.2 > com.diffplug.spotless:spotless-lib-extra:2.21.2
      > Could not resolve org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r.
         > Could not get resource 'https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/5.13.0.202109080827-r/org.eclipse.jgit-5.13.0.202109080827-r.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/eclipse/jgit/org.eclipse.jgit/5.13.0.202109080827-r/org.eclipse.jgit-5.13.0.202109080827-r.pom'. Received status code 502 from server: Bad Gateway`

It looks like bintray as deprecated last spring: https://plugins.gradle.org/docs/bintray

We're using gradle 6.8.3, spotless 6.1.2 running on Intel OS X 11.5.2 with open jdk 8 version `OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)`

our spotless configuration block is pretty elementary:
`spotless {
    java {
        targetExclude("**/SerializationTestTemplate.java")
        googleJavaFormat()
    }
}`

wondering if spotless taking a dependency on a newer version of that eclipse library may help? Like maybe that isn't somehow connected to Bintray? To be honest, I'm out of my depth here. Not sure how our build process is ending up trying to contact Bintray.

**Comment by four2five** [comment]
this just started today, so looks like something shifted out from under spotless.

**Comment by nedtwigg** [comment]
I think it's the whole Gradle ecosystem 😭 https://discuss.gradle.org/t/plugins-redirecting-to-jcenter/41909/3

Current status: https://status.gradle.com/

I'll close this issue when status.gradle.com and my first-hand experience says it's fixed.

**Comment by four2five** [comment]
oh, wow. It never dawned on me that it could be something at that level. 
Apologies for the noise on your project.

**Comment by nedtwigg** [comment]
JCenter is back up, and Gradle is working on mirroring it to `plugins.gradle.org`.
