### ISSUE TITLE
Plug-in name problem

### ISSUE THREAD

**Issue by tonycody** [diffplug/spotless#1091]
https://plugins.jetbrains.com/plugin/18321-spotless-gradle

Isn't this a plug-in for the IDE? Why do names include Gradle? Isn't that strange? Only Gradle projects can use ~

**Comment by jbduncan** [comment]
I think it's named like that because so far it only supports running Spotless instructions defined in Gradle projects.

Maven might be on the plugin creator's roadmap, but I'm not sure.
