### ISSUE TITLE
Java: //NOSONAR is reformatted to // NOSONAR => Sonarqube server does recognize it and does not ignore issue

### ISSUE THREAD

**Issue by LGX9** [diffplug/spotless#1092]
Spotless Version: 2.17.4, Maven Version: 2.17.4
With the comment //NOSONAR at the end of the line you can mark a certain code line in Java not to be an issue for sonarqube.
But spotless reformats that to // NOSONAR and it's not working anymore, to a certain degree you can get around with the trick /*- //NOSONAR */ but sometimes this is moved into a new line it is not working either.
You should really have a possibility to ignore certain lines from formatting in Java

**Comment by jbduncan** [comment]
Which formatter are you using? google-java-format, by any chance? If so, that's a generally known problem with that formatter, as it always puts a space between the start of a comment and the comment's text.

Try using the [`spotless:off` and `spotless:on`](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson) tags, and let us know if that solves the problem.

I hope this helps!

**Comment by nedtwigg** [comment]
I would use the [replace step](https://github.com/diffplug/spotless/tree/main/plugin-maven#generic-steps):

```xml
<replace>
  <name>fix nosonar comments</name>
  <search>//NOSONAR</search>
  <replacement>// NOSONAR</replacement>
</replace>
```

Just make sure you specify this step after the other formatter - order matters.

**Comment by LGX9** [comment]
Thank you @jbduncan and @nedtwigg, although I was granted admin rights in the sonarqube project and can now manage these issues using the UI instead of changing the code, I am still very thankful for your tips, which are really practical and helpful for future issues I (or my team ;-)) can encounter with spotless, your tips are really practical and I am sure I can make use of that!
