### ISSUE TITLE
When only running removeUnusedImports files are failing due reasons other than unused imports

### ISSUE THREAD

**Issue by OneGeek** [diffplug/spotless#1104]
If you are submitting a **bug**, please include the following:

### summary of problem
While using the maven plugin with the following configuration to only remove unused imports, files are failing for other reasons
```
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.20.0</version>
    <executions>
        <execution>
            <configuration>
                <java>
                    <removeUnusedImports />
                </java>
            </configuration>
        </execution>
    </executions>
</plugin>
```
The following failure is reported when running mvn spotless:check
```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.20.0:check (default-cli) on project foo-shared: The following files had format violations:
[ERROR] src\main\java\com\foo\shared\api\foo\IFooData.java
[ERROR] @@ -15,10 +15,10 @@
[ERROR] ]*/\r\n
[ERROR] \r\n
[ERROR] -    ProjectStatus getProjectStatus();\n
[ERROR] -    void setProjectStatus(ProjectStatus projectStatus);\n
[ERROR] -    Date getDate();\n
[ERROR] -    void setDate(Date date);\n
[ERROR] +    ProjectStatus getProjectStatus();\r\n
[ERROR] +    void setProjectStatus(ProjectStatus projectStatus);\r\n
[ERROR] +    Date getDate();\r\n
[ERROR] +    void setDate(Date date);\r\n
[ERROR] \r\n
[ERROR] }\r\n
```

I only want unused imports to be removed.

### maven & OS version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Java version: 11.0.8, vendor: Amazon.com Inc.
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by nedtwigg** [comment]
The file in question has windows line endings (`\r\n`) but in the middle of this file are 4 lines that have unix line endings `\n`.

Spotless doesn't care if a file uses windows or unix line endings, but it doesn't support mixing and matching within the same file.

https://github.com/diffplug/spotless/tree/main/plugin-maven#line-endings-and-encodings-invisible-stuff
