### ISSUE TITLE
Support exceptions for multi-line Strings

### ISSUE THREAD

**Issue by MarkusAmshove** [diffplug/spotless#1105]
Hi,

I'm using Spotless via Gradle and configured it to use tabs over spaces in Java source files.

It has spotted some violations which I did fix, but it also shows some (in my opinion) false positives.

For example, I'm heavily utilizing multi-line strings (text blocks) in test code.

For example:

```java
    var source = """
        if 1
            print 2
        endif
    """;
```

The formatting is the following:

```
\tvar source = """
\t\tif 1
\t\t    print 2
\t\tendif
\t""";
```

If I print the string, I get the following:

```
if 1
    print 2
endif
```

so Java trims the `\t` from the text block, which for me means the spaces should be considered as code/string in this case.

The following is not repoted by spotless, so I think it should also work for multiline strings:
```java
System.out.println(
\t"    hello"
);
```

EDIT:

I've found a hint in Gitter and `toggleOffOn('"""', '"""')` seems to work, however I'll leave this issue open for now, maybe this can be built in as a feature :-)

**Comment by nedtwigg** [comment]
You didn't post your configuration block, but I'll make a few points:

Whether you are using `googleJavaFormat()` or `eclipse()` or whatever, Spotless isn't responsible for how it handles multiline strings. We are just a switchboard, and you can file feature requests with whatever formatter you are using.

The `indentWithTabs` step is just a dumb find-replace. That means it can work with any language, but it also means that it doesn't have the grammar to parse whatever multiline string you are using.
