### ISSUE TITLE
Expecting a top level declaration

### ISSUE THREAD

**Issue by WebTiger89** [diffplug/spotless#1108]
When running _spotlessCheck_, ktlint throws following error:

> Step 'ktlint' found problem in 'src\main\kotlin\de\mycompany\android-compose-application.gradle.kts':
5:1 Expecting a top level declaration
com.pinterest.ktlint.core.ParseException: 5:1 Expecting a top level declaration

Configuration in project-level build.gradle.kts:
`configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    format("misc") {
        // define the files to apply misc to
        target("*.gradle", "*.md", ".gitignore")

        // steps to apply to those files
        trimTrailingWhitespace()
        endWithNewline()
    }

    kotlin {
        // by default the target is every '.kt' and '.kts` file in the java sourcesets

        // Cover all '.kt' and '.kts` files
        target(projectDir)

        ktfmt("0.30").dropboxStyle()
        ktlint("0.43.2")
        diktat()
    }
}`

android-compose-application.gradle.kts:
`@file:Suppress("UnstableApiUsage")

package de.mycompany

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}`

My assumption: **ktlint** does not recognize the

> @file:Suppress("UnstableApiUsage")
statement.

Should I file a bug in ktlint repo?

**Comment by nedtwigg** [comment]
There's a difference between Kotlin and KotlinScript. `.gradle.kts` files are script files, so the formatter needs to be setup differently for them.

Notice the difference [in the docs](https://github.com/diffplug/spotless/tree/main/plugin-gradle#kotlin) between `kotlin` and `kotlinGradle`. Also, you probably don't want `ktfmt` *and* `ktlint` *and* `diktat`, you probably want just one of them.
