### ISSUE TITLE
Breaking changes in ktfmt 0.31

### ISSUE THREAD

**Issue by msfjarvis** [diffplug/spotless#1117]
ktfmt 0.31 was [just released](https://github.com/facebookincubator/ktfmt/releases/tag/v0.31) which includes a couple breaking changes for Spotless. Specifically

- [ ] Library usage was updated to make the `format` method no longer be a top-level method. It is now inside the `Formatter` object.
- [ ] The binaries for 0.31 appear to have been published to Maven Central's new S01 infrastructure, which means the dependency needs to be resolved from `https://repo1.maven.org/maven2` as opposed to `https://repo.maven.org/maven2`.

I'm not super familiar with reflection so it might take me a day or two before I can propose a PR for at least the first part of this. Let me know if you'd prefer to do it yourself faster.

**Comment by nedtwigg** [comment]
PR is very welcome, I've got no plans to integrate these changes. If you'd like, you can avoid reflection entirely by following an example from #524. Could do `if (version < 31) { existingCode() } else { newCode() }`

**Comment by msfjarvis** [comment]
Oh that looks much easier, I will try that approach out. Thanks a lot!

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle 6.2.2` and `plugin-maven 2.20.2`.
