### ISSUE TITLE
`SpotlessExtension` should make use of `StandardCharsets` in `setEncoding`

### ISSUE THREAD

**Issue by x80486** [diffplug/spotless#1128]
Since with Java `7.x`, `StandardCharsets` provides constants for common `Charset` objects.

Using the constants is less error prone, and can provide a small performance advantage compared to, for instance, `Charset.forName/1` since no scan across the internal `Charset` caches is needed.

It would be great is `SpotlessExtension.encoding` can be changed/enhanced in that regard.

**Comment by nedtwigg** [comment]
Happy to take a PR for this.

**Comment by x80486** [comment]
I'll take it. I don't know much about this, but as far as I can tell it's just adding another method with the `StandardCharsets` type.
