### ISSUE TITLE
Add built in support for ktlint linting of gradle script kotlin files

### ISSUE THREAD

**Issue by JLLeitschuh** [diffplug/spotless#115]
Currently, the only ktlinting support is for production files.
It would be awesome if you could also configure it to lint any `.gradle.kts` files for [Gradle Script Kotlin](https://github.com/gradle/gradle-script-kotlin)

**Comment by nedtwigg** [comment]
[This is the code](https://github.com/diffplug/spotless/blob/823585cad2b51004836a0684ee7872ad53ca14b0/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinExtension.java#L55-L69) that sets up the default kotlin sources.

It needs tweaking for Gradle Script Kotlin, [Android](https://github.com/diffplug/spotless/issues/111#issuecomment-301557213), and probably for kotlin-js as well.

Setting the target manually is pretty easy, but we'd love a PR which improves the defaults.

**Comment by JLLeitschuh** [comment]
Would you like a new task added or the current one expanded?

Options:
 1. Add more configuration to the `kotlin` block.
 2. Create a new extension `KotlinBuildExtension` that is specific to formatting `build.gradle.kts` files.

Personally, I think option 2 makes more sense as a user may have different configuration for the `kotlin` block on a per-subproject basis while your formatting config for `build.gradle.kts` should be common across all of your files.

**Comment by nedtwigg** [comment]
I think 2 makes the most sense.  Code usually has a copyright notice at the top, and build files usually don't.

**Comment by JLLeitschuh** [comment]
Is there a pre-existing extension that already targets formatting groovy `build.gradle` files?

**Comment by nedtwigg** [comment]
Kinda.  There is a `groovy` extension written by @fvgh, but it's not specific to `build.gradle` files.  Might make sense to use the same approach for `groovy` / `gradleGroovy` and `kotlin` / `gradleKotlin`.  Any thoughts @fvgh?

**Comment by fvgh** [comment]
Sorry for the late response. Till now I was always able to work around the issue since the projects were using sub-projects and I have defined the formatting on all gradle files in the root project, using the `target` definition. I always wanted to make a proposal to extend the registration of all `FormatExtension` in `SpotlessExtension` by a custom name, so that you can specify multiple Groovy extensions with different `target`s.
But `gradleGroovy` as a fixed extension name with a default file pattern is also an option.

**Comment by nedtwigg** [comment]
For now, it looks like we'll have `kotlinGradle` which automatically applies to `*.gradle.kts`, and is otherwise identical in behavior to `kotlin`.  How do you feel about the same for groovy, `groovyGradle` which applies to `*.gradle`, and is otherwise identical to `groovy`?

**Comment by fvgh** [comment]
It is an option.
Drawback is the introduction  of another interface on spotless level.
The benefit is that nobody has to specify file extensions, like `*.gradle.kts` and `*.gradle`, which can be assumed as not modifiable. So the configuration is cleaner.

It worries me that the current solution forces the user to take the restrictions imposed by `parseTarget` in combination with the fixed extension. By allowing multiple configurations of language-specific formats, the user can do what ever he wants.

Just to get a common understanding, I was more thinking about something like:
 ```
groovy {
   /* The nominal config */
}

groovy, 'format-gradle' {
  target '*.gradle'
  /* What ever is necessary */
}
```

I think the `*.gradle` / `parseTarget` approach would currently omit any gradle files in custom directories which I include with `apply from`, so here the user has to specify a custom `target`, right?

Another thing I was once wondering about is how to deal with certain Java files which have a different licence but are in the same project. But I know that this is a rare scenario. Just needed it when I was patching code.

**Comment by nedtwigg** [comment]
[Here is one approach](https://github.com/diffplug/spotless/pull/129#issuecomment-319195321) to this problem.

What limitations in `target` are you worried about?  [The user can pass any FileCollection](https://github.com/diffplug/spotless/blob/6a3f8ad0bff4c5a1cad7691510cd97501e68457e/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L131-L186), so I can't think of any limitations, really.

Re: Java files within a project with a different license,

```
java, 'externalFiles' {
    target 'src/main/java/org/someexternernalpackage/**/*.java'
    ...
}
```

seems like a good idea to me.  But I think `*.gradle` and `*.gradle.kts` are common-enough usecases to earn their own DSL.  There are also subtle differences, e.g. license headers rely on a package statement, which gradle scripts don't have, so it doesn't make sense to support license headers for build scripts.

**Comment by nedtwigg** [comment]
But that's a matter for a new issue :)

**Comment by fvgh** [comment]
That would be a new issue, but quickly done.
Just thought whether in that case the `groovyGradle` and `kotlinGradle` becomes superfluous and many ways to achieve the same goal are just confusing.
But I see that you prefer convention over configuration. I'll provide you with an update :smile: 

I don't think that we should explicitly exclude the license header. It is valid (and I used it for minor things) to define a plugin and/or task within a gradle file. This is when one might also have a licence. The license header is already smart enough to deal with situation by throwing an exception to avoid unintended user configuration.
Agreed?

**Comment by nedtwigg** [comment]
Every `FormatExtension` has `licenseHeader(String header, String delimiter)`.

JavaExtension and KotlinExtension also have `licenseHeader(String header)` where the delimiter has the default value `package `, which works for code, but doesn't work for `build.gradle.kts`.  So that's all I meant by remove `licenseHeader`, just the `package ` specialization. 😃

**Comment by fvgh** [comment]
Ok, I see, my mistake. Agreed.
