### ISSUE TITLE
Delete master branch, google takes you to very outdated documentation

### ISSUE THREAD

**Issue by timja** [diffplug/spotless#1174]
Hi

If you google 'spotless maven plugin' it takes you to the master branch which is very outdated:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/21194782/164173661-3ae87aa0-7b9f-4de2-9b89-ce991257b1b9.png">

Could you delete the master branch please? or some other option?

Ideally the branch would have been renamed not a new one created but likely too late now.

**Comment by nedtwigg** [comment]
Thanks very much for this! Here's what I did:

- rename `main` to `main-temp`
- make `master` the default branch
- rename `master` to `main`

There will be some weirdness merging the existing PRs (which are now against main-temp), but after that it should be better, and we don't have a ton of open PR's anyway.
