### ISSUE TITLE
Add Support For GSK

### ISSUE THREAD

**Issue by napperley** [diffplug/spotless#118]
Support is needed for [GSK](https://github.com/gradle/gradle-script-kotlin) (Gradle Script Kotlin) which is used by some Kotlin projects, and there are some which provide support for it (eg [Spek](http://spekframework.org/docs/latest/#_gradle_kotlin_script)). Currently GSK is at version 0.9.1 so it is expected to stabilise (reach version 1.0) in about roughly 2-3 months (not too far away). Would be nice to have **spotless** support GSK before it reaches 1.0.

**Comment by nedtwigg** [comment]
I believe this is a duplicate of #115, no?

**Comment by napperley** [comment]
@nedtwigg - Yes it is a duplicate. Will the GSK support cover [Kotlin Native](https://github.com/JetBrains/kotlin-native)?

**Comment by nedtwigg** [comment]
Spotless delegates the formatting to [ktlint](https://github.com/shyiko/ktlint).  So whatever ktlint supports, so will Spotless.
