### ISSUE TITLE
Sortpom deleted the first blank line

### ISSUE THREAD

**Issue by longtai-cn** [diffplug/spotless#1187]
## Questions raised

Hello, I use `spotless` to build `sortpom `. I want to ask how to solve the problem of deleting empty lines.

## Reproduction steps

pom

```xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.22.1</version>
    <configuration>
        <pom>
            <sortPom>
                <encoding>UTF-8</encoding>
                <nrOfIndentSpace>4</nrOfIndentSpace>
                <keepBlankLines>true</keepBlankLines>
                <indentBlankLines>true</indentBlankLines>
                <indentSchemaLocation>true</indentSchemaLocation>
                <spaceBeforeCloseEmptyElement>true</spaceBeforeCloseEmptyElement>
                <sortModules>false</sortModules>
                <sortExecutions>false</sortExecutions>
                <expandEmptyElements>false</expandEmptyElements>
            </sortPom>
        </pom>
    </configuration>
</plugin>
```

execute

```shell
mvn spotless:apply
```

## After execution

![image](https://user-images.githubusercontent.com/77398366/165415339-3b5cb5a5-57fc-4431-8117-a25b38b34e0a.png)

## anticipate result

The spaces in the first line are not deleted

**Comment by nedtwigg** [comment]
I believe this is probably the correct behavior for `sortpom`. Should whitespace elements be sorted to the top of the container, or to the bottom? They don't mean anything, so I think the correct behavior for a sort-formatter is to remove them.  We have had similar questions in the past about import sorting, where users wished that whitespace lines could be preserved within an import sorter, but I don't think that makes much sense.

You could get the result you're looking for with (untested):

```xml
<configuration>
  <pom>
    <sortPom>...</sortPom>
    <replace>
      <name>Leading blank line</name>
      <search>--&gt;&#10;$lt;project </search>
      <replacement>--&gt;&#10;&#10;$lt;project </replacement>
    </replace>
    ...
```

**Comment by longtai-cn** [comment]
@nedtwigg Thank you very much for your reply, but it doesn't seem to work.

**Comment by longtai-cn** [comment]
@nedtwigg Hello, I tried to modify the program you gave, and it took effect.

```xml
<replace>
    <name>Leading blank line</name>
    <search>--&gt;&#10;&lt;project </search>
    <replacement>--&gt;&#10;&#10;&lt;project </replacement>
</replace>
```

![image](https://user-images.githubusercontent.com/77398366/165656658-4ed5e331-d2e8-4b9a-881e-0f26db8d03dd.png)

However, this will bring new problems. After the implementation of `mvn spotless: apply`, ` &#10` Will be considered a line feed.

![image](https://user-images.githubusercontent.com/77398366/165656498-11801018-05e3-446e-99ba-e468a5217aa2.png)

Do you have any good suggestions?

**Comment by nedtwigg** [comment]
Ha! That's a funny problem, sort of a Spotless quine, the first that I've seen!

Looks like the `sortPom` step is normalizing `&#10;` into a proper line feed, and I think that is the canonical way to represent a newline, so it's hard to call this a bug.

I suppose it could be a reasonable feature request for sortpom to retain `&#10;` as an escaped entity. But it's also reasonable to say that the point of `sortpom` is to pick an arbitrary standard sorting and not futz about it.

The philosophy behind Spotless is that formatting doesn't matter, so a tool should enforce some arbitrary formatting. If there's a straightforward feature we could add that would help your case, I'd be happy to merge a PR for it so long as it's simple and doesn't add a ton of code or API. But I think this is a minor issue that's not worth more effort.

You could add a `replaceRegex` rule which replaces `\n` with `&#10;` but only within `<search>...</search>` and `replacement` tags, but that's a tricky regex to write...
