### ISSUE TITLE
Add support for typescript-formatter

### ISSUE THREAD

**Issue by simschla** [diffplug/spotless#119]
I'm building a custom spotless rule for formatting typescript files using [typescript-formatter](https://github.com/vvakame/typescript-formatter). This all works well at the moment, however, my custom rule takes rather long, since I need to spawn a system process (using gradle "exec") for every single file. typescript-formatter, however, would have the ability to format a list of files all at once which would tremendously speed up things. It would be nice to have spotless support to do this "all files at once".

my current spotless format rule:

```
File nodeDistBin = (File) fileTree("${rootProject.buildDir}/nodejs").include("**/node").find()

...

    format 'typescript', {
        target fileTree(project.projectDir).include('**/*.ts').minus(EXCLUDED_DIRS)
        bumpThisNumberIfACustomStepChanges 1
        custom 'tsfmt', { String input ->
            String result = ""
            File.createTempFile("typescript-formatter", ".ts").with { File file ->
                deleteOnExit()
                file.write(input, 'UTF-8')
                exec {
                    workingDir "$rootProject.projectDir"
                    executable "${nodeDistBin.absolutePath}"
                    args "node_modules/typescript-formatter/bin/tsfmt", "--replace", "--useTslint", "tslint.json", "${file.absolutePath}"
                }
                result = file.getText('UTF-8')
            }
            return result
        }
        indentWithSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }
```

**Comment by nedtwigg** [comment]
Isn't that incremental checking handy though ;-)

Even if we batched these calls, you'd still be doing filesystem IO per file.  Compare that to the three steps below your custom step `indentWithSpaces`, `trimTrailingWhitespace`, and `endWithNewline` - each step can be composed on top of the previous without any filesystem IO.

Spotless requires each formatter step to be a function that turns a string into a string.  This allows Spotless to protect the user from [all kinds of](https://github.com/diffplug/spotless/blob/master/PADDEDCELL.md) misbehaving formatters, and to efficiently compose multiple formatters.  Changing this model to support batching would be very difficult, and it couldn't help with the filesystem IO part of your performance problem.

The right way to do this would be to create [a new `FormatterStep`](https://github.com/diffplug/spotless/blob/master/CONTRIBUTING.md#how-to-add-a-new-formatterstep) that calls into the node.js as a lib using [j2v8](https://github.com/eclipsesource/J2V8).  If you get this working in your `buildSrc` directory, we'd love to make it a part of spotless core, I'm sure you're not the only one looking for typescript support.

**Comment by simschla** [comment]
@nedtwigg Meanwhile I have a solution for batchprocessing typescript files on initial spotless check, while picking results from previously batch-processed typescript files when actual spotless call is performed.

I would be willing to give the solution using j2v8 a try on my end. It would probably be best to create a new formatter step for this. correct?

In order to be able to use NodeJS embedded in j2v8, I still have to manage a `node_modules` folder for keeping all dependencies and the modules `tsfmt` or `prettier` (as typescript formatting options) themselves. How should I solve that in a generic way?

1. Creating the `node_modules` during build (even when caching) requires a node installation on the machine running spotless. (not an option in my opinion)
2. Somehow figuring out how to use `j2v8` itself for creating the `node_modules`. (probably a dead-end telling from what little I could find on SO or Google on the matter).
3. Creating the `node_modules` on my end and reusing them on spotless run would need a prepared `node_modules` zip file (added to lib-extra?). If the dependencies contain native dependencies that zip would even be needed to be created for all supported platforms.

Suggestions? Ideas?

**Comment by nedtwigg** [comment]
A fourth option:

- shell out to npm to create the node_modules, then use j2v8 to run them

```
public class NpmFormatterStepBuilder {
  List<String> npmDeps;
  String scriptToExecute;

  static class State implements Serializable {
    String scriptToExecute;
    FileSignature nodeModulesContent;
    transient File nodeModulesDir;
  }

}
```

**Comment by simschla** [comment]
> shell out to npm to create the node_modules, then use j2v8 to run them
That was actually what I meant with my first option - it requires to have a matching npm/node installation on the machine running the formatting.

I see a slightly easier way using the gradle wrapper and https://github.com/srs/gradle-node-plugin - this installs a local node/npm on the fly which I can use to create the node_modules without requiring the user to install anything on the system itself.

**Comment by nedtwigg** [comment]
> That was actually what I meant with my first option

Apologies, you stated that very clearly :)

> installs a local node/npm on the fly which I can use to create the node_modules without requiring the user to install anything on the system itself

Gradle requires a JDK on the machine.  Most folks doing typescript or really any frontend dev are going to have npm on their machine.  `gradle-node-plugin` is fantastic, but the auto-download feature has been a pain in the neck for me on CI servers compared to just using a docker image that already has npm installed.  I think us JVM heads want gradle to do all-the-things (reasonable), but people who work primarily in other fields (e.g. frontend) prefer a more conventional approach (also reasonable).

If you build the typescript thing to say "pass me the npm executable to use", then you have options: pass it explicitly, procure it using gradle-node-plugin, or grab it from the path.  I think adding a hard dep on gradle-node-plugin puts you in a corner, especially if you can shrink your surface area pretty easily to just "pass me npm".

Spotless has 4 artifacts: `lib` (no deps), `lib-extra` (a few deps, no build system deps), `plugin-gradle`, and `plugin-maven`.  It's 100% fine to add something that only works in one build system, but ideally users of other build systems can at least have a chance to submit PR's to integrate it into their build system of choice.

**Comment by nedtwigg** [comment]
Great!  We have a similar problem in that we create a bunch of classloaders that need to be closed:

https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/SpotlessCache.java

We can change SpotlessCache to be something more generic, maybe `put(Serializable key, Runnable onClose)`?

Very excited for this improvement - supporting the entire npm ecosystem is a big deal!

**Comment by nedtwigg** [comment]
> 1. I see there is a com.diffplug.spotless.FormatterFunc.Closeable interface, ... I find no usage of the interface in spotless. Is that dead code that should not be used?

Ruh-roh.  I don't know for sure, but sounds like it!  I'll take a deeper look this weekend.

> 2. a new formatter-step "Has a test class named SomeNewStepTest"

I think we can use JUnit categories to mark these.

```java
/** Marker class for tests that need a native NPM to work. */
public static interface NeedsNpm {}

@Category(NeedsNpm.class)
public class SomeNewStepTest {}
```

Then we setup `gradlew test` to exclude `NeedsNpm`, and `gradlew testNpm` will run the tests that require NPM.  If you add me as a collaborator or open a PR then I can push this up sometime this weekend.  The order of priorities:

1) random user clones and runs `gradlew test` shouldn't rely on npm install
2) ideally CI server would run these tests too, but not the end of the world if not (e.g. it would be great if we did CI on windows, but we don't)
3) we can edit [`.travis.yml`](https://github.com/diffplug/spotless/blob/master/.travis.yml) to install an npm for us

> 3. The prettier formatter step is ... able to handle a lot of languages

My inclination is to integrate prettier into `FormatExtension`, so that it's available for all languages, a-la `LicenseHeaderStep`: https://github.com/diffplug/spotless/blob/f622379a4f3b2b952f483e3024ef4d5f6532fa2a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L421-L431

Then it could be used like this:

```gradle
spotless {
  format 'graphQl', {
    target 'src/main/resources/**/*. graphql'
    prettier()
  }
  freshmark {
    target '*.md'
    prettier()
  }
```

This also applies to @fvgh's work on integrating Eclipse's WTP formatters.  I was thinking the same `eclipseWtp()` for `FormatExtension` there, but not sure...

**Comment by nedtwigg** [comment]
Also, can't wait to review code, won't have time til this weekend.  Can you open a PR?  I won't merge till we're ready, but I think it's easier to discuss in that format.

**Comment by nedtwigg** [comment]
This has been resolved since September 2018 :P  Closing Feb 2019.  Thanks again @simschla, great contribution!
