### ISSUE TITLE
Maven Plugin and Eclipse Integration

### ISSUE THREAD

**Issue by lalib** [diffplug/spotless#1199]
Hi, I am using spotless with maven plugin and I am looking for a documentation how to use it via Eclipse. 

Is it possible to use maven plugin with Eclipse? 
I am looking for a way to replace my eclipse formatter key bindings with maven plugin.

**Comment by Emkas** [comment]
Is there a reason why you don't want to use save action in eclipse? You can bind formatting with a save.

Also you can run any maven action just like any other command like `clean package`. Just go in Project Explorer -> Run as -> Maven build... -> add action `spotless:apply`.

**Comment by nedtwigg** [comment]
We also have direct integration with m2e now

- https://github.com/diffplug/spotless/pull/1414

I'm not sure what that means exactly, lol, but we have it!
