### ISSUE TITLE
Four spaces are expected to be added to the empty line of the XML file

### ISSUE THREAD

**Issue by longtai-cn** [diffplug/spotless#1202]
Hello, I use spotless formatting XML file, but I found a problem.

I use [eclipse](https://github.com/diffplug/spotless/tree/main/plugin-maven#eclipse-jdt) to format.

Original:

![image](https://user-images.githubusercontent.com/77398366/167854047-590b5957-4da7-4175-b5e1-ce2cf1c18dc3.png)

Expected:

![image](https://user-images.githubusercontent.com/77398366/167854087-13b2f56b-d59f-4210-9eb9-ea4862dfc3e7.png)

I want to add four spaces to the blank line after formatting. I don't know if there is a way?

**Comment by nedtwigg** [comment]
Look at the replace and replaceRegex rules. Depending on how specific you want to make your build file, you can use `ref="rulesets/xsl/xpath.xml" />\n` as the beginning of your find/replace.

**Comment by longtai-cn** [comment]
@nedtwigg Thank you for your suggestion. I'll check it.
