### ISSUE TITLE
Supporting `buf format`

### ISSUE THREAD

**Issue by andrewparmet** [diffplug/spotless#1207]
The [Buf](https://buf.build/) tool for protobuf recently added the [`buf format`](https://docs.buf.build/format/usage) command. Buf is currently published with a download link on their GitHub release page and to DockerHub. They have an [open issue](https://github.com/bufbuild/buf/issues/154) to publish binaries to Maven Central.

Is there any precedent for adding a binary tool like this as a formatter? It could be supported with a [custom Ivy repository](https://github.com/andrewparmet/buf-gradle-plugin/blob/main/src/main/kotlin/com/parmet/buf/gradle/BufSupport.kt#L27-L57) (for Gradle, at least) if that's something you'd be willing to incorporate.

**Comment by nedtwigg** [comment]
Yes, we have support for two binary tools in Spotless right now, happy to add another one.

https://github.com/diffplug/spotless/blob/21b089f454ed2d50f929af71f1cae52421e32c55/lib/src/main/java/com/diffplug/spotless/python/BlackStep.java#L65-L70

https://github.com/diffplug/spotless/blob/21b089f454ed2d50f929af71f1cae52421e32c55/lib/src/main/java/com/diffplug/spotless/cpp/ClangFormatStep.java#L70-L84

I'm fine with making installation of the `buf` tool a problem for the user (that's how we handle black and clang currently), or it can be automatic.
