### ISSUE TITLE
Replace label replacement rule is invalid

### ISSUE THREAD

**Issue by longtai-cn** [diffplug/spotless#1217]
Hello, please ask a question about replacement.

Now there is an XML file, and I want to add four spaces before each blank line.

```xml
<beans xmlns="http://www.springframework.org/schema/beans">
    <context:property-placeholder location="classpath:spring/conf/conf.properties" />

    <alter-index sql-case-id="alter_index">
        <index name="order_index" start-index="12" stop-index="22" />
    </alter-index>

</beans>
```

The replacement rules are as follows:

version: 2.22.5

```
<replace>
    <name>Add spaces to empty xml lines</name>
    <search>/&gt;</search>
    <replacement>/&gt;&#10;&#160;&#160;&#160;&#160;</replacement>
</replace>

<replace>
    <name>Add spaces to empty xml lines2</name>
    <search>alter-index&gt;</search>
    <replacement>alter-index&gt;&#10;&#160;&#160;&#160;&#160;</replacement>
</replace>
```

The first one doesn't work, and the second one can achieve the expected function. Why doesn't the first replacement take effect?

> If you think the description is insufficient, I can explain it in detail.

**Comment by nedtwigg** [comment]
This is because Spotless enforces idempotence. Your first rule "diverges" (see [`PADDEDCELL.md`](https://github.com/diffplug/spotless/blob/main/PADDEDCELL.md) for more detail).

**Comment by longtai-cn** [comment]
Thank you very much for your reply.
