### ISSUE TITLE
Maven plugin skip no longer functional in 2.19.0 and above

### ISSUE THREAD

**Issue by bbarker-eb** [diffplug/spotless#1227]
The issue/enhancement: **Maven plugin should support skip #491** no longer functions as of release 2.19.0.
mvn spotless:check or mvn spotless:apply  does not get skipped as in earlier releases.
`            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.19.0</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
`

**Comment by tisonkun** [comment]
Ditto here https://github.com/apache/flink/pull/20911. I'm working on a fix.

**Comment by tisonkun** [comment]
OK. I locate the root cause and can show you a workaround at https://github.com/apache/flink/pull/20911 while prepare a patch to keep the manner.

**Comment by tisonkun** [comment]
Root cause: https://github.com/diffplug/spotless/commit/6788e1773f83354afa6463ed185ae2d270527819

**Comment by nedtwigg** [comment]
Fixed by @tisonkun, available in `plugin-maven 2.27.1`.
