### ISSUE TITLE
Gradle Plugin "6.7.2" - indentWithSpaces() is ignored when using googleJavaFormat()

### ISSUE THREAD

**Issue by hajdukd** [diffplug/spotless#1245]
If you are submitting a **bug**, please include the following:

- [X] summary of problem

Indent is ignored instead of 4 spaces only 2 are applied despite indent being after google format.

- [X] gradle version - 7.3
- [X] spotless version - 6.7.2
- [X] operating system and version - Windows 10
- [X] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
```
spotless {
    format 'misc', {
        // define the files to apply `misc` to
        target '*.gradle', '*.md'
        trimTrailingWhitespace()
        endWithNewline()
    }
    java {
        removeUnusedImports()
        googleJavaFormat('1.15.0')
        indentWithSpaces()
        endWithNewline()
        licenseHeader '/* Copyright (C) $YEAR - All Rights Reserved */'
    }
}
```

**Comment by nedtwigg** [comment]
The unintuitive thing here is that `indentWithSpaces` just find-replaces `\t` with n spaces. And `indentWithTabs` just find-replaces n spaces with a `\t`. The only semi-smart stuff is checking for the beginning of lines and some multiline comment stuff.

GJF indents with 2-spaces, correct? The solution for your case is:

```
googleJavaFormat()
indentWithTabs(2)
indentWithSpaces(4)
```

That is confusing, I agree. Hopefully someday we'll get a PR to rename these methods and end the confusion once and for all!

- #794
