### ISSUE TITLE
spotlessApply - how to make build fail if, after the execution of the task, any file is edited by Spotless

### ISSUE THREAD

**Issue by skyviolantea** [diffplug/spotless#1247]
Hi, 

In my app, I'm running a pre-commit hook in which, everytime I make a commit, I execute the following command:

gradlew lint spotlessApply

If Spotless detects edits to be done on some files, after the build and the commit process, these files are marked in git as modified.

The build will be successfully done.

What I would do is that, if some files are edited by Spotless, the build has to fail. 

Is it possible to configure Spotless so that, if Spotless edits some files, the build fails?

Gradlew version: 7.2.0

Spotless version: 6.6.1

Operating system and version: Windows 10

Spotless configuration:

``
spotless {
    kotlin {
        target '**/*.kt'
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
}
``

**Comment by jbduncan** [comment]
Hi, @skyviolantea!

I believe what you're looking for is the `spotlessCheck` task. It won't actually change/format your Kotlin files, but it will fail if any of them _would_ have been changed by `spotlessApply`.

Is this the sort of answer you were looking for? Regardless, I hope this helps.

**Comment by skyviolantea** [comment]
Hi,

I've seen that the **spotlessCheck** does it, but that task doesn't apply the edits and developers have to fix files by themselves. 

What I would do is that the task find errors, then apply the edits but fails the build.

In other words, I would Spotless make a successful build only when there aren't files to fix.

Is it possible? (It seems acually it isn't).

Eventually, do you know some plugins having more options of this kind?

Thanks a lot

**Comment by jbduncan** [comment]
I admit that I'm not aware of any other plugins that have the mode you're looking for.

**Comment by nedtwigg** [comment]
Failure doesn't compose. A multiproject build might have 100 different `spotlessApply` and `spotlessCheck` tasks. If one task fails, there's no guarantee about other tasks even running. Making some kind of summary task that aggregates the results of every `spotlessApply` and then fails at the end is possible, but adds a fair bit of complexity for the benefit of a niche use-case. Feel free to open a PR, if the docs and impl are short I'd be open to merging, but I suspect the docs & code will be longer than they are worth.
