### ISSUE TITLE
Spotless SQL LINE ORIENTED File Extensions

### ISSUE THREAD

**Issue by Akaame** [diffplug/spotless#1256]
Documentation states that Spotless.SQL can use a `dbeaver().configFile('dbeaver.props')` however trying to set this config throws and error that this file extension is not supported and I see that it is not supported [here](https://github.com/diffplug/spotless/blob/0fd20bb80c6c426d20e0a3157c3c2b89317032da/lib/src/main/java/com/diffplug/spotless/FormatterProperties.java).

Could we fix the documentation or add `.props` to list of supported file extensions?

Spotless configuration

```gradle
spotless.sql {
    target 'src/main/resources/**/*.sql'

    dbeaver().configFile('dbeaver.props') // works with 'dbeaver.properties'
}
```

Cheers.

**Comment by EricGao888** [comment]
I encountered the same bug and submitted a PR to fix it: https://github.com/diffplug/spotless/pull/1277

Thx : )
