### ISSUE TITLE
Inbuilt support for json formatting is missing

### ISSUE THREAD

**Issue by SharadSrc** [diffplug/spotless#1258]
Currently, via prettier you can format json files as well using spotless. But the downside is that you need to have npm installed in the machine which might not be the case for many machines which are running only java based projects. So a inbuilt functionality is much needed.

**Comment by SharadSrc** [comment]
check this issue also 
https://stackoverflow.com/questions/72893968/json-files-formatting-in-spring-boot-based-projects/72932715#72932715

**Comment by nedtwigg** [comment]
Correct, you can format json using prettier and it is a bit of a pain. For Spotless Gradle users, we include [three other JVM-based tools](https://github.com/diffplug/spotless/tree/main/plugin-gradle#json), `simple` (which is inbuilt), `gson`, and `eclipseWtp`. For Spotless Maven, `eclipseWtp` is also available, but `gson` and `simple` are not.

It would be very easy to expose `simple` and `gson` to maven users, and I'd be happy to merge a PR which adds them.
