### ISSUE TITLE
Spotless check fails in remote CI

### ISSUE THREAD

**Issue by EricGao888** [diffplug/spotless#1271]
Hello,

I'm using `Spotless` in my project. I want it to only check code different from a remote branch which is referred as `upstream/dev`. However, this causes remote CI to fail once I push the code to the remote repo and trigger the CI.

I set up `ratchet` as below:

```xml
<ratchetFrom>upstream/dev</ratchetFrom>
```

The error log I got from my `GitHub Actions`:

```
Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.23.0:check failed: No such reference 'upstream/dev' -> [Help 1]
```

In the end, I have to set `ratchetFrom` `HEAD` instead of `upstream/dev`, which is not recommended by the official doc:

![image](https://user-images.githubusercontent.com/34905992/183274703-96bcf8a3-9ddd-4938-b0f2-3060dcd7ff86.png)
 
May I ask whether there is a way to set `ratchetFrom` a remote branch without failing the remote CI?

Thanks!

**Comment by nedtwigg** [comment]
The problem you are having is about clone depth. See https://github.com/diffplug/spotless/issues/710 for a workaround.

**Comment by EricGao888** [comment]
> The problem you are having is about clone depth. See #710 for a workaround.

Thanks for the reply : )
