### ISSUE TITLE
Format http code in markdown

### ISSUE THREAD

**Issue by EricGao888** [diffplug/spotless#1272]
Sometimes we may have some `http` code in `markdown`, e.g. image link like:

```html
<p align="center">
   <img src="xxxx" width="60%" />
 </p>
```
Currently, [markdown.FlexmarkStep](https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/markdown/FlexmarkStep.java) in spotless could not fix `http` code formatting in `markdown`. It would be pretty handy if `spotless` could support this feature in the future. 

BTW, I'd like to help with it but currently I haven't found a good way to implement this. Any help will be appreciated! Thx

**Comment by nedtwigg** [comment]
With the Gradle plugin, you can apply different formatters on different blocks ([formatter inception](https://github.com/diffplug/spotless/blob/0fd20bb80c6c426d20e0a3157c3c2b89317032da/plugin-gradle/README.md#inception-languages-within-languages-within)).

But this only works if you have a regex that demarcates the nested HTML from the rest of the markdown. If all of the cases you care about fit with `'<p ', '</p>'` then you could use this pattern to apply prettier or the Eclipse WTP formatter onto the embedded HTML. If that regex doens't capture all of the cases you care about, then you're probably better off improving the Flexmark project directly.

**Comment by EricGao888** [comment]
> With the Gradle plugin, you can apply different formatters on different blocks ([formatter inception](https://github.com/diffplug/spotless/blob/0fd20bb80c6c426d20e0a3157c3c2b89317032da/plugin-gradle/README.md#inception-languages-within-languages-within)).
> 
> But this only works if you have a regex that demarcates the nested HTML from the rest of the markdown. If all of the cases you care about fit with `'<p ', '</p>'` then you could use this pattern to apply prettier or the Eclipse WTP formatter onto the embedded HTML. If that regex doens't capture all of the cases you care about, then you're probably better off improving the Flexmark project directly.

@nedtwigg Thanks for the reply. May I ask whether there is something similar to the `formatter inception` in the Maven plugin?

**Comment by nedtwigg** [comment]
There is not, but it might be possible. In the Gradle plugin, `FormatExtension` is the receiver for adding generic steps. It has this method for defining a block, and then defining the steps within that block.

https://github.com/diffplug/spotless/blob/ce98b688cb4724a95e0abb05f4bbaf398097c1b8/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L674-L682

In the Maven plugin, the equivalents would be [`AbstractSpotlessMojo`](https://github.com/diffplug/spotless/blob/main/plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java) and [`FormatterFactory`](https://github.com/diffplug/spotless/blob/main/plugin-maven/src/main/java/com/diffplug/spotless/maven/FormatterFactory.java), but I'm not sure how to do a nested DSL in the maven plugin (or if that's even possible).

**Comment by EricGao888** [comment]
> There is not, but it might be possible. In the Gradle plugin, `FormatExtension` is the receiver for adding generic steps. It has this method for defining a block, and then defining the steps within that block.
> 
> https://github.com/diffplug/spotless/blob/ce98b688cb4724a95e0abb05f4bbaf398097c1b8/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L674-L682
> 
> In the Maven plugin, the equivalents would be [`AbstractSpotlessMojo`](https://github.com/diffplug/spotless/blob/main/plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java) and [`FormatterFactory`](https://github.com/diffplug/spotless/blob/main/plugin-maven/src/main/java/com/diffplug/spotless/maven/FormatterFactory.java), but I'm not sure how to do a nested DSL in the maven plugin (or if that's even possible).

Got it, thanks!

**Comment by nedtwigg** [comment]
Feel free to comment further if you need more help.
