### ISSUE TITLE
Support Gradle configuration cache on multiple JVMs 

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#1274]
Gradle configuration cache requires task state to be round-trip serializable. As outlined at #987, this is a signficant constraint on plugin developers and it slows down the end-user experience of change-test-change-test on a single JVM daemon. We built a workaround ([`JvmLocalCache`](https://github.com/diffplug/spotless/blob/ba490439f27cacc9e188bb39f4a0a4173f83b136/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JvmLocalCache.java)) that complies with Gradle's requirement by making our tasks round-trip serializable without requiring much work from plugin developers or the end user's machine, but it only works within a single JVM.

To work on multiple JVMs, we need to

- make every step round-trip serializable
- remove `JvmLocalCache`

**Comment by nedtwigg** [comment]
Full roundtrip will work great on the same JVM, so Spotless will still work and not work under the same conditions it does currently.

**Comment by nedtwigg** [comment]
I think we now have a way to incrementally build this until we can eventually remove our workaround. See:

- https://github.com/diffplug/spotless/pull/1945

In this comment, I'm going to maintain a list of remaining TODOs before we will fully support Gradle's configuration cache model without any workarounds

- [ ] remove `LineEnding.GIT_ATTRIBUTES` (at least for Gradle) because very difficult to make it serializable
  - we can keep `GIT_ATTRIBUTES_FAST_ALLSAME` which is the default anyway
- [ ] lib(generic.EndWithNewlineStep)
- [ ] lib(generic.IndentStep)
- [ ] lib(generic.Jsr223Step)
- [ ] lib(generic.LicenseHeaderStep)
- [ ] lib(generic.NativeCmdStep)
- [ ] lib(generic.ReplaceRegexStep)
- [ ] lib(generic.ReplaceStep)
- [ ] lib(generic.TrimTrailingWhitespaceStep)
- [ ] lib(antlr4.Antlr4FormatterStep)
- [ ] lib(cpp.ClangFormatStep)
- [ ] extra(cpp.EclipseFormatterStep)
- [ ] lib(gherkin.GherkinUtilsStep)
- [ ] extra(groovy.GrEclipseFormatterStep)
- [ ] lib(java.GoogleJavaFormatStep)
- [ ] lib(java.ImportOrderStep)
- [ ] lib(java.PalantirJavaFormatStep)
- [ ] lib(java.RemoveUnusedImportsStep)
- [ ] extra(java.EclipseJdtFormatterStep)
- [ ] lib(java.FormatAnnotationsStep)
- [ ] lib(java.CleanthatJavaStep)
- [ ] lib(json.gson.GsonStep)
- [ ] lib(json.JacksonJsonStep)
- [ ] lib(json.JsonSimpleStep)
- [ ] lib(json.JsonPatchStep)
- [ ] lib(kotlin.KtLintStep)
- [ ] lib(kotlin.KtfmtStep)
- [ ] lib(kotlin.DiktatStep)
- [ ] lib(markdown.FreshMarkStep)
- [ ] lib(markdown.FlexmarkStep)
- [ ] lib(npm.EslintFormatterStep)
- [ ] lib(npm.PrettierFormatterStep)
- [ ] lib(npm.TsFmtFormatterStep)
- [ ] lib(pom.SortPomStepStep)
- [ ] lib(protobuf.BufStep)
- [ ] lib(python.BlackStep)
- [ ] lib(biome.BiomeStep)
- [ ] lib(scala.ScalaFmtStep)
- [ ] lib(sql.DBeaverSQLFormatterStep)
- [ ] extra(wtp.EclipseWtpFormatterStep)
- [ ] lib(yaml.JacksonYamlStep)

**Comment by lehmanju** [comment]
I checked `npm.EslintFormatterStep`, `npm.PrettierFormatterStep`, `npm.TsFmtFormatterStep` and `sql.DBeaverSQLFormatterStep`. They all use StepHarness for testing which has roundtrip serialization testing enabled by default. Since their tests do not fail, it should mean they are already serializable, am I correct?

For `NativeCmdStep` I created a PR #2108 which adds a test using StepHarness.

**Comment by nedtwigg** [comment]
Thanks mostly to @Goooler's tireless dedication, we have finally shipped:

- `plugin-gradle 3.0.0.BETA1`
- `plugin-maven 2.44.0.BETA1`

These contain a bazillion fixes.  Please test and let us know if you encounter any issues!

**Comment by marcphilipp** [comment]
JUnit build [updated](https://github.com/junit-team/junit5/pull/3844) ✅

**Comment by bddckr** [comment]
All working fine for me as well, except I used 
```kotlin
removeUnusedImports("cleanthat-javaparser-unnecessaryimport")
```
[as seen in the docs](https://github.com/diffplug/spotless/tree/main/plugin-gradle#removeunusedimports). That one seems to not support the config cache yet:
```
Could not load the value of field `steps` of task `:spotlessInternalRegisterDependencies` of type `com.diffplug.gradle.spotless.RegisterDependenciesTask`.
> Could not load the value of field `excluded` of `com.diffplug.spotless.java.CleanthatJavaStep` bean found in field `roundtripStateInternal` of `com.diffplug.spotless.FormatterStepSerializationRoundtrip` bean found in field `steps` of task `:spotlessInternalRegisterDependencies` of type `com.diffplug.gradle.spotless.RegisterDependenciesTask`.
```

I just removed it as it looks like `googleJavaFormat` already takes care of that.

**Comment by Magotchi** [comment]
I get a similar error to @bddckr if I use any `prettier` steps, like:
```text
Could not load the value of field `steps` of task `:spotlessJava` of type `com.diffplug.gradle.spotless.SpotlessTaskImpl`.
> Could not load the value of field `additionalNpmrcLocations` of `com.diffplug.spotless.npm.NpmPathResolver` bean found in field `resolver` of `com.diffplug.spotless.npm.NpmFormatterStepLocations` bean found in field `locations` of `com.diffplug.spotless.npm.PrettierFormatterStep$State` bean found in field `roundtripStateInternal` of `com.diffplug.spotless.FormatterStepSerializationRoundtrip` bean found in field `steps` of task `:spotlessJava` of type `com.diffplug.gradle.spotless.SpotlessTaskImpl`.
```

or:
```text
Could not load the value of field `steps` of task `:spotlessPrettierGeneric` of type `com.diffplug.gradle.spotless.SpotlessTaskImpl`.
> Could not load the value of field `additionalNpmrcLocations` of `com.diffplug.spotless.npm.NpmPathResolver` bean found in field `resolver` of `com.diffplug.spotless.npm.NpmFormatterStepLocations` bean found in field `locations` of `com.diffplug.spotless.npm.PrettierFormatterStep$State` bean found in field `roundtripStateInternal` of `com.diffplug.spotless.FormatterStepSerializationRoundtrip` bean found in field `steps` of task `:spotlessPrettierGeneric` of type `com.diffplug.gradle.spotless.SpotlessTaskImpl`.
```

**Comment by davidburstrom** [comment]
FWIW, I've upgraded to 7.0.0.BETA2 in all my repositories and everything seems to be in order! Great job!

**Comment by ZacSweers** [comment]
Just filed a regression on #2318

**Comment by cloudshiftchris** [comment]
CC issue w/ prettier on 7.0.0BETA4: https://github.com/diffplug/spotless/issues/2372
