### ISSUE TITLE
Support `google-java-format --skip-javadoc-formatting`?

### ISSUE THREAD

**Issue by kevinb9n** [diffplug/spotless#1287]
Just noticed that this command-line option doesn't seem to be supported by `GoogleJavaFormatConfig`. 

`google-java-format` is of course very stingy with options, but does allow some behaviors to be switched on or off, like this.

Should this be handled like #929 - is there a similar rationale?

**Comment by nedtwigg** [comment]
A PR along the lines of #929 is very welcome :) Optionally, you might want to also do

- https://github.com/diffplug/spotless/issues/524

while you're at it. Feel free to drop support for older GJF versions if you need to, but try to stay as compatible as possible.
