### ISSUE TITLE
Consider replacing Dependabot with Renovatebot

### ISSUE THREAD

**Issue by vpavic** [diffplug/spotless#1288]
For contributors to a project that uses Dependabot, a major annoyance is its inability to be disabled for forks. This is a well known issue with a lot of history - see https://github.com/dependabot/dependabot-core/issues/2804 (and as an example, [list of PRs](https://github.com/vpavic/spotless/pulls?q=is%3Apr+is%3Aclosed) it opened against my fork).

The alternative is Renovatebot, which generally seems more capable than Dependabot (for example, it supports Gradle's version catalogs) and also comes with [sane defaults](https://docs.renovatebot.com/configuration-options/#includeforks). So my proposal is to consider replacing Dependabot with Renovatebot.

**Comment by nedtwigg** [comment]
Done :)
