### ISSUE TITLE
Can't format java files (gradle plugin)

### ISSUE THREAD

**Issue by qwerty287** [diffplug/spotless#1307]
Hi!

I'm sorry for this issue, I believe it's just a config issue, but I'm not able to solve it myself.
I'm trying to use Spotless on an Android app written in Java and would like to format these Java files.

What I did is what you described on the gradle plugin docs, but I added the plugin / config to the **module** build file:
1. Add plugin (`plugins {  id "com.diffplug.spotless" version "6.10.0" }`)
2. Add some config for it, for example a simple one:
```groovy
spotless {
    java {
        googleJavaFormat()
    }
}
```

Now, I can run `gradle :app:spotlessJavaApply`. But, even with the simple config above, it does not work.
It always exits without doing anything. It does not format files where it would be necessary.
This also applies if I change it to another config like the generic `format`, it does not work here as well.
Running `gradle build` doesn't fail as in the example.

Now, I don't understand it. I did *almost everything* exactly like in your example, it does not work.
Adding it to the top-level build file ended up with the error that the java plugin is not applied, but using a generic `format` **worked with this**.

Is it not possible to use Spotless Gradle plugin within module build files? Must it be top-level? Or is there something else I'm doing completely wrong?

Thanks!

- Gradle version: 7.5.1
- Spotless version (gradle plugin): 6.10.0

**Comment by nedtwigg** [comment]
You can use Spotless within top-level or module-build files. However, you cannot format a different project's files! So `:lib` cannot format stuff in `:app`. My guess is that you are not editing the `build.gradle` that you think you are.

**Comment by nedtwigg** [comment]
We'd need a public git repo to help more.

**Comment by nedtwigg** [comment]
Point me to the commit that has the problem.

**Comment by nedtwigg** [comment]
Try adding this:

```gradle
spotless {
  java {
    target 'src/**/*.java'
```

Spotless can't autodetect the java sources with the Android plugin.
