### ISSUE TITLE
spotlessKotlinGradle with `**/*` failed on an excluded file path in build/

### ISSUE THREAD

**Issue by hakanai** [diffplug/spotless#1308]
We had a one-off failure during a build where `spotlessKotlinGradle` failed on a path which it shouldn't have been scanning presumably while the javadoc task happened to be deleting the directory.

```lang-none
Execution failed for task :spotlessKotlinGradle
> Could not read path '/path/to/project/build/docs/javadoc/acme/MetadataProfile.html'.
```

Since it happened with specific timing, I doubt this is going to be easily reproduced. Maybe it's some more fundamental issue with how targetExclude is being implemented which will be easy to spot, though.

**Spotless config:**

```kotlin
spotless {
    kotlinGradle {
        target("**/*.gradle.kts")
        targetExclude("**/build/**/*")
        ktlint("0.42.1")
    }
}
```

**Versions:**
- spotless-plugin-gradle 5.16.0
- spotless 2.19.0
- Gradle 7.5.1
- macOS Big Sur

**Comment by hobindar** [comment]
This bug also reproduced for me a couple times. In the most recent failed run, I see:
```
Execution failed for task ':module:spotlessMisc'.
> Could not read path '/mnt/jenkins/workspace/Project/module/build/intermediates/verified_library_resources/release/linked.apk'.
```

My Spotless config looks like so:
```
spotless {
    format 'misc', {
        target '**/*.java', '**/.gitignore', '**/*.gradle', '**/*.properties', '**/*.pro', '**/*.cfg', '**/*.feature', '**/*.groovy',
                '**/AndroidManifest.xml', '**/*.aidl', '**/*.bat', '**/*.json', '**/*.js', '**/*.MockMaker'
        targetExclude '**/build/**', '**/.gradle/**', '**/tmp/**', '**/GeneratedEnums.java'
        endWithNewline()
    }
    
    kotlin {
        target '**/*.kt'
        targetExclude '**/build/**', '**/.gradle/**', '**/tmp/**'
        ktlint('0.42.1').userData([
                "continuation_indent_size": "4",
                "max_line_length": "120"
        ])
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
}
```

As you can see, it's complaining about a file that cannot be read. That file is in `**/build/**` however, which is clearly in misc's `targetExclude`. Not to mention, `**/*.apk` is not present in `target` either.

I'm currently using Spotless 5.14.1, so a similar version to what was reported here. I'm planning to try upgrading, but given how rare this is, it'll likely be hard to confirm that it's fixed once I do update.

[Full stacktrace dump from failure is attached.](https://github.com/diffplug/spotless/files/10810592/stacktrace.txt)

**Versions**
spotless-plugin-gradle 5.14.1
Gradle 7.6
Windows 10 and Ubuntu 18.04

**Comment by nedtwigg** [comment]
Agreed this is a bug, but you can fix this bug and get a big perf boost if you replace all the `**/blah` with something with a prefix. e.g. `src/main/kotlin/**`. Newer versions of Gradle have gotten quite fancy with their file collections, and I will be surprised if we actually fix this. The default for `spotlessKotlin` is now 

https://github.com/diffplug/spotless/blob/adb4e733955dd31120603324a58c0e7d7dfd230e/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinGradleExtension.java#L38

You can do `target '*.gradle.kts', 'gradle/*.gradle.kts'`, something like that. But find all the Gradle script files with a `**` is massively inefficient, compared to `*.gradle.kts` applies to each subproject.

The first versions of Spotless used `**/` a lot in the docs, at some point we did a pass to remove every single one and replace with `some/prefix/**`. We also removed all the `**` from our defaults. So this is our fault for allowing `**` in the first place, but I think the unavoidable real fix here it going to be leaving `**/` behind.

**Comment by hobindar** [comment]
@nedtwigg Can you re-open this issue? (Given there's no fix nor working workaround for the bug.)

**Comment by nedtwigg** [comment]
Sure, happy to reopen. Can you include a stacktrace of an example failure for the `**` prefixes removed version?

**Comment by hobindar** [comment]
@nedtwigg Sure thing. Here's a stacktrace, as requested.

[spotless-stacktrace.txt](https://github.com/diffplug/spotless/files/11142794/spotless-stacktrace.txt)

**Comment by hobindar** [comment]
Just upgraded our project to Spotless 6.17.0 and ktlint 0.48.2. Same error, unfortunately.

I also had to update our Spotless config as part of this upgrade. So it now looks like:

```
var spotlessConfig
if (project == rootProject) {
    spotless { predeclareDeps() }
    spotlessConfig = spotlessPredeclare
} else {
    spotlessConfig = spotless
}

spotlessConfig.with {
    format 'misc', {
        target '.gitignore', '*.properties', 'gradle/wrapper/*.properties', 'src/*/resources/*.properties', '*.pro',
                'src/androidTest/assets/bdd_test_steps/**/*.feature', 'src/test/resources/bdd_feature_files/**/*.feature',
                '*.bat', 'bin/**/*.bat', 'ops/**/*.bat', '*.gradle', 'ops/**/*.groovy',
                'src/*/aidl/**/*.aidl', 'src/*/AndroidManifest.xml', 'src/*/java/**/*.java',
                'src/*/res/raw/*.json', '/src/*/resources/**/*.json', 'config/**/*.json', 'ops/**/.json',
                '*.json', 'doc/*/tutorials/**/*.json', 'src/test/resources/**/*.js',
                'src/test/resources/mockito-extensions/*.MockMaker'
        targetExclude 'build/**', '.gradle/**', 'tmp/**', 'src/main/java/com/foo/GeneratedEnums.java'
        endWithNewline()
    }

    kotlin {
        target 'src/*/java/**/*.kt'
        targetExclude 'build/**', '.gradle/**', 'tmp/**'
        ktlint(ktlint_version).editorConfigOverride([
                "continuation_indent_size": "4",
                "max_line_length": "120",
                "ktlint_standard_trailing-comma-on-declaration-site": "disabled", // this rule seems to be broken in ktlint 0.48.2
                "ktlint_standard_trailing-comma-on-call-site": "disabled"
        ])
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
}
```

[Here's a new stacktrace for this setup.](https://github.com/diffplug/spotless/files/11152536/spotless-stacktrace.txt)

**Comment by hobindar** [comment]
We encountered some other flaky failures with a different stacktrace. But upon closer inspection, it seems to be fundamentally the same problem (i.e. also caused by Spotless reading excluded files). [Here is the stacktrace for this other failure.](https://github.com/diffplug/spotless/files/11163368/spotless-variation-stacktrace.txt)

Also, one more update, we ended up upgrading Gradle to 7.6 and AGP to 7.4.1. This actually made the Spotless bug occur way, way more often. Maybe closed to 1/3 runs. For now I've split Spotless off into its own task in our Jenkins pipeline, but it makes `check` without `-x spotlessCheck` almost unusable.

**Comment by nedtwigg** [comment]
Aha! I think we have a solution! If we go back to the very beginning of this issue:

```
    kotlin {
        target '**/*.kt'
        targetExclude '**/build/**', '**/.gradle/**', '**/tmp/**'
```

Because you were doing `**/*.kt`, you needed to explicitly exclude `build`, `gradle` and `tmp`. But now you are doing `src/*/java/**/*.kt`, so you don't need `targetExclude` at all anymore, except for `src/main/java/com/foo/GeneratedEnums.java`.

**Comment by hobindar** [comment]
That seems to have worked! I've removed the folders that contain build artifacts from `targetExclude` as you recommended. That change was merged in on the 6th, and there hasn't been a single flaky spotless failure on our CI since.

I'll keep monitoring it, but that workaround appears to be good enough for us.

**Comment by nedtwigg** [comment]
Thanks for sticking with with, I think it is useful for others. I think the new take away is:

- don't use `'**/blah'` anywhere, not in `target` and also not in `targetExclude`

I'm going to edit that into the top of the issue.

**Comment by hobindar** [comment]
I believe it's more than just not excluding `**/blah`. In our case, we were only excluding `blah/**` (in the newer config) and still saw the issue. Seems the problem is more a race condition between whatever is looking for files to exclude vs other build processes creating files in those directories.

So it seems you need to not explicitly exclude any folder that might contain files that are generated at build time.

**Comment by nedtwigg** [comment]
Thanks for noting that it's not just about prefixes, I updated the hint at the top of the issue.

I bet it's not just about created/destroyed, but files in `build` that are not in the dependency chain of the spotless task. If the Spotless task doesn't have anything to do with `compileNative`, the Gradle runtime might be surprised it needs to resolve `build/compileNative` as part of `targetExclude` when it has nothing at all to do with the spotless task in the first place.

**Comment by runningcode** [comment]
Sorry to dig up this old issue. I see the “Edit” from @nedtwigg 
```
EDIT @nedtwigg 2023-Apr-12: Solution is

never use '**/blah'
use 'prefix/**/blah' instead
this is true for target and targetExclude
once you use prefixes to remove the leading ** from target, you might be able to remove targetExclude altogether
if you can, that will be good!
```

I don’t see this anywhere else in the documentation for these methods.

I’m curious, if I want to include all `.kt` files in all my subprojects/directories but exclude all source in the `build` directories, what is the most performant configuration? Here’s a concrete example I’m trying to optimize: https://github.com/getsentry/sentry-java/blob/main/build.gradle.kts#L230
