### ISSUE TITLE
How to use line length configuration in java

### ISSUE THREAD

**Issue by mozinrat** [diffplug/spotless#134]
Need help in using max line length configuration while using gradle/java. Here is my config

spotless {
    java {
        target fileTree(projectDir) {
            include '**/*.java'
            exclude '**/generated/**', '**/generated-src/**'
        }
        googleJavaFormat('1.3') // google format also have line length, need to override that
        licenseHeaderFile "${rootDir}/LICENSE"
        importOrder 'java', 'javax', 'com', 'org'
        removeUnusedImports()
        trimTrailingWhitespace()
        custom 'Lambda fix', { it.replace('} )', '})').replace('} ,', '},') }
    }
}

**Comment by jbduncan** [comment]
AFAIK, google-java-format (the formatter we use to power the `googleJavaFormat()` option) doesn't have an official way of setting the line length.

If you're not happy with the 80-character-per-line limit that google-java-format enforces, then you could try the Eclipse formatter instead (using the`eclipse().configFile()` option, as described in https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source).

@nedtwigg may have further suggestions if using the Eclipse formatter doesn't meet your needs.

**Comment by nedtwigg** [comment]
If you use the eclipse formatter instead of google-java-format, these are the keys you care about:

```
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="999"/>
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="999"/>
```

**Comment by Bartosz76** [comment]
@nedtwigg 
Hello, I found this thread as I am trying to do the same thing as the original poster, but I am completely stuck.
I want to set the line length to 140 and, as I understand, I cannot do it with googleJavaFormat.
And with eclipse format, I am absolutely clueless what I am supposed to do. I tried using these tags that you provided:
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="999"/>
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="999"/>
But I get an error that such tags doesn't exist. I managed to export an XML file with configuration which cannot be read and I have no clue why.
Any chances you could elaborate on how do these <setting> tabs work?

**Comment by istibekesi** [comment]
I ended up here and realized this configuration depends on the formatter.
In my case it was [prettier](https://github.com/jhipster/prettier-java/blob/main/docs/advanced_usage.md#configuration), the config for prettier formatter: `printWidth`

build.gradle
```
spotless {
	java {
		toggleOffOn()
		importOrder()
		removeUnusedImports()
		prettier().config([
			'parser': 'java',
			'tabWidth': 4,
			'printWidth': 120 // <--- line length 
		])
	}
}
```
