### ISSUE TITLE
Kotlin file could start with `@file:...` instead of `package ...`

### ISSUE THREAD

**Issue by JLLeitschuh** [diffplug/spotless#136]
The regex for finding the top of the file (where the license should go) doesn't work when you start your file with:
```kotlin
@file:JvmName("SomeFileName")
package ... // ect...
```

The default header regex for kotlin should support starting the file with the `@file` annotation.
As a note, the compiler will only let you legally put `@file:...` annotations above the package statement.

**Comment by jbduncan** [comment]
This sounds like a very good reason to me to amend the default header regex for Kotlin files.

I probably won't have the time and energy to make this change myself, but I'm sure we're open to PRs if @nedtwigg isn't already addressing this. But regardless, I would make a reasonable guess that he can direct you if you'd be happy to submit a PR yourself. as I think he knows the code base better than I do. :)

**Comment by nedtwigg** [comment]
You can workaround with something like this: `licenseHeaderFile('license.txt', '^(package|@file)')`.  Can you find a battle-tested regex that works for your codebase?  If so, we can change the [default regex](https://github.com/diffplug/spotless/blob/facd2cc3f3bd4d73a5f103d9efd59fa5f30eb677/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinExtension.java#L34-L40).

Issue #135 is about this same issue but for the default package.

**Comment by jbduncan** [comment]
@nedtwigg The regex would be for JUnit 5 I believe (please correct me if I'm wrong @JLLeitschuh), as I think @JLLeitschuh is submitting this bug in response to https://github.com/junit-team/junit5/pull/1001.

Not sure if the regex that would ultimately come out of this would count as "battle-tested", as AFAIK JUnit 5 doesn't use Kotlin much at this point in time.

**Comment by JLLeitschuh** [comment]
Well, I only discovered the bug because of my work on Junit5. I'd be more than happy to open an PR with a simple unit test for the regex.

**Comment by nedtwigg** [comment]
The `@file` issue that @JLLeitschuh brings up is more battle-tested than what we have now.  We don't need the perfect regex, not even sure that we need a unit test.  Just a `licenseFile()` incantation that works better on Kotlin codebases than what we have now.

**Comment by nedtwigg** [comment]
Released in `3.5.2`.
