### ISSUE TITLE
gradle allprojects in a multi project build  - can't find solution 

### ISSUE THREAD

**Issue by waveskimmer** [diffplug/spotless#1360]
My understanding is that the plugins should be looking at the buildscript repositories, but I get a number of errors on unless the project repos are defined.  

Gradle:  7.5.1
MacOS: Monterey 12.6

Here are some errors:
```
Could not determine the dependencies of task ':spotlessApply'.
> Could not create task ':spotlessGroovyApply'.
   > Could not create task ':spotlessGroovy'.
      > Could not resolve all files for configuration ':spotless-1429330901'.
         > Cannot resolve external dependency com.diffplug.spotless:spotless-eclipse-groovy:4.3.0 because no repositories are defined.
           Required by:
               project :
         > Cannot resolve external dependency com.diffplug.spotless:spotless-eclipse-base:3.5.2 because no repositories are defined.
           Required by:
               project :
         > Cannot resolve external dependency com.github.spotbugs:spotbugs-annotations:4.0.2 because no repositories are defined.
           Required by:
               project :
**snipped**
```

But, I can make it work by adding: 

```
repositories {
	mavenCentral()
}
```

Here's my full build.gradle.   It's the second repositories section that makes it work. 

```
buildscript {
	repositories {
		mavenCentral()
	}
}

plugins {
	id 'groovy'
	id "com.diffplug.spotless" version "6.11.0"
}

//  this needs to be here to make it work... 
repositories {
	mavenCentral()
}

group 'org.example'
version '1.0-SNAPSHOT'

spotless {
	java {
		googleJavaFormat()
		indentWithSpaces()
		trimTrailingWhitespace()
	}
	groovy {
		excludeJava()
		greclipse()
		indentWithSpaces()
		trimTrailingWhitespace()
	}
	groovyGradle {
		greclipse()
	}
}

```

**Comment by austek** [comment]
This would be because of https://github.com/diffplug/spotless/pull/1039

**Comment by nedtwigg** [comment]
> My understanding is that the plugins should be looking at the buildscript repositories

That used to be true, but was a breaking change in 6.0.0 ([changelog entry](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md#600---2021-11-09)) to use the regular project repositories. So you don't need to add buildscript repositories anymore.

However, as you found, starting with 6.1.0 you can use the [predeclare mechanism](https://github.com/diffplug/spotless/tree/main/plugin-gradle#dependency-resolution-modes) which can use project repositories or buildscript repositories, whichever you would like.
