### ISSUE TITLE
Cannot reach the javadoc for `JavaExtension.importOrder`

### ISSUE THREAD

**Issue by Ledmington** [diffplug/spotless#1364]
I am using palantir for my Java code and I wanted to force this specific order of imports:
```
<all static imports>
<blank line>
java.*
javax.*
javafx.*
<blank line>
com.*
<blank line>
org.*
<blank line>
<everything else>
```

So far, I only managed to write this `importOrder('java.*', 'javax.*', 'javafx.*', 'com.*', 'org.*', '*')` which compiles but doesn't work. I thought about checking the documentation but whenever I search `importOrder` it goes to [this URL](https://javadoc.io/doc/com.diffplug.spotless/spotless-plugin-gradle/latest/undefined/com/diffplug/gradle/spotless/JavaExtension.html#importOrderFile(java.lang.Object)) which shows this:
![image](https://user-images.githubusercontent.com/68538713/194413411-ab90b26a-aabb-465d-9b23-c612d9e908fe.png)

I am using gradle with groovy DSL, spotless version 6.11.0 and palantir version 2.26.0

**Comment by nedtwigg** [comment]
That URL works for me right now. Solved-ish!

I think it's a caching problem with `javadoc.io` that when a new version comes out, the first person to visit a given link has a not-so-great experience. If you come back a few minutes later I think it will work.
