### ISSUE TITLE
Forcing a specific imports order in java

### ISSUE THREAD

**Issue by Ledmington** [diffplug/spotless#1369]
I am using palantir to format my Java code with gradle and I wanted to force this specific order of imports:
```
<all static imports>
<blank line>
java.*
javax.*
javafx.*
<blank line>
com.*
<blank line>
org.*
<blank line>
<everything else>
```

So far, I only managed to write this `importOrder('java.*', 'javax.*', 'javafx.*', 'com.*', 'org.*', '*')` which compiles but doesn't work. I tried to check the [documentation](https://javadoc.io/doc/com.diffplug.spotless/spotless-plugin-gradle/latest/com/diffplug/gradle/spotless/JavaExtension.html) but it literally says nothing. I noticed that it's also possible to write a separate file just for the ordering but I would like to avoid that.

This is my current spotless configuration:
```
spotless {
	// optional: limit format enforcement to just the files changed by this feature branch
	//ratchetFrom 'origin/main'

	format 'misc', {
		// define the files to apply `misc` to
		target '*.gradle', '*.md', '.gitignore'

		// define the steps to apply to those files
		trimTrailingWhitespace()
		indentWithTabs()
		endWithNewline()
		setEncoding('utf-8')
	}

	java {
		target fileTree('.') {
			include '**/*.java'
			exclude '**/build/**', '**/build-*/**'
		}
		importOrder('java', 'javax', 'javafx', 'com', 'org')
		removeUnusedImports()
		formatAnnotations()
		trimTrailingWhitespace()
		endWithNewline()
		setEncoding('utf-8')
		palantirJavaFormat('2.26.0')
	}
}
```

I am using:
 - gradle 7.5.1
 - spotless gradle plugin 6.11.0
 - lubuntu 22.04

**Comment by Ledmington** [comment]
Oh my god, I am so dumb. Apparently, I never tried to put `importOrder` after the `palantirJavaFormat` call, which does work. I'm sorry for that. But the missing documentation is still a problem, in my opinion.

**Comment by nedtwigg** [comment]
No worries :). From our [quickstart](https://github.com/diffplug/spotless/tree/main/plugin-gradle#quickstart):

> a list of FormatterStep, which are just String -> String functions

People do often bump into the fact that order matters, the way we describe it currently isn't good enough. Happy to merge any PRs which improve the situation.
