### ISSUE TITLE
Provide snippet for adding spotless to gradle

### ISSUE THREAD

**Issue by dpew** [diffplug/spotless#137]
It would be helpful if your README.md included a cut-and-paste snippet for adding the spotless plugin to a gradle file.  Although using it for years I still need the snippet when creating a new project.  Yes, it's found at https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless, however google seems bring up your github site first.

```groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.diffplug.spotless:spotless-plugin-gradle:3.5.1"
  }
}

apply plugin: "com.diffplug.gradle.spotless"
```

**Comment by nedtwigg** [comment]
Whaddya think about #138?

**Comment by dpew** [comment]
Less eye-catching than a cut-and-paste snippet, but still a big help. Looks good.

**Comment by nedtwigg** [comment]
Merged :)
