### ISSUE TITLE
Can not create an EditorConfigOverride without properties. Use 'emptyEditorConfigOverride' instead.

### ISSUE THREAD

**Issue by Jadyli** [diffplug/spotless#1374]
kotlin {
            ktlint("0.47.1")
                .setUseExperimental(true)
                .editorConfigOverride([ 'max-line-length': 120, 'wrapping': false])
        }
Can not create an EditorConfigOverride without properties. Use 'emptyEditorConfigOverride' instead.

When i add `'indent_size': 2` to editorConfigOverride, android studio build success.

- [ ] ktlint 0.47.1
- [ ] gradle 7.5.1
- [ ] spotless 6.11.0
- [ ] win11

**Comment by ymaniz09** [comment]
Same issue here, the only difference is that I'm using Gradle 7.3.0

**Comment by bcmedeiros** [comment]
I did some digging, for the line length, the property needs to be snake case: `org.ec4j.core.model.PropertyType#max_line_length`.

As for `ktlint_disabled_rules`, it's really missing.

**Comment by tcrawford-figure** [comment]
This should be fixed in the next release of ktlint, 0.48.0. PR that fixes it: https://github.com/pinterest/ktlint/pull/1671

However, support for 0.47.x here in spotless would be great!

**Comment by bcmedeiros** [comment]
@tcrawford-figure Adjusted my PR so it's fixed for 0.47.x, let me know what you think.

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle 6.12.0` and `plugin-maven 2.28.0`.
