### ISSUE TITLE
Does spotless has a baseline feature similar to Detekt?

### ISSUE THREAD

**Issue by darthpaul-sanuk** [diffplug/spotless#1382]
Hi all, 
Does spotless have a feature baseline feature similar to Detekt baseline such that if added to an existing project, one doesn't have to apply the fixes for all the files on the project?

**Comment by nedtwigg** [comment]
It does, called `ratchetFrom`

- https://github.com/diffplug/spotless/tree/main/plugin-maven#how-can-i-enforce-formatting-gradually-aka-ratchet
- https://github.com/diffplug/spotless/tree/main/plugin-gradle#how-can-i-enforce-formatting-gradually-aka-ratchet
