### ISSUE TITLE
How to apply check to specific files? 

### ISSUE THREAD

**Issue by keeplearningandtrying** [diffplug/spotless#1384]
This is not really a bug but an inquiry. I have read the info here - https://github.com/diffplug/spotless/tree/main/plugin-maven#can-i-apply-spotless-to-specific-files and even dig into this unit test - https://github.com/diffplug/spotless/blob/main/plugin-maven/src/test/java/com/diffplug/spotless/maven/SpecificFilesTest.java. Still I am out of luck to get this work.

Assume I have a class under src/main/java/com/company/domain/MyDomain.java, how to apply spotless check to this class? I have tried both absolute file path and relative file path. Spotless check will run but this class is not checked.

I have tried the following ways on  MacBook
mvn sportless:check -DspotlessFiles=src/main/java/com/company/domain/MyDomain.java
mvn sportless:check -DspotlessFiles=/full/path/to/project/src/main/java/com/company/domain/MyDomain.java

Could you provide an example? Thank you so much.

**Comment by nedtwigg** [comment]
If you don't use `-DspotlessFiles`, and instead just format all the files, does that work? Possibly the file you are specifying manually is not within the set of formatted files?

**Comment by bwgjoseph** [comment]
If I recall correctly, I tried this previously and wasn't able to use the argument to apply/check for specific file too. It was unclear what is the expected path to the file.
