### ISSUE TITLE
Is there a tool to convert the checkstyle configuration file to the spotless configuration file

### ISSUE THREAD

**Issue by laglangyue** [diffplug/spotless#1387]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem
- [ ] gradle or maven version
- [ ] spotless version
- [ ] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

Is there a tool to convert the checkstyle configuration file to the spotless configuration file

**Comment by nedtwigg** [comment]
Nope. Checkstyle is for warning about problems, Spotless focuses on automatically fixing problems. There are lots of things that you can warn about but can't automatically fix, so the thing you are asking for will probably never happen.
