### ISSUE TITLE
How to stop spotless from merging short lines

### ISSUE THREAD

**Issue by Nevercomes** [diffplug/spotless#1394]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] gradle or maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

### Problems
**before format**
<img width="515" alt="image" src="https://user-images.githubusercontent.com/37074776/201293616-d159d76d-cf72-44d8-b56e-23253484cf83.png">

**after format**
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/37074776/201296053-a940e7a4-425e-4888-8d46-676592ee98c8.png">

### Version
- gradle 7.3.3
- spotless 6.11.0
- MacOS BigSur 11.7

### Spotless Config
```
  spotless {
      format 'misc', {
          target '**/.gitignore', '**/*.gradle', '**/*.md'

          trimTrailingWhitespace()
          indentWithSpaces()
          endWithNewline()
      }
      java {
          importOrder(['java', 'javax', 'com', 'org'] as String)
          removeUnusedImports()

          formatAnnotations()

          eclipse('4.20.0').configFile(rootProject.file('develop/codestyle/p3c-eclipse-codestyle.xml'))

          custom 'Lambda fix', { it.replace('} )', '})').replace('} ,', '},') }
      }
  }
```
codestyle file link: https://github.com/alibaba/p3c/blob/master/p3c-formatter/eclipse-codestyle.xml

And I tried junit5 project's formatter xml(https://github.com/junit-team/junit5/blob/main/src/eclipse/junit-eclipse-formatter-settings.xml), the result is the same.

**Comment by nedtwigg** [comment]
I think you've got two options here.

One is to disable javadoc formatting by setting this to false

https://github.com/alibaba/p3c/blob/6c59c8c36ecd8722c712d5685b8c3822c1c8b030/p3c-formatter/eclipse-codestyle.xml#L397

And the other is to remember that javadoc is meant to be valid HTML, so if you really want an ABC list, then you should do

```java
/**
 * <ul>
 * <li>A. blah blah</li>
 * <li>B. blah blah</li>
 * <li>C. blah blah</li>
 * </ul>
 */
```

The advantage of the HTML approach is that it will look like a list in the generated javadoc too.

**Comment by Nevercomes** [comment]
Thanks a lot!
