### ISSUE TITLE
Upgrade org.codehaus.groovy to org.apache.groovy

### ISSUE THREAD

**Issue by TomBursch** [diffplug/spotless#1399]
I'm using another plugin that uses `org.apache.groovy:groovy:4.0.2` which results in a conflict on capability with the dependency of `org.codehaus.groovy:groovy:3.0.10` required by this project. 

```
com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.11.0 > com.diffplug.spotless:spotless-plugin-gradle:6.11.0 > com.diffplug.spotless:spotless-lib-extra:2.30.0 > org.codehaus.groovy:groovy-xml:3.0.10
```

Starting with version 4.0 the naming changed:
https://groovy-lang.org/releasenotes/groovy-4.0.html

**Comment by ben-snaize-fg** [comment]
We're having the same issue with `react-native-gesture-handler` which requires this. The `groovy-xml` dependency is the problem.

**Comment by nedtwigg** [comment]
The groovy dep has been removed as of `plugin-gradle 6.13.0` and `plugin-maven 2.30.0`.
