### ISSUE TITLE
JavaExtension::eclipse doesn't work in Gradle Script Kotlin for IntelliJ

### ISSUE THREAD

**Issue by JLLeitschuh** [diffplug/spotless#141]
This is a bug in IntelliJ's gradle script kotlin and not spotless but I just want to make you aware of this bug.

Due to these bugs: 
 - https://github.com/gradle/kotlin-dsl/issues/417
 - https://youtrack.jetbrains.com/issue/KT-19310

The following shows up as bad syntax in IntelliJ IDE:
```kotlin
eclipse().configFile(file("$projectDir/eclipse-formatter-settings.xml"))
```

If you remove the deprecated API below then there won't be a way to configure the spotless eclipse formatter.
```kotlin
eclipseFormatFile(file("$projectDir/eclipse-formatter-settings.xml"))
```

It would be great if you could keep the API until after that bug above is resolved.

**Comment by nedtwigg** [comment]
Roger.  It'll stay at least until 4.0, and I don't see any reasons for a breaking change in the near future.  Thanks for the heads-up.

**Comment by nedtwigg** [comment]
Looks like the bugs are resolved.  Feel free to reopen if further issues emerge.
