### ISSUE TITLE
How to use html reporting

### ISSUE THREAD

**Issue by shubham96301** [diffplug/spotless#1411]
I am using spotless for my spring boot gradle based application written mainly in kotlin. How can i generate the html report for the same. 
Tried adding this dependency `com.pinterest.ktlint:ktlint-reporter-html`, not seeing any report generated.
Can someone help if this is even supported, if yes, how to configure with spotless ktlint?

**Comment by nedtwigg** [comment]
Spotless does not support HTML reporting right now, but we might support it after

- #1097

gets merged.
