### ISSUE TITLE
Support for execution during incremental builds with m2eclipse

### ISSUE THREAD

**Issue by kwin** [diffplug/spotless#1413]
[M2E](https://www.eclipse.org/m2e/index.html), the Maven integration feature in Eclipse, can optionally support the execution of Maven Plugins during incremental compilation. For that it is necessary to add some metadata to the plugin and also notify via the plexus-build-api about updates of files: https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html

**Comment by nedtwigg** [comment]
Released in `plugin-maven 2.29.0`.
