### ISSUE TITLE
maven spotless plugin doesn't respect "switch-case"

### ISSUE THREAD

**Issue by AcidS76** [diffplug/spotless#1415]
Hi all, I'm using spotless 2.28.0 with Maven:

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\eclipse-vari\apache-maven
Java version: 17.0.5, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17.0.5
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

I'm here because I would like to know if it's a known problem that option "Expressions in 'switch' case with arrow" and "Expressions in 'switch' case with colon" is not working if I run with Maven even if I correctly format with Eclipse 2022.12? I mean: I have a switch-case statement with a condition with many elements with colon, i.e.:

switch (color) {
    case RED, GREEN, BLACK, BLUE, CYAN, ORANGE, WHITE, PINK:
      return true;
    default:
      return false;
    }

And when I format with Eclipse I correctly get and want as:

    switch (color) {
    case RED,
         GREEN,
         BLACK,
         BLUE,
         CYAN,
         ORANGE,
         WHITE,
         PINK:
      return true;
    default:
      return false;
    }

but with the Maven plugin I get the all in row (case RED, GREEN, BLACK, BLUE, CYAN, ORANGE, WHITE, PINK)..

As JDT format version I use 4.21.0, the last I have seen here https://github.com/diffplug/spotless/tree/main/lib-extra/src/main/resources/com/diffplug/spotless/extra/eclipse_jdt_formatter

Thanks

**Comment by nedtwigg** [comment]
The eclipse formatter has a bazillion options. Probably there is an option which controls this.
