### ISSUE TITLE
Items order in java config is important 

### ISSUE THREAD

**Issue by slawekjaranowski** [diffplug/spotless#1417]
- [x] summary of problem

# working example

```
          <configuration>
            <java>
              <palantirJavaFormat/>
              <removeUnusedImports/>
              <importOrder>
                <order>javax,java,,\#</order>
              </importOrder>
            </java>
          </configuration>
```

Works as I expected.

# not working example

```
          <configuration>
            <java>
              <removeUnusedImports/>
              <importOrder>
                <order>javax,java,,\#</order>
              </importOrder>
              <palantirJavaFormat/>
            </java>
          </configuration>
```

As you see I change position of `palantirJavaFormat` and `importOrder` has no effect is such case 

Second example is based on your documentation.

One more hint - in documentation there is `\\#` for static import - should be `\#`

# Proposition for resolve

fix documentation, and add explain about items order in configuration.

- [x] maven version - 3.8.6
- [x] spotless version - 2.28.0

**Comment by nedtwigg** [comment]
Agreed this is a bug in our docs, thanks for reporting.

**Comment by kwin** [comment]
Instead of fixing the docs would it be possible to make the implementation work irrespective of the order. Having a certain order of elements in XML is totally unexpected.

**Comment by nedtwigg** [comment]
Order will always matter in Spotless, though I know that is unusual for a maven plugin. Why:

- https://github.com/diffplug/spotless/blob/main/PADDEDCELL.md
- https://github.com/diffplug/spotless/blob/main/CONTRIBUTING.md#how-spotless-works
