### ISSUE TITLE
Spotless not running for generated code

### ISSUE THREAD

**Issue by pedro93** [diffplug/spotless#1420]
Not sure if this is a bug but I can't seem to use spotless for my use-case.
I have some code which is autogenerated from an OpenAPI spec that I put into a `generated` folder, I then configure spotless to clean-up the generated code with the following config in my `build.gradle`:

```kotlin
spotless {
    enforceCheck false
    java {
        target "$projectDir/generated/src/main/java/**/*.java"
        removeUnusedImports()
        trimTrailingWhitespace()
        indentWithSpaces()
        googleJavaFormat()
    }
}
```

This is what my folder structure looks like:
```bash
├── build.gradle
├── generated
│   └── src
│       └── main # <- Generated OpenAPI code
└── src
    ├── main
    │   ├── java
    │   └── resources
    └── test
        └── java
```

When running `gradlew spotlessApply` I don't see any code changes in the code under `generated`. 
Running this on an M1 Mac in IntelliJ with the gradle plugin `"com.diffplug.spotless:spotless-plugin-gradle:6.12.0"`

Thank you.

**Comment by nedtwigg** [comment]
`spotlessDiagnose` is for a different thing ([formatting cycles](https://github.com/diffplug/spotless/blob/main/PADDEDCELL.md) which is not the problem here)

It looks like it should work, probably something silly going on. 

```gradle
// maybe instead of this
target "$projectDir/generated/src/main/java/**/*.java"

// try this
target "generated/src/main/java/**/*.java"

// or at least do
println("$projectDir/generated/src/main/java/**/*.java")
// to see if something funny is happening
```

**Comment by nedtwigg** [comment]
Feel free to add more data or best of all a public repo that reporoduces the data.
