### ISSUE TITLE
Does the `configuration/java/eclipse/file` tag support maven-dependency-plugin for jar reference?

### ISSUE THREAD

**Issue by me0106** [diffplug/spotless#1424]
Does the `configuration/java/eclipse/file` tag support maven-dependency-plugin for jar reference?

I try to get spotless.xml from inside a dependency jar.

like this:
```xml
        <dependency>
            <groupId>myGroupId</groupId>
            <artifactId>artifactId</artifactId>
        </dependency>
......
       <configuration>
             <java>
                   <eclipse>
                        <file>jar:file:${myGroupId:artifactId:jar}!/spotless.xml</file>
                   </eclipse>
               </java>
      </configuration>
```
I got a error "Could not find resource 'jar:file:${myGroupId:artifactId:jar}!/spotless.xml'." .

expect: `jar:file:[AbstractJarPath]!/spotless.xml` .

**Comment by lutovich** [comment]
Hi @me0106,

Sorry for the delayed response here!

In my experience, the typical configuration to read formatter configuration file from a JAR looks like this:
```xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.31.0</version>
    <dependencies>
        <dependency>
            <groupId>com.my.project</groupId>
            <artifactId>my-build-resources</artifactId>
            <version>1.2.3</version>
        </dependency>
    </dependencies>
    <configuration>
        <java>
            <eclipse>
                <file>build-resources/my-eclipse.xml</file>
            </eclipse>
        </java>
    </configuration>
</plugin>
```

Where `com.my.project:my-build-resources:1.2.3` is either a submodule of the same multi-module project or a separate dependency. It contains the needed configuration file for the Eclipse formatter - `build-resources/my-eclipse.xml`.

Spotless Maven plugin also supports fetching configuration files from a URL:
```xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.31.0</version>
    <configuration>
        <java>
            <eclipse>
                <file>http://my-company/my-eclipse.xml</file>
            </eclipse>
        </java>
    </configuration>
</plugin>
```

Would any of the above options work for you?

I think reading files from a JAR might not be fully supported but I can't fully understand the use case. Could you please provide a sample project to reproduce the problem or complete plugin XML configuration?
