### ISSUE TITLE
Warnings with Gradle 4.2

### ISSUE THREAD

**Issue by boris-petrov** [diffplug/spotless#145]
```
The name 'spotlessSource files' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0

The name 'spotlessSource filesCheck' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0

The name 'spotlessSource filesApply' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0
```

I'm not sure if it's a problem with you or with something I've written. Any ideas?

**Comment by nedtwigg** [comment]
We'd need to see your build.gradle.  It looks like you created a source set called `'Source files'`, which means that the tasks based on it have a space in their name, which is going to become an error in Gradle 5.

**Comment by boris-petrov** [comment]
Thanks for the quick response! I see now - I don't have a sourceset named "Source files" but rather a Spotless `format` name:

```gradle
spotless {
	format 'Source files', {
		target fileTree('.')

		trimTrailingWhitespace()
		indentWithSpaces()
		endWithNewline()
	}
}
```

I renamed it and this fixed the issue. You could write that in the documentation. Thanks again!
