### ISSUE TITLE
Speedup "npm install" step for npm-based formatters

### ISSUE THREAD

**Issue by simschla** [diffplug/spotless#1480]
From discussion in #1453 

Npm-based formatters require an npm install call to prepare running the npm process for formatting.
It would be nice if we could speedup that part (or alltogether prevent it, if it is not needed).
Some ideas:

1. Store the `node_modules`-directory and `package.json` somewhere in build-folder and copy/link those on later calls.
2. Similar, but more longevity: Store these folders/files somewhere in `$HOME/.cache/spotless/npm` and reuse/copy/link them from there? 
3. Gradle-specific: Leverage gradle's build-cache by creating a gradle task that generates the `package.json` and `node_modules` dir as (cachable) output. A second/third run would then just receive these files/folders from the build cache?

**Comment by nedtwigg** [comment]
I'm fine with any of the above, but I think you have the order right. I would implement 2, but I would set `build/spotless-npm` as the root. Make it an option to set something else, such as `~/.cache/spotless-npm` to be the root, but I wouldn't start with that as the default.

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 6.16.0` and `plugin-maven 2.34.0`.
