### ISSUE TITLE
palantirJavaFormat with indent

### ISSUE THREAD

**Issue by cemo** [diffplug/spotless#1483]
I am trying to override palantir java format indentation but I guess it is not working properly. It ended up 4 space.

I am using maven and macos. 

```
<configuration>
  <java>
    <palantirJavaFormat>
      <version>2.27.0</version>
    </palantirJavaFormat>

    <indent>
      <tabs>true</tabs>
      <spacesPerTab>2</spacesPerTab>
    </indent>
</configuration>
```

How can I change palantir indentation?

**Comment by nedtwigg** [comment]
palantirJavaFormat indents with 4 spaces. If you want to replace those 4 spaces with a tab, then you want `spacesPerTab = 2`, not `4`.

If you want to indent with only 2 spaces instead of 4, then you need to do

```
palantirJavaFormat // indent with 4-spaces
indent tabs=true spacesPerTab=4 // turn 4-spaces into a tab
indent tabs=false spacesPerTab=2 // turn a tab into 2 spaces
```

**Comment by cemo** [comment]
Would you please a give a try with maven plugin? I can not see what is wrong on my configuration.
Without Palantir I can successfully changed my indentation. However it is not working with it.

**Comment by nedtwigg** [comment]
If you make a repo I can clone, I'd be happy to clone and do a `spotless:apply`.

**Comment by cemo** [comment]
@nedtwigg 

Here is a sample project https://github.com/cemo/sample-spotless

You can see that it is not formatting properly.

**Comment by nedtwigg** [comment]
I cloned your project, here is the fix. I explained this in pseudocode above.

```xml
<palantirJavaFormat>
	<version>2.27.0</version>
</palantirJavaFormat>
<indent>
	<tabs>true</tabs>
	<spacesPerTab>4</spacesPerTab>
</indent>
<indent>
	<spaces>true</spaces>
	<spacesPerTab>2</spacesPerTab>
</indent>
```

For more details on why it works this way:

- https://github.com/diffplug/spotless/blob/main/PADDEDCELL.md
- https://github.com/diffplug/spotless/blob/main/CONTRIBUTING.md#how-spotless-works

**Comment by cemo** [comment]
Thank you. I really did not see your comments in your code before. However it is already different.

The first one you suggested:

```
palantirJavaFormat // indent with 4-spaces
indent tabs=true spacesPerTab=4 // turn 4-spaces into a tab
indent tabs=false spacesPerTab=2 // turn a tab into 2 spaces
```

and the last one which is really working is: 

```
<palantirJavaFormat>
	<version>2.27.0</version>
</palantirJavaFormat>
<indent>
	<tabs>true</tabs>
	<spacesPerTab>4</spacesPerTab>
</indent>
<indent>
	<spaces>true</spaces>
	<spacesPerTab>2</spacesPerTab>
</indent>
```

I must say that it is counter intuitive but thank your explaining.

**Comment by bmarwell** [comment]
For those who stumble across this: The suggested setup currently breaks multiline strings: https://github.com/diffplug/spotless/issues/1628
