### ISSUE TITLE
Spotless 6.13.0 has not been published to `gradlePluginPortal`

### ISSUE THREAD

**Issue by Goooler** [diffplug/spotless#1488]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem
- [x] gradle or maven version
- [ ] spotless version
- [ ] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

```
Plugin [id: 'com.diffplug.spotless', version: '6.13.0', apply: false] was not found in any of the following sources:

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.diffplug.spotless', version: '6.13.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.13.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    Google
    MavenRepo
```

https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless

**Comment by nedtwigg** [comment]
Fixed now.
