### ISSUE TITLE
Investigate removal of usage of internal Gradle APIs

### ISSUE THREAD

**Issue by jbduncan** [diffplug/spotless#149]
The only internal API that comes to mind yet is `org.gradle.api.internal.file.UnionFileCollection`, which is used in [FormatExtension.java](https://github.com/diffplug/spotless/blob/master/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java).

The advantage of moving away from internal APIs, if we can do so, is the Gradle plugin would be more future-proof in the face of internal Gradle changes.

**Comment by JLLeitschuh** [comment]
It's also used in the `JavaExtension` and in the `KotlinExtension`.
Wow, I totally didn't realize I'd done that when I wrote my addition to the plugin. Yea, that should totally be fixed.

**Comment by nedtwigg** [comment]
I'm not worried about a few internal utility classes, but if you do pull them out, make sure to use [`spotlessSelf.gradle`](https://github.com/diffplug/spotless/blob/8c428d9eea6b88994b83c636f6b559594ea1abab/spotlessSelf.gradle#L11-L23) to keep them out.  We already ban `org.gradle.internal`, but not `org.gradle.api.internal`.
