### ISSUE TITLE
Ktlint rules will be invalid if I override an invalid rule of `EditorConfig` in Spotless 6.13.0

### ISSUE THREAD

**Issue by Goooler** [diffplug/spotless#1495]
1. Override Ktlint rules with `ktlint("0.48.1").editorConfigOverride(mapOf("ktlint_filename" to "disabled"))`, but the `ktlint_filename` is invalid, it should be `ktlint_standard_filename` in Ktlint 0.48.1.
2. Make a style conflict in any kt file.
3. Run `./gradlew spotlessCheck` but without exception thrown.

My Spotless config:
```kotlin
    configure<SpotlessExtension> {
        kotlin {
            target("**/*.kt")
            targetExclude("$buildDir/**/*.kt")
            targetExclude("bin/**/*.kt")
            ktlint("0.48.1").editorConfigOverride(mapOf("ktlint_filename" to "disabled"))
            licenseHeaderFile(rootProject.file("spotless/copyright.txt"))
        }
    }
```
My env: Gradle 7.6 & Spotless 6.13.0 & Ktlint 0.48.1 & MacOS 13.1, you can repro this issue on https://github.com/Goooler/tivi/pull/6.

**Comment by nedtwigg** [comment]
Released in `plugin-gradle 6.14.0` and `plugin-maven 2.31.0`.
