### ISSUE TITLE
Custom gradle Java plugin embarking spotless : How To ?

### ISSUE THREAD

**Issue by jgiretimhaus** [diffplug/spotless#1498]
Hey, following the readme, I've successfully added Spotless java formatting to a java project and it has been ... well, spotless 😄
 
Since the test has been really conclusive, I'm now trying to apply spotless to all our Java repos (200+).

I created a common custom Gradle plugin that would hold Spotless plugin (including a default java configuration). 

*Objective* : apply this project to all concerned repos by just adding one single line in each repo build.gradle file like the following: 
 
```gradle
plugins {
    id 'customSpotlessPlugin' version '1.0'
}
```
 
It started well but I've hit a problem with the Spotless configuration that is supposed to be put in the `build.gradle`
Let's pretend I have my CustomSpotlessPlugin and that I am trying to import it in a Consumer project.
In my CustomSpotlessPlugin, I have :
 
```java
public  class  CustomSpotlessPlugin  implements Plugin<Project> {
    @Override
    public  void  apply(Project  project) {
        project.getPluginManager().apply(com.diffplug.gradle.spotless.SpotlessPlugin.class);
    }
}
```
 
and in my build.gradle :
 
```gradle
plugins {
  id 'java-library'
  id 'java-gradle-plugin'
  id 'maven-publish'
  id 'com.diffplug.spotless' version '6.12.1'
}
 
//
//other gradle stuff
//
 
spotless {
  java {
    // Use the default importOrder configuration
    importOrder()
    //importOrderFile('eclipse-import-order.txt') // import order file as exported from eclipse
    // Choose one of these formatters.
    //googleJavaFormat() // has its own section below
    eclipse() // has its own section below
    removeUnusedImports()
    trimTrailingWhitespace()
    endWithNewline()
    formatAnnotations() // fixes formatting of type annotations, see below
    licenseHeader '/* (C) XXX $YEAR */' // or licenseHeaderFile
  }
}
```
then when I import CustomSpotlessPlugin in Consumer Project, I see the `spotlessApply` & `spotlessCheck` tasks appearing in the **gradle verification/** folder of the Consumer project.
 
The problem I encounter is that the configuration doesn't port over and is not available to my Consumer Project. So I don't get all the nice `spotlessJavaApply`, `spotlessJavaCheck` & tutti quanti.
 
My questions are :
 
1. Is my approach correct ?
 
2. I'm almost sure it has been done before, and hopefully documented but I've found nothing after spending days trying to break the matrix lol. Please, kindly point me to it if it exists :) 
 
3. How can I implement the Spotless java formatter configuration only once (in my custom Plugin) so it will be available in my Consumer project ? (plugin build.gradle or in the apply code section of CustomSpotlessPlugin)
 
Many thanks

**Comment by nedtwigg** [comment]
> How can I implement the Spotless java formatter configuration ... in my custom Plugin

Like this:

```java
public  class  CustomSpotlessPlugin  implements Plugin<Project> {
    @Override
    public  void  apply(Project  project) {
        project.getPluginManager().apply(com.diffplug.gradle.spotless.SpotlessPlugin.class);
        SpotlessExtension extension = project.getExtensions().getByType(SpotlessExtension.class);
        extension.java(java -> {
            java.googleJavaFormat();
        });
    }
}
```

> Is my approach correct

You are building a "convention plugin", and I think the Gradle team officially recommends this. FWIW, I am strongly against them, I think that [blowdryer](https://github.com/diffplug/blowdryer) solves this problem better.

In particular, it's common that you'll want to provide a configuration file as input to Spotless or some other plugin. You can put one into your `src/main/resources` and extract it somewhere, but there's quite a bit of complexity to this with a convention plugin, and Blowdryer has none of those problems.

**Comment by jgiretimhaus** [comment]
Thanks a lot for your fast and detailled answer ! It worked spotlessly 😉 

I'll look into blowdryer today and "convention plugins". Thanks again and have a nice day
