### ISSUE TITLE
Plugin applied to a common gradle script causes issues

### ISSUE THREAD

**Issue by BrainStone** [diffplug/spotless#150]
When I apply the spotless plugin in a common script I get an error related to the plugin trying to add another plugin, when the buildscript repos aren't available in the project build script.

Example:

`common.gradle`:
```gradle
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            name "Gradle-Plugins"
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath "com.diffplug.spotless:spotless-plugin-gradle:3.5.2"
    }
}

apply plugin: "java"
apply plugin: com.diffplug.gradle.spotless.SpotlessPlugin

spotless {
    java {
        googleJavaFormat()
    }
}
```

`build.gradle`:
```gradle
apply from: "common.gradle"
```

This results in this error (shortened. See gist link below excerpt):
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':detachedConfiguration2'.
> Cannot resolve external dependency com.google.googlejavaformat:google-java-format:1.3 because no repositories are defined.
  Required by:
      project :
```

https://gist.github.com/BrainStone/14f0590ad092fd853a7f7cf59369b06b

It is fixed by using this `build.gradle`:
```gradle
apply from: "common.gradle"

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

However this is highly undesrired, as I try to keep stuff like that out of the actual build script.

**Comment by nedtwigg** [comment]
My understanding is that the `buildscript {}` block in your `common.gradle` doesn't do anything, unfortunately.  It's not possible to change the classpath of a buildscript anywhere except in that script.

One solution is to put this into your root project.

```gradle
allprojects {
    buildscript {
        repositories {
            jcenter()     
```

**Comment by BrainStone** [comment]
It's mostly just single projects. I might try adding that into the common.gradle file.

**Comment by BrainStone** [comment]
Small update, putting that in the common script actually worked!

**Comment by nedtwigg** [comment]
Huh!  Never woulda guessed, but glad it works!
