### ISSUE TITLE
Enable Option to Disable Javadoc-Formatting for Google Java Format

### ISSUE THREAD

**Issue by FireRedDev** [diffplug/spotless#1501]
Hey! GJF added the option to disable formatting of javadoc. 
EDIT: https://github.com/diffplug/spotless/issues/1287 already handles this but:
i would in general just like for the formatter to ignore comments, google java format still seems to format linebreaks in javadocs
is this possible to set? i couldnt find it in the example

**Comment by nedtwigg** [comment]
> i would in general just like for the formatter to ignore comments, google java format still seems to format linebreaks in javadocs

Spotless is mostly a switchboard for other formatters. We do have [`spotless:off/on` tags](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson) which you can use to preserve a specific section.

It would be possible to use that same technique to store *all* comments and then restore them after `gjf` or other steps have mangled them, but it would be very difficult. I don't think it's worth the effort, but I'd be happy to merge a PR which supports full comment preservation. My recommendation would be to

- Look at this PR first, which implements the easy part of what you'll need
  - https://github.com/diffplug/spotless/pull/691
- Now write the docs for your new step and open a draft PR to get feedback on the plan
- Now you'll need to parse comments, save them as per the PR above, and then restore them into the newly changed code (hard!!!)

Or, you can submit a PR to GJF or maybe palantir-java-format to get them to ignore comments. Once they have the feature, turning it on in Spotless would be easy.
