### ISSUE TITLE
Support Eclipse formatter 4.7.0

### ISSUE THREAD

**Issue by simonnagl** [diffplug/spotless#151]
When do you plan to support eclipse formatter 4.7.0? It seems the formatting changed in some cases without changing the preferences.

**Comment by nedtwigg** [comment]
Thanks for bringing this to our attention, we'll have this out in a few hours.

**Comment by nedtwigg** [comment]
You can now get version `4.7.0` or `4.7.1` like this:

```gradle
spotless {
    eclipse('4.7.0').configFile ...
```

`4.7.1` will be the default version in future versions of spotless, but we're not going to cut a new release for just a changed default.

**Comment by simonnagl** [comment]
Wow, this was fast! Thank's for the amazing project!
