### ISSUE TITLE
Failed to create Jar file groovy-2.9.98-SNAPSHOT.jar

### ISSUE THREAD

**Issue by shafty023** [diffplug/spotless#1548]
If you are submitting a **bug**, please include the following:

- summary of problem
When switching from spotless plugin 6.12.1 to 6.13.0 or 6.14.0 the build fails and throws the error:
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /Users/XXXX/.gradle/caches/jars-9/b3aed8604d58bde5d3b1fd37dd7831dc/groovy-2.9.98-SNAPSHOT.jar. The issue does not happen while on version 6.12.1. 

- gradle version
7.3.3

- spotless version
Issue happens on 6.13.0

- operating system and version
MacOS Ventura 13.2

- copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```
spotless {
    java {
        target project.fileTree(dir: 'src', include: '**/*.java',
                exclude: ['**/apache/**/*.java', '**/com/android/**/*.java'])

        indentWithSpaces()
        trimTrailingWhitespace()

        replaceRegex 'Modifier order 1', '^(\\s*)((?:static)|(?:final)|(?:abstract))\\s+((public)|(protected)|(private))\\s',
                '$1$3 $2 '
        replaceRegex 'Modifier order 2', '^(\\s*)final\\s+static\\s+((public)|(protected)|(private))\\s', '$1$2 static final '
        replaceRegex 'Modifier order 3', '^(\\s*)static\\s+final\\s+((public)|(protected)|(private))\\s', '$1$2 static final '
        replaceRegex 'Modifier order 4', '^(\\s*((public)|(protected)|(private))?\\s*)\\sfinal\\s+static', '$1 static final'
        replaceRegex 'Remove empty lines before end of block', '\\n[\\n]+(\\s*})(?=\\n)', '\n$1'
        replaceRegex 'Remove trailing empty comment lines.', '\n\\s*\\*(\n\\s*\\*/\n)', '$1'
    }
    kotlin {
        target project.fileTree(dir: 'src', include: '**/*.kt')

        trimTrailingWhitespace()
        ktlint("0.48.0")
    }
}
```

- copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
Unable to execute this command as the failure happens during configuration phase

If you're just submitting a feature request or question, no need for the above.

**Comment by shafty023** [comment]
I am still running into this issue. What do you need from my end to help debug this?

./gradlew :spotlessCheck

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

> Configure project :

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'MyApp'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /Users/myuser/.gradle/caches/jars-9/b3aed8604d58bde5d3b1fd37dd7831dc/groovy-2.9.98-SNAPSHOT.jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
6 actionable tasks: 5 executed, 1 up-to-date

**Comment by varunam** [comment]
How is this solved? I am also facing it while upgrading Spotless From 6.12.0 to 6.13.0

**Comment by varunam** [comment]
Thank you @shafty023. I will give it a try.

**Comment by varunam** [comment]
It worked. Thank you @shafty023.
