### ISSUE TITLE
Gradle: format generated sources

### ISSUE THREAD

**Issue by rolfw** [diffplug/spotless#155]
Spotless works great and I'm very happy with it. I'd like the plugin to format generated sources as well, so that all source code is consistently formatted when debugging. I haven't been able to get them formatted though;

## Attempt: changing the order of tasks
I initially thought sources are being generated in the `compileJava` task and spotless formats before this task is executed (which would make sense because then .class files and .java files are consistent). However, when I add a dependency to `javaCompile` the generated sources are still not formatted:

```
project.afterEvaluate{

    compileJava.dependsOn("licenseFormat")
    spotlessApply.dependsOn("compileJava")
}
```

## How to format generated sources?

What is the recommended way to format sources? My sources are generated in `build/generated/source/apt` and this is my current spotless config:

```
spotless {

    enforceCheck = false

	format 'misc', {
		target '**/*.gradle', '**/*.md', '**/.gitignore'

		trimTrailingWhitespace()
		indentWithTabs()
		endWithNewline()
		paddedCell() /* Makes sure build succeeds, even if formatting fails. See https://github.com/diffplug/spotless/blob/master/PADDEDCELL.md */
	}

	java {

		target fileTree(rootDir) {
			include '**/*.java'
		}

		removeUnusedImports() // removes any unused imports

		eclipse().configFile 'src/build/resources/eclipse-java-formatter-config.xml'

		paddedCell()    /* Makes sure build succeeds, even if formatting fails. See https://github.com/diffplug/spotless/blob/master/PADDEDCELL.md */
	}
}

**Comment by JLLeitschuh** [comment]
What task do you use to generate source code? Simply making that task a dependency of `spotlessApply` should work.

**Comment by rolfw** [comment]
I use [gradle-apt-plugin](https://github.com/tbroyer/gradle-apt-plugin), which configures JavaCompile and GroovyCompile tasks for annotation processing. So it's done as part of compiling, not as a separate task. Currently my compileJava task depends on spotless so that the sources are formatted on every compile:
```
project.afterEvaluate {
	compileJava.dependsOn("spotlessApply")
}
```
I removed the target from the config and confirmed that generated sources are being formatted when I run `gradle spotlessApplyJava` after the sources have been generated. 

Given all this, how can I change the build script so it also formats the generated sources on every compile? After experimenting a bit, I found that the following works (after removing `compileJava.dependsOn("spotlessApply")`):

```
tasks.withType(JavaCompile) {JavaCompile task ->
	task.finalizedBy 'spotlessJavaApply'
}
```

However, I suspect that formatting the sources after compiling is not a good idea because the line numbers in the sources may differ from those in the .class files if formatting changes results in moving code across lines? 

If so, how can I change the build script so that both the sources and generated sources are formatted each time? I'm currently trying to create a `generateSources` task that executes `compileJava` with the `proc:only` option, and make `compileJava` depend on `generateSources`. 

This should first do the annotation processing and then compile the generated + original sources (and formatting can be done in between). This doesn't seem possible though (running compileJava twice). Do you have any suggestions for other approaches?

**Comment by JLLeitschuh** [comment]
It's also probably a bad idea because you won't get the Java incremental compilation stuff.

Is there a task that the `gradle-apt-plugin` add that you can say that `spotlessJavaApply` can depend upon?

**Comment by rolfw** [comment]
That's a good point, I like it incremental :)

I'm afraid the apt plugin doesn't add any tasks, it only modifies the existing JavaCompile tasks. If it would, that would solve some other problems I'm having too (unrelated to spotless).

**Comment by nedtwigg** [comment]
If you wanted to generate sources, then format those sources, and maintain incremental-build support, then I think you'd need a structure like this

- sourceSet main -> src/main/java
- sourceSet generatedUnformatted -> src/main/generated-unformatted
- generated -> src/main/generated

`spotless` would need to slurp code from `generated-unformatted`, and output it into `generated` (which is currently unsupported


classes would need to com

**Comment by nedtwigg** [comment]
If you wanted to generate sources, then format those sources, and maintain up-to-date support (not just incremental, but any kind of up-to-date), then you need a structure like this:

- task generateCode `src/main/java -> src/main/generated-unformatted`
- task spotlessApply `src/main/generated-unformatted -> src/main/generated`
- task compile `(src/main/java, src/main/generated) -> build/classes`

Unless you have that intermediary `generated-unformatted` dir, then you're mashing the results of a previous task, which means that the `generateCode` task will never be up-to-date, thus `spotlessApply` and `compile` will never be up-to-date either.

Spotless does not support this mode of operation right now.  I'm a big fan of code-generation, but I personally don't care how it's formatted any more than how my `.class` files are formatted.  If you wanted to format the generated code, you'd need to:

- break-up your code generator so that it doesn't compile the generated code automatically
- add support for spotless to slurp from one place and output to another
- remove the generated code from compilation, and inject the formatted code for compilation

Those tasks seem like a lot of work for little benefit to me, but I'm happy to merge PR's for it if they don't add too much complexity to the docs or implementation.

**Comment by rolfw** [comment]
Thanks for your comments. I was thinking along the same lines and asked this question on stackoverflow: [Gradle+apt: a generateSources task to execute before compiling](https://stackoverflow.com/questions/47338146/gradleapt-a-generatesources-task-to-execute-before-compiling)

The reason I'd like to format generated sources as well is to have them consistent with regular sources, for easier debugging in case of apparent problems with processors or my use thereof. But the main reason is to prevent secondary compilation errors (see SO question).

So having a separate task as you suggest seems like the best solution. I'm not particularly experienced with Gradle or Groovy; Do you happen to know how to do this?

**Comment by nedtwigg** [comment]
> Do you happen to know how to do this?

Nope :)

**Comment by JLLeitschuh** [comment]
It would need to be something that the plugin developer implements if what you get right now comes "for free" when the plugin is applied.

**Comment by rolfw** [comment]
Thanks for both your suggestions. I added a feature request for `gradle-apt-plugin` [here](https://github.com/tbroyer/gradle-apt-plugin/issues/71).
