### ISSUE TITLE
ktlint gradle docs incorrect method names

### ISSUE THREAD

**Issue by gotson** [diffplug/spotless#1550]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] gradle version: 7.6
- [x] spotless version: 6.14.0
- [x] operating system and version: macOS 13.2
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

I can't use `editorConfigPath` for the ktlint extension in Kotlin Script using Gradle:

```kotlin
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
      targetExclude("**/db/migration/**")
      ktlint("0.46.1")
         .editorConfigPath("$rootDir/.editorconfig")
    }
  }
```

IntelliJ highlights an error: `Cannot access 'editorConfigPath': it is private in 'KotlinFormatExtension'`

```
Expression 'editorConfigPath' of type 'FileSignature?' cannot be invoked as a function. The function 'invoke()' is not found
```

**Comment by nedtwigg** [comment]
Try `setEditorConfigPath`

https://github.com/diffplug/spotless/blob/fd40aa751ea502062d38287af6c47079c48cde16/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinExtension.java#L99-L107

Looks like our docs are wrong

https://github.com/diffplug/spotless/tree/main/plugin-gradle#ktlint
