### ISSUE TITLE
Sport for Groovy Android Plugin

### ISSUE THREAD

**Issue by AndrewReitz** [diffplug/spotless#157]
When using spotless with groovy formatting for a project that is using groovy an exception is thrown saying that the groovy plugin needs to be applied. Since this is an Android project the regular groovy plugin provided by gradle cannot be used but [groovy-android-gradle-plugin](https://github.com/groovy/groovy-android-gradle-plugin) can be instead.

**Comment by nedtwigg** [comment]
Have you tried setting the target manually?

**Comment by AndrewReitz** [comment]
That worked! Is that required for the Android plugin in general? Noticed a lot of things don't get applied if you don't specify a target.

**Comment by nedtwigg** [comment]
All the language-specific plugins (Java, Groovy, Scala, Kotlin) use the default language plugin to set the target *if* no target is specified.  So if you're not using the default language plugin, you can avoid the troubles by setting the target yourself.  We're open to PR's that add support for other plugins, [this would be the place to do it](https://github.com/diffplug/spotless/blob/6d6c0d06745bdfb460f569d5fccb772ef67b0fbe/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GroovyExtension.java#L124-L143).

**Comment by AndrewReitz** [comment]
Thanks, is there a place to have kotlin and Java automatically added instead of specifying a target as well? Guessing it's something similar.

**Comment by nedtwigg** [comment]
Yup, it's almost exactly the same.
