### ISSUE TITLE
To integrate spotless apply while saving the file in Intellij

### ISSUE THREAD

**Issue by subhashiniv** [diffplug/spotless#1597]
Hello Team,

I have integrated spotless gradle plugin in build.gradle and that works perfectly. To format the code, we run spotless java apply task in gradle. I am looking for integrating spotlessjava apply and spotlessgroovy apply tasks as part of saving the file (ctrl+s) in Intellij. Could you please let me know the steps or point me to the documentation links if there are any.

I tried with ExternalTools setup in Intellij to assign a shortcut for the gradle spotless tasks, but didn't work for me.

Thanks.

Regards,
Subha

**Comment by jbduncan** [comment]
@subhashiniv Welcome! There are two solutions you can try:

1. IntelliJ has a neat feature where if you tap <kbd>Ctrl</kbd>+<kbd>Ctrl</kbd> (so <kbd>Ctrl</kbd> twice in a row), you can enter your desired Gradle command (or any terminal command for that matter) and hit Enter to run it. So you could tell IntelliJ to run `gradle spotlessApply` this way. On future taps of <kbd>Ctrl</kbd>+<kbd>Ctrl</kbd>, that command will be at the top of the dialog, so on future invocations, you only need to tap <kbd>Ctrl</kbd>+<kbd>Ctrl</kbd>+<kbd>Enter</kbd>.
2. Spotless has a third-party IntelliJ plugin, which you can find in the [JetBrains Marketplace] (https://plugins.jetbrains.com/plugin/18321-spotless-gradle). I've never used it though, so YMMV.

I hope this helps.

**Comment by subhashiniv** [comment]
Thanks for your response.
