### ISSUE TITLE
configuration cache warning in Android Studio

### ISSUE THREAD

**Issue by WildOrangutan** [diffplug/spotless#1601]
I've noticed in change logs, that configuration cache support was added. But, when using latest spotless version, my Android studio, still produces a [warning](https://user-images.githubusercontent.com/5972966/222399703-5b39b96b-f377-4763-8bb4-319a9429fae2.png), that spotless in not compatible.

With some open issues and this warning I'm confused, is spotless actually safe to use with configuration cache?

**Comment by nedtwigg** [comment]
That warning is surprising to me, thanks for reporting! I wonder if it's specific to Android studio...

Spotless is safe to use with configuration cache, in that it will either behave correctly or fail the build and error loudly with this message

> Spotless JVM-local cache is stale. Regenerate the cache with
rm -rf .gradle/configuration-cache

**Comment by ColtonIdle** [comment]
Got the same issue. i have a bunch of plugins. but AS likes to single spotless out. lol

<img width="1380" alt="2023-08-30 at 20 52 58" src="https://github.com/diffplug/spotless/assets/31751141/7e1eb0d5-5544-45a7-a862-f0a0a9d581d2">

**Comment by nedtwigg** [comment]
This should be fixed in `plugin-gradle 7.0.0.BETA4` and later.

**Comment by ColtonIdle** [comment]
NOOOO WAY! Thank you @nedtwigg !!!
