### ISSUE TITLE
[Feature Request] Additional <exclude> on a per-step basis

### ISSUE THREAD

**Issue by blacelle** [diffplug/spotless#1607]
In some cases, one need to exclude some step for some files. It happens in project requiring faulty code to remain faulty.

For instance :

- https://github.com/skylot/jadx/pull/1792
- Anything in https://github.com/solven-eu/cleanthat/tree/master/java/src/test/java/eu/solven/cleanthat/do_not_format_me

This need is especially useful with new steps enabling linting (cleanthat, [eclipse cleanup](https://github.com/diffplug/spotless/pull/1587), etc), which is more opinionated than formatting.

- I believe it would be bad that each step implement implement its own exclusion mechanism, which it could be one way to go (through `FilterByFileFormatterStep`).
- Is there any existing mechanism to achieve this ?
- Is this was introduced as a new-feature, what would be the recommended design?

**Comment by nedtwigg** [comment]
There is no existing mechanism to achieve this. I would probably name it `skipStep`. Something like

```gradle
skipStep('cleanthat').forFiles('Blah.java')
```

It is blocked on #1096. I try very hard not to be a blocker for things that people want to get merged, but there's a couple structural things that are piling up while I remain responsive on minor issues. I'm going to go dark on issues and PR's for the rest of this week until I am able to get a few of these blockers completed and merged.

**Comment by nedtwigg** [comment]
- This is now possible in `plugin-gradle 7.0.0.BETA4`. Making this possible in maven will require #2309.
