### ISSUE TITLE
Running spotless throws git related exception due to /usr/etc not existing

### ISSUE THREAD

**Issue by staffanf** [diffplug/spotless#164]
When I run spotless I sometimes get exceptions like the one below.
```Ξ main → ./gradlew --parallel spotlessApply
Parallel execution is an incubating feature.

> Task :SubProjA:spotlessJava
Exception caught during execution of command '[git, config, --system, --edit]' in '/usr/bin', return code '128', error message 'fatal: Invalid path '/usr/etc': No such file or directory
'
```

It does not fail so it's probably caught and logged somewhere but I'm unsure if it affects if the task did it's work.
Anyhow it's annoying now that gradle outputs very little a a default.
Also I don't understand why spotless wan't to check my git config...line endings?

**Comment by jbduncan** [comment]
Hi @staffanf, ta for raising this! Can you provide us with an [MVCE](https://stackoverflow.com/help/mcve) or some instructions to help us reproduce this?

**Comment by staffanf** [comment]
I have been trying to do this... seems to be hard to get a small example to fail, my complete multi project build where I use git-p4 fail pretty often but in a simple gradle init project not so much apparently.
If I run the failing command in my /usr/bin I get the same output on stderr and sometimes this error seems to be forwarded to the gradle output and sometimes (mostly) not...
This line 
https://github.com/eclipse/jgit/blob/176466ed281f85f2ba92ae8b605fb43eb3e010d9/org.eclipse.jgit/src/org/eclipse/jgit/util/FS.java#L639 seems to run such a command and spotless/lib-extra/src/main/java/com/diffplug/spotless/extra/GitAttributesLineEndings.java seems to be using these config classes so I guess it originates from there.
It seems if there is a CommandException, it will do a Log.warn() so I guess this is forwarded to gradle.

https://github.com/eclipse/jgit/blob/176466ed281f85f2ba92ae8b605fb43eb3e010d9/org.eclipse.jgit/src/org/eclipse/jgit/util/FS.java#L515 indicates that it is not certain that stderr will always be read, but rather readpipe() will more often continue with it's work.

For me this indicates that there is some kind of race condition here whether the error will be logged.

Sorry I can't supply I proper reproducible example at this time.

**Comment by nedtwigg** [comment]
> Also I don't understand why spotless wan't to check my git config...line endings?

Correct.  If spotless doesn't handle line endings the same way as git, then they will fight each other.  And in order to know what git is doing, we have to match git's behavior exactly.  We haven't updated our version of jgit in a long time, it's possible the newer version has a fix for your warnings.  I just bumped it to the latest (from 4.5.0 to 4.9.0).

Can you try `3.7.0-SNAPSHOT`, which lives in the `https://oss.sonatype.org/content/repositories/snapshots/` repository, and let us know if it fixes your problem?  If it doesn't, a fix will require changes somewhere in [this code](https://github.com/diffplug/spotless/blob/d349656c5cf414cd4f28f2232f55b9a7fc6a2725/lib-extra/src/main/java/com/diffplug/spotless/extra/GitAttributesLineEndings.java#L130-L192).

**Comment by staffanf** [comment]
I did not change the error, I got on the first try.
Did you also updated the default eclipse formatter?  Cause I get some misbehaving warnings now.

**Comment by nedtwigg** [comment]
Bummer - looks like we'd have to dog in to the code linked above.  Happy to take a PR for it, but it's not gonna make the top of my todo list.

4.7.0 bumps the default eclipse formatter to `4.7.1` from `4.6.3`.  You can pin the eclipse version with:

```
spotless {
    java {
        eclipse('4.6.3')
...
```

**Comment by staffanf** [comment]
I just got this on gradle stderr(out?) in one run with 3.6.0.
```
Exception in thread "Thread-482" java.lang.IllegalThreadStateException: process hasn't exited
        at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423)
        at org.eclipse.jgit.util.FS$GobblerThread.setError(FS.java:588)
        at org.eclipse.jgit.util.FS$GobblerThread.run(FS.java:576)
```
So this indeed indicated issues jgit handling of output from the `git config --system --edit` command.

**Comment by AlexanderStohr** [comment]
jgit seems to have issues also in other contexts.
versions from 2016 received a fix. you might not necessarily have them by default or as an update. somtimes java comes as a bundle (maybe when applied to a Jenkins slave) so its hard to solve that on the slave - only the rolled out package from the master can solve it.
https://github.com/danielflower/multi-module-maven-release-plugin/issues/44

**Comment by nedtwigg** [comment]
We've had lots of jgit fixes since this.  Happy to reopen if it is reproducible on spotless latest.
