### ISSUE TITLE
Disabled rule ktlint not working

### ISSUE THREAD

**Issue by Mason19dev** [diffplug/spotless#1646]
Hi, I would like to disable `no-wildcard-imports` and I config spotless task like below 

```
spotless {
    kotlin {
        target "**/*.kt"
        ktlint("0.48.2")
                .userData(
                        [
                                "android": "true",
                        ]
                )
                .editorConfigOverride(
                        [
                                "ktlint_no-wildcard-imports": "disabled",
                        ]
                )

    }
}
```

but I still found an error. What did I do wrong?
```
Error on line: 5, column: 1
rule: no-wildcard-imports
Wildcard import
```
I try to change rule to 
`ktlint_no-wildcard-imports` (I found from [this](https://stackoverflow.com/a/62420057)) and also

`ij_kotlin_packages_to_use_import_on_demand` from this [doc](https://pinterest.github.io/ktlint/rules/standard/#no-wildcard-imports)  

and `no-wildcard-imports` are still not work

```
gradle 7.1.2
spotless 6.17.0
ktlint 0.48.2
```

**Comment by DenWav** [comment]
I believe it should be `ktlint_standard_no-wildcard-imports`, since it's from the standard ruleset.

**Comment by Goooler** [comment]
You should use `ktlint_standard_no-wildcard-imports` with Ktlint 0.48.2, see https://pinterest.github.io/ktlint/0.48.2/rules/standard/#no-wildcard-imports

**Comment by nedtwigg** [comment]
Thanks to @DenWav and @Goooler for finding a solution.
