### ISSUE TITLE
Is there any formatting tool that can configure the max line length? Formatting code into garbage??

### ISSUE THREAD

**Issue by zxiaozhou** [diffplug/spotless#1686]
1. Is there any formatting tool that can configure the newline length?google format 100 characters is disgusting.
2. 100 length,Really fit？？？Ugly as hell.I can't stand watching this shit....Formatting code into garbage??
<img width="922" alt="image" src="https://user-images.githubusercontent.com/62740686/234596443-72dfcfa7-e694-4334-8de3-16ef66074222.png">
3. Now let's look at the code before formatting.The former turned into garbage
<img width="974" alt="image" src="https://user-images.githubusercontent.com/62740686/234597401-e65abb70-1361-4f18-8a9a-6e63440032ae.png">

**Comment by nedtwigg** [comment]
The eclipse formatter can do that.
