### ISSUE TITLE
encoding is not working

### ISSUE THREAD

**Issue by matthiasbalke** [diffplug/spotless#169]
I'm trying to configure spotless to check the encoding of my source, propertie files like configured below. But whatever encoding I use for german umlauts in the files spotless does not fail due to the wrong encoding. What am I doing wrong? This is a key feature of spotless for me.

```groovy
buildscript {
    ext {
        spotless_version = '3.6.0'
    }
    repositories {
        jcenter()
    }
    dependencies {
        classpath("com.diffplug.spotless:spotless-plugin-gradle:${spotless_version}")
    }
}

apply plugin: 'com.diffplug.gradle.spotless'

spotless {
    java {
        lineEndings 'UNIX'

        removeUnusedImports()
        importOrderFile  'project.importorder'
        eclipse().configFile 'code-formatter.xml'
    }

    format 'properties', {
        target '**/*.properties'

        lineEndings 'UNIX'
        encoding 'ISO-8859-1'
    }

    encoding 'UTF-8'
}
```

**Comment by jbduncan** [comment]
Hi @matthiasbalke. By my understanding, `encoding` is actually not meant to check that a given file has its characters encoded in bytes according to the corresponding encoding scheme. I could be wrong on this (please correct me if I'm wrong @nedtwigg), but all `encoding` is meant to do is to tell its formatters how they should translate the bytes in a given text file into human-readable characters.

By my superficial understanding, [it's actually _very_ hard to check that file is encoded in a certain encoding automatically](https://softwareengineering.stackexchange.com/a/187174/288332). Whereas text editors and IDEs have had such the ability to "detect" encodings for a long time (so they could determine if a file is in "UTF-8" or something else), by my understanding they use clever heuristics (in other words, guesses) to determine what encoding the file is _probably_ encoded with.

@matthiasbalke I feel as if I've not really understood your problem yet, as I'm not sure why you expect German umlauts to fail the build if detected within a `.properties` file. Are German umlauts not valid characters in ISO-8859-1?

**Comment by nedtwigg** [comment]
@jbduncan has it right.  Spotless loads and writes files using the specified encoding, but if some other piece of tooling (e.g. misconfigured IDE) has mucked the encoding up, the information has been destroyed, and Spotless can't magically fix it.

What it *can* do is detect if a canary has been mucked with, e.g. at the top of every properties file:

```properties
canary=Nürburgring
```

```gradle
spotless {
    format 'properties', {
        custom 'encodingWasTrashed', {
            if (!it.contains('canary=Nürburgring')) {
                throw new AssertionError("The encoding was trashed")
            }
        }
        bumpThisNumberIfACustomStepChanges(1)
    }
}
```

The downside of this approach is that if both `build.gradle` *and* `.properties` files get smashed in the same way, it won't be able to detect it.  And it can't tell you which file got smashed, only that they disagree.

**Comment by matthiasbalke** [comment]
Maybe the docs should explain this behavior more explicitly. I think I'm not the only one not getting this right.

**Comment by nedtwigg** [comment]
👍 Happy to take a PR to the docs
