### ISSUE TITLE
Update JRE 11+ requirement in README

### ISSUE THREAD

**Issue by simontunnat** [diffplug/spotless#1690]
I was just testing out the Spotless Maven Plugin and was first confused that it was not working with JRE 8. The I found the info in the changelog, that version 2.31.0 and later only support JRE 11+:
https://github.com/diffplug/spotless/blob/main/plugin-maven/CHANGES.md#2310---2023-01-26

But the README still says JRE 8+ is supported:
https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#requirements

Please update the README. :)

**Comment by nedtwigg** [comment]
Thanks for the report!
