### ISSUE TITLE
gherkin always add a trailing whitespace after Background:

### ISSUE THREAD

**Issue by Jiehong** [diffplug/spotless#1693]
If you are submitting a **bug**, please include the following:

If you're just submitting a feature request or question, no need for the above.

Using spotless-maven-plugin:2.36.0, and the following configuration:

```
<gherkin>
  <includes>
    <include>src/**/*.feature</include>
  </includes>
  <gherkinUtils>
    <version>8.0.2</version>
  </gherkinUtils>
</gherkin>
```

Creating a feature file with the following content:

```
Feature: my_feature

  Background:
    def thing = "hello"
````

and running `mvn spotless:check` will generate the following error:

```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.36.0:check (default-cli) on project maestro_server_qa_karate: The following files had format violations:
[ERROR]     src\test\java\my_feature.feature
[ERROR]         @@ -1,6 +1,6 @@
[ERROR]          Feature:·my_feature
[ERROR]
[ERROR]         -··Background:
[ERROR]         +··Background:·
[ERROR]          ····*·def·thing·=·"hello"
```

Note the trailing space added after `Background:`.

**Comment by Jiehong** [comment]
Might not be with spotless, but with the plugin instead, so cross-referencing it in https://github.com/cucumber/gherkin-utils/issues/24.

**Comment by blacelle** [comment]
@Jiehong What happens if you run `spotless:apply` before the check?

**Comment by Jiehong** [comment]
spotless:apply is actually adding that trailing space (and the check is then happy).

problem is, in our company git config refuses to commit trailing spaces but spotless:check is part of the CICD.

**Comment by blacelle** [comment]
Then this is definitely a bug/feature for https://github.com/cucumber/gherkin-utils

**Comment by nedtwigg** [comment]
In the meantime Spotless also has a workaround `<trimTrailingWhitespace/>`.
