### ISSUE TITLE
importOrder does not work with prettier formatter

### ISSUE THREAD

**Issue by Quang810** [diffplug/spotless#1695]
**Summary of problem**
Defined import order does not change the grouped order of import statements on Prettier formatted

**Gradle or maven version**
gradle: 6.9

Spotless version:
6.14.1

Operating system and version
macOS Ventura 13.3.1 (a)

**Spotless config**
```
apply plugin: "com.diffplug.spotless"

spotless {
	format 'misc', {
		// define the files to apply `misc` to
		target '*.gradle'
		// define the steps to apply to those files
		trimTrailingWhitespace()
		indentWithTabs()
		endWithNewline()
	}
	java {
                 importOrder('java|javax', 'com.facebook','com.braze','com.reactlibrary', 'android|androidx', '\\#')
		target("src/*/java/**/*.java")
		targetExclude("node_modules/**/*.java")
		removeUnusedImports()
		prettier().config(['parser': 'java', 'tabWidth': 4, 'useTabs': true])
		// fix formatting of type annotations
		formatAnnotations()
	}
} 
```
Compiled successfully and no error showed up on the terminal. However, the import order remains the same (without line breaks and not grouped)

**Comment by simschla** [comment]
I'm pretty sure that the order of steps matters. So to get what you want: have you tried to move the `importOrder` step after the `prettier` step?
