### ISSUE TITLE
Support kotlin style with linebreak after @ annotation declarations?

### ISSUE THREAD

**Issue by alwa** [diffplug/spotless#1732]
When using the spotless gradle plugin with different styles (google, dropbox, kotlin) my code:

```
    @MockK
    private lateinit var foo: Foo
```

becomes:

```
    @MockK private lateinit var foo: Foo
```

How can I configure Spotless not to do this?

**Comment by simschla** [comment]
Hi @alwa and thanks for checking out spotless.

Regarding your question, I'm unsure if I got the facts correct:

- Do you want to format Kotlin files? Or Java files?
- Can you provide the configuration you are trying? Which formatters and/or formatter steps?

Side note: Spotless does not format code itself, it uses other formatters in a super efficient and convenient way.

**Comment by alwa** [comment]
> Hi @alwa and thanks for checking out spotless.
> 
> Regarding your question, I'm unsure if I got the facts correct:
> 
> * Do you want to format Kotlin files? Or Java files?
> * Can you provide the configuration you are trying? Which formatters and/or formatter steps?
> 
> Side note: Spotless does not format code itself, it uses other formatters in a super efficient and convenient way.

Hi @simschla ,
I tried to format Kotlin files. I tried with the different built-in styles provided by spotless (google, dropbox)

**Comment by simschla** [comment]
@alwa According to documentation, spotless provides the following options for kotlin out of the box:

```gradle
spotless { // if you are using build.gradle.kts, instead of 'spotless {' use:
           // configure<com.diffplug.gradle.spotless.SpotlessExtension> {
  kotlin {
    // by default the target is every '.kt' and '.kts` file in the java sourcesets
    ktfmt()    // has its own section below
    ktlint()   // has its own section below
    diktat()   // has its own section below
    prettier() // has its own section below
    licenseHeader '/* (C)$YEAR */' // or licenseHeaderFile
  }
  kotlinGradle {
    target '*.gradle.kts' // default target for kotlinGradle
    ktlint() // or ktfmt() or prettier()
  }
}
```
(From our [README](https://github.com/diffplug/spotless/tree/main/plugin-gradle#kotlin)

Did you try all these styles? (ktfmt/ktlint/diktat/prettier) With all their configuration options?

**Comment by alwa** [comment]
> @alwa According to documentation, spotless provides the following options for kotlin out of the box:
> 
> ```groovy-gradle
> spotless { // if you are using build.gradle.kts, instead of 'spotless {' use:
>            // configure<com.diffplug.gradle.spotless.SpotlessExtension> {
>   kotlin {
>     // by default the target is every '.kt' and '.kts` file in the java sourcesets
>     ktfmt()    // has its own section below
>     ktlint()   // has its own section below
>     diktat()   // has its own section below
>     prettier() // has its own section below
>     licenseHeader '/* (C)$YEAR */' // or licenseHeaderFile
>   }
>   kotlinGradle {
>     target '*.gradle.kts' // default target for kotlinGradle
>     ktlint() // or ktfmt() or prettier()
>   }
> }
> ```
> 
> (From our [README](https://github.com/diffplug/spotless/tree/main/plugin-gradle#kotlin)
> 
> Did you try all these styles? (ktfmt/ktlint/diktat/prettier) With all their configuration options?

It looks like I have a few things to read up on. Thanks for the pointer! Will check this and give an update
