### ISSUE TITLE
Support project-less execution and externalized configuration of the Maven plugin

### ISSUE THREAD

**Issue by gdupontf** [diffplug/spotless#1735]
Are there already efforts to support project-less execution of the Maven plugin?
Else this would be a matter of having an externalized configuration format derived from the XML config, and implementing either a separate goal or a configuration property switch, along with flipping the projectRequired property accordingly.

**Comment by nedtwigg** [comment]
This is sort of what @blacelle's [cleanthat](https://github.com/solven-eu/cleanthat) project does.
