### ISSUE TITLE
Gradle enterprise shows a deprecation log that relates to Spotless

### ISSUE THREAD

**Issue by Omico** [diffplug/spotless#1737]
summary of problem

Gradle enterprise shows `Consider defining toolchain download repositories, otherwise the build might fail in clean environments; see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories` after I run `spotlessApply` task.

I guess it may be related to https://github.com/gradle/gradle/issues/24197 and https://github.com/diffplug/spotless/blob/cc3ca6e652b6b7c55d8b99ca19a7c268a620949d/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleProvisioner.java#LL111C2-L111C2

gradle or maven version: Gradle 8.1.1
spotless version: 6.19.0
operating system and version: Windows 11
reproduce project: https://github.com/Omico/Gradm
spotless configuration: https://github.com/Omico/Gradm/blob/main/build-logic/convention/src/main/kotlin/gradm.build-logic.spotless.gradle.kts, some extensions source https://github.com/Omico/age/blob/main/age-gradle-plugin/spotless/src/main/kotlin/me/omico/age/spotless/Spotless.kt

**Comment by Goooler** [comment]
Please check this issue in `7.0.0.BETA1`, and paste your build scan link here if possible.
