### ISSUE TITLE
Unable to exclude a Gradle module from `spotlessCheck`

### ISSUE THREAD

**Issue by kenfinnigan** [diffplug/spotless#1740]
With a multi-module Gradle build it's possible to exclude the module from `spotlessCheck` during a `gradlew build` with the below in the modules `build.gradle`:
```
spotless {
  enforceCheck false
}
```

However, when I run `gradlew spotlessCheck` the module is no longer excluded from the check. Is there another way to always exclude a module from the check no matter what Gradle command is run? The code is customized from a completely different project with different Spotless settings and I'd prefer not to change these classes to align with my own projects settings.

I'm using Gradle 7.6 and Spotless gradle plugin 6.15.0

**Comment by simschla** [comment]
Thanks for raising this question. I don't think there is a "spotless-way" to disable spotless for one module in a multimodule Gradle build. But, of course, there's always the Gradle way 😄 

Add this to the `build.gradle` _in the module where you want to disable spotless_:

```gradle
tasks.withType(com.diffplug.gradle.spotless.SpotlessTask).configureEach { Task spotlessTask ->
    spotlessTask.enabled = false
}
```

This should do the trick.

LMK if this works for you.

**Comment by kenfinnigan** [comment]
Thanks, much appreciated!
