### ISSUE TITLE
Add support for ktlint 0.50.0

### ISSUE THREAD

**Issue by JakeWharton** [diffplug/spotless#1741]
We all know the drill!

[Another release](https://github.com/pinterest/ktlint/releases/tag/0.50.0), another set of breaking changes.

Thank you for the continued efforts in supporting this tool whose API instability is very painful to endure.

**Comment by TWiStErRob** [comment]
@nedtwigg do you know when the next release of spotless will come out? (including the above commit)

**Comment by nedtwigg** [comment]
Released in `plugin-gradle 6.20.0` and `plugin-maven 2.38.0`.
