### ISSUE TITLE
Unable to run spotless apply in jhipster projects

### ISSUE THREAD

**Issue by CodingSpiderFox** [diffplug/spotless#1745]
I am trying to use spotless-maven plugin in a JHipster 8 project.

JHipster is an application source generator that generates full stack Spring Boot apps

The generated app specifies source/target versions=17 for the maven compiler plugin in the pom.xml

I added the following configuration to my pom.xml build plugins

```

    <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.37.0</version>
        <configuration>
            <java>
                <removeUnusedImports>true</removeUnusedImports>
            </java>
        </configuration>
        <executions>
            <execution>
                <id>spotless</id>
                <phase>compile</phase>
                <goals>
							 <goal>check</goal>
                    <goal>apply</goal>
                </goals>
            </execution>
        </executions>
    </plugin>	
```

When running mvn compile spotless:apply, I get the following error: 

"Unable to parse configuration of mojo com.diffplug.spotless.spotless-maven-plugin:2.37.0:apply for parameter removeUnusedImports: Cannot find default setter in class com.diffplug.spotless.maven.java.RemoveUnusedImports"

Could the problem be that JHipster 18 uses Java 17? I have installed openjdk-17-jdk and openjdk19 on my Ubuntu 22.04 machine.

When necessary, I can provide a MCVE repository

**Comment by nedtwigg** [comment]
Try `<removeUnusedImports/>` rather than `<removeUnusedImports>true</removeUnusedImports>`

**Comment by CodingSpiderFox** [comment]
Yep, just found out that this works after I found an example here:

https://github.com/jhipster/prettier-java/issues/468#issuecomment-845157368

Thanks for the advice :)
