### ISSUE TITLE
Groovy: greclipse formatter version check is crazy and hard to understand. Must be aligned for v5.0.0:

### ISSUE THREAD

**Issue by Jiehong** [diffplug/spotless#1766]
Hello,

Currently, the version of greclipse plugin to use does a seemingly crazy calculation that is not indicated anywhere in the doc, and thus is impossible to guess when trying to update it:

https://github.com/diffplug/spotless/blob/main/lib-extra/src/main/java/com/diffplug/spotless/extra/groovy/GrEclipseFormatterStep.java#L44

Aka, the only way to know which version to use is to check https://groovy.jfrog.io/ui/native/plugins-release/org/codehaus/groovy/groovy-eclipse-integration, and to add 18 to the latest 4.x.0 -> 4.(x+18)

Also, now that version 5.0.0 (https://groovy.jfrog.io/ui/native/plugins-release/org/codehaus/groovy/groovy-eclipse-integration/5.0.0/) has been released, I propose to have the greclipse’s version in spotless maven plugin be strictly aligned, aka 5.0.0.

By the way, it would be nice if spotless would offer a way to check if there is an update available for all the versions specified in its maven plugin configuration.

**Comment by nedtwigg** [comment]
Thanks for raising this! Greclipse releases are synchronized with Eclipse SimRel, so when Eclipse 4.27 is released, there is a specific Greclipse that goes with that. The version we are using here is Eclipse platform version, and we calculate the Greclipse version off of that.

If we do it the other way - start with the Greclipse version - we'll still have to do this crazy math, just backwards, to instead calculate the Eclipse platform version based on the Greclipse version. Happy to take a PR which improves the docs for this.
