### ISSUE TITLE
UpToDateChecking ignores java formatter ?

### ISSUE THREAD

**Issue by fischermatte** [diffplug/spotless#1767]
### Summary

We noticed that with spotless-maven-plugin version 2.35.0 some formatting stopped working in our repo where we use it in conjunction with prettier. The reason was, that the `upToDateChecking` property was set to `true` by default. When we set it back to `false` it works. But now that we know about this property we would love to use it!

### Configuration

``` xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.38.0</version>
    <configuration>
        <upToDateChecking>
            <!-- FIXME upToDateChecking ignores java section -->
            <enabled>true</enabled>
        </upToDateChecking>
        <formats>
            <format>
                <includes>
                    <include>src/**/*.java</include>
                </includes>
                <trimTrailingWhitespace/>
                <endWithNewline/>
            </format>
        </formats>
        <java>
            <importOrder>
                <order>java,javax,com,de,lombok,net,org</order>
            </importOrder>
            <removeUnusedImports/>
            <prettier>
                <devDependencies>
                    <prettier>2.8.8</prettier>
                    <prettier-plugin-java>2.1.0</prettier-plugin-java>
                </devDependencies>
                <config>
                    <tabWidth>2</tabWidth>
                    <parser>java</parser>
                    <printWidth>120</printWidth>
                </config>
            </prettier>
        </java>
    </configuration>
</plugin>

```

### So Java Formatting not Supported with UpToDateChecking ?
 
So is the config above wrong? It looks like with enabled `upToDateChecking` the Java formatter is ignored, only the Format section is applied.

**Comment by nedtwigg** [comment]
FYI @lutovich. This is surprising behavior, we should warn about it

- #1771 

I think you can fix this by adding `<trimTrailingWhitespace/><endWithNewline/> ` to the bottom of your `java` section. The problem is that your java files are being formatted by two different formatters - the `<java>` block and the `<format><includes><include>src/**/*.java` block. I think that will fix it, please comment again if it does not.

**Comment by fischermatte** [comment]
Thx @nedtwigg. At the end we just removed the formats section and let everything be done by the java formatter. 

Actually there are some contradictory examples out there with prettier. Some seem to configure prettier within a <format> some within <java>. Not clear to me what is recommended. Is there any documentation about that?

**Comment by nedtwigg** [comment]
I think the concept you are missing is

- you have a list of `formats`, each format defines a set of files (you are missing this)
  - some are built-in (e.g. `java`) and others you have to specific manually (`format`)
- each format has a list of steps (you understand this)

So you could have a one format for `.js` files, which would use prettier, and another format for java files. There are some formats which have built-in DSL (e.g. java) and others that don't, you have to specify a generic format manually.

The docs cover this, but they are hard to read quickly. Ideally our docs would communicate this better, but we could also help with just a better error message.
