### ISSUE TITLE
Emit warning if a given file is formatted by multiple formatters

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#1771]
If a file is being changed by more than one format, it's unclear what the correct behavior should be. Checking for this on every run is pretty expensive, but it would be worth checking for on failure.

If a `spotlessCheck` fails, we should test to see if the failing file is a target of multiple formatters, and if it is, we should warn about that.

- [ ] gradle plugin
- [ ] maven plugin

**Comment by blacelle** [comment]
Seems a duplicate of https://github.com/diffplug/spotless/issues/1656

**Comment by nedtwigg** [comment]
Thanks! I thought we had addressed this already but I couldn't find it.
