### ISSUE TITLE
ktlint_standard_enum-entry-name-case = disabled does not work on .editorconfig

### ISSUE THREAD

**Issue by daniel-lopes-optimizely** [diffplug/spotless#1785]
The .editorconfig file

```
[*.{kt,kts}]
indent_style = space
indent_size = 4
ktlint_standard_no-wildcard-imports = disabled # works
ktlint_standard_filename = disabled # works
ktlint_standard_enum-entry-name-case = disabled # doesnt work
```

The error:

```
Error on line: 209, column: 4
rule: standard:enum-entry-name-case
Enum entry name should be uppercase underscore-separated names like "ENUM_ENTRY" or upper camel-case like "EnumEntry"
````

The gradle.kts

```
plugins {
        id("com.diffplug.spotless") version "6.20.0"
    }
...
spotless {
    kotlin {
        ktlint("0.50.0").setEditorConfigPath("$projectDir/../.editorconfig")
    }
}
```

Is this something you can help me figure out? I'm using the latest spotless gradle plugin, but I think this is related to ktlint. Let me know if I have to take this to the ktlint devs instead.

**Comment by Goooler** [comment]
It works, see https://github.com/Goooler/AndroidOAuth2WebView/pull/36.

I guess the issue is what you are using `"$projectDir/../.editorconfig"` to override file path.

**Comment by daniel-lopes-optimizely** [comment]
The file path needs to be overridden because the project is a submodule of a bigger project.
The plugin fails if it can't find the file in the config path:
```
Could not determine the dependencies of task ':spotlessApply'.
> Could not create task ':spotlessKotlinApply'.
   > Could not create task ':spotlessKotlin'.
      > File signature can only be created for existing regular files, given: .../looker-sdk-codegen/.blablah
```

Plus, the other settings I have in the .editorconfig file seem to work fine.

**Comment by Goooler** [comment]
Overriing `.editorconfig` works, I just tried with a simular case in https://github.com/Goooler/AndroidOAuth2WebView/pull/36, I guess you are still setting a wrong path.

**Comment by daniel-lopes-optimizely** [comment]
Shouldn't the plugin fail if the file isn't found?

**Comment by Goooler** [comment]
> Shouldn't the plugin fail if the file isn't found?

@nedtwigg WDYT?

**Comment by daniel-lopes-optimizely** [comment]
If I change the file name or path [I get an error.](#issuecomment-1690105039) 
The current behaviour ignores the file content if it's not in the root directory.
