### ISSUE TITLE
spotless not working for the second time in the same project

### ISSUE THREAD

**Issue by moulalis** [diffplug/spotless#1790]
- I am running mvn spotless:apply for the second time in the project after doing some changes, its not making the changes eventhought maven checkstyle plugin is not passing it.

- maven version : 11.0.12
- spotless version: 2.38.0
- operating system and version: fedora 37

**Comment by nedtwigg** [comment]
checkstyle only has to find problems. spotless has to fix them too. there are a bunch of things which checkstyle fings which spotless does not.
