### ISSUE TITLE
Imports are not in lexicographical order

### ISSUE THREAD

**Issue by gauravic08** [diffplug/spotless#18]
Hi,
I have mentioned my imports to be in order :  ['java', 'javax', 'org', 'com'']
but after spotlessApply, imports are organized in order :  ['java', 'javax', 'lombok' ,'org', 'com','io'].
I guess lombok should come after 'io'.

**Comment by nedtwigg** [comment]
Try asking for your imports to be like this: `['java', 'javax', 'org', 'com', '']` (note the empty string at the end).

The formatter will put all of the unspecified imports (in this case, `lombok` and `io`) into the empty group at the end.  If you don't tell the formatter where to put the unspecified imports, I don't know what determines where they'll go.  See #17 for more details if you're curious.

**Comment by gauravic08** [comment]
Thanks.
It's working
