### ISSUE TITLE
Updates for the Rome -> Biome transition

### ISSUE THREAD

**Issue by blutorange** [diffplug/spotless#1804]
So apparently Rome was moved / forked to [Biome](https://biomejs.dev/blog/annoucing-biome) due to ownership issues. From what I can tell, not much has changed in their API, so we don't have to change much in spotless:

* Update the default links for downloading the binary
* Support the `biome.json` configuration file name in addition to deprecated file name `rome.json`
* Possibly change the naming of folders and options from rome to biome
  * For compatibility reason, I guess we should keep the `<rome>` option in addition to the new `<biome>` option.

**Comment by nedtwigg** [comment]
Shipped in `plugin-gradle 6.22.0` and `plugin-maven 2.40.0`.
