### ISSUE TITLE
Spotless Gradle plugin cannot handle arbitrary text files

### ISSUE THREAD

**Issue by johnshajiang** [diffplug/spotless#1812]
Using Spotless Gradle plugin 6.21.0 with Gradle 8.3, OpenJDK 11.0.19 and macOS 13.5.

It looks the plugin cannot handle arbitrary text files, like `*.txt`.

The Spotless Gradle script looked like the below,
```
spotless {
    format 'misc', {
        target '*.txt'

        trimTrailingWhitespace()
        endWithNewline()
    }
}
```

Created a text file `test.txt` with the below command in the Gradle project,
```
printf "test " > test.txt
```
This file contained a trailing whitespaces, and not ended with a newline.

`./gradlew spotlessCheck` didn't raise any error.
`./gradlew spotlessApply` didn't modify `text.txt`.

**Comment by nedtwigg** [comment]
I'm 99.9% sure this is user error. Try `cat test.txt` to make sure it has the content you think, maybe try `**/*.txt` to double check that the wildcard is matching the files you expect.

**Comment by johnshajiang** [comment]
@nedtwigg 
> Try cat test.txt to make sure it has the content you think

I did that.
In my above test case, the file `text.txt` contains trailing space and have no newline.

> maybe try **/*.txt to double check that the wildcard is matching the files you expect.

Just tried this, but it didn't work.

**Comment by nedtwigg** [comment]
Maybe we have a bug in files that only have one line. Maybe try multiple lines?

**Comment by johnshajiang** [comment]
It looked Spotless just checked the Java classes.

Please tried the below test case.

1. Create a file, named `Test.txt`, and the content is the below,
```
public class Test {

    public static void main(String[] args) {
        System.out.println("test");     
    }
}
```
Note that the file extension is `.txt` not `.java` and there are some spaces after `System.out.println("test"); `.

2. The Spotless scripts just be the followings,
```
apply plugin: "com.diffplug.spotless"

spotless {

    format 'misc', {
        target '**/*.txt'

        trimTrailingWhitespace()
        endWithNewline()
    }
}
```

3. Run spotlessCheck and it raises the error,
```
      src/test/java/Test.txt
          @@ -1,6 +1,6 @@
           public·class·Test·{
           
           ····public·static·void·main(String[]·args)·{
          -········System.out.println("test");·····
          +········System.out.println("test");
           ····}
           }
```
That is fine so far.

4. Modify `Test.txt` and remove the class declaration statement, like the below,
```


    public static void main(String[] args) {
        System.out.println("test");     
    }
}
```
Now, this is not a valid Java class.

5. Run spotlessCheck again, but it passes without any complaint.

**Comment by nedtwigg** [comment]
Do you have an example I can clone? One possibility is that the file is being targeted by multiple formats, something like this:

```
spotless {
  java { target '**/*' ...
  format 'misc',  { target '**/*' ...
```

**Comment by johnshajiang** [comment]
> Do you have an example I can clone?

Did you try my above test case?
Did you reproduce this issue?

> One possibility is that the file is being targeted by multiple formats

In my given test case, there was only one format.

```
spotless {

    format 'misc', {
        target '**/*.txt'

        trimTrailingWhitespace()
        endWithNewline()
    }
}
```

**Comment by johnshajiang** [comment]
@nedtwigg 
I hope you can reproduce this issue with this `jetcd` [branch].

Please note [test.txt] has trailing spaces but hasn't newline.
And the Spotless style format is [here].

[branch]:
<https://github.com/johnshajiang/jetcd/tree/spotless>

[test.txt]:
<https://github.com/johnshajiang/jetcd/blob/spotless/test.txt>

[here]:
<https://github.com/johnshajiang/jetcd/blob/spotless/gradle/style.gradle>
