### ISSUE TITLE
Allow raw license header to be autoformated to language comment.

### ISSUE THREAD

**Issue by bric3** [diffplug/spotless#1815]
I propose to make the license rule to be able to auto format a *raw* license header. Today if I'm not mistaken, it is necessary to create multiple header file adapted for each language.

```
spotless {
    java {
        licenseHeaderFile(project.file("$rootDir/.spotless/java.HEADER"))
        target("**/*.java")
    }
    kotlin {
        licenseHeaderFile(project.file("$rootDir/.spotless/java.HEADER"))
        target("**/*.kt", "**/*.kts")
        targetExclude("**/*.gradle.kts")
    }
    kotlinGradle {
        licenseHeaderFile(project.file("$rootDir/.spotless/java.HEADER"),
            "(@file|fun|package|import|plugins|pluginManagement) "
        )
        target("**/*.gradle.kts")
    }
    // more
}
```

The header file here has the exact license header with the comments, e.g. `/*` style. I propose the enable a way to pass a raw HEADER file, that is without any comments.
Spotless would be able to auto format this raw content to the language's comment syntax (`/*` for java/kotlin, `<!--` for HTML/XML/markdown, `#` for yaml/properties, `////` for asciidoc files, etc.)

----
Gradle 8.3
Spotless 6.21.0
macOs 13.5.2

**Comment by nedtwigg** [comment]
People can be picky about `//` vs `/*` vs `/**` vs `/* ` vs `/** `. My guess is if we add up:

- extra docs to describe license transformation
- extra implementation complexity per language
- extra user issues about wanting to control the transformation

then this will never break even relative to the complexity of making two versions of the header, etc.

I'm going to close as won't implement, but I am open to being convinced. If you really want this, I would first modify the docs and open a draft PR with the documentation. If that gets signed off, then I would continue on with implementing. My guess is that if you try to document this, it will turn out to be too much work to be worth it.
