### ISSUE TITLE
Can we create releases from tags? 

### ISSUE THREAD

**Issue by Goooler** [diffplug/spotless#1818]
<img width="1510" alt="image" src="https://github.com/diffplug/spotless/assets/10363352/1ec31554-29c5-403e-a0b5-cb2b1e477dee">

<img width="1168" alt="image" src="https://github.com/diffplug/spotless/assets/10363352/68ca1876-d6ed-4f53-abf4-32183a626920">

See https://github.com/Goooler/spotless/releases/tag/gradle%2F6.21.0.

**Comment by nedtwigg** [comment]
I think that would be great

- https://github.com/diffplug/spotless-changelog/issues/10
