### ISSUE TITLE
No such reference 'origin/main'

### ISSUE THREAD

**Issue by fullstackctp** [diffplug/spotless#1876]
I am getting this proplem with my springboot project after applying spotless.It builds in local.
Could not determine the dependencies of task ':exchange-api:spotlessCheck'.
> Could not create task ':exchange-api:spotlessMiscCheck'.
   > Could not create task ':exchange-api:spotlessMisc'.
      > No such reference 'origin/main'

I don't use gitlab . 
I am using Space by jetspace as my repositorty

**Comment by fullstackctp** [comment]
HI is there any response on this ?

**Comment by nedtwigg** [comment]
Dupe of https://github.com/diffplug/spotless/issues/710
