### ISSUE TITLE
spotless:on / off is not ignoring unsupported formats

### ISSUE THREAD

**Issue by matsev** [diffplug/spotless#1887]
`palantir-java-format` does not currently all Java 21 additions (see palantir/palantir-java-format#952). In an attempt to work around this problem, I tried to use [spotless:off and spotless:on](https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#spotlessoff-and-spotlesson). The example below compiles using JDK 21 as it is supported by [JEP 441 : Pattern Matching for switch](https://openjdk.org/jeps/441):
```java
class Example {
    // spotless:off
    static String test(CharSequence charSequence) {
        return switch (charSequence) {
            case String s when s.isEmpty() -> "empty string";
            case String s -> "non-empty string";
            default -> "not a String";
        };
    }
   // spotless:on
}
```

Since the code is currently not supported by `palantir-java-format`, I tried to mute the problem by adding the `// spotless:off` and `// spotless:on` comments to disable evaluation of the code as showed above.

## Expected result
The source code between `// spotless:off` and `// spotless:on` should be ignored by spotless and the evaluation should succeed.

## Actual result
The spotless evaluation fails in the same way as if the comments were not added, i.e.

```bash
mvn spotless:apply
[...]
Unable to format file [path to Example.java]: com.palantir.javaformat.java.FormatterException: error: expected token: 'when'; generated - instead -> [Help 1]
```

## References

Maven config:
```xml
                <plugin>
                    <groupId>com.diffplug.spotless</groupId>
                    <artifactId>spotless-maven-plugin</artifactId>
                    <version>2.40.0</version>
                    <configuration>
                        <java>
                            <palantirJavaFormat>
                                <version>2.38.0</version>
                            </palantirJavaFormat>
                           <toggleOffOn/>
                        </java>
                    </configuration>
                </plugin>
```

Maven:
```bash
mvn -v
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Java version: 21, vendor: Amazon.com Inc.
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.6.1", arch: "x86_64", family: "mac"
```

**Comment by nedtwigg** [comment]
This is the expected behavior. For why, you can look at the `spotless:off` PR, details below

- #691

> ... It implements this under the hood with PipeStepPair, which has an In step and an Out step. The In step is the very first step which gets applied, Out is the last step, and all the other formatting steps go in between them. The In step finds matching off/on pairs, and stores the text between them. The intermediate steps like google-java-format or whatever do their work, and at the end the Out step finds the off/on pairs again, which may have moved. Then it replaces those pairs with whatever was stored by the In step.

**Comment by matsev** [comment]
Ok, that's unfortunate. Thanks for the quick reply!
