### ISSUE TITLE
Error: Unsupported major.minor version 52.

### ISSUE THREAD

**Issue by CraigAnderson8** [diffplug/spotless#19]
Executed: gradle build
Output: java.lang.UnsupportedClassVersionError: com/diffplug/gradle/spotless/SpotlessPlugin : Unsupported major.minor version 52.0

gradle.build:

plugins {
    id "com.diffplug.gradle.spotless" version "1.3.3"
}

apply plugin: 'com.diffplug.gradle.spotless'
spotless {
    java {
        eclipseFormatFile	'eclipse-java-google-style.xml'	// XML file dumped out by the Eclipse formatter
    }
}

Java version: 1.7.0_79

**Comment by nedtwigg** [comment]
Spotless requires that you run Gradle using Java 8.  It can format any version of Java, but it needs to be running on Java 8.  See #7 for details.
