### ISSUE TITLE
Regression in gradle/6.23.0. Unable to configre ktlint

### ISSUE THREAD

**Issue by AntsyLich** [diffplug/spotless#1911]
## summary of problem
```kt
spotless {
    kotlin { 
        ktlint()
    }
}
```
Having the simple block below highlights `ktlint()`. Hovering on it shows the message "Type BaseKotlinExtension.KtlintConfig! is inaccessible in this context due to: public open inner class KtlintConfig defined in com.diffplug.gradle.spotless.BaseKotlinExtension". But spotless works fine. Now if i try to access any method of ktlint config like below red squiggly line appers below that method and hovering over them shows the message "Cannot access 'BaseKotlinExtension': it is package-private in 'com.diffplug.gradle.spotless'"
```kt
spotless {
    kotlin {
        ktlint()
            .customRuleSets(listOf("io.nlopez.compose.rules:ktlint:0.3.3"))
    }
}
```
## Gradle or Maven version
Gradle 8.4
## spotless version
gradle/6.23.0
## operating system and version
Windows 11
## copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
See above
## copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
```
> Configure project :app
w: file:///D:/[...]/android/app/build.gradle.kts:46:9: Type BaseKotlinExtension.KtlintConfig! is inaccessible in this context due to: public open inner class KtlintConfig defined in com.diffplug.gradle.spotless.BaseKotlinExtension
w: file:///D:/[...]/android/app/build.gradle.kts:46:9: Type BaseKotlinExtension.KtlintConfig! is inaccessible in this context due to: public open inner class KtlintConfig defined in com.diffplug.gradle.spotless.BaseKotlinExtension
e: file:///D:/[...]/android/app/build.gradle.kts:47:14: Cannot access 'BaseKotlinExtension': it is package-private in 'com.diffplug.gradle.spotless'

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\[...]\android\app\build.gradle.kts' line: 47

* What went wrong:
Script compilation error:

  Line 47:             .customRuleSets(listOf("io.nlopez.compose.rules:ktlint:0.3.3"))
                        ^ Cannot access 'BaseKotlinExtension': it is package-private in 'com.diffplug.gradle.spotless'
```                        

If you're just submitting a feature request or question, no need for the above.

**Comment by Goooler** [comment]
Fixing this in #1912.

**Comment by TWiStErRob** [comment]
See also https://github.com/gradle-nexus/publish-plugin/pull/286

**Comment by madorb** [comment]
Same issue with `greclipse()`

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle 6.23.1`. It has been published in the Gradle plugin repository, but the maven central sync appears to be jammed for now. Should resolve in a few hours.

**Comment by StefanLobbenmeierObjego** [comment]
I was able to update to v6.23.2 now and that fixed the issue, thanks ❤️

**Comment by yoobi** [comment]
I am having the same issue with 6.25.0 
```
No signature of method: com.diffplug.gradle.spotless.BaseKotlinExtension$KtlintConfig.userData() is applicable for argument types: (LinkedHashMap) values: [[android:true]
```

**Comment by Goooler** [comment]
> `userData` method has been removed from Ktlint step in #1891, you may use `editorConfigOverride` instead.

I noted this in 6.23.0 changelog.

**Comment by yoobi** [comment]
Oh shoot I missed this, sorry
