### ISSUE TITLE
Gralde plugin for 6.23.1/2 not correctly published?

### ISSUE THREAD

**Issue by snazy** [diffplug/spotless#1919]
I see that the Gradle plugin has been released to [Gradle plugins](https://plugins.gradle.org/plugin/com.diffplug.spotless), but it seems that the Maven artifact has [not been published](https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-plugin-gradle/). Last published artifact for `com.diffplug.spotless:spotless-plugin-gradle` was 6.23.0, but 6.23.1 and 6.23.2 are missing.

**Comment by thc202** [comment]
They are now available (since some hours ago).
