### ISSUE TITLE
kotlin examples aren't valid kotlin

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#1967]
If you are submitting a **bug**, please include the following:

https://github.com/diffplug/spotless/tree/main/plugin-gradlexkotlin

This and more simply don't compile in kotlin, I suspect they are copy and paste from groovy

**Comment by Goooler** [comment]
It works in Kotlin dsl.

https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md#ktlint

**Comment by xenoterracide** [comment]
no it doesn't, this isn't valid kotlin, dsl or otherwise. This ` target '*.gradle.kts' // default target for kotlinGradle` is groovy

```
spotless { // if you are using build.gradle.kts, instead of 'spotless {' use:
           // configure<com.diffplug.gradle.spotless.SpotlessExtension> {
  kotlin {
    // by default the target is every '.kt' and '.kts` file in the java sourcesets
    ktfmt()    // has its own section below
    ktlint()   // has its own section below
    diktat()   // has its own section below
    prettier() // has its own section below
    licenseHeader '/* (C)$YEAR */' // or licenseHeaderFile
  }
  kotlinGradle {
    target '*.gradle.kts' // default target for kotlinGradle
    ktlint() // or ktfmt() or prettier()
  }
}
```

**Comment by Goooler** [comment]
That is for Groovy intendedly, easy to convert it to Kotlin in your build scripts.

**Comment by xenoterracide** [comment]
Why would you use a groovy example for a script that is explicitly written to reformat kotlin Gradle? Also it's worth noting that if you wrote it in kotlin it would be perfectly valid groovy. No translation required on either side

**Comment by nedtwigg** [comment]
PRs welcome :)
