### ISSUE TITLE
kotlinGradle doesn't seem to do anything

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#1968]
```kt
  kotlinGradle {
    target("**/*.gradle.kts")
    licenseHeader(license, "//")
    ktlint() // or ktfmt() or prettier()
  }
```

I tried this, but in the very file I was editing, no license was added. Docs aren't clear on what licenseHeader(.., delimeter) is, nor is it mentioned.

**Comment by caleb-cushing0-kr** [comment]
oh, seems like I need to apply spotless to my root project even though it's not java... wonder if I can get rid of the `java-base`...

I feel like the default's should look like this?
```
  kotlinGradle {
    target("**/*.gradle.kts")
    licenseHeader(license, "^(import|buildscript|plugins)")
    // ktfmt()
  }
```

**Comment by caleb-cushing0-kr** [comment]
although that piece of formatting with spotless apply worked with that, check failed, and I'm not even sure how it was enabled still O.o

https://github.com/xenoterracide/ai-wh40k/actions/runs/7200891950/job/19615835365?pr=61
it's not even supposed to run in CI and locally CI="true" ./gradlew build fails the same way
https://github.com/xenoterracide/ai-wh40k/blob/main/buildSrc/src/main/kotlin/our.spotless.gradle.kts#L12
https://gradle.com/s/bdzahuolm7kxo (edited)

**Comment by xenoterracide** [comment]
I've updated my configuration, seems to work even better

```kt
    target("**/*.gradle.kts")
    targetExclude("**/build/**")
    licenseHeader(license, "(import|buildscript|plugins|root)")
```

**Comment by Goooler** [comment]
It works for you after adding `licenseHeader(license, "(import|buildscript|plugins|root)")`, right?

**Comment by xenoterracide** [comment]
well, the real fix was it needed to be applied on the root project which was not a java project.

**Comment by xenoterracide** [comment]
could you maybe improve the documentation so it wasn't a big pile of trial and error?

**Comment by Goooler** [comment]
I will.

**Comment by nedtwigg** [comment]
Putting `**/` in your `target` is going to be a big performance hit. If this works it would be a lot faster

```gradle
  target '*.gradle', '*/*.gradle'
```

**Comment by caleb-cushing0-kr** [comment]
that wouldn't get buildsrc plugins

**Comment by nedtwigg** [comment]
I think `*/*.gradle` should get it, but if not you can add `buildSrc/*.gradle`

**Comment by xenoterracide** [comment]
You're missing the idea they're a ton of plugins beneath build source... All of those would still need formatting. And they're all technically gradle files. The root project isn't the only thing.

**Comment by nedtwigg** [comment]
```gradle
target '*.gradle`, '*/*.gradle', 'buildSrc/src/**/*.gradle`
```

You can do `target '**/*.gradle'` if you want, but we're not going to fix perf bugs related to any `**/*` includes.

**Comment by xenoterracide** [comment]
sure, I'm just wanting the examples to be more correct as far as what needs to be done in order for things to actually work as expected, and/or perhaps simply a default configuration that should work in in most cases. I dislike "trial and error", and the less code I have to maintain the better.
