### ISSUE TITLE
Possibility to output the license header

### ISSUE THREAD

**Issue by fabriziocucci** [diffplug/spotless#197]
It would be nice to use the same template to update both the `.java` files and the `LICENSE` file on the root of a project.

Something like:

```
spotless {
  java {
    licenseHeaderFile 'license.template'
    licenseHeaderOutputFile 'LICENSE'
  }
}
```

Although, if this is a welcome enhancement, for consistency, maybe it would be nice also to rename `licenseHeaderFile` as `licenseHeaderInputFile`, if backward compatibility is not an big issue.

The main reason why we can't use directly the `LICENSE` as template is due to the possibility of having the `$YEAR` placeholder.

**Comment by nedtwigg** [comment]
We only break back-compat if there's no other way.

This is probably the easiest way to accomplish your goal

```gradle
spotless {
  format 'justLicense', {
    target 'LICENSE'
    licenseHeaderFile 'spotless.license.java', '\Z'
    // licenseHeader needs regex to know what counts as "the header"
    // since you want to format whole file, you need a regex that matches the end
    // of the file, which is '\Z`.  Might need to be '\\Z', not sure
  }
}
```

Does this work for you?

**Comment by fabriziocucci** [comment]
@nedtwigg first things first, thanks for your prompt reply and sorry for my delay.

I've tried the above, specifically with this spotless configuration:
```gradle
spotless {
  java {
    licenseHeaderFile 'license.template'
  }
  format 'justLicense', {
    target 'LICENSE'
    licenseHeaderFile 'license.template', '\\Z'
  }
}
```

The result is the following:
1. if the `LICENSE` file does **not** exist, the build will just succeed but the file will not be created. I guess this is expected since the `target` property is meant to specify files to be processed as documented [here](https://github.com/diffplug/spotless/tree/master/plugin-gradle#custom-rules).
2. if the `LICENSE` file exists but it's empty (e.g. `touch LICENSE`), the build fails because the regular expression cannot match the end of file.
3. if the `LICENSE` file exists and it's *not* empty (e.g. `echo "" > LICENSE`), the build fails because the license header is missing in the `LICENSE` file. 

If `3` can be considered an acceptable solution (where acceptable really means _not-too-clunky_) maybe it would make sense to document this. I could give it a shot if you agree.

**Comment by nedtwigg** [comment]
I think this issue is probably good-enough docs for a rare usecase, but feel free to submit a PR.  README space is valuable - only stuff with broad appeal makes the cut.

You are correct that the LICENSE will have to already exist.  Instead of the fancy `\\Z`, you could also just put a `----------------------` at the bottom of the license file, and use that as the delimiter.

**Comment by fabriziocucci** [comment]
@nedtwigg I won't proceed with the PR if you don't think it's worth it! 😉 

Thanks again for your help! 👍
