### ISSUE TITLE
Only format changed code in changed files

### ISSUE THREAD

**Issue by alexec** [diffplug/spotless#1975]
I'm writing a tool to do the following:

- List to Github webhook.
- Check out code.
- Lint/format/fix changed code.
- Commit changes.
- Push back to branch.

How can I use Spotless to do this?

**Comment by nedtwigg** [comment]
Spotless can do the `spotlessApply`. There are also some projects to turn spotless into a bot:

- https://github.com/marketplace/cleanthat by @blacelle 
- #655
- #1704
