### ISSUE TITLE
[gradle] spotlessCheck.dependsOn someOtherTask doesn't work

### ISSUE THREAD

**Issue by d1ss0nanz** [diffplug/spotless#198]
- [x] summary of problem
Could not get unknown property 'spotlessCheck' for root project 'xxx' of type org.gradle.api.Project

- [x] gradle version
4.4
- [x] spotless version
3.9.0
- [x] operating system and version
Linux/Mac/Windows

- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```
apply plugin: "com.diffplug.gradle.spotless"

buildscript {
    dependencies {
        classpath group: "com.diffplug.spotless", name: "spotless-plugin-gradle", version: "3.9.0"
    }
}

spotlessCheck.dependsOn extractConfigDependencies

spotless {
    java {
        // Available versions are listed at https://bintray.com/diffplug/opensource/spotless-ext-eclipse-jdt
        eclipse('4.7.2').configFile 'config/eclipse/SEP_eclipse_formatter_settings.xml'
    }
    groovyGradle {
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
}
```

- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
This is the error:
Could not get unknown property 'spotlessCheck' for root project 'xxx' of type org.gradle.api.Project

Stacktrace is not adding relevant information.

**Comment by nedtwigg** [comment]
There are two reasons this isn't working:

- spotless' tasks are created in the `afterEvaluate` phase, so they don't exist yet when the code is throwing its exception
- even if they did, `spotlessCheck` and `spotlessApply` don't do the work, they rely on other tasks (e.g. `spotlessJava`) to do the actually check and apply, so the `extractConfigDependencies` task might not have run in time.

I think this should work:

```gradle
tasks.withType(com.diffplug.gradle.spotless.SpotlessTask) { it.dependsOn(extractConfigDependencies) }
```

**Comment by nedtwigg** [comment]
Feel free to reopen if you'd like to discuss further.
