### ISSUE TITLE
What is the recommended phase for `apply`?

### ISSUE THREAD

**Issue by alexec** [diffplug/spotless#1981]
I'm unclear on the best phase to use `apply` in. 

Maven does not have a `lint` phase. 

- `generate-sources` this causes problems when the parent pom has spotless and the child pom has some code generation plugins. 
- `process-sources` (or `process-test-sources`) prevent interfering with code generator, also seems semantically correct
- `compile` (or `test-compile`) this works well as why both linting code which cannot compiled?
- `package` some teams seem to use this phase?
- `install` or `verify` this means that it won't happen in a standard compile/run loop, which is good for local-dev. Does mean it might get missed.

**Comment by nedtwigg** [comment]
It should not be called in any of those phases, it should be called manually. If `apply` is called on a CI machine, then you can commit broken code, and it will pass because the CI machine will fix the code after it is checked-out.

Some people use spotless this way, but it is not recommended.
