### ISSUE TITLE
gradle doesn't respect repository setting when downloading eclipse jdt libraries

### ISSUE THREAD

**Issue by stamhankar999** [diffplug/spotless#1985]
If you are submitting a **bug**, please include the following:

- [ X] summary of problem
- [ X] Gradle or Maven version
- [ X] spotless version
- [ X] operating system and version
- [ X] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

Summary: our CI environment is fairly locked down, so we retrieve artifacts from an in-house Artifactory, which proxies to the internet as needed. When a Gradle build runs with a spotify config that requires the Eclipse jdt, it fails because the retrieval attempt occurs directly against... some Maven-central-type end-point.

Gradle version: 8.5
Spotless version: 6.22.0
OS: Linux; not easy to get distro, but probably not relevant for this ticket.
Spotless config:
```
spotless {
    java {
        toggleOffOn()
        removeUnusedImports()
        eclipse().configFile('fmt.xml')
        formatAnnotations()
    }
}
```

**Comment by nedtwigg** [comment]
> When a Gradle build runs with a spotify config that requires the Eclipse jdt, it fails because the retrieval attempt occurs directly against... some Maven-central-type end-point.

Here's what's happening

- eclipse publishes its jars natively to p2, not maven
- they are mirrored to maven central, but the maven artifacts don't have enough dependency metadata
- we should embed that metadata so it can be pure maven, that is tracked in #1996
  - there is a workaround for your issue in that issue (use old version)
- once that dependency metadata is downloaded, it would respect your repository setting
- but you are correct to say "hey!", it sucks
