### ISSUE TITLE
Handling unambiguous imports and optimizing imports for Java on the fly through spotless

### ISSUE THREAD

**Issue by umarpro18** [diffplug/spotless#1993]
Need help, I ran spotlessApply during commit (via git hooks) post successful commit the java files again undergoes changes that applied via "intellij auto unambiguous imports and optimizing imports on fly". How we can omit this happening without disabling the auto import on the fly option?
java {
          target '**/*.java'
          googleJavaFormat().aosp()
          removeUnusedImports()
          trimTrailingWhitespace()
          indentWithSpaces()
          endWithNewline()
    }

**Comment by nedtwigg** [comment]
Until Spotless can embed the IntelliJ formatter directly

- #200 

we can't guarantee that no changes between Spotless and IntelliJ.
