### ISSUE TITLE
Option to enable JavaDoc formatting for Palantir code formatter

### ISSUE THREAD

**Issue by blutorange** [diffplug/spotless#1995]
Formatting JavaDoc can be very helpful when writing docs, especially to add the appropriate line breaks so that text is not longer than the configured line width.

Palantir, which is based on the Google formatter, supports formatting JavaDoc.

In https://github.com/palantir/palantir-java-format/pull/152 they've disabled the formatting of JavaDoc by hardcoding a "false" value.

According to the comments https://github.com/palantir/palantir-java-format/issues/724, the intended way forward is that it should stay disabled by default, but tools may expose an option to enable it.

After taking a quick look, all we would have to do is to add an option `formatJavadoc` to the Palantir settings, pass on that configuration value to  `PalantirJavaFormatFormatterFunc`, and add `.formatJavadoc(formatJavadoc)` when [creating](https://github.com/diffplug/spotless/blob/main/lib/src/palantirJavaFormat/java/com/diffplug/spotless/glue/pjf/PalantirJavaFormatFormatterFunc.java#L35) the [formatter options](https://github.com/palantir/palantir-java-format/blob/develop/palantir-java-format-spi/src/main/java/com/palantir/javaformat/java/JavaFormatterOptions.java).

I would take a look at a PR if adding such an option is OK?

**Comment by Goooler** [comment]
That would be awesome!

**Comment by Goooler** [comment]
Links #1287.
