### ISSUE TITLE
Consider raising minimum supported Gradle version to 8

### ISSUE THREAD

**Issue by ciscoo** [diffplug/spotless#2004]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem
- [ ] Gradle or Maven version
- [ ] spotless version
- [ ] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

----

The current required minimum Gradle 6.1.1 which was released nearly 4 years ago: https://docs.gradle.org/6.1.1/release-notes.html

I think its time to raise the minimum to a supported version of Gradle. By supported, I mean the Gradle team has a milestone for it: https://github.com/gradle/gradle/milestones

There exists a milestone for Gradle 7, but there have been several release of 8 already, I suggest going for the latest.

I'm not familiar with Spotless' codebase, but I would think this would reduce some technical debt due to maintaining support for legacy versions of Gradle. And of course take advantage of any new things.

**Comment by nedtwigg** [comment]
The only technical debt around Gradle that I am aware of is 

- https://github.com/diffplug/spotless/issues/987

which is not related to supporting old versions of Gradle. I'd happily bump minimum to 8 if it provided anything, and I'm happy to reopen if someone finds something where our thorough back-compat is holding us back.
