### ISSUE TITLE
shfmt - Shell support should respect .editorconfig configurations instead of using defaults

### ISSUE THREAD

**Issue by tcrawford-figure** [diffplug/spotless#2014]
shfmt supports [.editorconfig](https://github.com/mvdan/sh/blob/7f96e7d84a265f4d1005b96493422cde800bf9d1/cmd/shfmt/shfmt.1.scd#examples) out of the box so spotless should support this too, if possible, instead of using the current default flags. If editorconfig can't be supported for some reason, maybe a fallback to some `shfmt()` extension DSL should be added in case developers want to codify the flags into their Gradle configuration. The current default flags do not appear to give developers any way of overriding them however and force developers to use an indent of 2 spaces and for case statements to be indented (which some developers may not want).

**Comment by Goooler** [comment]
I believe we can ref the implementation of .editorconfig support for Ktlint.
