### ISSUE TITLE
How to ignore javaDoc formatting on JDK8

### ISSUE THREAD

**Issue by bingo982426** [diffplug/spotless#2015]
JDK 8
spotless 6.13.0
How to ignore javaDoc formatting？ 
Only the latest configuration can be found on the documentation!

**Comment by Goooler** [comment]
Check https://github.com/diffplug/spotless/tree/main/plugin-gradle#google-java-format

**Comment by bingo982426** [comment]
> Use the latest Spotless Gradle plugin:
> 
> ```groovy
> spotless {
>   java {
>     googleJavaFormat().formatJavadoc(false)
>     ...
>   }
> }
> ```
> 
> Check: https://github.com/diffplug/spotless/tree/main/plugin-gradle#google-java-format Note: this feature is introduced in `6.22.0`.

on JRE 8, use id 'com.diffplug.spotless' version '6.13.0' or older

**Comment by Goooler** [comment]
No plan for backporting.

**Comment by bingo982426** [comment]
> No plan for backporting.

6.13 can't ignore javadoc?

**Comment by Goooler** [comment]
This feature is supported from Spotless Gradle plugin 6.22.0. I believe you can bump your running JDK and pin the compatibility and target to Java 8.
