### ISSUE TITLE
Possibility to update licenses only if they match existing pattern?

### ISSUE THREAD

**Issue by hzsweers** [diffplug/spotless#202]
In some projects, there's source code copied in from other open source projects, and their licenses should presumably remain in tact. Is it possible (or considerable) to only update if the license name matches a specific subset of existing authors?

**Comment by nedtwigg** [comment]
I think you're probably best off setting the `target` parameter to exclude the source code copied-in from the entire formatting process.  Something like (might be missing some `**`:

```gradle
target fileTree(dir: 'src/main/java', exclude: 'src/main/java/org/apache/stuffIcopied')
```

If you wanted to make a license step that only applies if a certain regex is met, you could certainly do that easily as a [custom step](https://github.com/diffplug/spotless/blob/master/CONTRIBUTING.md).  It seems difficult to do what you'd like without making the api/docs too complex.  If you can figure out a clean API / docs, it would be trivial to implement from there.  Happy to accept PRs.

**Comment by nedtwigg** [comment]
Feel free to reopen if you'd like to discuss further.

**Comment by nedtwigg** [comment]
Not exactly what you were asking for, but closely related is our new [`ratchetFrom 'origin/master'`](https://github.com/diffplug/spotless/tree/master/plugin-gradle#ratchet) feature.  If you commit third-party code with its own headers and leave it alone, then Spotless will too.
