### ISSUE TITLE
Bug: Error while evaluating property 'lineEndingsPolicy' Spotless JVM-local cache is stale.

### ISSUE THREAD

**Issue by eye2web** [diffplug/spotless#2025]
- Gradle 8.5
- Spotless 6.25.0
- Windows 10 enterprise

spotless.conventions.gradle.kts
```
spotless {
    java {
        lineEndings = LineEnding.UNIX
        importOrder("\\#java", "\\#javax", "\\#org", "\\#", "java", "javax", "org")
        target("src/*/java/**/*.java")
        removeUnusedImports()
    }
}
```

```
* What went wrong:
Execution failed for task ':project:spotlessJava'.
> Error while evaluating property 'lineEndingsPolicy' of task ':x:spotlessJava'.
   > Spotless JVM-local cache is stale. Regenerate the cache with
       rmdir /q /s .gradle/configuration-cache
     To make this workaround obsolete, please upvote https://github.com/diffplug/spotless/issues/987
```

Reproduce: 
- Run `./gradlew build` from umbrella includeBuilds project. (Generates the config cache)
- Run `./gradlew --stop` Stop running deamons
- Run `./gradlew build` from umbrella includeBuilds project. (Fails)

**Comment by nedtwigg** [comment]
The workaround is in the message:

> rmdir /q /s .gradle/configuration-cache

Regardless these will hopefully go away in a week or two when this gets finished

- #1274
