### ISSUE TITLE
ignoreErrorFromPath or targetExclude not seems to be working as indented

### ISSUE THREAD

**Issue by umarpro18** [diffplug/spotless#2028]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem
- [ 8.1] Gradle or Maven version
- [ 6.25.0] spotless version
- [ Mac OS] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

spotless {
    //ratchetFrom 'origin/main'

    kotlin {
        target '**/*.kt'
        ignoreErrorForPath("**/DebugMessageItems.kt")
        ignoreErrorForPath("**/DataConsentStorage.kt")
        ignoreErrorForPath("**/AppTheme.kt")

        targetExclude("$rootDir/core/ui/src/main/AppTheme.kt")
        targetExclude("$rootDir/core/datastorage/src/main/StorableAliases.kt")

        ktlint().setEditorConfigPath("${projectRootDir}/.editorconfig")
                .editorConfigOverride(["max_line_length": 140])

    }
}

The above files were not excluded from formatting nor skipped without build error.
The above kt files produce ktlint formatting error and I need to skip those without build error due to exception. please advise.

**Comment by nedtwigg** [comment]
I advise heavily againt `target '**/*.kt'`, something like `target 'src/**/*.kt'` will have much better performance and fewer errors

- `ignoreErrorForPath` doesn't accept wildcards
- I would use relative paths in `targetExclude`, or at least println the `rootDir`, might be targetExcluding the wrong path
