### ISSUE TITLE
Respect .gitattributes to check file encodings

### ISSUE THREAD

**Issue by lehmanju** [diffplug/spotless#2029]
We plan to use spotless in projects with java files that still have Cp1252 encoding mixed with other files that have UTF-8 encoding. We want to use `.gitattributes` to set the encoding of a project on a per file basis. However, with spotless we would have to configure the encoding separately instead of just respecting the settings in `.gitattributes`.

There is already a similar feature with line endings where you can configure spotless to use settings from `.gitattributes`. (https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md#line-endings-and-encodings-invisible-stuff)

Would a similar feature be possible for encodings?

**Comment by nedtwigg** [comment]
Probably not. As it stands, our code is structured such that the encoding is set at the formatter level:

https://github.com/diffplug/spotless/blob/2e33d3b04d13ab398ca9b48363f74a8fb2cde81f/lib/src/main/java/com/diffplug/spotless/Formatter.java#L39-L48

As you can see, there is `LineEndingPolicy` which can be a per-file function, but there is no `CharsetEncodingPolicy` to accept a per-file encoding.

It could be added, but non-UTF-8 encodings are so rare now that it is not worth accepting this complexity into the code. It would be pretty easy to maintain a fork with this capability if you really need it, but it's probably less effort to either

- convert all your code to the same encoding
- manually specify the encodings for each target
  - https://github.com/diffplug/spotless/tree/main/plugin-gradle#line-endings-and-encodings-invisible-stuff

**Comment by nedtwigg** [comment]
To change my mind, link some open source projects which have this issue (random files with unusual encodings which are properly configured in `.gitattributes`). It could be that I have a blindspot to how important this is since I only know one language.
