### ISSUE TITLE
Enable specifying of formatter configuration using URL

### ISSUE THREAD

**Issue by reinhapa** [diffplug/spotless#2040]
It would be a big benefit to specify an URL instead of a file to configure shared settings in case of a central definition, instead to have redundant files in each repository.

**Comment by jbduncan** [comment]
@reinhapa I understand this can be done already with https://github.com/diffplug/blowdryer, which allows any Gradle build to import stuff from "immutable" URLs. I imagine you could use this to import a common Gradle file containing your Spotless setup in all of your projects, if I understood you correctly. Does this work for you, by any chance?

**Comment by nedtwigg** [comment]
@jbduncan is correct, Spotless is not going to support this natively, but you can achieve this with blowdryer

- https://github.com/search?q=repo%3Adiffplug%2Fspotless+blowdryer&type=issues
