### ISSUE TITLE
Formating files in a temporary directory

### ISSUE THREAD

**Issue by siba-dev** [diffplug/spotless#2065]
Hey everyone,
I have a Gradle task that generates a bunch of java classes into a temporary directory (And its subdirectories) and im trying to format them with spotless using Eclipse JDT and my own formating config.
Currently, relevant parts of, my build file look like this: 

```
project.ext.tempDir = layout.buildDirectory.dir('tmp/gen').get().getAsFile().getAbsolutePath()

spotless {
  java {
    eclipse('4.26').configFile("$codeformatConfig")
    target "$tempDir"
  }
}

tasks.register('format') {
    dependsOn tasks.named('generate') <= Generates the files into $tempDir
    dependsOn tasks.named('spotlessApply')
}
```

Whenever i run it I get this Exception

java.nio.file.NoSuchFileException: PROJECTDIR\build\spotless\spotlessJava\entitygen_spotless\SUBDIRECTORIES\FILE.java -> PROJECTDIR\entitygen_spotless\SUBDIRECTORIES\FILE.java

Why does this occur and how can I fix it?
Thanks in advance

**Comment by Goooler** [comment]
```groovy
tasks.named('spotlessApply') {
  dependsOn tasks.named('generate')
}
```

**Comment by siba-dev** [comment]
> ```groovy
> tasks.named('spotlessApply') {
>   dependsOn tasks.named('generate')
> }
> ```

Thanks for your reply,
the problem was caused by the build cache and was fixed!
