### ISSUE TITLE
How to suppress a custom rule for a function

### ISSUE THREAD

**Issue by NikhilMunna** [diffplug/spotless#2104]
i've added https://mrmans0n.github.io/compose-rules/rules/#hoist-all-the-things custom ruleset to ktlint spotless

but  i'm unable to suppress a rule for a function

I tried adding 
@Suppress("ktlint:compose:vm-forwarding-check") above the function but it doesn't work

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessKotlin'.
> Error on line: 127, column: 17
  rule: compose:vm-forwarding-check
  Forwarding a ViewModel/Presenter through multiple @Composable functions should be avoided. Consider using state hoisting.
  
  See https://mrmans0n.github.io/compose-rules/rules/#hoist-all-the-things for more information.

* Try:
> Run with --info or --debug option to get more log output.

**Comment by Goooler** [comment]
See https://github.com/mrmans0n/compose-rules/issues/139.

**Comment by NikhilMunna** [comment]
I want to suppress for only one function not across the app.

**Comment by Goooler** [comment]
Did you see my comment issue?

```kt
@Suppress("ktlint_compose_vm-forwarding-check")
```

**Comment by NikhilMunna** [comment]
Yes, thats also not working
added this 
`@Suppress("ktlint_compose_vm-forwarding-check")`

**Comment by Goooler** [comment]
If any suppression is not working, please file it to the ruleset project.

**Comment by NikhilMunna** [comment]
It is working with ktlint CLI but when added to spotless it is not working
