### ISSUE TITLE
could not resolve plugin artifact 'com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.25.0') Searched in the following repositories maven(https://plugins.gradle.org/m2/)

### ISSUE THREAD

**Issue by yyang99** [diffplug/spotless#2105]
I got the following errors when run gradlew build on my new Macbook M2, this build run successfully on my old Macbook, not sure if it's CPU architectue related issue
> ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/yufeng.yang/uDev/matterhorn/cosmos-candyfloss/build.gradle' line: 2

* What went wrong:
Plugin [id: 'com.diffplug.spotless', version: '6.25.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.25.0')
  Searched in the following repositories:
    maven(https://plugins.gradle.org/m2/)

I have following line in build.gradle file

plugins {
    id "com.diffplug.spotless" version "6.25.0" apply false
...

**Comment by Goooler** [comment]
https://plugins.gradle.org/plugin/com.diffplug.spotless
