### ISSUE TITLE
Only last step in `kotlin {}` would apply

### ISSUE THREAD

**Issue by ziqiao-wang** [diffplug/spotless#2117]
If you are submitting a **bug**, please include the following:

- [x] summary of problem: I use both ktfmt and ktlint to format my kotlin codes. I added both ktfmt and ktlint to `kotlin` block in gradle spotless configuration, it used to be applied in sequential order but seems now only the last step got applied.
- [x] Gradle or Maven version: `8.7`
- [x] spotless version: `6.25.0`
- [x] operating system and version: `macOS 14.5`
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
    ```kt
        kotlin {
            toggleOffOn()
            target(ktTargets, ktsTargets)
    
            ktfmt(ktfmt_version).kotlinlangStyle()
    
            ktlint(libs.versions.ktlint.get())
                .setEditorConfigPath(file(".editorconfig"))
                .editorConfigOverride(
                    mapOf(
                        "ij_kotlin_allow_trailing_comma" to "true",
                        "ij_kotlin_allow_trailing_comma_on_call_site" to "true",
                        "ij_kotlin_packages_to_use_import_on_demand" to "*",
                        "ktlint_standard_property-naming" to "disabled",
                        "ktlint_standard_discouraged-comment-location" to "disabled",
                    ),
                )
        }
    ```
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`: N/A

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment]
I don't think that's true. Both will run, it's just that `ktlint` runs last and undoes some of `ktfmt`. What's the bug?

**Comment by ziqiao-wang** [comment]
> I don't think that's true. Both will run, it's just that `ktlint` runs last and undoes some of `ktfmt`. What's the bug?

I have something like this
```kt
NettyChannelBuilder.forAddress(host, port)
        .usePlaintext()
        .apply {
        }
        .build()
```

with `ktfmt`(0.46) applied then `ktlint`(1.0.1) it will be formatted like above
however, with spotless 6.25.0
If I have unformatted code like below
```kt
NettyChannelBuilder.forAddress(host, port)
        .usePlaintext()
        .apply {
        } .build()
```
it will be formatted like
```kt
NettyChannelBuilder.forAddress(host, port)
        .usePlaintext()
        .apply {
        }.build()
```

I am currently hacking it with below to get ktfmt applied first then ktlint
```kt
    kotlinGradle {
        toggleOffOn()
        target(ktTargets, ktsTargets)

        ktfmt(libs.versions.ktfmt.asProvider().get()).kotlinlangStyle().configure {
            it.setMaxWidth(120)
            it.setRemoveUnusedImport(true)
        }
    }

    kotlin {
        toggleOffOn()
        target(ktTargets, ktsTargets)

        ktlint(libs.versions.ktlint.get())
            .setEditorConfigPath(file(".editorconfig"))
            .editorConfigOverride(
                mapOf(
                    "ij_kotlin_allow_trailing_comma" to "true",
                    "ij_kotlin_allow_trailing_comma_on_call_site" to "true",
                    "ij_kotlin_packages_to_use_import_on_demand" to "*",
                    "ktlint_standard_property-naming" to "disabled",
                    "ktlint_standard_discouraged-comment-location" to "disabled",
                ),
            )
    }
    
    
tasks.named("spotlessKotlin").configure { dependsOn("spotlessKotlinGradle") }

tasks.named("spotlessKotlinApply").configure { dependsOn("spotlessKotlinGradleApply") }

tasks.named("spotlessKotlinGradle").configure { finalizedBy("spotlessKotlin") }

tasks.named("spotlessKotlinGradleApply").configure { finalizedBy("spotlessKotlinApply") }
```

**Comment by nedtwigg** [comment]
It looks you prefer the `ktfmt` style. Your workaround is a verbose way to put the `ktfmt` step after the `ktlint` step.

My advice is to remove the `ktlint` step entirely, you probably don't want both. But if you do really want both, the order matters.

**Comment by ziqiao-wang** [comment]
> It looks you prefer the `ktfmt` style. Your workaround is a verbose way to put the `ktfmt` step after the `ktlint` step.
> 
> My advice is to remove the `ktlint` step entirely, you probably don't want both. But if you do really want both, the order matters.

I actually put ktlint after ktfmt. I mostly want ktfmt but needs ktlint to redo some indentation. Now whatever order I put in `kotlin {}`, always last one got applied 😭. I verified this by reformatting the whole repo with `kotlin { ktfmt() ktlint()}` or `kotlin { ktlint() ktfmt() }` always seeing a bunch of diff(with codes formatted by my current workaround)

**Comment by nedtwigg** [comment]
This is the expected behavior. The steps aren't doing "checks", they `Function<String, String>`. So the next one will wipe out parts of the previous one.

**Comment by ziqiao-wang** [comment]
> Member

If that's the case I would expect my workaround got same wiping, right? but it's not, so I think it's ktfmt not got applied

**Comment by nedtwigg** [comment]
Aha! Your workaround is doing two things:

- it's swapping the order
- it's working around this bug https://github.com/diffplug/spotless/issues/1599

**Comment by ziqiao-wang** [comment]
> Aha! Your workaround is doing two things:
> 
> * it's swapping the order
> * it's working around this bug [ktlint appears to be reading from the `File` not the `String` #1599](https://github.com/diffplug/spotless/issues/1599)

Gotcha, I guess it's related to https://github.com/diffplug/spotless/issues/1599 then, cuz I am not actually swapping orders, it's still ktfmt => ktlint 😂 .
