### ISSUE TITLE
How to use gradle spotless in multi-module ?

### ISSUE THREAD

**Issue by yoobi** [diffplug/spotless#2150]
Hello ! 

This is quite straight forward, how are we supposed to use gradle spotless for multi module ?
I have this repo https://github.com/yoobi/CleanArch in which I'd like to add spotless as you can see there is multiple gradle module
- `:app`
- `:core:fragment-ui`
- `:core:network`
- `:core:view`
...

Should I declare spotless once in the `build.gradle` of the project or declare spotless in each module ?

**Comment by nedtwigg** [comment]
Use spotless in each module. You might get some benefit by declaring which formatters you use in the root project.

https://github.com/diffplug/spotless/tree/main/plugin-gradle#dependency-resolution-modes
