### ISSUE TITLE
ImportOrderStep reads its config file eagerly, rather than lazily

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#218]
https://github.com/diffplug/spotless/blob/995b6a92cbfa39417b89cd5ec2d68e05b26a8498/lib/src/main/java/com/diffplug/spotless/java/ImportOrderStep.java#L56-L59

It shouldn't read the file until its state is calculated.  First discovered in #217.

**Comment by jbduncan** [comment]
I suspect the easiest fix would be to make `getImportOrder` return a lazy `Supplier<List<String>>`.

**Comment by jbduncan** [comment]
...and the memoize the result of this supplier somehow.

**Comment by nedtwigg** [comment]
`FormatterStep.createLazy` handles the memoization for you.

**Comment by jbduncan** [comment]
Cheers for tackling this, @nedtwigg. :)

**Comment by nedtwigg** [comment]
Published in 3.18.0
