### ISSUE TITLE
There is no way to specify java modifier order

### ISSUE THREAD

**Issue by estradanic** [diffplug/spotless#2206]
As far as I can tell, there are no formatters that are able to sort java modifier order.

Consider:

```java
final static public @Nullable String test = "";
```

That's gross. I want to reformat it like this:

```java
@Nullable public static final String test = "";
```

It would be cool if there was some way to specify modifier order. Maybe by a function where a user could pass in a list of modifier types in the order they'd like them to appear.

Proposed modifier types: annotation, access, abstract, static, final, transient, volatile, synchronized, native, strictfp

**Comment by nedtwigg** [comment]
We support a lot of different formatters. If any of them land this feature, you can use it here. You can use `replace` to fix `final static public` into `public static final`, and many other minor customizations like that.
