### ISSUE TITLE
update eslint to 9.x

### ISSUE THREAD

**Issue by jvaa** [diffplug/spotless#2214]
Currently supported version seems to be 8.45 which is more than 1 year old. Should support later 9.x version. Could eslint be updated?

**Comment by nedtwigg** [comment]
You can set a different version manually

- https://github.com/diffplug/spotless/tree/main/plugin-maven#eslint-typescript
- https://github.com/diffplug/spotless/tree/main/plugin-gradle#eslint-typescript

Happy to take a PR that updates the default.

**Comment by jvaa** [comment]
No. Tested and 9.x versions do not work. Need to check if I can create PR to update required libs.
