### ISSUE TITLE
How to replace one year with another in license header

### ISSUE THREAD

**Issue by snuyanzin** [diffplug/spotless#2217]
Here in documentation it is mentioned https://github.com/diffplug/spotless/tree/main/plugin-maven#license-header
that `$YEAR` and `$today.year` could be used.

also there were mentioned possible variations
>
    No license header -> 2020
    2017 -> 2017-2020
    2017-2019 -> 2017-2020

the question is whether it is possible always to set only last (e.g. current) year like

>
    No license header -> 2020
    2017 -> 2020

**Comment by nedtwigg** [comment]
Maybe I'm missing something, but you can just put the year you want: `/* Apache-2.0 (c) 2020 */`
