### ISSUE TITLE
Disable import change to star/wildcard

### ISSUE THREAD

**Issue by poliveira-fuze** [diffplug/spotless#2245]
I've made the changes manually, but the spotless keep changing back to the start/wildcard.

Is possible to turn off?

**Comment by nedtwigg** [comment]
Definitely! But it depends on what formatter you're using. If you're using `eclipse` then you'll need to look at the eclipse docs if you're using `googleJavaFormat` then you'll need to look at their docs, etc. Spotless is just a switchboard to those.

**Comment by poliveira-fuze** [comment]
> Definitely! But it depends on what formatter you're using. If you're using `eclipse` then you'll need to look at the eclipse docs if you're using `googleJavaFormat` then you'll need to look at their docs, etc. Spotless is just a switchboard to those.

In my case is `<gooleJavaFormat>` but I'm struggling to find a way to "implement" `AvoidStartImport` or even disable any import related change.

**Comment by nedtwigg** [comment]
Ah, we might not expose that property in our DSL. Happy to take a PR to expose it.

**Comment by jbduncan** [comment]
Sadly I don't think it's possible due to https://github.com/google/google-java-format/issues/1154#issuecomment-2321722479. :(
