### ISSUE TITLE
How about adding a git hook to check

### ISSUE THREAD

**Issue by stuarthendren** [diffplug/spotless#225]
Feature request: Add a goal to install a git-hook to run the check pre-commit.

Something like this is done here for the google style <https://github.com/Cosium/maven-git-code-format>

**Comment by smoothreggae** [comment]
[This article](https://proandroiddev.com/ooga-chaka-git-hooks-to-enforce-code-quality-11ce8d0d23cb) describes a way to set up a pre-commit hook using Gradle. I have been meaning to try this out in conjunction with a Spotless configuration. It would be nice to see this feature in Spotless.

**Comment by nedtwigg** [comment]
Dup of #178
