### ISSUE TITLE
class propeties formatter one line 

### ISSUE THREAD

**Issue by xinyu162** [diffplug/spotless#2263]
I use  IDEA  :

one class properties doc not one line : 
like this  :
![image](https://github.com/user-attachments/assets/a6f1a214-6ac4-4ca7-9bfc-1bea93175665)

use spotless conf  ：

           <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.30.0</version>
                <configuration>
                    <java>
                        <googleJavaFormat>
                            <version>1.7</version>
                            <style>AOSP</style>
                        </googleJavaFormat>     
                        <removeUnusedImports/>
                        <formatAnnotations/>
                        <importOrder>
                            <order>,javax,java,\#</order>
                        </importOrder>

                        
                        
                        
                        
                        
                        <endWithNewline/>
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <id>spotless-check</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>apply</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

spotless   apply formatter  get  

![image](https://github.com/user-attachments/assets/200a839c-e508-4833-b824-8d4c03df38c0)

but I want   ,  not formatter  one line doc common , 

wath can I do ?

**Comment by xinyu162** [comment]
I use jdk 8

**Comment by nedtwigg** [comment]
Spotless is just a switchboard for other formatters, I think this is asking for a feature in google-java-format, which is out of scope. You might be able to make the eclipse formatter do what you want, but you will have to mess with the settings file.
