### ISSUE TITLE
Fetch config files from remote repository/dependency/jar

### ISSUE THREAD

**Issue by nickmelis** [diffplug/spotless#227]
I'm using Spotless across several projects and I find myself in the situation where I have to copy/paste the config files (license, import order and format) in every single project in order to make it work consistently across the board.

It would be nice to be able to fetch config files from a remote location or read them from a dependency of some sort. I've tried fiddling with Gradle but there doesn't seem to be any easy solution to that.

**Comment by JLLeitschuh** [comment]
I think this might be useful to you:
https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins
> Script plugins are automatically resolved and can be applied from a script on the local filesystem or at a remote location. Filesystem locations are relative to the project directory, while remote script locations are specified with an HTTP URL. Multiple script plugins (of either form) can be applied to a given target.

**Comment by nedtwigg** [comment]
Getting resources from a jar is being considered in #217.
