### ISSUE TITLE
JavaDoc Block Modified Despite // spotless:off Directive

### ISSUE THREAD

**Issue by halber** [diffplug/spotless#2276]
### Bug Report

**Summary of the problem:**  
When running `./gradlew spotlessApply`, the JavaDoc in `Example.java` is altered despite the usage of `// spotless:off` and `// spotless:on`, which are supposed to prevent formatting in that section.

**Before executing** `./gradlew spotlessApply`:
```java
package io.example;

// spotless:off
/**
 * some text
 *
 * <pre>
 * {@code
 * @SuppressWarnings("unused")
 * public class SomeClass {
 *
 *     @Override
 *     public String someMethod() {
 *         return "something";
 *     }
 * }
 * }</pre>
 */
// spotless:on
public class Example {
}
```

**After executing** `./gradlew spotlessApply`:
```java
package io.example;

// spotless:off
/**
 * some text
 *
 * <pre>
 * {
 * 	&#64;code
 * 	&#64;SuppressWarnings("unused")
 * 	public class SomeClass {
 *
 * 		@Override
 * 		public String someMethod() {
 * 			return "something";
 * 		}
 * 	}
 * }
 * </pre>
 */
// spotless:on
public class Example {
}
```

In the second example, the JavaDoc block gets altered, even though it is within the `// spotless:off` and `// spotless:on` block, where no formatting should be applied.

**Gradle Version:**  
Gradle 8.8

**Spotless Version:**  
6.25.0

**Operating System and Version:**  
macOS 15

**Spotless Configuration:**  
The Spotless configuration block in the `build.gradle` file:
```groovy
plugins {
  id 'java'
  id "com.diffplug.spotless" version "6.25.0"
}

group = "io.example"
version = "1.0.0-SNAPSHOT"

repositories {
  mavenCentral()
}

spotless {
  java {
    eclipse().configFile('gradle/eclipse-formatter.xml')
  }
}
```

**Eclipse Formatter Configuration:**  
The Eclipse formatter configuration (`eclipse-formatter.xml`) used:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="15">
    <profile kind="CodeFormatterProfile" name="forme" version="15">
        <setting id="org.eclipse.jdt.core.formatter.comment.format_javadoc_comments" value="true" />
    </profile>
</profiles>
```

**Console Output:**  
No specific errors are emitted when running the command, but the formatting changes occur unexpectedly:
```bash
BUILD SUCCESSFUL in 702ms
3 actionable tasks: 2 executed, 1 up-to-date
```

**Reproducible Example:**  
You can find a full example on GitHub: [https://github.com/halber/spotless-issue.git](https://github.com/halber/spotless-issue.git)

**Comment by jbduncan** [comment]
@halber Are you missing [`toggleOffOn()`](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson), by any chance? :)

**Comment by halber** [comment]
@jbduncan Oh damn, yes you are right, I forgot toggleOffOn(). 
Thanks!
