### ISSUE TITLE
Add option to preserve line ending during check/formatting

### ISSUE THREAD

**Issue by kwin** [diffplug/spotless#2277]
Currently the [lineEndings option](https://github.com/diffplug/spotless/tree/main/plugin-maven#line-endings-and-encodings-invisible-stuff) does only allow to configure which line endings to expect. There is no single option which works on non-Git based source code (i.e. extracted from a ZIP source archive) accepting both line endings (Windows and Unix).

This is crucial though because by default source archives created with [maven-source-plugin](https://maven.apache.org/plugins/maven-source-plugin/) are not normalized with respect to line endings, i.e. the archives end up with Windows endings on a Windows machine and Unix endings on all other machines. As the spotless configuration is part of the source archive, building should not fail with spotless errors irrespective of the line ending.

**Comment by nedtwigg** [comment]
> the archives end up with Windows endings on a Windows machine and Unix endings on all other machines

PLATFORM_NATIVE should work here, yeah?

**Comment by kwin** [comment]
No, you have arbitrary line endings in the source and it should work with the same config in Windows and Unix machines. PLATFORM_NATIVE only works if source was created with the same platform, but not if created on a platform with another line ending.

**Comment by nedtwigg** [comment]
I'm open to a `PRESERVE` option here:

https://github.com/diffplug/spotless/blob/b2a2cbb8b6026397c0adb8cb8b3571e399276f9b/lib/src/main/java/com/diffplug/spotless/LineEnding.java#L45-L50

https://github.com/diffplug/spotless/blob/b2a2cbb8b6026397c0adb8cb8b3571e399276f9b/lib/src/main/java/com/diffplug/spotless/LineEnding.java#L134-L136

Two ambiguous cases:

- file with zero line endings
- file with both kinds of line endings

My vote is that both these cases round to "UNIX", but print a warning message.

**Comment by kwin** [comment]
I agree with all you said except for the case

> file with both kinds of line endings

In this case I would just throw an exception. This is IMHO never acceptable.
