### ISSUE TITLE
jgit "fork"

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#2282]
This is neither a bug nor feature but intended as conversation for devs

I have the same need as you guys for a shaded jgit and stopping it from forking to real git. The sheer number of shaded jgit jars makes me think it would be good to upload a "fork" of it somewhere for people to use. Would anyone here be interested in co-maintaining such a thing? mostly to prevent hit by a bus?

P.S [I didn't convince upstream to fix the fundamental issue in this bug](https://github.com/eclipse-jgit/jgit/issues/24), but you can now reduce the subclass code

```java
  static void preventJGitFromCallingExecutables() {
    SystemReader reader = SystemReader.getInstance();
    SystemReader.setInstance(
      new SystemReader.Delegate(reader) {
        @Override
        public String getenv(String variable) {
          if ("PATH".equals(variable)) {
            return "";
          } else {
            return super.getenv(variable);
          }
        }
      }
    );
  }
```

**Comment by nedtwigg** [comment]
Thanks for the offer, not interested in a third-party shaded jgit.
