### ISSUE TITLE
Strange and inconsistent formatting of multiline `try`-with-resources blocks

### ISSUE THREAD

**Issue by dlenskiSB** [diffplug/spotless#2289]
Minimal reproducing example using Java `try`-with-resources syntax and [multiple resources specified](
https://medium.com/@satyendra.jaiswal/the-autocloseable-interface-and-automatic-resource-management-using-try-with-resources-in-java-c2a17c81eede#:~:text=You%20can%20declare%20and%20initialize%20multiple%20resources%20within%20the%20parentheses%2C%20separated%20by%20a%20semicolon.):

```java
class Whatever {
  public Whatever() {
    try (
      // Now here's a lengthy comment about some subtleties in
      // why we're constructing the objects in this order.
      ClassName thing1 = new ClassName();
      ClassName thing2 =
          ClassName.builder().with("something very long and complicated here").stuff().build();
      ClassName thing3 =
          ClassName.builder()
              .foo("more complicated stuff here and here and")
              .blah("also here")
              .build();
    )
    {
      // do stuff
      // with the objects
    }
  }
}
```

Spotless checks wants to _dedent_ the comment and the first resource, but _indent_ the subsequent resources:

```diff
@@ -1,18 +1,16 @@
class·Whatever·{
··public·Whatever()·{
····try·(
-······//·Now·here's·a·lengthy·comment·about·some·subtleties·in
-······//·why·we're·constructing·the·objects·in·this·order.
-······ClassName·thing1·=·new·ClassName();
-······ClassName·thing2·=
-··········ClassName.builder().with("something·very·long·and·complicated·here").stuff().build();
-······ClassName·thing3·=
-··········ClassName.builder()
-··············.foo("more·complicated·stuff·here·and·here·and")
-··············.blah("also·here")
-··············.build();
-····)
-····{
+····//·Now·here's·a·lengthy·comment·about·some·subtleties·in
+····//·why·we're·constructing·the·objects·in·this·order.
+····ClassName·thing1·=·new·ClassName();
+········ClassName·thing2·=
+············ClassName.builder().with("something·very·long·and·complicated·here").stuff().build();
+········ClassName·thing3·=
+············ClassName.builder()
+················.foo("more·complicated·stuff·here·and·here·and")
+················.blah("also·here")
+················.build();·)·{
······//·do·stuff
······//·with·the·objects
····}
```

This results in a very strange looking output:

```java
class Whatever {
  public Whatever() {
    try (
    // Now here's a lengthy comment about some subtleties in
    // why we're constructing the objects in this order.
    ClassName thing1 = new ClassName();
        ClassName thing2 =
            ClassName.builder().with("something very long and complicated here").stuff().build();
        ClassName thing3 =
            ClassName.builder()
                .foo("more complicated stuff here and here and")
                .blah("also here")
                .build(); ) {
      // do stuff
      // with the objects
    }
  }
}
```

If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] Gradle or Maven version
  - Gradle 7.4.2
- [x] spotless version
  - `com.diffplug.spotless:spotless-plugin-gradle:5.14.2`
- [x] operating system and version
  - MacOS 14
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
  - Not a public repo
  - ```
    dependencies {
        implementation 'com.diffplug.spotless:spotless-plugin-gradle:5.14.2'
    }
    ```
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
  - No output

**Comment by nedtwigg** [comment]
You didn't supply your configuration block. Are you using `google-java-format` or `eclipse`? Either way, Spotless is just a switchboard for other formatters, the root cause is the settings of the formatter which has been configured.

**Comment by dlenskiSB** [comment]
Apologies for omitting that. We are indeed using `google-java-format`:

```gradle
dependencies {
    compileOnly 'com.google.googlejavaformat:google-java-format:1.11.0'
}

spotless {
    java {
        googleJavaFormat()
    }
}
```

**Comment by nedtwigg** [comment]
You don't need the `compileOnly`, it won't affect what version you get. Spotless has a default version, or you can do `googleJavaFormat('blah')` to get a specific version. I would update to the latest GJF, and if you still don't like it raise an issue with GJF.
