### ISSUE TITLE
Add support for enforcing line endings from .gitattributes

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#23]
@chkpnt submitted a great PR #22 which allows different line endings for different formats.  After discussion, we've decided to instead implement support for the `.gitattributes` `eol` property.

Provisionally, support will look like this:

```groovy
spotless {
    lineEndings GITATTRIBUTES
}
```

This should probably have been the default behavior all along, but it's a breaking change compared to the current default, `lineEndings PLATFORM_NATIVE`.  As a result I think I'll make this next release version `2.0` to alert users to check the changelog.

As for timeline, I'm planning on implementing this in late June when Eclipse 4.6 and Gradle 2.14 will be released, the combination of which should fix quite a few issues.

**Comment by sbrannen** [comment]
Hi @nedtwigg,

If I'm not mistaken, the proposal here would solve the problem raised by a user who is trying to build JUnit 5 on Windows: https://github.com/junit-team/junit5/issues/398

Is my assumption correct?

Thanks in advance for feedback!

Sam

**Comment by sbrannen** [comment]
Also, no pressure... but are you still planning on releasing Spotless 2.0 in the near future?

**Comment by nedtwigg** [comment]
Hi @sbrannen!  I just finished up [goomph](https://github.com/diffplug/goomph), which makes it [easier for Spotless to get new versions of Eclipse](https://github.com/diffplug/spotless/commit/4131b15cf3181b47aa4c5f57648202c83b9e7253) (namely neon).

With that finished, my task list is:

- incorporate neon (seems a few things are now broken)
- support `.gitattributes`

Looking at the linked bug, I think Spotless 2.0 will not fix it automatically, and I think there's a way to fix it in Spotless 1.x.  [I replied on the issue itself](https://github.com/junit-team/junit5/issues/398#issuecomment-232805577).

**Comment by sbrannen** [comment]
Thanks for the prompt feedback!

Goomph sounds interesting. Seems you've been hard at work.

I followed your advice on the line ending issue in JUnit on Windows, and as far as I can tell... it works like a charm.

Cheers!

**Comment by nedtwigg** [comment]
Finally landed .gitattributes support in 2.0.0-SNAPSHOT.  Ready for testing, see CHANGES.md for details.

**Comment by nedtwigg** [comment]
Fixed in 2.0.0.
