### ISSUE TITLE
Jakarta Validation @Valid annotation is not treated as a type-annotation

### ISSUE THREAD

**Issue by jskov** [diffplug/spotless#2334]
Using Gradle spotless 7.0.0.BETA4 I see wrong handling of formatAnnotations for code like this:

```java
    @Valid
    public TemplateDTO getMetadata() {
         return metadata;
     }
```

Since Jakarta Validation [@Valid](https://jakarta.ee/specifications/bean-validation/3.0/apidocs/jakarta/validation/valid) is annotated with TYPE_USE, it should be changed to:

```java
    @Valid public TemplateDTO getMetadata() {
         return metadata;
     }
```

I will open a PR shortly fixing this.

**Comment by jskov** [comment]
Hm, this is probably more generic and should cover all (relevant) Validation annotations such as Pattern, Size,...

What is the thinking on this? Would that be OK?

**Comment by mernst** [comment]
I agree to add annotations supported by well-known tools.  Thanks!

**Comment by jskov** [comment]
Thanks, will do. Probably this weekend.

**Comment by jskov** [comment]
Got a few moments to complete it now.
I have made #2335 ready for review.

Cheers!
