### ISSUE TITLE
formatAnnotations merges type and non-type annotations in records

### ISSUE THREAD

**Issue by jskov** [diffplug/spotless#2336]
I find that FormatAnnotationsStep works OK with annotations on fields/getters that follow the form mentioned in [this note](https://github.com/diffplug/spotless/issues/1366#issuecomment-1275061403).

But I have started using records in my project and have code like this:

```java
public record EnumsDto(
        @JsonbProperty("external") @Valid @Nullable ExternalEnum external,
        @JsonbProperty("externalLower") @Valid @Nullable ExternalLowerEnum externalLower,
...
```

The above is the formatAnnotations() output.

But it should (if I understand things correctly) be:

```java
public record EnumsDto(
        @JsonbProperty("external")
        @Valid @Nullable ExternalEnum external,
        @JsonbProperty("externalLower")
        @Valid @Nullable ExternalLowerEnum externalLower,
...
```

But since there is no protection keyword (public/private) to separate the non-type annotations from the type-annotations, they all get merged into the same line by FormatAnnotationsStep.

This is observed with version [Gradle Plugin v7.0.0.BETA4](https://github.com/diffplug/spotless/releases/tag/gradle%2F7.0.0.BETA4)

**Comment by jskov** [comment]
I think this can be fixed simply by only stripping newlines from type-annotations.
And thus leaving them for unknown annotations (which does not happen now).

I will work on a patch for this.

**Comment by nedtwigg** [comment]
This is a breaking change that makes me nervous. If you can gate it behind a flag, then I can easily merge. If you can't, we need to consider the impact to existing users a bit. @mernst any thoughts?

**Comment by jskov** [comment]
Sounds reasonable.

**Comment by jskov** [comment]
I have had another look, and the code actually does the right thing.

That is, assuming the input does not mix non-type and type annotations on the same line:

```java
record FormatAnnotationsTest(
  @JsonbProperty("r0")
  @Valid
  @Nullable
  Object r0,
  @JsonbProperty("r1") @Valid
  @Nullable
  Object r1,
  @JsonbProperty("r2") @Valid @Nullable Object r2,
  @Valid
  @Nullable
  String r3) {
}
```

The r0+r3 are formatted correctly with the current implementation.

r1+r2 is what I want to fix.


The existing code handles (explicitly) annotations split with newlines (and whitespace).

The above problems (r1+r2) are of another type; there is not the nice EOL/whitespace markers to guide changes.

So I expect to run into problems with formatting of method arguments.

I will add some more tests and see where it leads me.

**Comment by jskov** [comment]
I cannot see how to do this consistently with just simple line processing, so I am closing the issue.
