### ISSUE TITLE
Spotless-gradle: defined import order is not respected

### ISSUE THREAD

**Issue by zhan3680** [diffplug/spotless#2360]
### summary of problem
I am using spotless-gradle. I defined the import order as `importOrder("", "java", "javax", "\\#")`, which based on my understanding means static import should come at the very end. However, after `spotlessApply` I saw the static imports appearing at the beginning of import section instead.

### Gradle or Maven version
I am using Gradle 8.10.2

### spotless version
I am using spotless-gradle 7.0.0.BETA2

### operating system and version
MacOS 15.1.1

### copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
here is the configuration:
```
extensions.getByType<SpotlessExtension>().apply {
                    java {
                        importOrder(EMPTY_STRING, "java", "javax", "\\#")
                        googleJavaFormat()
                            .aosp()
                            .formatJavadoc(true)
                            .reflowLongStrings(true)
                            .reorderImports(true)
                        formatAnnotations()
                    }
                    groovy {
                        importOrder(EMPTY_STRING, "java", "javax", "\\#")
                        removeSemicolons()
                    }
                }
```

the project resides in an internal private repository and could not be shared for security reasons, sorry for the inconvenience. However, I believe the bug can be reproduced with the above configuration applied to any projects.

### copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
There is no error, `spotlessApply` finished successfully.

**Comment by jbduncan** [comment]
@zhan3680 One thing that I notice is your `googleJavaFormat()` rule is right after your `importOrder()` one. Rule order matters in Spotless because, for example, google-java-format could override the other rules before it.

What happens if you swap the two rules? Does that fix your issue? :)

**Comment by zhan3680** [comment]
> @zhan3680 One thing that I notice is your `googleJavaFormat()` rule is right after your `importOrder()` one. Rule order matters in Spotless because, for example, google-java-format could override the other rules before it.
> 
> What happens if you swap the two rules? Does that fix your issue? :)

This works, thanks very much for the help!
