### ISSUE TITLE
Error ignored when using multiple checks

### ISSUE THREAD

**Issue by awallat** [diffplug/spotless#2362]
# summary of problem

When using multiple checks in kotlin, both tasks are executed but only the last one shows errors. The errors of the first running task seem to be completely ignored.

I have the following configration in my build.gradle
```
spotless {
    kotlin {
        licenseHeaderFile(file('../LICENSE')).updateYearWithLatest(true)
        ktlint()
    }
}
```
Although I have some license header missing, the task spotlessCheck does not show any errors when ktlint was successful.

# Gradle or Maven version
Gradle 8.10.2

# spotless version
6.25.0

# operating system and version
Mac

**Comment by nedtwigg** [comment]
I believe this is fixed in `7.0.0.BETA4`
