### ISSUE TITLE
scala license header

### ISSUE THREAD

**Issue by georgThesis** [diffplug/spotless#255]
How can I apply the `licenseHeader` for `scala?`
My configuration:
```
spotless {
        scala {
            scalafmt()
            licenseHeader = '// TMA IOT'
        }
    }
```
fails with:
`Could not set unknown property 'licenseHeader' for object of type com.diffplug.gradle.spotless.ScalaExtension.`

**Comment by nedtwigg** [comment]
Drop the equals sign.

**Comment by nedtwigg** [comment]
HTH, reopen if it didn't.

**Comment by geoHeil** [comment]
```
spotless {
        scala {
            scalafmt()
            licenseHeader = '// <<m<_value>>'
        }
    }
```
same problem for me `> Could not set unknown property 'licenseHeader' for object of type com.diffplug.gradle.spotless.ScalaExtension.`

**Comment by geoHeil** [comment]
@nedtwigg I can't reopen / do not have permissions.

**Comment by jbduncan** [comment]
@geoHeil Have you tried removing the `=` sign? :)

**Comment by geoHeil** [comment]
yes. ;)

**Comment by nedtwigg** [comment]
Aha - the license header actually takes two arguments.  The first one is a regex that finds the first line in the code - everything above that gets replaces with the license header.

https://github.com/diffplug/spotless/blob/de8ea62dcb3b407f404bb9c5e6b7744c50bb3f52/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L409-L419'

For java, we've got a good regex hardcoded in:

https://github.com/diffplug/spotless/blob/de8ea62dcb3b407f404bb9c5e6b7744c50bb3f52/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java#L45-L57

But we don't have one for Scala:

https://github.com/diffplug/spotless/blob/de8ea62dcb3b407f404bb9c5e6b7744c50bb3f52/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/ScalaExtension.java#L31-L44

So you'll have to do `licenseHeader('someRegex', 'the license that I want')`.  If you're able to find *the* regex, we'd love a PR to make it part of ScalaExtension.

**Comment by jbduncan** [comment]
Ah, @nedtwigg got there before me! I was going to say more or less what he said, other than I think that actually the license header method is `licenseHeader('the license that I want', 'someRegex')`, so the two arguments are swapped. :)

**Comment by geoHeil** [comment]
cools. In general `package ` sounds great. ´

However both ways of calling fail with:

> Unable to find delimiter regex ^someRegex

**Comment by geoHeil** [comment]
I.e. 
`licenseHeader('// my license', 'package ')`

fails with
`> Unable to find delimiter regex ^package `

**Comment by nedtwigg** [comment]
I think that means there's a file that you're trying to format where the license regex is never matching.

**Comment by jbduncan** [comment]
Hmm, that's strange. Does not the word `package` exist near the top of the Scala source file(s) you're trying to format? :thinking:

**Comment by geoHeil** [comment]
No @nedtwigg was correct. Thx.

**Comment by jbduncan** [comment]
Cool! I hope this has helped.

Feel free to continue the conversation on Gitter or open a new issue if you still encounter problems. :)

**Comment by nedtwigg** [comment]
If you care about license headers, you should checkout our new [`ratchetFrom 'origin/master'`](https://github.com/diffplug/spotless/tree/master/plugin-gradle#ratchet) feature.
