### ISSUE TITLE
doesn't apply import ordering to test files

### ISSUE THREAD

**Issue by kevinludwig** [diffplug/spotless#26]
the import order is unchanged in src/test/java, although it does appear to have applied the eclipseFormatFile to the test files.

**Comment by nedtwigg** [comment]
#worksforme.  Any chance you can copy-paste your `build.gradle`?  My best guess is that your `src/test/java` directory isn't defined as a source set, but if that was the case you should be seeing other compilation problems...

**Comment by kevinludwig** [comment]
I hava a standard directory structure and I haven't modified the default source sets. The build works, and the reason I noticed was I added a check style plugins that flagged all my test imports. I'll attach the build.grade a bit later.

**Comment by nedtwigg** [comment]
For the tests that aren't having their imports sorted - if you make them fail (throw an exception right away), do they fail in the build?  Are they `.java` files?

**Comment by kevinludwig** [comment]
Yes, they fail for sure. They're just normal java test files under src/test/java with package structure mirroring src tree...standard stuff in Java land.

**Comment by nedtwigg** [comment]
Interesting...  Well I'd love to see your `build.gradle`, or at least the `spotless` section of it.

**Comment by kevinludwig** [comment]
OK so I have a better description of the issue now! The import ordering generally works, but does not work for static imports. In tests, it's fairly common to do import static for stuff like Mockito or Hamcrest matchers, e.g.

```
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.not;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;
```

And so it seems to be the case that `import static ...` are always glued to the top of the import list, before anything else. Not sure if that was intentional or not but checkstyle complains about it for sure.

**Comment by nedtwigg** [comment]
Gotcha.  Can I see your eclipse import ordering file?  `spotless.importorder`, perhaps?

The import ordering file can specify different locations for static imports vs standard (New vs New Static).

![image](https://cloud.githubusercontent.com/assets/2924992/15793065/5d86b0a0-2996-11e6-9615-2d2576065fb6.png)

**Comment by kevinludwig** [comment]
I'm not actually using eclipse, I just grabbed the format.xml from the google style guide. Everything is controlled via the gradle file. The spotless build config is:

```
 spotless {
     java {
         trimTrailingWhitespace()
         importOrder(['java', 'javax', 'org', 'com', 'lombok'])
         eclipseFormatFile "${projectDir}/eclipse-formatter.xml"
     }
 }
```

**Comment by nedtwigg** [comment]
So Eclipse automatically puts static imports at the top of the file, and so does the Google style guide I believe:

https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Converter.java

If you don't want the static imports to be glued to the top, I think this will fix it:

```
importOrder(['java', 'static java', 'javax', 'static javax', 'org', 'static org', 'com', 'static com', 'lombok', 'static lombok'])
```
