### ISSUE TITLE
Allow configuration of when to run spotless in gradle build

### ISSUE THREAD

**Issue by simschla** [diffplug/spotless#27]
Currently spotless adds itself automatically to the gradle checkTask.

    // Add our check task as a dependency on the global check task
    // getTasks() returns a "live" collection, so this works even if the
    // task doesn't exist at the time this call is made
    project.getTasks()
        .matching(task -> task.getName().equals(JavaBasePlugin.CHECK_TASK_NAME))
        .all(task -> task.dependsOn(rootCheckTask));

We would like to be able to decide when to actually run the spotless task or even be able to only run it when directly invoked from the command line like `gradlew spotless`

e.g. for configuration

    spotless {
        ...
    }
    // new
    taskX.dependsOn spotless

**Comment by nedtwigg** [comment]
If you'd like to remove `spotlessCheck` from the `check` task, this will do it:

```groovy
afterEvaluate {
    tasks.getByName('check').dependsOn.remove(tasks.getByName('spotlessCheck'))
}
```

We're going to keep the default behavior of adding `spotlessCheck` to `check` automatically.  A positive value in the gradle ecosystem is "convention over configuration" - when you add unit tests, style checkers, static analysis tools, they all hook into `check` by default, so that you don't have to do the plumbing yourself.  Perfectly valid that you'd like to use it a different way though :)

**Comment by simschla** [comment]
Thanks for the workaround, good enough for our case. 👍 
Maybe adding this to the Readme.md would help other people too.

**Comment by nedtwigg** [comment]
> Maybe adding this to the Readme.md would help other people too.

It's a good question, and GitHub's issue search is very good.  Hopefully others who have this same issue will find this question.

I try to make the readme describe the project as concisely as possible.  I believe this use case is a less <10% case, and thus doesn't earn a spot.  As evidence, if your use case was more common, then every stylechecker / static analyzer / unit test runner in the gradle ecosystem should have this in their readme.

**Comment by nedtwigg** [comment]
Also, out of curiosity, why do you not want `spotlessCheck` to run on every call to `check`?

**Comment by simschla** [comment]
We like to separate concerns in the build on CI
e.g. `compiling/packaging` <-> `running unit tests` <-> `running integration tests` <-> `auditing code`. 

Also, we like to keep the build as fast as possible during development to achieve small turnaround times.

**Comment by nedtwigg** [comment]
Here's gradle's task dependency graph:

![image](https://cloud.githubusercontent.com/assets/2924992/15816741/1ca619b4-2b89-11e6-9e97-f503dd1b8647.png)

If you'd like to just compile and package, run `assemble`.  If you just want to run tests, run `test` (or `integTest` if you've made a separate unit test task).

The objective of the `check` task is (according to the [gradle docs](https://docs.gradle.org/current/userguide/java_plugin.html)):
```
All verification tasks in the project, including test. Some plugins add additional verification tasks to the project.
```

You can use Gradle however you'd like, but it sounds like you're swimming upstream :)  If you want people to always be able to run `gradle build` and have it be fast, I'd recommend that you instead print out the task graph above and leave it on their desk, and then they'll know which tasks to run for themselves, depending on how fast they'd like their result.

Also, spotless is *much* faster than a reasonable unit test suite :)

**Comment by simschla** [comment]
as a matter of fact you are totally right both in "when the task is called" and in the statement that spotless is _much_ faster ;-)

**Comment by kirici** [comment]
For anyone else stumbling upon this from Google: this has been added in the meantime.
To remove `spotlessCheck` as a dependency to `check` when using the gradle plugin, add
```kotlin
spotless {
    isEnforceCheck = false
}
```
See the [plugin-gradle/README.md](https://github.com/diffplug/spotless/blob/012c13569c101086137cee96ac2ec4e5c5398749/plugin-gradle/README.md#disabling-warnings-and-error-messages)

[Background](https://github.com/diffplug/spotless/issues/79#issuecomment-290844602)
