### ISSUE TITLE
Broken link in the readme

### ISSUE THREAD

**Issue by JoshBrudnak** [diffplug/spotless#281]
The link in the readme to the contribution guide section on adding a code format option no longer works.
The old link: https://github.com/nedtwigg/spotless/blob/markdown-preview-temp/CONTRIBUTING.md#how-to-add-a-new-formatterstep
The new location: https://github.com/diffplug/spotless/blob/master/CONTRIBUTING.md#how-to-add-a-new-formatterstep

**Comment by JoshBrudnak** [comment]
The link to the license in the contribution guide is also broken.
It should be: https://github.com/diffplug/spotless/blob/master/LICENSE.txt :+1:

**Comment by jbduncan** [comment]
Hi @JoshBrudnak, thanks a lot for the PR! It's great to see small things like this, which are otherwise missed, get fixed, so cheers. :)
