### ISSUE TITLE
Support license header for Java classes in default package

### ISSUE THREAD

**Issue by sbrannen** [diffplug/spotless#30]
## Overview

Disclaimer: I don't condone the use of the _default_ package in Java at all.

However... having said that, we need to support test classes declared in the default package in JUnit 5. So I added a `DefaultPackageTestCase` to our test suite to verify our support for such use cases.

Consequently, when Spotless is applied during the JUnit 5 builds, we now see the following:

```
Unable to apply step LicenseHeader to src/test/java/DefaultPackageTestCase.java: Unable to find delimiter regex ^package
```

Since a Java class in the default package does not have a `package` declaration, it makes sense that your regular expression would fail to find `^package`; however, just because a class exists in the default package shouldn't mean that it does not have the license header rule applied.

## Proposal

If a class is in the _default_ package, consider doing one of the following:

1. use a different means for determining the location of the license header file -- for example, prior to `^import `, `^/** `, or similar.
1. just make sure the license header exists at the top of the document.

**Comment by sbrannen** [comment]
Hi @nedtwigg,

Thanks for the super fast response!

> Does the workaround work for you?

Well... yes and no. 😉 

It gets rid of the annoying warning in the build. So that of course makes us happy! 👍 

However, it does something odd with blank lines.

For example, it converts this:

```java
/*
 * Copyright 2015-2016 the original author or authors.
 *
 * All rights reserved. This program and the accompanying materials are
 * made available under the terms of the Eclipse Public License v1.0 which
 * accompanies this distribution and is available at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 */

import org.junit.jupiter.api.Test;
```

to this:

```java

/*
 * Copyright 2015-2016 the original author or authors.
 *
 * All rights reserved. This program and the accompanying materials are
 * made available under the terms of the Eclipse Public License v1.0 which
 * accompanies this distribution and is available at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 */
import org.junit.jupiter.api.Test;
```

Of course, you can't see the leading blank line in the above, so let me explain in _words_.

The new regex causes the following:

- a blank line is inserted before the existing license header.
- the existing, intentional blank after the license header is removed.

This behavior is, however, not the case for any Java classes that are not in the default package.

**Comment by sbrannen** [comment]
FYI: you can see the related changes to the JUnit 5 build here: https://github.com/junit-team/junit5/commit/5ab611650d90a0ebd35533021df8dc5a635ed137

**Comment by nedtwigg** [comment]
I think your build looks like this:

```
spotless {
    licenseHeaderFile
    eclipseFormatFile
    ...
```
The license header step is putting the license where it's supposed to go, and then the eclipse formatter is screwing it up, because the eclipse formatter doesn't work very well with the default package either.

To fix this, just swap the order (apply the eclipse formatter first, and then the license header).

Also, I found some cases which further complicate the regex, which convinces me further that Spotless won't support the default package out-of-the-box.  You might have a class with no imports at all, in which case the first line will either be a comment or the class definition, which might or might not be public.  So the regex sorta needs to be `(package|import|public|class|/\\*)`, and there's a lot that could go wrong...

**Comment by sbrannen** [comment]
Hmmmm.... swapping the eclipse formatter and license header steps ended up modifying every single Java file in the project, b/c it then removed the blank line we have between the license header and the `package` declaration.

So we'll just stick with the previous results from the `'(package|import) '` tip you gave us. 😉

**Comment by sbrannen** [comment]
> You might have a class with no imports at all,

Yeah, that was actually the case for us. That's why I added the unnecessary import for `@Test` in https://github.com/junit-team/junit5/commit/5ab611650d90a0ebd35533021df8dc5a635ed137.

**Comment by sbrannen** [comment]
> there's a lot that could go wrong...

Agreed.

So feel free to close this as "won't fix" if you like.

Thanks for all of your assistance!

**Comment by nedtwigg** [comment]
Thanks for raising the issue!  It'll be a useful reference for anyone else who bumps into this :)
