### ISSUE TITLE
Gradle configuration time taking too long in windows

### ISSUE THREAD

**Issue by regrog** [diffplug/spotless#303]
### summary of problem
There is a huge gap in configuration time when spotless plugin is applied in a multi-project build between windows and linux.
I've created a multiproject build with 150 projects to test this out:

**Configuration time with spotless plugin**
- 5 seconds in linux
- between 1m 30s and 2m in windows.

**Configuration time without spotless plugin**
-  0.6 seconds in linux
- 1 seconds in windows.

In windows the difference is overwhelming, slowing down the overall build time.

### versions
Java 1.8
Spotless 3.15.0
Gradle 4.10.2
Windows 10

example project: [projectA.zip](https://github.com/diffplug/spotless/files/2427769/projectA.zip)

In `projectA.gradle` there is a boolean variable to activate spotless plugin called `spotless_plugin`. You can try to enable and disable it.
you can test this running from within the root projectA:
linux `./gradlew clean build --parallel --scan`
windows `gradlew.bat clean build --parallel --scan`

**Comment by nedtwigg** [comment]
Thanks for the interesting case.  Until someone finds time to investigate the root cause, #277 should at least alleviate the symptoms of this.

**Comment by regrog** [comment]
Any news about this?
It's starting to be a pain even in linux.

Thanks

**Comment by jbduncan** [comment]
> PR #277 would help your case. Its author has run out of time, but it is done except for tests. Anyone is welcome to finish off the PR :)

Indeed! As the author of said PR, I wanted to apologise for my lack of activity or even acknowledgement that I'd run out of time (and energy) to continue working on it. I intend to say this on the PR within the next few days and to provide a pointer or two on how it could be finished.

**Comment by regrog** [comment]
I have done a really big mistake here!

> target fileTree(dir: **project.rootDir**, includes: [

`project.rootDir` must be **`project.projectDir`** 

DAMN!
sorry, my fault...
