### ISSUE TITLE
Support Jenkinsfile extension

### ISSUE THREAD

**Issue by JLLeitschuh** [diffplug/spotless#304]
A `Jenkinsfile` is a groovy file that you put in your project's root directory and is read by Jenkins.
They are groovy files that could be formatted using logic very similar to the `GroovyGradleExtension`.
It would just require some very simple modifications (probably drop the `GroovyGradleExtension` logic into a base `GroovyScriptExtension`).

Should be a fairly simple change. @nedtwigg what are your thoughts? There is no file extension. The file is just called `Jenkinsfile` but you can have additional groovy scripts that it calls out to.

**Comment by nedtwigg** [comment]
Can you solve the problem by setting the target explicitly on the `groovy` or `groovyGradle` extensions?

**Comment by JLLeitschuh** [comment]
I don't know about the `groovy` extension because that one is already setup for parsing sources, not looking at the project's root directory.

As for the `groovyGradle`, the `parseTarge` is by default using the `*.gradle` extension.
It seems like a bad idea to hijack an existing extension called `groovyGradle` for groovy script that are not gradle scripts.
