### ISSUE TITLE
Control static import placement

### ISSUE THREAD

**Issue by mkordas** [diffplug/spotless#306]
Is there a way to configure Spotless so that static imports in Java/Groovy are put below normal imports? That's IntelliJ default...
I cannot find anything about it in docs, but I think the behavior should be documented and configurable.

**Comment by fvgh** [comment]
@nedtwigg I don't think that the import sorter is really suitable for C++. CDT provide a nice [article](https://www.eclipse.org/community/eclipse_newsletter/2013/october/article3.php)  about their rules. Gives a good reasoning why the topic in C++ is complex. As stated in #232, my aim is to get the CDT implementation in and provide it as an optional step.

**Comment by teur** [comment]
There are examples of configuration static imports in ImportOrderStepTest by using `\#`.
For example a configuration `importOrder 'java', '\\#java', 'javax', '\\#javax', '', '\\#'` may be used to put static imports below.

**Comment by fvgh** [comment]
@nedtwigg I had another go on the IncludeOrganizer as it is provided by CDT. Unfortunately it is not an option as I described in my comment for #232. So maybe there can be a common code base for the Java/C++ import/include order.

**Comment by azizbekian** [comment]
This issue is still valid and needs to be resolved, because formatting file in IDE differs from spotless config.

**Comment by nedtwigg** [comment]
Thanks for verifying.  PR’s welcome!

**Comment by aljoscha** [comment]
@azizbekian Did you see @teur's comment? I have this config in a project and it puts static imports at the bottom:

```
<order>org.apache.flink,org.apache.flink.shaded,javax,java,scala,\#</order>
```

**Comment by yooksi** [comment]
Like @teur mentioned, adding `'\\#'` to the end of `importOrder` arranges static imports to be placed last.

**Comment by nedtwigg** [comment]
Looks like this issue is solved. Thanks all!

**Comment by NathanQingyangXu** [comment]
I tried many times, but seems the issue is still there.
