### ISSUE TITLE
Add gradle kotlin DSL usage

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#310]
Per https://github.com/gradle/gradle/issues/6790, the Kotlin DSL for gradle is now mature, and we should make sure our docs are clear for both Kotlin and Groovy DSL users.  I'm not a Kotlin DSL user yet, and migrating won't make the top of my TODO anytime soon.  If any Kotlin DSL users can comment on what parts of our docs are different for Kotlin, that would be great.

**Comment by JLLeitschuh** [comment]
Surprisingly, the documentation is pretty solid. And because spotless is strongly typed, it's really solidly self documenting. It's really awesome how having the plugin written in Java has just allowed this to fall out for free.

When doing the translation, basically you just have to add a bunch of parentheses that aren't required in Groovy.
As an example, here's a simple translation:
```groovy
spotless {
  format 'misc', {
    target '**/*.gradle', '**/*.md', '**/.gitignore'

    trimTrailingWhitespace()
    indentWithTabs() // or spaces. Takes an integer argument if you don't like 4
    endWithNewline()
  }
  format 'cpp', {
    target '**/*.hpp', '**/*.cpp'

    replace      'Not enough space after if', 'if(', 'if ('
    replaceRegex 'Too much space after if', 'if +\\(', 'if ('

    // Everything before the first #include or #pragma will
    // be replaced with whatever is in `spotless.license.cpp`
    licenseHeaderFile 'spotless.license.cpp', '#'
  }
}
```
This becomes this in Kotlin:
```kotlin
spotless {
  format ("misc") {
    target("**/*.gradle", "**/*.md", "**/.gitignore")

    trimTrailingWhitespace()
    indentWithTabs() // or spaces. Takes an integer argument if you don't like 4
    endWithNewline()
  }
  format ("cpp") {
    target("**/*.hpp", "**/*.cpp")

    replace("Not enough space after if", "if(", "if (")
    replaceRegex("Too much space after if", "if +\\(", "if (")

    // Everything before the first #include or #pragma will
    // be replaced with whatever is in `spotless.license.cpp`
    licenseHeaderFile("spotless.license.cpp", "#")
  }
}
```

**Comment by jbduncan** [comment]
I very much agree with @JLLeitschuh's observation! I'm using Spotless in https://github.com/jbduncan/jupiter-collection-testers, which uses the Kotlin DSL, and the only thing I had to do was make sure I used parentheses. :)

**Comment by nedtwigg** [comment]
As kotlin users, are the parentheses which are missing from the documentation obvious?  If so, then i think we can close this as "already good enough".  If not then maybe one of you can take a pass at the gradle README to make sure all the required parens are there, and then we'll close?

**Comment by JLLeitschuh** [comment]
For a new user of the Kotlin DSL I would argue that they aren't obvious. I've been working with the Kotlin DSL for almost two years now so I can automatically do the translation very easily.

Maybe I'm wrong, I want to get someone elses insights on this. I'll ask them to take a look.

**Comment by eriwen** [comment]
Here are a couple additional resources for any contributors:

 * [Migrating build logic from Groovy to Kotlin guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/)
 * [Exemplar for automated samples testing](https://blog.gradle.org/documentation-samples-testing-exemplar)
 * [Join #kotlin-dsl channel in Gradle Community Slack for personalized help](https://join.slack.com/t/gradle-community/shared_invite/enQtNDE3MzAwNjkxMzY0LTYwMTk0MWUwN2FiMzIzOWM3MzBjYjMxNWYzMDE1NGIwOTJkMTQ2NDEzOGM2OWIzNmU1ZTk5MjVhYjFhMTI3MmE)

Thank you for providing a great Gradle plugin! —The Gradle Team

**Comment by nedtwigg** [comment]
I've wanted something like Examplar for a long time, thanks for the link.

**Comment by nedtwigg** [comment]
I'm happy to reopen, but it looks unlikely that we're going to take further action here.

**Comment by s-ayush2903** [comment]
Hi, I want to write the following in kotlin dsl, but facing some problem and unable to figure it out via following the pattern derived from docs,
```groovy

subprojects {
    apply plugin: 'com.diffplug.spotless'
    spotless {
        kotlin {
            target '**/*.kt'
            ktlint().userData(['indent_size': '2', 'continuation_indent_size': '2'])
            ktfmt().googleStyle()
            licenseHeaderFile "${project.rootProject.projectDir}/license-header.txt"
        }
        format 'xml', {
            target '**/*.xml'
            prettier(['prettier': '2.0.5', '@prettier/plugin-xml': '0.13.0']).config(['parser': 'xml', 'tabWidth': 4])
        }
    }
}
```

I've almost written it into kotlin dsl, but unable to fix the problem that is arising for prettier formatted(for XML), here is what I wrote:

```.kts
subprojects {
    apply(plugin = "com.diffplug.spotless")
    configure<com.diffplug.gradle.spotless.SpotlessExtension> {
        kotlin {
            target ("**/*.kt")
            ktlint().userData(mapOf("indent_size" to "2", "continuation_indent_size" to "2"))
            ktfmt().googleStyle()
            licenseHeaderFile("${project.rootProject.projectDir}/license-header.txt")
        }

        format ("xml") {
            target ("**/*.xml")
            prettier(mapOf("prettier" to "2.0.5", "@prettier/plugin-xml" to "0.13.0")).config(["parser" = "xml", "tabWidth" = 4]) // this is erroneous
        }
    }
}

``` 
When I hit sync on android studio, it complains only on that specific line, which I'm unable to fix now. Please help if you have time.
PS: I've read [docs](https://github.com/diffplug/spotless/tree/master/plugin-gradle#prettier) but it didn't help me for prettier, but they did worked for ktfmt. Thanks!

**Comment by s-ayush2903** [comment]
Oh sorry I fixed at my own, I was being silly and lazy, only missed to map params in the `config` as well. Final working code in `erroneous` line, just if someone finds the same problem as mine:
``` .kts
            prettier(mapOf("prettier" to "2.0.5", "@prettier/plugin-xml" to "0.13.0")).config(mapOf("parser" to "xml", "tabWidth" to 4))
```
