### ISSUE TITLE
format only locally changed files

### ISSUE THREAD

**Issue by vvaka** [diffplug/spotless#313]
First of all, Thanks for making spotless 
It would be very useful if there is an option to format only files locally modified  both in maven , gradle plugins, This allows us to adapt this plugin in existing projects and incrementally format the sources.

This feature exists in another maven-plugin which is not actively maintained,  [talios/googleformatter-maven-plugin  option filterModified ](https://github.com/talios/googleformatter-maven-plugin)

**Comment by nedtwigg** [comment]
There's a workaround for this in #178.

Totally open to a PR to implement this with a flag, but #178 is the place to propose it.
