### ISSUE TITLE
googleJavaFormat and indentWithSpaces can not work together

### ISSUE THREAD

**Issue by kabike** [diffplug/spotless#317]
- [ ] summary of problem

> googleJavaFormat and indentWithSpaces can not work together for java files.They are still got indent with 2 spaces

- [ ] gradle or maven version

> Gradle 4.10.1

- [ ] spotless version

> 3.16.0

- [ ] operating system and version

> win 10

- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```
plugins {
    id 'java'
    id "com.diffplug.gradle.spotless" version "3.16.0"
}

group 'test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

spotless {
    java {     
		googleJavaFormat()
		indentWithSpaces(4)
    }
}
```
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
> no error, but java files still get indent with 2 spaces, while what I want was 4.

**Comment by nedtwigg** [comment]
`indentWithSpaces()` is pretty limited.  It's only useful for turning tabs into spaces or spaces into tabs - not for changing the number of spaces.  There's a fundamental limitation here, see #58 for info.

One trick might work...

```gradle
indentWithTabs(2)
indentWithSpaces(4)
```

**Comment by kabike** [comment]
> `indentWithSpaces()` is pretty limited. It's only useful for turning tabs into spaces or spaces into tabs - not for changing the number of spaces. There's a fundamental limitation here, see #58 for info.
> 
> One trick might work...
> 
> ```groovy-gradle
> indentWithTabs(2)
> indentWithSpaces(4)
> ```

thanks
