### ISSUE TITLE
removeUnusedImports fails in file with or without imports

### ISSUE THREAD

**Issue by chresan** [diffplug/spotless#318]
I started using spotless in a maven java project for the first time. I am getting an exception indicating that there are unused imports. I can strip down the file to be as simple as 
```
package example;
public interface Test {
}
```
There are no imports at all, but still there is the `removeUnusedImports` error.

Full Stack trace:
[spotless-stacktrace.txt](https://github.com/diffplug/spotless/files/2613241/spotless-stacktrace.txt)

**Comment by nedtwigg** [comment]
Perhaps a newline between the package and the class will fix it?

**Comment by nedtwigg** [comment]
removeUnusedImports() uses `google-java-format` under the hood, which has released a few new versions.  Decent chance this has been fixed already.  Happy to reopen if someone confirms the bug is still present in a recent version.
