### ISSUE TITLE
how to indent multi-line XML

### ISSUE THREAD

**Issue by Avinash-Bhat** [diffplug/spotless#319]
## summary of problem
Consider the following unformatted xml snippet below:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="my.app">
...
```
when running with a configuration of:
```groovy
spotless {
    ...
    xml {
        target '**/*.xml'
        trimTrailingWhitespace()
        endWithNewline()
    }
    ...
```
the xml gets formatted to:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="my.app">
...
```
how ever I want it to indent the multi-line xml to add an additional indent (i.e., here `package` should start as the 9th character instead of being the 5th)

i.e., like this:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="my.app">
```

Is is possible to get something like this with the current state of spotless? if not, should & could this be done using custom formatter?

PS the above xml can also be formatted to start indenting at the position of the first argument.
i.e.:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="my.app">
```

- gradle: 4.6
- spotless version: 3.16.0

**Comment by fvgh** [comment]
The [Eclipse WTP](https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-xml-sources) formatter allows to configure indentation size. The `xml` instruction only specifies things like the `target`, but not the formatters to use. So you must at least add `eclipse` to use the Eclipse formatter (with the default configuration). To figure out all formatting options (Eclipse WTP offers quite a lot of options), I recommend to install Eclipse and its web tools.
Have a look at the [spotless configuration](https://github.com/diffplug/spotless/blob/master/spotlessSelf.gradle#L51) for an example usage.

**Comment by fvgh** [comment]
I assume that you used the eclipse formatter. Your example above is irritating in that respect. Just had a look myself. You are right, Eclipse WTP only offers configuration of argument indentation in case the maximum line width is exceeded, or to place all arguments on separated lines.
The `xml` step can contain multiple formatters, so you can add a [custom](https://github.com/diffplug/spotless/tree/master/plugin-gradle#custom) one, fixing the things you don't like about the Eclipse WTP formatting.

**Comment by Avinash-Bhat** [comment]
@fvgh this is actually the AndroidStudio's (Intellij Idea) default formatting for XML.

The most weird thing for this is that when running code format manually in the IDE, the format is changed to match that of the last example, although running spotlessApply after the change doesn't change it back. This to me seems a bit inconsistent as it should stick either one of the formats; spotless seems to not care about the extra indents.

**Comment by Avinash-Bhat** [comment]
I guess you are right in that I need to write a custom xml formatter for this additional change.

But maybe this can be handled by adding support for IntelliJ's formatters as well.

**Comment by Avinash-Bhat** [comment]
@fvgh This can be handled by adding a custom formatter for Intellij. Is this something that will be pulled to the core if worked on?

I can see that formatting is done generically in [`com.intellij.formatting.FormatterImpl`](https://github.com/JetBrains/intellij-community/blob/ce45c783cef4ab350e9b31b4efbcdc422a45991b/platform/lang-impl/src/com/intellij/formatting/FormatterImpl.java); maybe that can be an entry-point to get this implemented.

**Comment by nedtwigg** [comment]
This would definitely be pulled to core if you [follow this](https://github.com/diffplug/spotless/blob/master/CONTRIBUTING.md#how-to-add-a-new-formatterstep).

**Comment by fvgh** [comment]
@Avinash-Bhat  
Please have a look at #200 which already requests IntelliJ support.
About the other issue you raise:
>>> spotless seems to not care about the extra indents.

You configured 
```
trimTrailingWhitespace()
endWithNewline()
```
Both formatter steps do not care about indents. The thing is that you configure a chain of formatters. If you add the Eclipse formatter, it would alter indents, but unfortunately not in the way you want it.

Does this answer settles your questions?

**Comment by fvgh** [comment]
@Avinash-Bhat I consider this issue solved. Let me know if there are still open issues from your side.
