### ISSUE TITLE
Add support for Antlr4 grammars

### ISSUE THREAD

**Issue by matthiasbalke** [diffplug/spotless#326]
I'm working on an integration of [antlr/Antlr4Formatter](https://github.com/antlr/Antlr4Formatter) by @teverett. The formatter is in an early stage, but already formats Antlr4 grammars.

I started with the Gradle Plugin integration, but once thats done, would be willing to add support to Maven too. I'll push my current status within today, so we can talk about things that need to be done.

**Comment by jbduncan** [comment]
Sounds neat to me!

I used ANTLR when I was working on my dissertation a couple of years ago, so having an ANTLR grammar formatter included by default in Spotless sounds interesting to me.

I look forward to whatever work towards this you manage to make. :+1:

**Comment by jbduncan** [comment]
Cheers @matthiasbalke! I'd be more than happy to review it when you're ready. :)

**Comment by nedtwigg** [comment]
Released in `plugin-maven 2.0.0` and `plugin-gradle 4.5.0`.
