### ISSUE TITLE
Line wrapping of annotation parameters only for annotations on parameters

### ISSUE THREAD

**Issue by JamieMagee** [diffplug/spotless#329]
- summary of problem

That title was a bit of a mouthful, but to give an example when I have this code

```java
public myTestMethod(
    @Min(1) int arg1,
    @Min(1) int arg2,
    @Min(1) int arg3,
    @Min(1) int arg4,
    @Min(1) int arg5,
    @Min(1) int arg6
) {
    // TODO
}
```

it gets wrapped as

```java
public myTestMethod(
    @Min(
        1
    ) int arg1,
    @Min(
        1
    ) int arg2,
    @Min(
        1
    ) int arg3,
    @Min(
        1
    ) int arg4,
    @Min(
        1
    ) int arg5,
    @Min(
         1
    ) int arg6
) {
    // TODO
}
```

This only occurs when the annotations are on parameters, and only when the annotations themselves have parameters. This issue doesn't appear when I preview this code in eclipse

![](https://i.imgur.com/1ypbnn2.png)

However it does appear if I set the line length too small

![](https://i.imgur.com/HZ0Ozi3.png)

- gradle or maven version

```sh
$ mvn -version
Apache Maven 3.6.0 (NON-CANONICAL_2018-11-06T03:14:22+01:00_root; 2018-11-06T03:14:22+01:00)
Maven home: /opt/maven
Java version: 1.8.0_192, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.20.0-arch1-1-arch", arch: "amd64", family: "unix"
```
- spotless version

maven/1.17.0

- operating system and version

Arch Linux

- copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```xml
<configuration>
  <java>
      <eclipse>
          <file>${session.executionRootDirectory}/eclipseformat.xml</file>
      </eclipse>
      <removeUnusedImports/>
      <trimTrailingWhitespace/>
      <importOrder>
          <order>
              java,javax,
          </order>
      </importOrder>
      <lineEndings>UNIX</lineEndings>
      <indent>
          <spaces>true</spaces>
          <spacesPerTab>4</spacesPerTab>
      </indent>
  </java>
</configuration>
```

[gist of eclipseformat.xml](https://gist.github.com/JamieMagee/cac807fccd7df32165785df10d17460f)

- copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

n/a

**Comment by nedtwigg** [comment]
Can you see any change in the `eclipseformat.xml` when you change the preview line width?

**Comment by JamieMagee** [comment]
No, the preview line width only affects the preview in eclipse settings. My line width is set to 140 in `eclipseformat.xml`

```xml
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="140"/>
```

**Comment by fvgh** [comment]
@JamieMagee / @nedtwigg:
Can you help me out. I am afraid I have not followed closely the latest Java development.
I tried to reproduce the problem with Open-JDK 11 and Eclipse Photon 4.8.0.
So the preview inserts line breaks when I change the "preview line width" or if I switch between "view/edit raw code".
The editor however does no formatting at all, since it directly detects a parser error.
Spotless gradle plugin shows the same behaviour, which is OK.
As soon as I fix the most obvious errors (add package, class and a method return value type), the editor also inserts the line breaks,

Why the Eclipse preview formats the example, though the Eclipse parser cannot cope with it, seems odd to me.

Sorry, but I don't see a problem. Somethings wrong with my setup/understanding?

**Comment by JamieMagee** [comment]
I'll try to find some time to put together a small repo that reproduces this issue.

**Comment by JamieMagee** [comment]
Hi, I had some time to take another look at this. TL;DR I fixed my issue by checking `Prefer wrapping outer expressions (keep nested expression on same line)`

I think what was confusing, is that eclipse format preview, and eclipse didn't have the same behaviour (but spotless and eclipse do). Apologies for wasting your time on this one.
