### ISSUE TITLE
Better extensibility support

### ISSUE THREAD

**Issue by robzienert** [diffplug/spotless#330]
This issue is part enhancement request, part call for guidance (maybe I'm going about this the wrong way?)

Summary: I have a [handful of large projects](https://www.github.com/spinnaker) that we're trying to enforce code standards on, where Java and Groovy code all live within the `groovy` source set. We've deprecated adding new Groovy code in favor of Java and after experimentation with the Eclipse Groovy formatter, we've decided it would be better to not format Groovy at all. The issue is we want to still format the Java files in the `groovy` source set. We basically just want the Java formatter to also scan the groovy source set for Java files.

There's an option for conditionally formatting Java in `groovy`, but not scanning a groovy source set and only processing Java therein. I tried to write my own extension but unfortunately it doesn't look like there are public interfaces available to add extensions without contributing to spotless upstream. It would be neat if there were a configuration available to define what source sets to scan in the Java formatter extension.

I wrote a custom `FormatExtension`, but I don't really understand how to register it into the `SpotlessPlugin`. It seems like the private `configure` method is what I need? Writing a custom `Action<FormatExtension>` doesn't seem to do the trick either.

I'd be eager to hear if there's some other way about this. Can you suggest a solution that may fit our needs?

**Comment by nedtwigg** [comment]
I would probably do it something like this:

```gradle
spotless {
    java {
       target 'src/*/**.java'
```

**Comment by robzienert** [comment]
Well... that was a much easier resolution. 😆 Thanks!
