### ISSUE TITLE
Update default google-java-format version from 1.5 to 1.6 or 1.7

### ISSUE THREAD

**Issue by nogwater** [diffplug/spotless#335]
The default version of googleJavaFormat is currently set to 1.5.
https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java#L34

1.6 was released May 2018, and 1.7 was released yesterday (Jan 2019).
https://github.com/google/google-java-format/releases

Here's an old issue where it was decided to keep spotless should default to the latest formatters:
https://github.com/diffplug/spotless/issues/74

Thanks.

**Comment by nedtwigg** [comment]
Published in 3.18.0
