### ISSUE TITLE
How to measure performance impact of Spotless

### ISSUE THREAD

**Issue by epag** [diffplug/spotless#336]
I am trying to implement spotless where I work and in order to get it approved I need to collect some metrics on it first. I want to put it into my company's build chain and have it run up to the point of finding the errors and then not report them. To be able to shut off full format blocks from ever reporting. Does anyone know if this is possible?

**Comment by epag** [comment]
I guess I would be looking for a way to find errors and not report them. I just want to start to understand the performance impacts that this would have before having it change our current system

**Comment by nedtwigg** [comment]
> find errors and not report them

How do you want it to tell you about errors, if not in a report?  Seems like a tree in the forest and no one there to hear it sort of thing ;)

**Comment by epag** [comment]
Currently, I don't care if it tells me about the errors. I am just trying to find a way to test the performance impacts that it would have. I take it there is no way to currently do that?

**Comment by nedtwigg** [comment]
I'm 99% sure that spotless is going to be a non-factor in your performance.  That said, I would do this:

- `gradlew clean`
- `gradlew check` (measure its performance, repeat x10)
- add Spotless to your build, and run `spotlessApply` so that future calls to `spotlessCheck` will succeed
- `gradlew clean`
- `gradlew check` (measure its performance, repeat x10)

You'll now see how expensive the spotless is.  Would love to see your results in this issue.

**Comment by epag** [comment]
Not sure if this is the most accurate method of testing since I think sequential runs would be optimized, but this is a great starting place for me. Thanks! 

After averaging 8 runs with and without spotless I can see that spotless added ~8.37 seconds total time

**Comment by epag** [comment]
After I ran the build like 3 or 4 times it was averaging to be around ~35 seconds

**Comment by nedtwigg** [comment]
So it's 35 seconds without Spotless, and 45 seconds with?  Are those 35 seconds all about compiling java?  Or is that running unit tests also?

**Comment by epag** [comment]
Yeah I was averaging ~35 without spotless and ~43 with it. That is all just compiling I think. If all the unit tests are running then it takes upward of 20 minutes for the command to run.

**Comment by nedtwigg** [comment]
Ok, so useful stats for other people:

- spotlessCheck: 8 seconds
- compileJava: 35 seconds
- unit tests: > 20 minutes

**Comment by epag** [comment]
I plan on doing some more testing/continued metric collection. I can update this as the I get more numbers

**Comment by nedtwigg** [comment]
Closing, feel free to continue discussion here if something comes up in the future.
