### ISSUE TITLE
Docs for gradle dbeaver are incomplete

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#339]
According to [our docs](https://github.com/diffplug/spotless/blob/master/plugin-gradle/README.md#applying-dbeaver-to-sql-scripts):

```gradle
spotless {
  sql {
    // default value for target files
    target '**/*.sql'
    // configFile is optional, arguments available here:
    // https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/sql/DBeaverSQLFormatterStep.java
    dbeaver().configFile('dbeaver.props')
  }
}
```

However, that link [takes you here](https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/sql/DBeaverSQLFormatterStep.java), which doesn't say what any of the options are.

@baptistemesta, you know what options there are, and/or where people can find them?

**Comment by baptistemesta** [comment]
My bad, I might have refactored it.
It's here: https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/sql/dbeaver/DBeaverSQLFormatterConfiguration.java

```
	/**
	 * UPPER, LOWER or ORIGINAL
	 */
	private static final String SQL_FORMATTER_KEYWORD_CASE = "sql.formatter.keyword.case";

	/**
	 * ';' by default
	 */
	private static final String SQL_FORMATTER_STATEMENT_DELIMITER = "sql.formatter.statement.delimiter";
	/**
	 * space or tag
	 */
	private static final String SQL_FORMATTER_INDENT_TYPE = "sql.formatter.indent.type";
	/**
	 * 4 by default
	 */
	private static final String SQL_FORMATTER_INDENT_SIZE = "sql.formatter.indent.size";
```
