### ISSUE TITLE
The version 3.17.0 of the plugin is not yet published

### ISSUE THREAD

**Issue by giulianfazio** [diffplug/spotless#341]
I saw that with the version 3.17.0 was added a new property (_spotlessFiles_) to target specific files for the _spotlessApply_ task. Therefore I decided to update to that version but it seems not available.

### Summary of the "bug"
* Added the plugin to my project's `build.gradle`
```groovy
plugins {
    ....
    id "com.diffplug.gradle.spotless" version "3.17.0"
}
```
* Get the error `could not resolve plugin artifact com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:3.17.0`
* Reverting to version `3.16.0` everything works
* Checking the repo we are already at the version `3.18.0-Snapshot` but here: https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless the version 3.16.0 results to be the latest

Is it on purpose, is the release maybe not stable?

### Additional info
* gradle version: 5.1
* spotless version: 3.17.0
* OS: Ubuntu 18.04.1 LTS

**Comment by nedtwigg** [comment]
Thanks for the bug report.  Dunno what went wrong with publishing 3.17 to the plugin portal.  It made it to maven central and jcenter, but not to the plugin portal.  Fixed now.

**Comment by giulianfazio** [comment]
That was a quick fix! 
Thank you ^^
