### ISSUE TITLE
Gradle: Eclipse WTP dependency

### ISSUE THREAD

**Issue by sebastianhaeni** [diffplug/spotless#346]
I'm trying to integrate Eclipse WTP using the Gradle plugin.

But I don't get it to work, because, I suppose, Eclipse WTP is no longer in the plugin since version 3.14.

I get this error:

    Could not find method eclipseWtp() for arguments [html] on object of type com.diffplug.gradle.spotless.FormatExtension.

Could you point out which dependencies I have to add? 
Maybe a docs section dedicated how to integrate Spotless in Gradle would be useful.

My configuration:

    spotless {
        format 'html', {
            target fileTree('.') {
                include '**/*.html'
            }
            eclipseWtp('html')
        }
    }

**Comment by fvgh** [comment]
Sorry, WTP has been added for XML with version 3.15. With 3.18 HTML will also be supported. Have a look at the [CHANGES](https://github.com/diffplug/spotless/blob/master/plugin-gradle/CHANGES.md). The configuration you are using is not supported by the latest release (3.17), but will be part of 3.18. The documentation for 3.17 is [here](https://github.com/diffplug/spotless/blob/9ff51754f13d94731f715b9f302a4de606f3f62d/plugin-gradle/README.md).

**Comment by sebastianhaeni** [comment]
Ah okay. Got it. Thanks for the clarification. I was looking at the master branch.
