### ISSUE TITLE
Ktlint + EndWithNewLine does not end with new line

### ISSUE THREAD

**Issue by AllanWang** [diffplug/spotless#359]
With both `ktlint` and `endWithNewLine`, reformatted files doesn't actually end with new lines. Ktlint does also have its own [editor configs](https://github.com/shyiko/ktlint#editorconfig), so are we meant to specify that instead?

Gradle version 3.3.0
Spotless version 3.17.0
MacOS, Mojave

Spotless config:

```
apply plugin: "com.diffplug.gradle.spotless"

spotless {
    kotlin {
        target "**/*.kt"
        ktlint()
//        licenseHeaderFile '../spotless.license.kt'
        trimTrailingWhitespace()
        endWithNewline()
    }
}
```

Running apply works fine without errors.

Our project is located [here](https://github.com/jguerinet/MyMartlet/tree/e8f815b07d07963469ff1b006b3b1fd5a10fbf33), though you can see the same problem in other projects like [Material Dialogs](https://github.com/afollestad/material-dialogs/tree/3dea9c87f1216b80b3067c02dac2557761aaeaf3)

**Comment by nedtwigg** [comment]
Are you sure Spotless is actually running on the files you're expecting?  My first guess is that the config isn't applying to the files.  You can test by adding a simple custom rule that wipes out the file content, like

```gradle
spotless {
  kotlin {
    custom 'wipeOut', { return 'appliedToMe' }
```

Once you're sure that there's a bug, I would

- reproduce here: https://github.com/diffplug/spotless/blob/master/testlib/src/test/java/com/diffplug/spotless/generic/EndWithNewlineStepTest.java
- fix here: https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/generic/EndWithNewlineStep.java

**Comment by AllanWang** [comment]
I'm certain spotless works because you can see changes [here](https://github.com/jguerinet/MyMartlet/pull/111/commits/8775ac04c7f6cc76b03a58b0493e76288a2148f0).

**Comment by nedtwigg** [comment]
I think you are asking for your files to end with two newlines instead of just one.  They already end with one, [see here](https://github.com/jguerinet/MyMartlet/pull/111/commits/8775ac04c7f6cc76b03a58b0493e76288a2148f0#r257026783).

You can use a custom rule after `endWithNewline()` and add an extra newline to every file if you wish.

**Comment by AllanWang** [comment]
Thank you for reviewing. It looks like we were too hasty in our report. We didn't realize that github's file viewer doesn't show new lines, and we should have checked our files locally first. Thanks again!
