### ISSUE TITLE
Make file encoding configurable

### ISSUE THREAD

**Issue by kec2** [diffplug/spotless#36]
It would be nice if file encoding was configurable. UTF-8 is not always desired.

**Comment by nedtwigg** [comment]
If anybody wants to add this, here's where you could add an `encoding` attribute into the Gradle DSL:

- [SpotlessExtension.java](https://github.com/diffplug/spotless/blob/master/src/main/java/com/diffplug/gradle/spotless/SpotlessExtension.java)

And here's where the encoding is used:

- [Formatter.java](https://github.com/diffplug/spotless/blob/master/src/main/java/com/diffplug/gradle/spotless/Formatter.java)

So long as there are a few tests, I'd be happy to merge and release this.

**Comment by nedtwigg** [comment]
Just encountered a need for this myself for the first time.  Eclipse defaults to CP1252.  Will implement by the end of the week.

**Comment by nedtwigg** [comment]
Shipped in 2.3.0.
