### ISSUE TITLE
gradle plugin dependencies are missing

### ISSUE THREAD

**Issue by mcico** [diffplug/spotless#373]
Since today a few of our gradle builds broke because of the latest release of the gradle plugin with the following error, which seems to be a missing dependency.
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gocd-config-PR'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.diffplug.spotless:spotless-lib-extra:1.20.0.
     Searched in the following locations:
       - https://binrepo.adnovum.ch/artifactory/adn-public-maven-vi/com/diffplug/spotless/spotless-lib-extra/1.20.0/spotless-lib-extra-1.20.0.pom
       - https://binrepo.adnovum.ch/artifactory/adn-public-maven-vi/com/diffplug/spotless/spotless-lib-extra/1.20.0/spotless-lib-extra-1.20.0.jar
     Required by:
         project : > com.diffplug.spotless:spotless-plugin-gradle:3.20.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
```

After some digging, I found that in maven central there is a mismatch of the versions
* The version of the gradle plugin is 3.20.0: https://search.maven.org/artifact/com.diffplug.spotless/spotless-plugin-gradle/3.20.0/jar
* The version of the spotless-lib-extra library of 1.20 does not exist: https://search.maven.org/search?q=g:com.diffplug.spotless%20AND%20a:spotless-lib-extra&core=gav

Unfortunately the plugin version 3.20.0 references the spotless-lib-extra library in version 1.20.0 which I was unable to find.

It could very much be, that this is just bad timing and maven central and jcenter are not yet up to date.

We fixed the broken builds by specifying a specific version of the plugin
`classpath 'com.diffplug.spotless:spotless-plugin-gradle:3.19.0'`
Before we always used the latest version of the plugin, like this
`classpath 'com.diffplug.spotless:spotless-plugin-gradle:+'`

**Comment by nedtwigg** [comment]
Sorry, fixed now.

**Comment by mcico** [comment]
thx
