### ISSUE TITLE
Add support for Eclipse 4.11.0 auto formatter

### ISSUE THREAD

**Issue by iemejia** [diffplug/spotless#381]
Eclipse 4.11 (2019/3) was released recently so it would be nice to update the support for it.

**Comment by fvgh** [comment]
Can do. Would like to combine it with #292. But that will take a while...
You can also provide a simple PR if you like. JDT upgrade is quite simple. [Have a look...](c01e3771029e1c2493238c029b91ec667172a28d)

**Comment by iemejia** [comment]
Done PTAL at #384
