### ISSUE TITLE
Invalid plugin descriptor for com.diffplug.spotless:spotless-maven-plugin:1.21.0

### ISSUE THREAD

**Issue by atkawa7** [diffplug/spotless#388]
Plugin's descriptor contains the wrong version: 1.22.0-SNAPSHOT

**Comment by mancini0** [comment]
I also encountered this - had to use 1.22.0-SNAPSHOT in my pom.

**Comment by nedtwigg** [comment]
Fixed in `1.21.1`.  Sorry about this, the travis builds have been timing out / not starting lately, which has required manual human intervention (aka error-prone-monkey) to get releases to finish.  We'll find a more permanent fix before the next release.
