### ISSUE TITLE
Couldn't find resource eclipse-fmt.xml

### ISSUE THREAD

**Issue by christowly** [diffplug/spotless#393]
Hi,

This is my first time using spotless and maven. I already following the documentation and trying to install maven on eclipse and have no problem at all with updating the project. But when i try to run the command mvn spotless:check it give me error 

> [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:1.22.0:check (default-cli) on project idm: Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:1.22.0:check failed: Unable to locate file with path: <path>/eclipse-fmt.xml: Could not find resource '<path>/eclipse-fmt.xml'. -> [Help 1]

I'm using maven 3.5.3 and spotless 1.22.0 and using windows 10.

What's the inside of eclipse-fmt.xml, i try to find it on your code but seems like i can't find anything.

Thank you for your help

**Comment by fvgh** [comment]
I assume you started off with the initial example in the [README.md](https://github.com/diffplug/spotless/blob/master/plugin-maven/README.md). So your configuration looks like
```xml
<eclipse>
  <file>${basedir}/eclipse-fmt.xml</file>
  <version>4.7.1</version>
</eclipse>
```
I am afraid the Maven README requires an update. It should reference to the [Eclipse Screenshots](https://github.com/diffplug/spotless/blob/master/ECLIPSE_SCREENSHOTS.md).
The `eclipse-fmt.xml`  is jsut an example name for the Eclipse Formatter configuration export.

Some hints:
* You can omit the `version` element. In that case the Eclipse version is taken released with the Spotless version. Supported versions are listed [here](https://github.com/diffplug/spotless/tree/master/lib-extra/src/main/resources/com/diffplug/spotless/extra/eclipse_jdt_formatter).
* You can omit the `file` element to apply the Eclipse defaults.

**Comment by fvgh** [comment]
I propose to leave this issue open. A Maven README.md update is rquired.
