### ISSUE TITLE
Feature request: Add support for python Black

### ISSUE THREAD

**Issue by iemejia** [diffplug/spotless#403]
Python's [Black](https://github.com/python/black) has become the de-facto code auto-formatter for python. It would be great if we could call it with spotless.

**Comment by nedtwigg** [comment]
The key thing needed to integrate with Spotless is a `Function<String, String>`.  So if you can either

A) Write some python code that configures the formatter, then has a function that consumes a string and returns a string
B) Find some commandline flags which accomplishes this (e.g. read on stdin and write to stdout, or possibly read some tempfile and write back out to it)

then that's the first step.  The second step is integrating python and JVM, for which I believe there are many alternatives.

**Comment by rpdelaney** [comment]
> Find some commandline flags which accomplishes this (e.g. read on stdin and write to stdout, or possibly read some tempfile and write back out to it)

```console
black --code "$text"
```

**Comment by nedtwigg** [comment]
Implemented in #672, shipped in `plugin-gradle 5.2.0` ([tweet](https://twitter.com/NedTwigg/status/1298156965277732866?s=20)), PR for maven is welcome.  The setup experience could be better, we'll track that at #674.

**Comment by iemejia** [comment]
Great ! :clap: thanks!

**Comment by nedtwigg** [comment]
@iemejia, @rpdelaney, do you have any feedback on what info would be helpful for the black docs: https://github.com/psf/black/pull/1622
