### ISSUE TITLE
Any way to discover which rule is being violated when using eclipse formatting file?

### ISSUE THREAD

**Issue by boatmisser** [diffplug/spotless#406]
Updated to the latest spotless gradle plugin (for gradle 5) and I noticed that spotless is now complaining that my implements and extends are not on separate lines.

My code
```
public final class MyClass
    implements InterfaceOne, InterfaceTwo
{
```
Spotless
```
public final class MyClass
    implements 
    InterfaceOne, 
    InterfaceTwo
{
```
I'm using the eclipse formatting configuration, so i know that it something either in that, or missing from that, which is triggering this; but for the life of me I can not work out which rule is driving this.
I tracked this back to version 3.7.0, before that my format is acceptable.
So I assume it is related to "Updated default eclipse-jdt version to 4.7.1 from 4.6.3".
Can anyone tell me either how to find out which rule is causing this, or how to fix it; as this is annoying a lot of devs I work with.

Thanks

**Comment by nedtwigg** [comment]
Spotless isn't a formatter itself, it's just a harness that delegates out to other formatters.  With each new release of Spotless, we upgrade the default versions of formatters to their latest, but you can specify which version of a formatter to use.  The easiest fix for you is probably to change `eclipse()` to `eclipse('4.6.3')`.  That way you can keep upgrading Spotless and getting access to new formatters, but you can lock the eclipse formatter in forever.

As for which rule to set in the newest eclipse formatter, you'll have to look at [bugs.eclipse.org](https://bugs.eclipse.org/bugs/buglist.cgi?quicksearch=formatter) for that.

**Comment by nedtwigg** [comment]
Feel free to reopen if there's new info.
