### ISSUE TITLE
Support Eclipse 4.12 core runtime 3.15

### ISSUE THREAD

**Issue by fvgh** [diffplug/spotless#413]
The Eclipse team finally replaced the [usage of deprecated PackageAdmin](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544423) by `org.osgi.framework.wiring.FrameworkWiring`.
Hence `spotless-eclipse-base` must also replace/add a corresponding service since it currently [provides (only) PackageAdmin](https://github.com/diffplug/spotless/blob/master/_ext/eclipse-base/src/main/java/com/diffplug/spotless/extra/eclipse/base/osgi/BundleController.java#L67).

**Proposal**
Provision of a new `spotless-eclipse-base` version supporting additionally `org.osgi.framework.wiring.FrameworkWiring` implementation by the existing [EclipseBundleLookup](https://github.com/diffplug/spotless/blob/master/_ext/eclipse-base/src/main/java/com/diffplug/spotless/extra/eclipse/base/osgi/EclipseBundleLookup.java).
Note that there are some more things to do, since the new `InternalPlatform` version requires to be started whereas superfluous activities like Eclipse authorization handling must be prevented.

**Work-around**
If new Eclipse versions shall be supported beforehand, try to pin the `org.eclipse.platform:org.eclipse.core.runtime` version to `3.14.0` and `org.eclipse.platform:org.eclipse.core.resources` to `3.13.0`.

**Comment by fvgh** [comment]
If anybody else wants this task, I am happy to assist.

**Comment by nedtwigg** [comment]
FWIW, I just [updated goomph for 2019-06](https://github.com/diffplug/goomph/blob/master/CHANGES.md#version-3177---june-26th-2019-javadoc-jcenter).
