### ISSUE TITLE
Javadoc links are broken in readme

### ISSUE THREAD

**Issue by spartanhooah** [diffplug/spotless#417]
Summary: The two existing Javadoc links in the readme for the Gradle plugin are broken, returning 404 from GitHub:
 - "...using simple rules (javadoc)..." currently points to https://diffplug.github.io/spotless/javadoc/spotless-plugin-gradle/3.23.1/com/diffplug/gradle/spotless/FormatExtension.html
 - "...take a look at this javadoc for a big..." points to https://diffplug.github.io/spotless/javadoc/spotless-plugin-gradle/3.23.1/com/diffplug/gradle/spotless/FormatExtension.html#bumpThisNumberIfACustomStepChanges-int-

**Comment by nedtwigg** [comment]
Thanks for noticing this.  They have been fixed in the new `x.24.0` release.
