### ISSUE TITLE
Spotless and Asciidoctor

### ISSUE THREAD

**Issue by t-buss** [diffplug/spotless#418]
Hello, we are trying to use Spotless and AsciiDoctor simulatiously in a project. When we run `./gradlew spotlessApply`, the Asciidoc-formatted comments are manipulated (`<p>`tags are added in places where there should not).

Is there a way to disable spotless for JavaDoc or (even better) set the format for Javadoc to Asciidoc?

Gradle 5.4.1
Spotless 3.23.1
Ubuntu 19.04 Disco Dingo

```gradle
spotless {
    java {
        target 'src/main/java/**/*.java', 'src/test/java/**/*.java'
        googleJavaFormat()
        trimTrailingWhitespace()
        indentWithSpaces()
        removeUnusedImports()
    }
    groovyGradle {
        target '*.gradle', 'gradle/*.gradle'
        greclipse()
        trimTrailingWhitespace()
        indentWithSpaces()
    }
}
```

If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] gradle or maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment]
You are using `googleJavaFormat()` which doesn't have many options.  If you instead use `eclipse()`, you can provide a config file where you can set a bunch of options, including options about javadoc formatting.

We don't have an asciidoctor formatter, but if we had one, and you wanted to apply it only to the comments, we would also need to implement #412, which no one is currently working on.

**Comment by t-buss** [comment]
Thanks, using the eclipse formatter worked. Here's the solution (if anyone stumbles across this):
```gradle
spotless {
    java {
        target 'src/main/java/**/*.java', 'src/test/java/**/*.java'
        eclipse().configFile 'gradle/eclipse.formatter.xml'
        trimTrailingWhitespace()
        indentWithSpaces()
        removeUnusedImports()
    }
    groovyGradle {
        target '*.gradle', 'gradle/*.gradle'
        greclipse()
        trimTrailingWhitespace()
        indentWithSpaces()
    }
}
```
We used the Quarkus Formatting configuration: https://raw.githubusercontent.com/quarkusio/quarkus/master/ide-config/eclipse-format.xml
There, you can simply set `org.eclipse.jdt.core.formatter.comment.format_javadoc_comments` to false.
Now, javadoc comments are not processed by Spotless and can remain in Asciidoc format.
