### ISSUE TITLE
Could not find method spotless() for arguments on root project when subprojects are used

### ISSUE THREAD

**Issue by ksemer** [diffplug/spotless#421]
I do not know if it is a bug or missing functionality.
When you have subprojects you have to define spotless plugin in the main build.gradle and add  in all build.gradle files of your subprojects the following:

```gradle
spotless {
    java {
          licenseHeaderFile 'spotless.licence.java'               // License header json
          importOrder 'java', 'javax', 'org', 'com', 'com.diffplug', ''   // A sequence of package     names
          trimTrailingWhitespace()
          endWithNewline()
          eclipse().configFile 'spotless.eclipseformat.xml'
          indentWithSpaces(2) // or spaces. Takes an integer argument if you don't like 4
          removeUnusedImports() // removes any unused imports
    }
}
```

Now if you want to only build one subproject you get the following error:
 * What went wrong:
A problem occurred evaluating root project 'project_name'.
> Could not find method spotless() for arguments

With other words it allows you to only build the project from the main build.gradle file but does not allow you to build any subproject separately.

**Comment by nedtwigg** [comment]
I use spotless on multiproject builds, but I haven't observed this behavior before, and I can't reproduce.  Is there a reproducible example?

This isn't related to your specific problem, but if these are in your subprojects, it might help to do `licenseHeaderFile rootProject.file('blahblah')`.

Btw, use [triple-backticks for code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) :)

**Comment by ksemer** [comment]
> rootProject.file

Hi,
my project has 1 folder and 2 subfolders which are the subprojects

mainFolder
mainFolder/A
mainFolder/B

from mainFolder you build the whole project.
mainFolder/A has the subproject A which has subproject B as dependency.

If I include spotless in mainFolder/A and try to build it I get the same error as my first post.
Now if I import the plugin  ```com.diffplug.gradle.spotless version '3.18.0' apply true``` in the A project I can build it but when I am going to build the whole project from the mainFolder I get 
Error resolving plugin [id: 'com.diffplug.gradle.spotless', version: '3.18.0', apply: false]
> Plugin request for plugin already on the classpath must not include a version.

**Comment by JLLeitschuh** [comment]
Do you have `org.gradle.configureondemand=true` flag enabled in Gradle? If so, this could absolutely cause this sort of issue.

**Comment by nedtwigg** [comment]
The way I have it setup in all my projects is:

```
<root>
plugins {
  id 'com.diffplug.gradle.spotless' version '3.23.0'
}

<any subdir>
 (either)
plugins {
  id 'com.diffplug.gradle.spotless'
}
  (or)
apply plugin: 'com.diffplug.gradle.spotless'
```

**Comment by ksemer** [comment]
Nothing worked but I fixed it using ```allprojects {
}```
