### ISSUE TITLE
Support for eclipse formatter 4.12 / 2019-06

### ISSUE THREAD

**Issue by k-brooks** [diffplug/spotless#422]
4.11 formatter contains a bug that we hit (https://bugs.eclipse.org/bugs/show_bug.cgi?id=545898), hoping to update to 4.12 where this issue is fixed.
Happy to assist if you can point me in the right direction.

**Comment by fvgh** [comment]
It's OK, I'll provide an update for:

- JDT (major fixes)
- CDT (better support of C11 and above)
- WTP (minor model change for HTML5)
- GrEclipse (in the underlying Groovy some parser issues have been solved, might have an impact)

Sorry for the delay, wanted to solve #292 first, but have to realize that I have not enough time to solve that one quickly.

**Comment by k-brooks** [comment]
No need to apologize, your work is appreciated greatly.
Let me know if I can assist in some way.

**Comment by basil** [comment]
Thank you for your efforts, which are much appreciated. I'm personally looking forward to being able to take advantage of groovy/groovy-eclipse#721 (which was released in Groovy Eclipse 3.3.0) via Spotless.

**Comment by fvgh** [comment]
@basil Yes, just noticed that the unit tests results changed/improved. Don't use Groovy myself anymore. Please, remind me to provide updates if there are improvements on the formatters.
Hope I can more or less automate the process in the future...

**Comment by nedtwigg** [comment]
Released in x.24.0

**Comment by k-brooks** [comment]
You guys are awesome, thanks again!!
