### ISSUE TITLE
Running test on plugin-gradle errors

### ISSUE THREAD

**Issue by carbotaniuman** [diffplug/spotless#424]
If you are submitting a **bug**, please include the following:

I'm on Windows 10. I've cloned a copy of spotless and run gradlew test and I get the error below for 41 of the tests. Commit is b6b79f964, Java is 1.8.0_211.

```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in C:\Users\quydx\AppData\Local\Temp\junit7334509706983622057 with arguments [spotlessApply]

Output:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'junit7334509706983622057'.
> Failed to notify project evaluation listener.
   > org.gradle.api.execution.TaskExecutionGraph.whenReady(Lorg/gradle/api/Action;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.211 secs
```

**Comment by nedtwigg** [comment]
Try a `gradlew clean`.  Obviously not a good answer, but we run an old version of gradle (for compat / time priority reasons), and it might not be worth the effort to fix if a `clean` can fix it.

**Comment by carbotaniuman** [comment]
What's your normal build system? I'm trying to see if I can resurrect an old half-done PR, but I can't get tests to work. (I jumped on Ubuntu and now all of the tests are failing with GradleConnectionException.

**Comment by nedtwigg** [comment]
So `gradlew clean` isn't fixing it?  The normal build system is just the gradle wrapper that's committed into the repo.  I work on spotless from win, mac, and linux machines.

Are you behind a corporate firewall?  I wonder if [this](https://github.com/diffplug/spotless/blob/b6b7f964ff4af04ea54cd8914bb41de222ffd027/testlib/src/main/java/com/diffplug/spotless/TestProvisioner.java) might be causing some of your problems...

Thanks for reviving your PR, hope we can get it merged :)

**Comment by carbotaniuman** [comment]
Deep derp. I was testing my "initial build" against the PR, not the fresh download. PR is one of jduncan's that I was going to fry and ix but never got around to :P
