### ISSUE TITLE
Indentation for custom files

### ISSUE THREAD

**Issue by t-buss** [diffplug/spotless#439]
I'm not sure if this is just a question or a bug, because it seems to be such an obvious feature, it would have been noticed by now:
We're trying to format XML-Files, specifically the indentation.
The following is the config:
```
<plugin>
            <groupId>com.diffplug.spotless</groupId>
            <artifactId>spotless-maven-plugin</artifactId>
            <version>1.23.0</version>
            <configuration>
                <java>
                    ...
                </java>
              <formats>
                <format>
                  <includes>
                    <include>src/**/*.xml</include>
                  </includes>
                  <indent>
                    <spaces>true</spaces>
                    <spacesPerTab>4</spacesPerTab>
                  </indent>
                  <!--<endWithNewline />-->
                </format>
              </formats>
            </configuration>
        </plugin>
```
However, spotless does not report those xml-files with 2 space indentation.
I know the `includes` block is correct as when I uncomment `<endWithNewline />` tag, the files are reported for the missing new line.
So why is the file not reported for wrong indentation?

EDIT: Just had a chat with @matthiasbalke about this. For custom formats, the plugin cannot know how to indent files, as it would have to parse it.
The plugin can only convert from tabs to spaces with this setting, it will not check whether all indentations are done with 4 spaces

**Comment by aaron-ai** [comment]
@t-buss  have you solved the problem?

**Comment by t-buss** [comment]
@aaron-ai I honestly cannot remember, it's been so long. I also do not have access to the project's files. Sorry I cannot help you.
