### ISSUE TITLE
Add vertical-blank SQL formatter?

### ISSUE THREAD

**Issue by colindean** [diffplug/spotless#459]
I'm setting up SQL formatting for the benefit of some data scientists on my team. They're not a fan of how DBeaver formats SQL but they do like how [vertical-blank's sql-formatter](https://github.com/vertical-blank/sql-formatter) formats SQL.

Would it be permissible to add an additional SQL formatter that uses this other library?

I figure if DBeaver is configured like so:

```groovy
spotless {
  sql {
    // default value for target files
    target '**/*.sql'
    dbeaver().configFile('sql_formatter_settings.properties')
  }
}
```

then I could configure sql-formatter like so:

```groovy
spotless {
  sql {
    // default value for target files
    target '**/*.sql'
    verticalBlank().configFile('sql_formatter_settings.properties')
  }
}
```

I'm willing to do the work but want to run it past the maintainers before committing any time to it.

**Comment by nedtwigg** [comment]
That would be great!  We have multiple formatters available for many file types (e.g. eclipse vs google-java-format for java, tsfmt vs prettier for typescript, prettier vs WTP for web resources, etc.).  Spotless is opinionated that you should use automatic code formatting, it is explicitly agnostic about *which* style you should use.

https://github.com/diffplug/spotless/blob/master/CONTRIBUTING.md#how-to-add-a-new-formatterstep

**Comment by nedtwigg** [comment]
Perhaps some useful background: https://github.com/diffplug/spotless/issues/156

**Comment by colindean** [comment]
Cool. We're evaluating a few different formatters to find one we like. When we choose, I'll head in that direction. vertical-blank is winning right now.

**Comment by jbduncan** [comment]
@colindean To add to @nedtwigg's comments, I did a search just now and I've realised that vertical-blank's sql-formatter is a Java port of [zeroturnaround's sql-formatter](https://github.com/zeroturnaround/sql-formatter) for JavaScript and that vertical-blank's pretty hasn't been updated in a few months.

Thus if you felt inclined to submit a PR (no pressure, though!), I'd suggest you look into how Spotless integrates the JavaScript formatter prettier, and then use the same technique to integrate zeroturnaround's sql-formatter.

If you need any help with this, I'd be more than happy to guide you in any way I can. :)

**Comment by jbduncan** [comment]
That being said, I'm equally happy to help out with integrating vertical-blank's formatter if you'd prefer that. :)

**Comment by jbduncan** [comment]
...and I've just seen your [earlier comment](https://github.com/diffplug/spotless/issues/459#issuecomment-534685184) about you still deciding which formatter to go for. Sorry about that!

In any case, I'm happy to help in any way I can!

**Comment by nedtwigg** [comment]
Just an update, it is now possible to use [any formatter](https://github.com/diffplug/spotless/tree/main/lib/src/main/resources/com/diffplug/spotless/npm) from the NodeJS world, and especially [any plugin for `prettier`](https://github.com/diffplug/spotless/tree/main/plugin-gradle#using-plugins-for-prettier), such as [prettier-plugin-pg](https://prettier.io/docs/en/plugins.html#community-plugins) and others.

We're still happy to take a PR for vertical-blank, or any other SQL formatter.  But since this has sat dormant for almost a year, I'm going to close it for now.  Happy to reopen if there is renewed interest.
