### ISSUE TITLE
Feature request: Allow exclusions for licenseHeaderFile block

### ISSUE THREAD

**Issue by ivorywang** [diffplug/spotless#460]
Our company has changed names over the time we have been writing code and I don't want to exclude files entirely from formatting, just the license header file. Our new license header looks like Company Company $YEAR but was Company company company $YEAR and spotless wants to format the old ones even though that copyright is still valid

**Comment by nedtwigg** [comment]
How would you like your `build.gradle` to look?

**Comment by ivorywang** [comment]
Ideally it would be something the snippet below for kotlin

licenseHeaderFile {
    filePath = "path/to/license/file"
    targetExclude("dont/format/me/bro/**")
}

**Comment by nedtwigg** [comment]
This is a pretty special case, so it's unlikely to become first-class API.  Here is an awkward way that I believe will work already.  The main hiccup is that there's no guarantee about which formatter will run first, `java` or `license`, but it shouldn't matter.  If it does turn out to matter, you could enforce the order by doing something like `tasks.spotlessJava.dependsOn(tasks.spotlessLicense)`.

```gradle
spotless {
  java { eclipse() }
  format 'license' {
    licenseHeaderFile(licenseHeaderFile, 'package ');
    target 'src/main/java/**/*.java'
    targetExclude 'dont/format/me/bro/**'
  }
}
```

Another way, which could work if we made more of the API public, is this:

```gradle
spotless {
  java {
    eclipse()
    licenseHeaderFile('path/to/file')
    replaceStep(getExistingStep('licenseHeader')
      .filterByFile(SerializableFileFilter.skipStartsWith('dont/format/me/bro/')))
  }
}
```

The second way is how we handle problems like this internally:

https://github.com/diffplug/spotless/blob/3ac6c7c5d8b1eb563f69545421968164e70c4b50/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java#L190-L196

But for general user code to be able to do this, we would need to make changes to all of the following:

https://github.com/diffplug/spotless/blob/3ac6c7c5d8b1eb563f69545421968164e70c4b50/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L270-L296

https://github.com/diffplug/spotless/blob/3ac6c7c5d8b1eb563f69545421968164e70c4b50/lib/src/main/java/com/diffplug/spotless/SerializableFileFilter.java

So I'd recommend the first way.  Whatever you end up doing, post your build.gradle back to this issue before you mark it closed in case others have the same issue.

**Comment by ivorywang** [comment]
So finally got around to trying out your suggestion (thanks for the quick reply btw!) and I ended up going with solution 1 which looks like the following for kotlin
```groovy
    format("license", {
        licenseHeaderFile("${rootProject.file("path/to/licenseHeader.txt")}", "package ");
        target("src/main/java/**/*.java")
        targetExclude("**/foo/bar/*")
    })
```
