### ISSUE TITLE
Eclipse 4.13 support

### ISSUE THREAD

**Issue by k-brooks** [diffplug/spotless#480]
Support for 4.13, please!
I'd be happy to contribute - I think I see what needs to be done based on (components of, not the default update) https://github.com/diffplug/spotless/pull/423

**Comment by nedtwigg** [comment]
PRs are always welcome!  Here's another example, a little simpler: https://github.com/diffplug/spotless/pull/384/files

**Comment by k-brooks** [comment]
As always - a speedy response @nedtwigg 
Would you / diffplug prefer separate issues/PRs for the supporting _ext updates?

**Comment by k-brooks** [comment]
Actually, it looks like the version ranges in the _ext artifacts will permit what is necessary, disregard.

**Comment by k-brooks** [comment]
I take that back, the fat jar is bundling the pinned version.

**Comment by nedtwigg** [comment]
Bumping JDT shouldn't require any changes in _ext, #384 is a canonical example.

**Comment by k-brooks** [comment]
I was hoping to hit Groovy as well, we use it for Gradle and would like to have consistent eclipse versions, and figured I'd do the rest while I was there.
But can break that out if desired

**Comment by nedtwigg** [comment]
Ahh, roger.  Combined or broken-out is fine, either way!
