### ISSUE TITLE
Please specify the desired project "import order" via editorconfig

### ISSUE THREAD

**Issue by vlsi** [diffplug/spotless#486]
IDEA supports "import order" configuration via `.editorconfig`.
See https://github.com/apache/jmeter/blob/master/.editorconfig#L20-L23

Would you please update https://github.com/diffplug/spotless/blob/master/.editorconfig accordingly?

It is not clear what is the "project desired" order, and it is sad that is not configured automatically on project import.

**Comment by nedtwigg** [comment]
Happy to take a PR for this.  Here is the current order:

- https://github.com/diffplug/spotless/blob/04d5c7d9d110283aceef72e053f6c8a66e734805/spotlessSelf.gradle#L35
- https://github.com/diffplug/spotless/blob/master/spotless.importorder
