### ISSUE TITLE
Please use no-timestamps for JavaDoc generation

### ISSUE THREAD

**Issue by vlsi** [diffplug/spotless#487]
`gh-pages` contains lots of irrelevant "changes" like https://github.com/diffplug/spotless/commit/534fb57b06f1d68f7f18a6c23f90f2169bd60c24

Please consider force-pushing `gh-pages` branch (to remove irrelevant timestamp-only diffs).

Here's the way to remove the timestamps from the generated files (it should be `options.noTimestamp = true` to remove the timestamps): https://github.com/gradle/gradle/pull/10488/files#diff-e41b3af4bdc91cb5f1659b821bd29500R58

Alternative option is to wait for Gradle 6.0 (it should switch to notimestamp by default)

**Comment by nedtwigg** [comment]
Happy to take a PR for this.  I've been thinking about dumping the gh-pages stuff and just using https://javadoc.io/
