### ISSUE TITLE
Spotless does not respect line endings on Windows 10

### ISSUE THREAD

**Issue by jaredjstewart** [diffplug/spotless#49]
We have `lineEndings = 'unix';` specified in our Spotless config, but it appears to not be respected in Windows 10 or Windows Server 2016.

Here are the instructions to reproduce: 

I ran ./gradlew spotlessApply on the Windows 10 machine using git bash this
is what has happened.
NOTE: I started the below steps on a fresh git clone of the open side.
[Steps:
1.  git clone https://git-wip-us.apache.org/repos/asf/incubator-geode.git
open
2. cd open
3. git checkout -b develop origin/develop]

*Step 1. ./gradlew clean build -Dskip.tests=true*

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geode-core:spotlessJavaCheck'.
Format violations were found. Run 'gradlew spotlessApply' to fix them.

geode-core\src\main\java\org\apache\geode\internal\statistics\StatArchiveReader.java

geode-core\src\test\java\org\apache\geode\cache\query\dunit\PdxLocalQueryVersionedClassDUnitTest.java

geode-core\src\test\java\org\apache\geode\internal\cache\execute\ClientServerFunctionExecutionDUnitTest.java

geode-core\src\test\java\org\apache\geode\internal\cache\functions\TestFunction.java

geode-core\src\test\java\org\apache\geode\internal\statistics\StatArchiveWithMissingResourceTypeRegressionTest.java

*Step 2: ./gradlew spotlessApply*

BUILD SUCCESSFUL

Total time: 12.728 secs

*Step 3: git status*

modified:
geode-core/src/main/java/org/apache/geode/internal/statistics/StatArchiveReader.java
       modified:
geode-core/src/test/java/org/apache/geode/cache/query/dunit/PdxLocalQueryVersionedClassDUnitTest.java
       modified:
geode-core/src/test/java/org/apache/geode/internal/cache/execute/ClientServerFunctionExecutionDUnitTest.java
       modified:
geode-core/src/test/java/org/apache/geode/internal/cache/functions/TestFunction.java
       modified:
geode-core/src/test/java/org/apache/geode/internal/statistics/StatArchiveWithMissingResourceTypeRegressionTest.java

*Step 4 : git add .*
warning: LF will be replaced by CRLF in
geode-core/src/main/java/org/apache/geode/internal/statistics/StatArchiveReader.java.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in
geode-core/src/test/java/org/apache/geode/cache/query/dunit/PdxLocalQueryVersionedClassDUnitTest.java.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in
geode-core/src/test/java/org/apache/geode/internal/cache/execute/ClientServerFunctionExecutionDUnitTest.java.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in
geode-core/src/test/java/org/apache/geode/internal/cache/functions/TestFunction.java.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in
geode-core/src/test/java/org/apache/geode/internal/statistics/StatArchiveWithMissingResourceTypeRegressionTest.java.
The file will have its original line endings in your working directory.

*Step 5: git status*
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working tree clean

*Step 6: ./gradlew clean build -Dskip.tests=true*
BUILD SUCCESSFUL

Total time: 5 mins 28.64 secs

**Comment by jbduncan** [comment]
Admittedly I'm on Windows 7 and don't have access to a Windows 10 VM, but when I clone the repo and do `git checkout -b develop origin/develop` and `./gradlew clean build -Dskip.tests=true`, I get a very different error message. It's too long to include it fully here, so I'll only show you the last part I got.

```
...
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

18: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':geode-web-api:spotlessJavaCheck'.
> Format violations were found. Run 'gradlew spotlessApply' to fix them.
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\AbstractBaseController.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\BaseControllerAdvice.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\CommonCrudController.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\FunctionAccessController.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\PdxBasedCrudController.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\QueryAccessController.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\support\JSONTypes.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\support\QueryResultTypes.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\support\RegionData.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\support\RegionEntryData.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\support\RestServersResultCollector.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\controllers\support\UpdateOp.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\exception\DataTypeNotSupportedException.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\exception\GemfireRestException.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\exception\MalformedJsonException.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\exception\RegionNotFoundException.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\exception\ResourceNotFoundException.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\http\converter\CustomMappingJackson2HttpMessageConverter.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\security\GeodeAuthenticationProvider.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\security\RestSecurityConfiguration.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\security\RestSecurityService.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\swagger\config\SwaggerConfig.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\util\ArrayUtils.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\util\DateTimeUtils.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\util\IdentifiableUtils.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\util\JSONUtils.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\util\JsonWriter.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\util\NumberUtils.java
    geode-web-api\src\main\java\org\apache\geode\rest\internal\web\util\ValidationUtils.java

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED

Total time: 12 mins 34.144 secs
```

Does anyone on the geode team use Windows 7? Do they get a similar trace when running the same commands?

**Comment by nedtwigg** [comment]
I think you're misinterpreting git's message.  The line endings are in fact unix line endings - look in a text editor.  This message is telling you "git's settings say that these should be CRLF, and you're checking in LF.  That's fine, but just so you know, we think this should be CRLF, and when you do a clean checkout on a different machine, that's what you'll get."

Git has strong opinions about line endings.  [We *really* don't recommend setting Spotless' line endings](https://github.com/diffplug/spotless#line-endings-and-encodings-invisible-stuff) to anything other than default of GIT_ATTRIBUTES, because if you do, git and spotless will be fighting each other.  The previous link shows how to set a `.gitattributes` file which sets the line endings to unix.

**Comment by jaredjstewart** [comment]
@nedtwigg Maybe I am missing something - can you explain why the initial spotlessCheck fails upon checkout?  That would seem to be independent of any git settings.

**Comment by nedtwigg** [comment]
>That would seem to be independent of any git settings.

It's not.  Git is not a pure content store, it mucks with line endings.  Regardless of what you check-in, it will store your files with unix line endings in the repo.

Then, when you checkout, it will modify the line endings to suit your platform.  Unless you add a `.gitattributes` file to tell git "forget the platform, do what this file says".

Remove `lineEndings 'UNIX'` in your build.gradle, and add a `.gitattributes` file in your root directory with the content `* text eol=lf` and your problem will be fixed.

**Comment by jaredjstewart** [comment]
I thought Git only mucked with line endings when you add files, I didn't know it actually did that on checkout.  Thank you so much for your explanation.

**Comment by nedtwigg** [comment]
If there's any truth in the world, it's this:  git is *always* mucking with your line endings ;-)

Everything I said above can be changed based on a variety of more obscure git settings files spread across your machine-global config, your home directory, and your repo.  But `.gitattributes` blasts all that and defines the truth unambiguously.
