### ISSUE TITLE
Maven plugin should support skip

### ISSUE THREAD

**Issue by thegreystone** [diffplug/spotless#491]
Many maven plug-ins support skipping the plug-in altogether when skip is set to true in the configuration. In a big tree of modules, that can be useful for supporting setting up reasonable defaults, and then opting out in modules where this is not necessary. So, e.g.:

> 			<plugin>
>   				<groupId>com.diffplug.spotless</groupId>
>   				<artifactId>spotless-maven-plugin</artifactId>
>   				<configuration>
>     				<skip>true</skip>
>   				</configuration>
> 			</plugin>

**Comment by nedtwigg** [comment]
Happy to merge a PR for this.

**Comment by Xendar** [comment]
I am a bit surprised actually :D
In the documentation there is a mention of `-Dspotless.check.skip=true` option to disable Spotless check. I tried and it seems not to be working, so I did a search in the issues and found this issue...

**Comment by nedtwigg** [comment]
Fixed by @tisonkun, available in `plugin-maven 2.27.1`.
