### ISSUE TITLE
[Question] A Few Questions

### ISSUE THREAD

**Issue by t-rad679** [diffplug/spotless#494]
A few questions:

I'm wondering if it possible to override rules applied in a given step. For instance, would specifying a rule that conflicts with a rule specified earlier replace or overwrite the output of the earlier rule. This is only one possible way for this to work, but it seems the most natural to me so that is my initial guess as to how it works.

For a more concrete example, consider the following gradle config:
```gradle
spotless {
     java {
        googleJavaFormat()
        indentWithSpaces(4)
     }
}
```
My first thought (and what I want) is that the formatted java files would be indented with 4 spaces, rather than the 2 spaces specified in google-java-format. Is this correct?

Second, I'd like to just confirm the functionality of the Eclipse formatter. My understanding is that this just does exactly what Eclipse would do to files when it formats them with a given config, and this config is the exact same config you would import to/export from Eclipse. Are these assumptions correct? If that be the case, it seems like this would be the most powerful step (at least for Java), and most other steps could be configured as part of this one.

Third, do you have any more documentation about custom rules? I'm interested in the feature but would like to see some more specific notes about how to use it and what can/cannot be done with it.

**Comment by thc202** [comment]
Not answering your question... you can use AOSP style for 4 spaces:
https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source-with-google-java-format

**Comment by nedtwigg** [comment]
> google-java-format and 4 spaces

- https://github.com/diffplug/spotless/search?q=googleJavaFormat+4+spaces&type=Issues
- https://github.com/diffplug/spotless/issues/420
- https://github.com/diffplug/spotless/issues/317

> My understanding is that this just does exactly what Eclipse would do to files when it formats them with a given config, and this config is the exact same config you would import to/export from Eclipse

Correct

> If that be the case, it seems like this would be the most powerful step (at least for Java), and most other steps could be configured as part of this one.

That is correct.  But if you don't want power, just a widely adopted standard which you don't have to configure, then `google-java-format` might be a better choice.  We are not an opinionated project - if someone wants to add a formatter which is useful to them, we encourage them to do so, whether or not there is already another formatter which can do something similar.

> do you have any more documentation about custom rules

Not any more than this, which includes links to javadoc and code.  The API asks you to provide a `Function<String, String>`.  You can do anything you want inside that function.

https://github.com/diffplug/spotless/tree/master/plugin-gradle#custom

**Comment by nedtwigg** [comment]
More custom rule docs: https://github.com/diffplug/spotless/blob/master/CONTRIBUTING.md#how-spotless-works

**Comment by t-rad679** [comment]
Thank you!
