### ISSUE TITLE
Support license header with shebang

### ISSUE THREAD

**Issue by irrandon** [diffplug/spotless#496]
Hi,
for the license header step to work for linux script files correct handling of shebang lines is required. 
Currently it is not handled correctly.

**Comment by nedtwigg** [comment]
Can you provide an example?

```gradle
spotless {...}
```

```sh
# EXAMPLE SCRIPT:

# ACTUAL OUTPUT:

# DESIRED OUTPUT:
```

**Comment by vlsi** [comment]
@irrandon , you might want to give https://github.com/autostyle/autostyle a try

It supports Shell (e.g. `#!/`), Batch (e.g. `@echo off`), XML (e.g. `<?..?>`), Java (including `package-info.java` and `module-info.java`), and Gradle (Kotlin / Gradle scripts) automatically.

Samples: https://github.com/apache/jmeter/pull/549, https://github.com/apache/calcite/pull/1682

**Comment by jbduncan** [comment]
@vlsi Wow, those sound like some fantastic features!

If you felt up to raising PRs for any of those features that you'd feel comfortable seeing integrated into Spotless, I'd be more than happy to review them and facilitate merging them in. :)

@irrandon Going for @vlsi's suggestion of using autostyle seems to be the best way forward in the shorter term, as development for Spotless has been slow for quite a while now. (I know that I've myself been struggling to find the time and energy to contribute to Spotless and other open source projects over the past year, so that hasn't helped things.)

**Comment by nedtwigg** [comment]
> development for Spotless has been slow for quite a while now

I disagree strongly!!  I just checked, and in November alone we had two releases with commits from 6 different authors!  We have a release almost every month, and PR's almost always get feedback within 24 hours.  That's not slow!

I do agree completely that @vlsi has released some great features in his autostyle fork.  If autostyle solves your problem and you'd rather not investigate further, feel free to close.  However, I am still interested in solving the problem, but I could use help understanding what is currently broken with the shebang handling.

**Comment by jbduncan** [comment]
@nedtwigg D'oh! Silly me. Thanks for correcting my faulty memory. :man_facepalming:

**Comment by jbduncan** [comment]
(Note for self: Check the commit history first before making any claims on project development speed! :wink:)

**Comment by irrandon** [comment]
We have a temporary solution with a python script but a support via spotless would be nice :)

Here an example:
```c
spotless{
  format('python') {
    licenseHeaderFile 'com/company/gradle/hash.license', '(import |""")'
    target '**/*.py'
  }
}
```

(If you add the shebang to the delimiter regex, it push the shebang under the license header, what would be invalid.)
##### hash.license:
```
#==========================================================================
#  Copyright (c) Awesome Corp., 1980-2020.
#
#  All rights reserved. All hardware and software names used are registered
#  trade names and/or registered trademarks of the respective manufacturers.
#
#  The user of this computer program acknowledges that the above copyright
#  notice, which constitutes the Universal Copyright Convention, will be
#  attached at the position in the function of the computer program which the
#  author has deemed to sufficiently express the reservation of copyright.
#  It is prohibited for customers, users and/or third parties to remove,
#  modify or move this copyright notice.
#==========================================================================
```

##### EXAMPLE SCRIPT:
```python
#!/usr/bin/env python3
import sys
print("Hello world")
```

##### ACTUAL OUTPUT:
```python
#==========================================================================
#  Copyright (c) Awesome Corp., 1980-2020.
#
#  All rights reserved. All hardware and software names used are registered
#  trade names and/or registered trademarks of the respective manufacturers.
#
#  The user of this computer program acknowledges that the above copyright
#  notice, which constitutes the Universal Copyright Convention, will be
#  attached at the position in the function of the computer program which the
#  author has deemed to sufficiently express the reservation of copyright.
#  It is prohibited for customers, users and/or third parties to remove,
#  modify or move this copyright notice.
#==========================================================================
import sys
print("Hello world")
```

##### DESIRED OUTPUT:
```python
#!/usr/bin/env python3
#==========================================================================
#  Copyright (c) Awesome Corp., 1980-2020.
#
#  All rights reserved. All hardware and software names used are registered
#  trade names and/or registered trademarks of the respective manufacturers.
#
#  The user of this computer program acknowledges that the above copyright
#  notice, which constitutes the Universal Copyright Convention, will be
#  attached at the position in the function of the computer program which the
#  author has deemed to sufficiently express the reservation of copyright.
#  It is prohibited for customers, users and/or third parties to remove,
#  modify or move this copyright notice.
#==========================================================================
import sys
print("Hello world")
```

**Comment by nedtwigg** [comment]
An easy workaround is to put the `#!/usr/bin ...` inside the license that you give to Spotless.  Any problems with that?

**Comment by irrandon** [comment]
The problem is that this only works, when you have the same shebang for all python files.
But we also have #!/usr/bin/env python2. The same problem is there with linux script files.(#!/usr/bin/env sh | #!/usr/bin/env bash)

**Comment by nedtwigg** [comment]
(comment deletions just to remove off-topic discussion and condense on the feature request)

Aha!  This is a good feature request.  It's tricky - the license step has so far had a very simple model:  find the "top" of the file with regex Y, and then add header X.  Solving this issue will require complicating the model somewhat.

A simple way to do this would be to allow something like `$FIRST_LINE` within the replacement text.  So your `hash.license` could be

```
$FIRST_LINE
#==========================================================================
#  Copyright (c) Awesome Corp., 1980-2020.
#
#  All rights reserved. All hardware and software names used are registered
#  trade names and/or registered trademarks of the respective manufacturers.
```

The other option would be to make the license step generally more powerful and context-sensitive, as @vlsi has done in his fork, linked above.  I would definitely merge a PR to add support for $FIRST_LINE, since it is so simple.  I'm also open to a more powerful context-sensitive option, but backwards compatibility and long-term maintenance burden would be an important challenge to keep in mind.

**Comment by abelk2** [comment]
I think this is supported now with #1441.

**Comment by nedtwigg** [comment]
Thanks @abelk2! Relevant example:

```gradle
format "licenseHeaderSh", {
  target "*.sh"
  licenseHeaderFile(file("$rootDir/config/license/sh.txt"), "^(?!##).+")
    .skipLinesMatching("^#!.+?\$")
  // license header MUST start with ##
}
```
