### ISSUE TITLE
EndWithNewLine not working for maven plugin and scala formatter

### ISSUE THREAD

**Issue by cwholmes** [diffplug/spotless#498]
Using the maven plugin and the following configuration that can be found in the [readme](https://github.com/diffplug/spotless/tree/master/plugin-maven#applying-to-scala-source) for the plugin, the build fails for an invalid configuration.

```xml
<plugin>
  <groupId>com.diffplug.spotless</groupId>
  <artifactId>spotless-maven-plugin</artifactId>
  <version>${spotless.version}</version>
  <configuration>
    <scala>
      <endWithNewLine/>
      <trimTrailingWhitespace/>
      <scalafmt>
        <file>${user.dir}/src/etc/scalafmt.conf</file>
        <version>${scalafmt.version}</version>
      </scalafmt>
    </scala>
  </configuration>
</plugin>
```

The failure:
```bash
Unable to parse configuration of mojo com.diffplug.spotless:spotless-maven-plugin:1.26.1:apply for parameter endWithNewLine: Cannot find 'endWithNewLine' in class com.diffplug.spotless.maven.scala.Scala
```

Spotless Maven Plugin Version: 1.26.1
ScalaFMT Version: 2.3.2
Maven Version: 3.6.2
Java Version: 1.8.0_222
Operating System: Windows 10

If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] gradle or maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment]
Hmm...  Looks like our docs might be wrong.  Can you try `endWithNewline` (lowercase L) rather than `endWithNewLine` (uppercase L).  If that fixes it, we need to update our docs.

**Comment by nedtwigg** [comment]
@cwholmes did that fix it for you?

**Comment by cwholmes** [comment]
Well, I definitely missed that, and for the bit of testing I did it seems to be working with that. I also opened a PR for the README change. #517
