### ISSUE TITLE
Eclipse formatting not performed during the build

### ISSUE THREAD

**Issue by javaman-888** [diffplug/spotless#51]
I inserted 
`apply plugin: 'com.diffplug.gradle.spotless'
...
spotless {
	    java {
	        eclipseFormatFile '../misc/collections-team-format.xml'  // XML file dumped out by the Eclipse formatter
	    }
	}` into my build.gradle. 
I understand the formatting should happen automatically (why would I need the plugin otherwise?), but it doesn't - I receive "> The following files had format violations:..." diff and the build fails. I realize that explicit invocation of "./gradlew spotlessApply build" will format the code prior to the build but why wouldn't it automatically format when "./gradlew build" is invoked?

**Comment by javaman-888** [comment]
Solution is here: http://stackoverflow.com/questions/40432291/gradle-spotless-task-not-firing-when-needed?newreg=a2409b5626b04244aef99084d17df4f8

**Comment by nedtwigg** [comment]
> I understand the formatting should happen automatically

Not quite.  From the README:

```
cmd> gradlew build
...
:spotlessJavaCheck FAILED
> Format violations were found. Run 'gradlew spotlessApply' to fix them.
    src\test\java\com\diffplug\gradle\spotless\ResourceTest.java

cmd> gradlew spotlessApply
:spotlessApply
BUILD SUCCESSFUL

cmd> gradlew build
BUILD SUCCESSFUL
```

The error message you're seeing says to run `spotlessApply`, and that will fix the formatting.

> why wouldn't it automatically format when "./gradlew build" is invoked?

Let's say your CI server run `gradlew build` to test that a commit is good.  I commit code with bad formatting.  If `gradlew build` fixed the formatting, then bad formatted would never fail a build, and your history would be full of dirty commits.

**Comment by javaman-888** [comment]
Thanks,

Vadim

**Comment by jbduncan** [comment]
Ah, seems like I was ninja'd! But nonetheless, I think it might be worthwhile if post here was I was going to say. :)

> I admit I don't fully understand why you're asking the question you're asking, but I'll do my best to answer it, in the hope it clear things up for you.
> 
> On one hand, I think it's because Spotless is mainly meant to be a tool to _check_ that code follows a certain formatting, and if it doesn't follow that formatting to then allow one to apply a quick corrective action if you so wish.
>
> On the other hand, I also think it's because using `spotlessApply` by default is a bit risky because, to give a couple of examples, if there is either a bug in Spotless or if you've told Spotless to use a custom formatting rule which itself is buggy or misbehaving, then you may end up losing work which you've not committed to your VCS yet, which would be bad. To prevent this, `spotlessCheck` allows you to see what the code _will_ end up looking like, and if you're a little paranoid (like me!), you can apply beforehand some precautionary measures (as explained by [these instructions](https://github.com/diffplug/spotless#how-do-i-preview-what-spotlessapply-will-do)) to make sure you don't end up losing any of your hard work. :)

**Comment by javaman-888** [comment]
Hi Jonathan,

I appreciate your help! The way we do builds is first do it locally before
checking in, so auto formatting works well in this situation.

Thanks,

Vadim
