### ISSUE TITLE
[question] Prohibition of use of specified classes

### ISSUE THREAD

**Issue by ZacharyTech** [diffplug/spotless#516]
Expect to use certain classes in Java projects, for example : `android.util.Log`

**Comment by nedtwigg** [comment]
One option is to use the `replace` step.  Here's a rule from one of my projects.

```gradle
replace 'AutoValue fix', 'import autovalue.shaded.', 'import '
```

Another option is to make a custom rule.  Here is one we use to make sure that Spotless doesn't accidentally depend on internal Gradle API.

https://github.com/diffplug/spotless/blob/9051c97ac1e8f50a517d866940b44cdf19d20f50/gradle/spotless.gradle#L3-L14

https://github.com/diffplug/spotless/blob/9051c97ac1e8f50a517d866940b44cdf19d20f50/gradle/spotless.gradle#L18-L19

**Comment by ZacharyTech** [comment]
Currently, it is only necessary to check whether the disabled class appears in the project. 
I will use `replace` to handle it. 
THX
