### ISSUE TITLE
Consider changing README to include updated error message example

### ISSUE THREAD

**Issue by jbduncan** [diffplug/spotless#52]
Currently, the README shows the following example error message.

```
cmd> gradlew build
...
:spotlessJavaCheck FAILED
> Format violations were found. Run 'gradlew spotlessApply' to fix them.
    src\test\java\com\diffplug\gradle\spotless\ResourceTest.java

cmd> gradlew spotlessApply
:spotlessApply
BUILD SUCCESSFUL

cmd> gradlew build
BUILD SUCCESSFUL
```

But since Spotless version 2.3.0, it now outputs a different message that includes a git-style diff for each of the first few files that violate the specified formatting rules. I suspect this confuses new users, from my observation of issue #51.

When we have the time, I think we should update the README to show what a typical error message looks like now.

**Comment by nedtwigg** [comment]
So long as the example is still short I'm all for it.

**Comment by jbduncan** [comment]
Fix pushed via https://github.com/diffplug/spotless/commit/46bbb2f4f6d197fb7bd1bdd5c4d7a2f4e1cbeb78.
