### ISSUE TITLE
Relative Path Support for spotlessFiles

### ISSUE THREAD

**Issue by t-rad679** [diffplug/spotless#531]
As discussed extensively from this [comment](https://github.com/diffplug/spotless/issues/529#issuecomment-588421298) in issue 529 onward, it would be nice to add some kind of support for specifying relative paths in ```spotlessFiles```, which currently only works with absolute paths. **The documentation should be very clear about how this will function in all cases, including what directory the path should be relative to**.

After some discussion in the other ticket, I think it makes the most sense for the path to be relative to the root directory of the root project.

**Comment by nedtwigg** [comment]
Whatever discussion or work happens in service of this ticket, please make sure that it is driven by a usecase that you have.  E.g. you are connecting to a tool and it is difficult to generate the absolute paths which are currently neeeded.  If you have a usecase, and can solve your problem without creating new problems for the people who are already using the `-PspotlessFiles` feature, then you can merge whatever.

**Comment by nedtwigg** [comment]
With the work happening in #568, I'm more convinced than ever that relative path support is likely to cause problems.  I think this issue is mostly driven by frustration with the surprising regex behavior, which is a separate problem.

**Comment by t-rad679** [comment]
Ok, sounds good! Thanks, Ned!

**Comment by nedtwigg** [comment]
FYI, `-PspotlessFiles` has been deprecated and will be removed.  Migration path available here: https://github.com/diffplug/spotless/pull/602
