### ISSUE TITLE
Eclipse disable tag ignored

### ISSUE THREAD

**Issue by luciano-fiandesio** [diffplug/spotless#534]
When using the eclipse formatter, the enabling/disabling tags does not seem to work.
When running `mvn spotless:check`, blocks which are surrounded by `@formatter:off ... @formatter:on` are reported as errors.
When running `mvn spotless:apply`, blocks which are surrounded by `@formatter:off ... @formatter:on` are formatted.

Maven configuration:
```
<plugin>
          <groupId>com.diffplug.spotless</groupId>
          <artifactId>spotless-maven-plugin</artifactId>
          <version>${spotless.version}</version>
          <configuration>
            <java>
              <eclipse>
                <file>${rootDir}/eclipse-format-rule.xml</file>
                <version>4.7.1</version>
              </eclipse>
            </java>
            <trimTrailingWhitespace />
            <removeUnusedImports />
          </configuration>
</plugin>
```

Relevant configuration from eclipse file:

```
<setting id="org.eclipse.jdt.core.formatter.disabling_tag" value="@formatter:off"/>
<setting id="org.eclipse.jdt.core.formatter.enabling_tag" value="@formatter:on"/>
```
Other info:

Maven version: 3.6.3
Spotless version: 1.27.0
OS: OSX 10.14.6

**Comment by nedtwigg** [comment]
Do you have

```
<setting id="org.eclipse.jdt.core.formatter.use_on_off_tags" value="true"/>
```

**Comment by luciano-fiandesio** [comment]
Gotcha, it was somehow missing from the eclipse file. Thanks for the quick reply.

**Comment by nedtwigg** [comment]
Just an update that since `plugin-gradle 5.5.0` and `plugin-maven 2.3.0`, it is now possible to use any formatter step in any language [with `spotless:off` tags](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson), and then you don't have to muck with obscure config files.
