### ISSUE TITLE
Enable support for IntelliJ compatible place holders in license header templates

### ISSUE THREAD

**Issue by sameer-b** [diffplug/spotless#541]
IntelliJ supports  the following format`$today.year` for injecting the current year in the license header. Since the syntax for spotless is `$YEAR`; they are not compatible. 

Since IntelliJ can auto inject this while creating new files, it would be convenient to have a single copyright template for both.

Could we enable support for `$today.year`? If we agree on the solution I can send a PR.

Thanks!
Sameer

**Comment by nedtwigg** [comment]
Absolutely, I'd love to merge such a PR.

**Comment by sameer-b** [comment]
@nedtwigg Thanks for the quick response! Here's the PR: https://github.com/diffplug/spotless/pull/542

**Comment by nedtwigg** [comment]
Released in `x.28.0`

**Comment by nedtwigg** [comment]
If you care about license headers, you should checkout [`ratchetFrom 'origin/master'`](https://github.com/diffplug/spotless/tree/master/plugin-gradle#ratchet).
