### ISSUE TITLE
Add support for eclipse 4.15 formatter

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#543]
Goomph just shipped support for 4.15.  It might be a tad more complicated for us to turn the crank this time than usual, due to [this change](https://www.eclipse.org/eclipse/news/4.15/jdt.php#new-formatterapp-bundle).

**Comment by nedtwigg** [comment]
Eclipse 4.15 has not been published to mavencentral yet, due to [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=561187).  When it gets resolved, I will update this issue.

**Comment by nedtwigg** [comment]
Fixed now.

**Comment by nedtwigg** [comment]
Hi @fvgh, hope you're doing well.  Our last supported eclipse version is `4.13.0` (~a year ago), and `4.17.0` will come out soon.  Java has added some new language features, like multiline strings, which our latest eclipse doesn't support (#676).  Do you foresee any time to bring these up to date?  `4.14.0` is pretty straightforward, but `4.15.0` will likely require some rework, and `4.17.0` (when it arrives in ~a month) is likely to require some rework too.  We're all volunteers on this, no obligation, just asking if you expect to have time.  If you do, I'm happy to pair with you and finally give you control over publishing `_ext` artifacts.

**Comment by fvgh** [comment]
Hi  @nedtwigg. I am afraid I had to keep my engagement in Spotless to a minimum for the last half year. Put I was planing to work on it again in October. Anyhow, I can try to do some catch-up this weekend, but I can't promise. If it is alright with you, let me see what I can accomplish till Monday morning.

**Comment by nedtwigg** [comment]
Sounds great!

**Comment by fvgh** [comment]
The `org.eclipse.jdt.core.formatterapp`only contains a slim `IApplication` providing the formatter as a stand-alone. It only [contains one class](https://github.com/eclipse/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.formatterapp/src/org/eclipse/jdt/core/formatterapp). We could use it to replace partly the functionality of `spottless-eclipse-base`, but of course `spottless-eclipse-base` is much more light-wight and sophisticated :grin:

**Comment by nedtwigg** [comment]
I have tried to run `IApplication` instances without the OSGi runtime, and it's tricky.  I think what you built in `_ext` is much better.  I was worried that the existing functionality that we use had moved, very glad that it turns out to just be a new entrypoint.  Huzzah!

**Comment by nedtwigg** [comment]
Oh, support for everything up to and including eclipse `4.16.0` was released  in `plugin-gradle 5.3.0` and `plugin-maven 2.1.0`
