### ISSUE TITLE
README links for examples results in GCP bucket error

### ISSUE THREAD

**Issue by rhoughton-pivot** [diffplug/spotless#574]
For the java gradle section, under [Custom Rules](https://github.com/diffplug/spotless/tree/master/plugin-gradle#custom-rules), There is a link to "you might want to take a look at this javadoc for a big performance win". That link is invalid

**Comment by nedtwigg** [comment]
Thanks!  The links are working for me right now.  I bet it was either a temporary outage on javadoc.io, or a transient from the recently-released `3.30.0` cascading through the systems.
