### ISSUE TITLE
Support for other Scala versions

### ISSUE THREAD

**Issue by hnoson** [diffplug/spotless#579]
Currently, only Scala 2.11 is supported. It's better to have a parameter to specify the version from config file.
https://github.com/diffplug/spotless/blob/54bd58d9a50f5e1dace0d0d56b7a842032167cbf/lib/src/main/java/com/diffplug/spotless/scala/ScalaFmtStep.java#L45-L46

**Comment by nedtwigg** [comment]
Would be happy to merge and release a PR for this!

Besides the place you pointed out, the other affected locations are:

- https://github.com/diffplug/spotless/blob/master/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/ScalaExtension.java
- https://github.com/diffplug/spotless/blob/master/plugin-maven/src/main/java/com/diffplug/spotless/maven/scala/Scala.java

`ScalaFmtStep` probably needs to add a `versionScala` parameter, and ideally that could be autopopulated by the gradle and maven plugins by slurping it from the build context, but it's alright if that's not possible.

**Comment by hnoson** [comment]
I realized that the version doesn't matter as long as it's used from Java because the version suffix is for binary compatibility. The formatting functionality doesn't change depending on the Scala version. Please close this issue if there is no concern.

**Comment by nedtwigg** [comment]
Thanks, useful to know!
