### ISSUE TITLE
Java files under src/*/groovy aren't detected by default

### ISSUE THREAD

**Issue by ajoberstar** [diffplug/spotless#59]
Spotless Version 2.4

In projects that do joint Java/Groovy compilation, you often need some or all of the Java files to be under the src/main/groovy directory. Spotless currently uses `sourceSets.main.java` to get the Java files to format by default. Using `sourceSets.main.allJava` would pick up the full set of Java source in these joint compile scenarios and the existing use case.

I should have a PR ready today for this.

**Comment by nedtwigg** [comment]
Released in 2.4.1, available on gradle plugin portal and jcenter, but not yet mavencentral do to a sync error.  It'll get to mavencentral eventually...

**Comment by nedtwigg** [comment]
Just made it to mavencentral.
