### ISSUE TITLE
Adopt the latest Gradle APIs

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#601]
There are three main tasks here:

- https://github.com/diffplug/spotless/blob/ca5f50debcd79948831216f2be3c58af9c940c85/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessTaskModern.java#L40
- https://github.com/diffplug/spotless/blob/ca5f50debcd79948831216f2be3c58af9c940c85/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionModern.java#L47-L48

Each TODO can be implemented independently, and should probably be in a separate PR (the bottom two could maybe be in one PR).  As detailed in #600, this code is tested by `:plugin-gradle:modernTest`, and is not yet being used by end-users, though it is possible to opt-in with `-PspotlessModern=true`.

PRs welcome!

**Comment by bigdaz** [comment]
FYI I'm working on these.

**Comment by nedtwigg** [comment]
From the [migration guide for Gradle 6.5](https://docs.gradle.org/current/userguide/upgrading_version_6.html#abstract_task_deprecated):

> `AbstractTask` is an internal class which is visible on the public API, as a superclass of public type `DefaultTask`.  `AbstractTask will be removed in Gradle 7.0`

Will its public methods become part of `DefaultTask`?  We haven't upgraded the gradle wrapper to 6.5 in the spotless build yet (feel free to do so if you'd like in any modernization PR), but in other projects I'm getting deprecation warnings around calls to `getProject()` and `getInputs()`, which I guess will need to get injected into the constructor now?

**Comment by big-guy** [comment]
@nedtwigg do you have particular APIs in mind? I think everything that needs to be public is a part of the [Task](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html) interface.  Part of the reason to remove AbstractTask is to reduce places where internal interfaces leak into the public API (e.g., AbstractTask overrides getInputs to specialize the return type with an internal type). 

Do you have any examples of deprecations to getProject or getInputs? Is that in the IDE?

Eventually something like tasks won't have direct access to the Project, but that's going to be awhile and the current way will keep working for some time.

**Comment by nedtwigg** [comment]
Aha, I pretty much only care about `getProject()` and `getInputs()`, which are both in Task.  Yeah, the deprecations I'm seeing are in Eclipse, e.g.

<img width="370" alt="Screen Shot 2020-06-09 at 12 56 59 PM" src="https://user-images.githubusercontent.com/2924992/84193726-bf313480-aa50-11ea-9e66-f0a5bb71b767.png">

I can resolve the warnings with `((Task) this)`, but I'll probably just leave them be.

**Comment by nedtwigg** [comment]
The three todo's that we outlined in the top of this issue are now all complete.  The only remaining items I can see are:

- switching to `Provider<>` in the `FormatExtension` (discussed [here](https://github.com/diffplug/spotless/pull/618#issuecomment-646738282))
- using `Worker` to make within-project execution parallel
  - requires us to bump minimum from 5.4 to 5.6, not a big deal, and the worker api is still incubating
  - I think we're pretty darn thread safe already, so the Worker transition should be relatively painless if anybody wants to make it

If anyone wants to explore the `Provider` approach, I'm happy to allow time for that.  Otherwise, I think we can safely say that `-PspotlessModern=true` is getting all the performance advantages that are allowed by the very latest version of Gradle, and close out this issue.

**Comment by nedtwigg** [comment]
All of the above has been released in `4.4.0`.
