### ISSUE TITLE
scala doc wrong

### ISSUE THREAD

**Issue by jxnu-liguobin** [diffplug/spotless#609]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem
Scala document breaks through after formatting
- [ ] gradle or maven version
5.3.1
- [ ] spotless version
2.5.2
- [ ] operating system and version
OSX 10.14.4 (18E227)
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
no error message
![image](https://user-images.githubusercontent.com/29496873/84143271-dd1a8b80-aa88-11ea-9503-7af74394cb87.png)

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment]
Spotless `2.5.2` is very old, try updating to the latest `4.3.0`.  Also, we just call out to [scalafmt](https://github.com/olafurpg/scalafmt), so you'll have to report the bug there.  Best to make sure you're using the latest version of everything first :)

**Comment by jxnu-liguobin** [comment]
sorry 2.5.2 is scalafmt version, maybe is a scalafmt's bug

**Comment by nedtwigg** [comment]
Ah.  Yes, it is definitely a scalafmt bug.
