### ISSUE TITLE
Allow passing the formatJavadoc flag to Google Java Formatter

### ISSUE THREAD

**Issue by coyotesqrl** [diffplug/spotless#614]
Back in November, the Google Java Formatter was updated to support turning off formatting of javadocs. This is particularly useful functionality with newer javadoc trends as well as older codebases that include heterogenous license headers.

Here is the PR that added the functionality: google/google-java-format#418

**Comment by nedtwigg** [comment]
Happy to take a PR for this (useful guide pr: https://github.com/diffplug/spotless/pull/193).

If you'd like to gradually unify the license headers, without ever having a history-clobbering "format-the-world" moment, maybe try [`ratchetFrom 'origin/main'`](https://github.com/diffplug/spotless/tree/main/plugin-gradle#ratchet).

**Comment by fcurts** [comment]
Is there a workaround/hack for this? We can't adopt the Google formatter without this, as it unnecessarily changes the Javadoc in our entire codebase.

**Comment by nedtwigg** [comment]
The PR referenced above (#193) is a very similar situation. To my knowledge, no workaround besides a PR.

**Comment by fcurts** [comment]
Is it possible to support a generic way to pass options so that users aren't blocked every time a new option is added?

**Comment by nedtwigg** [comment]
Maybe! PR's welcome :)

**Comment by Goooler** [comment]
Closed by #1793.
