### ISSUE TITLE
licenseHeaderStep is never up to date

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#64]
One of the simplest rules we have!  Very interesting.  Working on it in the `licenseHeaderStepUpToDate` branch, I'll report any findings here.

**Comment by nedtwigg** [comment]
Totally baffled.  All the elements in the list claim to be equal, but the list claims that it is not equal.  But only for the LicenseHeaderStep.  :-/

**Comment by nedtwigg** [comment]
Ahaaa!!  Equality problems in FilterByFileFormatterStep, which was missing an equality() test.  Fixing now...

**Comment by jbduncan** [comment]
:tada: :tada: :tada:
