### ISSUE TITLE
[google-java-format] Annotation format on Java class attributes

### ISSUE THREAD

**Issue by antero** [diffplug/spotless#652]
Hi there!

Firstly, thanks for this awesome plugin!

I'm using spotless 5.1.0 with GJF version 1.8. When I apply GJF, the following code:
```
    @Inject
    @RestClient
    private LoginClient loginClient;
```
Becomes this:
```
  @Inject @RestClient private LoginClient loginClient;
```

Is there a way to prevent the annotations collapsing to the same line?

**Comment by nedtwigg** [comment]
The `eclipse()` formatter has a zillion config options, and it can definitely do that.  The point of `googleJavaFormat()` is to have no config options.  If you're a regex wizard, you might be able to get something like the following to work (below is definitely broken)

```gradle
googleJavaFormat()
replaceRegex 'rearrange one annotation', '^(\w+)@(^\w+) (^@^\w+)', '$1@$2\n$1$3'
replaceRegex 'rearrange one annotation', '^(\w+)@(^\w+) @(^\w+) (^@^\w+)', '$1@$2\n$1@$3\n$1$4'
