### ISSUE TITLE
Gradle plugin: `removeFormat "java"` is broken in 5.x

### ISSUE THREAD

**Issue by jduan** [diffplug/spotless#653]
I have a Gradle multiple project setup and I'm trying to upgrade the spotless plugin (https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless) from 3.24.2 to the latest version and I'm running into issues.

My setup looks like this:
* In the root build.gradle file, we apply the spotless plugin and configure "spotless" for each subproject like this:

```
    spotless {
      ratchetFrom 'origin/main'
      enforceCheck = false
      java {
        target 'src/**/*.java'
        googleJavaFormat('1.4')
      }
      kotlin {
        target 'src/**/*.kt'
        ktlint('0.32.0')
      }
    }
```
* Subprojects are owned by different teams and some of them want to configure spotless in their own projects' build.gradle file, eg:

```
spotless {
  removeFormat "java"
  java {
    target 'src/**/*.java'
    googleJavaFormat('1.7')
  }
}
```

This all works for version 3.24.2. However, it fails with the following error starting from version 3.25.0:

```
* What went wrong:
A problem occurred evaluating project ':projects:charisma'.
> Cannot add task 'spotlessJava' as a task with that name already exists.
```

This change looks suspicious: https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md#3250---2019-10-06 but I don't fully understand it.

Can someone take a look?

- [x] summary of problem
- [x] gradle or maven version: Gradle 6.2.1
- [x] spotless version: trying to upgrade to 3.24.2 to 5.1.0
- [x] operating system and version: macOS 10.15.6
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment]
Ah, yes.  It looks like `removeFormat` is completely broken in our latest release.  It's a bit tricky to restore it, but definitely possible.

https://github.com/diffplug/spotless/blob/43e4e97bb31f68bed6a751d40202f4e7fcaca175/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtension.java#L219-L223

As a workaround, rather than calling `removeFormat`, you could use `clearSteps()` to achieve the same thing, e.g. in a subproject:

```gradle
spotless {
  // removeFormat "java" (don't do this)
  java {
    clearSteps() // do this instead, same effect except it doesn't wipe out the target
    target 'src/**/*.java'
    googleJavaFormat('1.7')
  }
}
```

**Comment by jduan** [comment]
Hi @nedtwigg thanks for the quick response. I'll give that a try and report back.

**Comment by jduan** [comment]
@nedtwigg I confirmed that your suggestion worked! Thanks again for your prompt response!

**Comment by nedtwigg** [comment]
Thanks for the clean bug report!  Is definitely a bug, and we should either fix it or remove the method in 6.x.  Not high priority, but I'm gonna leave this open until we get around to one or the other.
