### ISSUE TITLE
Documentation is confusing for Kotlin (groovy vs kotlin for buildscript language)

### ISSUE THREAD

**Issue by kenptr** [diffplug/spotless#659]
Please update documentation on using spotless. For kotlin, I had to use this to make it work:

```gradle
# File: top level build.gradle

plugins {
    id "com.diffplug.spotless" version "5.1.0"
}

spotless {
    kotlin {
        target '**/*.kt'
        ktlint()
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
    format 'misc', {
        target '**/*.gradle', '**/*.md', '**/.gitignore'
        indentWithSpaces()
        trimTrailingWhitespace()
        endWithNewline()
    }
}
```

**Comment by kenptr** [comment]
README.md suggests using `configure<com.diffplug.gradle.spotless.SpotlessExtension>`, but I couldn't make it work.

**Comment by nedtwigg** [comment]
It looks like your build file is called `build.gradle`, as opposed to `build.gradle.kts`, is that correct?

You raise a good point.  All of our documentation examples assume you are using the default groovy buildscript language (`build.gradle`), but we assume, without stating that assumption, that people who are formatting Kotlin code are also using it for their buildscript (`build.gradle.kts`).

**Comment by kenptr** [comment]
Yes, I was using build.gradle, without .kts extension. Thanks for the reply, Ned

**Comment by nedtwigg** [comment]
Can you take a look at #661?  Any other changes we could have made to make it more clear?

**Comment by nedtwigg** [comment]
Thanks for good feedback, always nice to know where our users get stuck.
