### ISSUE TITLE
spotlessCheck failed in Windows but not in linux

### ISSUE THREAD

**Issue by yinan-liu** [diffplug/spotless#66]
with the same spotless plugin applied, the project's build failed in Windows, but not in Linux, is it possible to have a log to check the issue? Could it be an issue of line ending characters? Please advise

**Comment by nedtwigg** [comment]
What version of spotless?  What does your `spotless` config block look like?

**Comment by nedtwigg** [comment]
The answer is probably in one of these:

- https://github.com/diffplug/spotless#line-endings-and-encodings-invisible-stuff
- https://github.com/diffplug/spotless/issues/49

**Comment by yinan-liu** [comment]
hi,
the version is 2.4.0, the config block is like

`
    spotless {
            java {
                target project.fileTree(project.rootDir) {
                    include '**/*.java'
                    exclude '**/package-info.java'
                    exclude '**/proactive.license.java'
                    exclude '.gradle/**/*.java'
                    exclude '**/generated/'
                }

                licenseHeaderFile   "$rootDir/gradle/ext/proactive.license.java"  // License header file

                importOrderFile     "$rootDir/gradle/ext/proactive.importorder"     // An import ordering file, exported from Eclipse

                eclipseFormatFile   "$rootDir/gradle/ext/ProactiveCodeFormatter.xml"    // XML file dumped out by the Eclipse formatter

                // Eclipse formatter puts excess whitespace after lambda blocks
                //    funcThatTakesLambdas(x -> {} , y -> {} )  // what Eclipse does
                //    funcThatTakesLambdas(x -> {}, y -> {})    // what I wish Eclipse did
                custom 'Lambda fix', { it.replace('} )', '})').replace('} ,', '},') }

                paddedCell()
            }

            format 'misc', {
                target project.fileTree(project.rootDir) {
                    include '**/.gitignore'
                    include '**/*.gradle'
                    include '**/*.md'
                    include '**/*.sh'
                    exclude 'gradle/ext'
                }
                indentWithSpaces()
                trimTrailingWhitespace()
                endWithNewline()
            }
        }
`
