### ISSUE TITLE
All examples seem to use old plugin without the plugin {} section with id {plugin} format

### ISSUE THREAD

**Issue by deanorderly** [diffplug/spotless#667]
I could not find an example of using the new plugin section with spotless and I ran into issue with just a basic build.gradle file as shown here

https://stackoverflow.com/questions/63442550/new-gradle-format-confusion-and-migrating-causes-could-not-find-method-testcompi

I do not know if this is a bug or am I misusing.  I looked through all those examples linked on spotless and can't find one with the newer plugin {} section.

**Comment by nedtwigg** [comment]
The answer you got on stackoverflow is correct.
