### ISSUE TITLE
Applying gradle plugin in init script

### ISSUE THREAD

**Issue by MarkusAmshove** [diffplug/spotless#680]
Hello,

I'm trying to apply `spottless` globally in my gradle builds via the Gradle init script (`$GRADLE_USER_HOME/init.gradle`).

After some googling, I've come to the following definition which should work according to a [thread in the Gradle forum](https://discuss.gradle.org/t/cannot-apply-plugin-by-id-in-init-gradle-script/30377)

```
initscript {
    repositories {
        maven {
            url  = 'http://corporateartifactory'
        }
    }
    dependencies {
        classpath 'com.diffplug.spotless:spotless-plugin-gradle:5.3.0'
    }
}
allprojects {
    apply plugin: com.diffplug.gradle.spotless.SpottlessPlugin

    spotless {
            java {
                removeUnusedImports()
                trimTrailingWhitespace()
                eclipse().configFile Paths.get("path", "to", "Formatter.xml").toFile()
                targetExclude 'src/main/gen/**/*.java'
            }
    }
}
```

The error in the output of any build is the same as in the forum:

```
Could not get unknown property 'com' for root project 'myproject' of type org.gradle.api.Project.
```

I'm using the package + class name of `SpottlessPlugin` from this repository, without any quotes.

Does anyone use spotless this way and can guide me to my problem? :-)

**Comment by nedtwigg** [comment]
I think you want `apply plugin: 'com.diffplug.spotless'`.

**Comment by MarkusAmshove** [comment]
Then I get the error `Plugin with id 'com.diffplug.spotless' not found.` as stated in the linked forum post.
The init script seems to want the actual qualified class name.

**Comment by MarkusAmshove** [comment]
Then I get the error `Plugin with id 'com.diffplug.spotless' not found.` as stated in the linked forum post.
The init script seems to want the actual qualified class name.

**Comment by DeflatedPickle** [comment]
I'm having a similar problem with the new plugin ID. When I use the old ID, it tells me to use the new ID. When I use the new ID, it can't be found. I'm not smart enough to fix it, so I'll be sticking with `4.5.1`. I hope this is fixed or figured out soon!

**Comment by nedtwigg** [comment]
@MarkusAmshove, your example has a typo, you put two `t`s in `Spotless`.  If you fix that, it should work.  This worked for me:

```gradle
initscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2' }
  }
  dependencies {
    classpath 'com.diffplug.spotless:spotless-plugin-gradle:5.3.0'
  }
}
allprojects {
  apply plugin: com.diffplug.gradle.spotless.SpotlessPlugin
}
```

@DeflatedPickle I think you're having a slightly different problem.  The example above works in `5.0+`.  In `4.x`, there are two plugins.  The old [`com.diffplug.gradle.spotless.SpotlessPlugin`](https://github.com/diffplug/spotless/blob/gradle/4.5.1/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessPlugin.java) and [`SpotlessPluginModern`](https://github.com/diffplug/spotless/blob/gradle/4.5.1/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessPluginModern.java).  Then in `5.0`, the "Modern" one became the only one.

For both of you, I'd be curious why you use Spotless in your init script rather than per-project.  I use `init.gradle` for the [versions plugin](https://github.com/ben-manes/gradle-versions-plugin), but it doesn't seem like a very useful place for Spotless.  Unless everyone on the team sets up their `init.gradle` exactly the same, which seems hard to do.

**Comment by DeflatedPickle** [comment]
@nedtwigg, I don't have `initscript` at all, sorry. My [project](https://github.com/DeflatedPickle/BugMagic/blob/21849b9fb0066ce9d4452002b155f2ca00ce48e0/build.gradle#L13) uses `buildscript`. Then [applies](https://github.com/DeflatedPickle/BugMagic/blob/21849b9fb0066ce9d4452002b155f2ca00ce48e0/build.gradle#L19) it, then I [use](https://github.com/DeflatedPickle/BugMagic/blob/21849b9fb0066ce9d4452002b155f2ca00ce48e0/build.gradle#L98-L112) Spotless.

When applying the new version, Gradle throws `Plugin with id 'com.diffplug.spotless' not found`, though it downloads fine.

**Comment by nedtwigg** [comment]
The id `com.diffplug.spotless` only exists in `5.0+`.  If you set the version to `5.3.0`, and then apply the new `com.diffplug.spotless` id, it should work.  If it doesn't, and you open a PR on your repository with that change, I'd be happy to take a look and figure out what's wrong.

**Comment by DeflatedPickle** [comment]
@nedtwigg, I am aware. When using `4.5.1`, a Gradle refresh will trigger Spotless to recommend I update to `5.3.0`. After changing the version to `5.3.0`, removing the `apply` and `spotless` block so it can download first, refreshing Gradle to invoke tge download, then re-adding the `apply` and `spotless` block after it's been downloaded, then I get the error.

I was initially notified of this update when `dependabot` [opened a PR](https://github.com/DeflatedPickle/BugMagic/pull/43) to update, which I pulled as soon as I saw. After pulling and fetching the update, then the error started to throw.

**Comment by nedtwigg** [comment]
The error I get in your repository when bumping the version to `5.3.0` is this:

```
A problem occurred evaluating root project 'BugMagic'.
> Failed to apply plugin [id 'com.diffplug.spotless']
   > Could not create an instance of type com.diffplug.gradle.spotless.SpotlessExtensionImpl_Decorated.
      > org.gradle.api.tasks.TaskContainer.register(Ljava/lang/String;Lorg/gradle/api/Action;)Lorg/gradle/api/tasks/TaskProvider;
```

That indicates that the Gradle version is too old.  Spotless 5.0 requires Gradle 5.4+, and you're on 4.8.  We should proactively warn in this case rather than failing with an obscure error, I opened #682 to track.

**Comment by DeflatedPickle** [comment]
@nedtwigg, I feel a bit idiotic for missing that. It wasn't obvious to me from the error that I needed to update Gradle. I'm sorry for making you figure this out, I feel really bad. Thank you for testing this and being so kind with expressing the solution!

**Comment by nedtwigg** [comment]
No worries, it's not your fault, it's ours.  Thanks for reporting, probably other people are hitting the same problem.  #682 will fix it.
