### ISSUE TITLE
Improve release notification

### ISSUE THREAD

**Issue by regrog** [diffplug/spotless#692]
Hello,
I usually check your GitHub repo to see if new release is come out.
In other repos I have a notification when a new version is out.
As I can see you only have tags in you repo:
![image](https://user-images.githubusercontent.com/7606880/92877252-4228a900-f40b-11ea-8668-9445e02caa36.png)
But as you can see in PMD repo for example you can have a better representation:
![image](https://user-images.githubusercontent.com/7606880/92877423-713f1a80-f40b-11ea-8b2d-1b86ce79739b.png)

I hope this link can be helpful : https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository
Thanks!

**Comment by nedtwigg** [comment]
Our release is completely automatic.  We click "publish" in CI, and it uploads jars, bumps the changelogs, tags the commits, etc.  We use our sister plugin spotless-changelog to do that, and it has an open issue (https://github.com/diffplug/spotless-changelog/issues/10) to integrate with GitHub's releases.  I'm not going to add any manual trudgery to our release process, but if we get a PR for spotless-changleog, we would immediately turn on that feature here.  Closing this, you can track completion by subscribing to the issue above.
