### ISSUE TITLE
Jgit is causing long execution time in GitLab Pipeline

### ISSUE THREAD

**Issue by MM-Hahn** [diffplug/spotless#726]
Hello :wave: 

we are using Spotless for our verification tasks in our Pipeline ~~and are experiencing long waiting times~~. This is only related when executing Spotless in a docker environment.

Gradle version: 6.5.1 (We got many projects with slightly different versions)
Spotless version: 3.27.1 & 5.7

Spot of issue in GitLab Pipeline:

```
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.2/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
locking FileBasedConfig[/root/.gitconfig] failed after 5 retries
```

After some research I found a corresponding bug from Jgit: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566170
The bug is now resolved with version 5.9.0.202009080501-r and spotless is using 5.8.0.202006091008-r

Are any others of you experiencing this issue? ~~The Pipeline stops for about 2 minutes at this point.~~

Possible workaround in Gradle:

```
buildscript {
    configurations.classpath {
        resolutionStrategy {
            force("org.eclipse.jgit:org.eclipse.jgit:5.9.0.202009080501-r")
        }
    }
}
```

**EDIT:**

This failure does not affect the execution time of the pipeline. Nevertheless it is an error and can be solved by updating jGit (like above).

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 5.8.1` and `plugin-maven 2.6.0`.
