### ISSUE TITLE
Maven scanning time issue for big projects

### ISSUE THREAD

**Issue by barmakoWS** [diffplug/spotless#729]
Hi,
I have a project that has a directory with an insane amount of code that I don't want spotless to consider (the code inside this directory is used as an input for some tests).
I'm providing spotless with an include/exclude configuration that should skip said directory.

Spotless takes over 90 seconds to complete.

I looked at the code for the maven plugin and it seems that the files spotless works on are computed by a 3rd party as follows:
https://github.com/diffplug/spotless/blob/48b5cb9e117b00e0ccd3a85c293f9c87c12eaf0f/plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java#L204-L210

`FileUtils.getFiles` is provided by org.codehaus.plexus:plexus-utils:3.0.8 which is a transitive dependency of org.codehaus.plexus:plexus-resources:1.0.1

I've checked to see if the problem comes from the plexus-utils, and indeed the folder scan is slow (probably doesn't skip entire directories).
This issue was fixed in a later version of plexus-utils and I verified that it works much faster when using its latest version  - 3.3.0

The direct dependency spotless uses (org.codehaus.plexus:plexus-resources:1.0.1) has a newer version (1.1.0) that uses org.codehaus.plexus:plexus-utils:3.0.22 - but it doesn't fix the issue.

I can suggest the following solutions:
1. Use another library to scan the `baseDir`
2. Override the used version of org.codehaus.plexus:plexus-utils to 3.3.0 - this is, of course, risky, as plexus-resources wasn't "compiled" against it

What are your thoughts?
I'd be happy to help with a PR if needed.

**Comment by nedtwigg** [comment]
That seems like a fine workaround to me. If you make the PR, I'd be happy to merge it and publish. We'll note the change in the changelog, and worst-case we can always revert it.

Our maven build is a bit tricky. Sounds like you already navigated it, but while you're in the guts of it, #554 is an option too.

**Comment by barmakoWS** [comment]
Thanks for your response and sorry for my late reply.
Great, I'll try to open a PR soon with that fix.

**Comment by nedtwigg** [comment]
Possibly fixed in `plugin-maven 2.6.1`. Please test and confirm.

**Comment by barmakoWS** [comment]
It solves my issue.
Thanks for the help!

**Comment by nedtwigg** [comment]
Huzzah!
