### ISSUE TITLE
Release of lib/2.10.0 did not lead to a release of the whole project

### ISSUE THREAD

**Issue by JakubStas** [diffplug/spotless#730]
Hi guys, I might be wrong, but it looks like the recent `.npmrc` related fix seems to have triggered the release that subsequently failed.

[CircleCI main](https://circleci.com/gh/diffplug/spotless/tree/main) see the build #4399

If the feature is ready to be used, can you please release `spotless` again to include it? Thanks!

**Comment by nedtwigg** [comment]
Thanks, you are correct. Just released `plugin-gradle 5.8.0`. About to fix a few small things then release `5.8.1` and also the maven plugin.
