### ISSUE TITLE
ktlint rule violation name

### ISSUE THREAD

**Issue by afaucogney** [diffplug/spotless#738]
I tried to use spotless (not so straight forward). I setup for kotlin with ktlin.
I detect a violation with the Check task. This violation come from ktlint, and I accept it on my projet. How can I get the name of the rule ? There is nothing in the log.

**Comment by nedtwigg** [comment]
I'm not sure, but it sounds like it is not supported right now, and would require adding a new feature. I might suggest `ktfmt` instead, [see here](https://github.com/diffplug/spotless/issues/719#issuecomment-710270652) for more info.
