### ISSUE TITLE
spotlessApply doesn't seem to be applying regardless of conditions

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#739]
```
> yarn gradle --version                                                                                                                                                       # ppm -> 2-authentication !

------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.8 (AdoptOpenJDK 11.0.8+10)
OS:           Mac OS X 10.16 x86_64
```

```
"com.diffplug.spotless:spotless-plugin-gradle:5.8.2"
```

```
val header = "Copyright © \$YEAR Caleb Cushing. All rights reserved"
spotless {
  format("misc") {
    target("*.ts", "*.java", "*.scss", "*.css")
    licenseHeader("/* $header */", "")
  }
```
is not adding headers to java files (or probably any, but java has all I've tried) coudl be misusage of delimiter, it is not well documented, I was unable to find any examples of its usage. This is probably just a doc bug to fix that.

works fine with

```
spotless {
  ratchetFrom = "HEAD"
  java {
    licenseHeader("/* $header */")
  }
```

**Comment by nedtwigg** [comment]
You probably need `src/**/*.ts`. If you just do `*.ts`, that will only apply to files in the root directory. See [project.fileTree](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#fileTree-java.lang.Object-) for more info.

> could be misusage of delimiter

Yep, each language will need its own delimiter. It is used to identify the top of the file, [see javadoc](https://javadoc.io/doc/com.diffplug.spotless/spotless-plugin-gradle/5.6.1/index.html).

Our built-ins:

- java https://github.com/diffplug/spotless/blob/d9474fbffb03cfa1f54c55b8c3beebe81cd7611a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java#L46-L53
- cpp https://github.com/diffplug/spotless/blob/d9474fbffb03cfa1f54c55b8c3beebe81cd7611a/lib/src/main/java/com/diffplug/spotless/cpp/CppDefaults.java#L26-L42
- antlr4 https://github.com/diffplug/spotless/blob/d9474fbffb03cfa1f54c55b8c3beebe81cd7611a/lib/src/main/java/com/diffplug/spotless/antlr4/Antlr4Defaults.java#L19
- kotlin https://github.com/diffplug/spotless/blob/d9474fbffb03cfa1f54c55b8c3beebe81cd7611a/lib/src/main/java/com/diffplug/spotless/kotlin/KotlinConstants.java#L21

And here is a user-delimiter that a project is using for typescript:
- https://github.com/mytakedotorg/mtdo/blob/53f3be668719a03a250ca4077ad1cae2448d72b1/client/build.gradle#L11-L12
