### ISSUE TITLE
com.google.googlejavaformat.java.FormatterException: error: Imports not contiguous (perhaps a comment separates them?)

### ISSUE THREAD

**Issue by varununnikrishnan** [diffplug/spotless#742]
Execution default-cli of goa
l com.cosium.code:git-code-format-maven-plugin:2.4:format-code failed: com.google.googlejavaformat.java.FormatterException: error: Imports not contiguous (perhaps
a comment separates them?

**Comment by jbduncan** [comment]
@varununnikrishnan  That looks like a known problem of google-java-format to me; one of things it does is it sorts your imports for you, but it doesn't know how to do so if your imports have a comment in between. Where should it place the comment after it's sorted the imports? Above the import it was right above before sorting? Or how about below? Basically, it doesn't know what your intention for writing that comment was, so it "yells" and stops.

The solution is to either remove the comment, or place it below your imports section and expand the comment to explain which import line it's referring to.

Sorry I couldn't find you a more satisfying answer. :(

That being said, feel free to reopen if I've misunderstood the problem.

**Comment by varununnikrishnan** [comment]
I will check with this approach and update you.

**Comment by varununnikrishnan** [comment]
Thank you for the faster updates.

**Comment by varununnikrishnan** [comment]
The approach make sense to me. Thank you.

**Comment by jbduncan** [comment]
Excellent, glad to hear that!
