### ISSUE TITLE
googleJavaFormat naming conventions not being enforced

### ISSUE THREAD

**Issue by MelanieBrett** [diffplug/spotless#743]
I'm trying to implement Spotless but finding that it doesn't detect incorrect naming conventions as per the [google style guide](https://checkstyle.sourceforge.io/styleguides/google-java-style-20180523/javaguide.html#s5-naming) eg. naming a variable in camel case or a method in upper-letters.

Does spotless support this feature and should it be enforcing these rules? If not how could I modify it to do so?

**Comment by nedtwigg** [comment]
There is a difference between a formatting error which can be easily fixed locally (e.g. indentation) versus one which requires a widespread refactor which might affect multiple files (e.g. naming conventions). Read [this comment](https://github.com/diffplug/spotless/issues/719#issuecomment-710270652) for more info.

That said, if you want Spotless to enforce naming conventions, that is possible. You have three paths:

1. add a feature to https://github.com/google/google-java-format
2. add a custom step inside a buildscript https://github.com/diffplug/spotless/tree/main/plugin-gradle#custom-steps
3. create a new step https://github.com/diffplug/spotless/blob/main/CONTRIBUTING.md
