### ISSUE TITLE
Ktlint 0.4.0 not formatting code

### ISSUE THREAD

**Issue by tobi6112** [diffplug/spotless#745]
If you are submitting a **bug**, please include the following:

- [x] summary of problem: 

Ktlint 0.4.0 is not formatting the code.

- [x] gradle or maven version
- [x] operating system and version

```
❯ gradle -v

------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.9 (AdoptOpenJDK 11.0.9+11)
OS:           Windows 10 10.0 amd64
```

- [x] spotless version

id("com.diffplug.spotless") version "5.8.2"

- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```kts
spotless {
    //ratchetFrom("origin/master")
    encoding("UTF-8")
    lineEndings = com.diffplug.spotless.LineEnding.UNIX

    kotlin {
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
        ktlint().userData(
            mapOf(
                "indent_size" to "2",
                "continuation_indent_size" to "2",
                "max_line_length" to "120"
            )
        )
    }
}
```

- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

No error thrown. Build successful

**Comment by nedtwigg** [comment]
Try setting the target explicitly.  `kotlin { target 'src/**/*.kt' `
