### ISSUE TITLE
`ratchetFrom` not working in git-submodule

### ISSUE THREAD

**Issue by conderls** [diffplug/spotless#746]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
`ratchetFrom` not working if current project is a git-submodule. if `<ratchetFrom>origin/master</ratchetFrom>` section is set, nothing happended. But if the `<ratchetFrom>` is removed, everything works fine.
- [x] gradle or maven version
maven 3.6.5
- [x] spotless version
2.6.1
- [x] operating system and version
Mac

there is no `.git` dir in git-submodule which is presented in parent module directory. Is It parsing and filter modified files using `./.git` directory?

**Comment by conderls** [comment]
BTW, why not using 'origin/master' instead of 'origin/main' by default.

**Comment by nedtwigg** [comment]
Interesting... I thought that we did support submodule, but we don't have a test for that, so not too surprised if it is broken. This is probably where the bug lives, PR's welcome.

https://github.com/diffplug/spotless/blob/d9474fbffb03cfa1f54c55b8c3beebe81cd7611a/lib-extra/src/main/java/com/diffplug/spotless/extra/GitRatchet.java#L201-L228

> why not using 'origin/master' instead of 'origin/main'

https://www.infoq.com/news/2020/10/github-main-branch/

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle 5.9.0` and `plugin-maven 2.7.0`, can you confirm?

**Comment by nedtwigg** [comment]
Bump.
