### ISSUE TITLE
spotless:check is not bound to the verify phase by default

### ISSUE THREAD

**Issue by emmberk** [diffplug/spotless#749]
The documentation says
> By default, `spotless:check` is bound to the `verify` phase.

https://github.com/diffplug/spotless/tree/maven/2.6.1/plugin-maven#disabling-warnings-and-error-messages

`mvn spotless:apply` and `mvn spotless:check` work, but `mvn install` does not fail if there are formatting errors in a java file.

```xml
<build>
    <plugins>
        <plugin>
            <groupId>com.diffplug.spotless</groupId>
            <artifactId>spotless-maven-plugin</artifactId>
            <version>2.6.1</version>
            <configuration>
                <java>
                    <googleJavaFormat/>
                </java>
            </configuration>
        </plugin>
        ...
    </plugins>
</build>
```

Work-around: manually binding `check` to the `verify` phase appears to fix the issue.
```xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.6.1</version>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
            <phase>verify</phase>
        </execution>
    </executions>
    <configuration>
        ...
    </configuration>
</plugin>
```

```
$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
...
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by jordanwilking** [comment]
Same issue with the same code, but on Windows:

```
PS> mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
...
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by nedtwigg** [comment]
Thanks for reporting and workaround! I'm not a maven expert, but I think this is where we (attempt to) bind to the verify phase by default:

https://github.com/diffplug/spotless/blob/75fdd3ece5857687a05d0259df66f4de4661dabc/plugin-maven/src/main/java/com/diffplug/spotless/maven/SpotlessCheckMojo.java#L36-L37

Not sure why it isn't working, PR's welcome!

**Comment by setu9760** [comment]
I don't think this is a code bug but rather a documentation update and a bit of misunderstanding of how the `defaultPhase` is supposed to behave. Adding `defaultPhase = LifecyclePhase.VERIFY` to `Mojo` annotation does NOT mean that specific mojo will be run when `mvn verify` is run. It means if you have specified that goal in plugin definition than the goal will be bound to the give phase automatically. 

For this specific scenario the plugin definition still needs to have the execution > goals section like below;

```
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
            <!--  <phase>verify</phase> --> <!-- This is no longer required with defaultPhase in Mojo -->
        </execution>
    </executions>
```

Some stackoverflow threads discussing similar and explaining how `defaultPhase` works;
https://stackoverflow.com/questions/5732828/how-to-define-a-default-mojo-for-a-maven-plugin
https://stackoverflow.com/questions/31968685/binding-a-custom-maven-plugin-to-a-default-phase
https://stackoverflow.com/questions/26607834/maven-lifecycle-vs-phase-vs-plugin-vs-goal

**Comment by nedtwigg** [comment]
PR's welcome, either to code or docs :)

**Comment by nedtwigg** [comment]
Thanks @setu9760 for the PR. @emmberk, @jordanwilking thanks for raising the issue! Do [these new docs](https://github.com/diffplug/spotless/tree/main/plugin-maven#binding-to-maven-phase) clarify the issue, or are more changes needed?
