### ISSUE TITLE
Document how to enable the android flag in ktlint

### ISSUE THREAD

**Issue by JoseAlcerreca** [diffplug/spotless#750]
It took me a while to find (in a [gitter conversation](https://gitter.im/diffplug/spotless?at=5d068304a8d9871b329b49df)) how to pass the `--android` flag to ktlint, so I don't think it's documented.

groovy: `ktlint(Versions.ktlint).userData([android: "true"])`

**Comment by nedtwigg** [comment]
Here is how it is documented currently. Happy to take a PR which changes the example:

https://github.com/diffplug/spotless/tree/main/plugin-gradle#ktlint

Note that the example is a `build.gradle.kts`, whereas it looks like you might be using `build.gradle`?

**Comment by JoseAlcerreca** [comment]
That documents how to pass .editorconfig settings to ktlint but the --android flag is a command line parameter so I assume this is a spotless feature. Maybe it's also an editorconfig setting? It's not documented [either](https://github.com/pinterest/ktlint#editorconfig).

**Comment by nedtwigg** [comment]
It's not just for "editorConfig" or "commandLine", it's for "userData" generally. Agreed that it's not clear what the exact mapping for various ktlint options to "userData" is.
