### ISSUE TITLE
Improve how to apply spotless plugin

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [diffplug/spotless#755]
I usually apply Gradle plugins creating precompiled plugins with all the config and using them in the root build.gradle.kts file (if the plugin supports multimodule/multiproject setup out of the box like `Dokka` or `Detekt` plugins. Example of what I want to get:

```
// buildSrc/.../Spotless.gradle.kts
plugins {
    id("com.diffplug.spotless")
}

spotless {
    kotlin {
        target("src/**/*.kt", "src/**/*.kts")
        ktfmt("0.18").dropboxStyle()
    }
}
```

```
// build.gradle.kts (root folder)
plugins {
    Dokka
    Spotless
}
```

But it doesn't work, I have to use it inside allproject:
```
// build.gradle.kts (root folder)
allprojects {
    apply<SpotlessPlugin>()
}
```

Meanwhile, with other plugins, I can simply apply them so:

```
// build.gradle.kts (root folder)
plugins {
    Dokka
    Detekt
}
```

**Comment by nedtwigg** [comment]
The default behavior of Spotless is to apply itself only to the project to which it is applied. If I understand correctly, you want the default behavior to be that Spotless applies itself to every project automatically?

**Comment by JavierSegoviaCordoba** [comment]
Yeah, for example, Dokka or Detekt can be applied manually in each project, in their build.gradle.kts, but if you want to apply it globally to all modules, you can use them inside the main `plugins` block instead of using `allproject` block.

Maybe reading Detekt docs can explain it better than me https://detekt.github.io/detekt/howto-buildupondefaultconfig.html

**Comment by nedtwigg** [comment]
Dokka and Detekt are both kotlin-focused, but Spotless is polyglot. For example, I have a gradle build with some C/C++ native code in one subproject, lots of java subprojects, a few typescript/sass subprojects, and a markdown subproject. It doesn't make any sense to apply a "global" spotless to all of these.

But you can make a "SpotlessGlobal" which does "allprojects {}" internally if you want. A nice property of granular designs is that anybody can ball them up into bigger things if they want.

**Comment by ColtonIdle** [comment]
@nedtwigg I currently have this setup as such. This is in my root build.gradle and I have 30 modules

```
plugins {
    id("com.diffplug.spotless") version "5.12.4"
}

configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target(target("**/*.kt", "**/*.kts"))
        ktfmt("0.24").dropboxStyle()
    }
}
```

Running `./gradlew :spotlessApply` works as I expected... across ALL 30 modules. 

@nedtwigg reading your response in this thread though makes it seem like this should not work. Am I doing something wrong, or did something changes since Dec of 2020?
