### ISSUE TITLE
less verbose spotless check

### ISSUE THREAD

**Issue by maxandersen** [diffplug/spotless#762]
when build fails with spotless check fails it always includes the full dump of the differences.

Gets tedious to scroll through in github action ci pages ;)

Is it possible to have it (maybe its just gradle integration?) just print the file names without the full diff and the sometimes milelong stacktrace ?

**Comment by nedtwigg** [comment]
Prrrobably not. The point of Spotless is "just run spotlessApply and fix it". We *could* add a flag, but now there's one more paragraph of documentation, and one more feature to test and keep working, and how does that new feature interact with other planned features like #655.

One workaround for the workflow you seem to want is [this](https://github.com/diffplug/spotless/tree/main/plugin-gradle#how-do-i-preview-what-spotlessapply-will-do).

If you use Spotless for a couple weeks and still want it, come back with a PR that adds documentation for what you want (don't bother implementing). If the docs make sense, then we'll be open to implementing it.

**Comment by maxandersen** [comment]
I've been using spotless a year by now. 

It's generating massively long stack traces / info logs. 

that's why I reported it as it's tedious to have this much log generated just to say one file was missed.

**Comment by maxandersen** [comment]
I'll try find docs pr for it.
