### ISSUE TITLE
How can I configure line length in Java?

### ISSUE THREAD

**Issue by H00fie** [diffplug/spotless#763]
Hello,

So I already found a thread about the issue, but I fail to understand the solution.

I understand that googleJavaFormat will not allow me to modify the length of the lines of my code and I need to rely on eclipse formatter.
@nedtwigg provided an answer saying that below are keys I should care about:
```
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="999"/>
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="999"/>
```
My problem is when I implement these and try to build the project... it says that "setting" does not exist at all. I also keep failing while trying to make my project use an external XML file to configure the length of the lines:
```
<configuration>
                    <java>
                        <eclipse>
                            <version>4.13.0</version>
                            <file>${basedir}/muh-code-style.xml</file>
                        </eclipse>
                        <removeUnusedImports/>
                    </java>
</configuration>
```
Any idea what I am doing wrong? All I want is to set a column limit at around 140.

**Comment by nedtwigg** [comment]
We'll probably need a full stacktrace and a repo that reproduces the issue.
