### ISSUE TITLE
Default config results in: No value has been specified for property

### ISSUE THREAD

**Issue by aloifolia** [diffplug/spotless#782]
I configured spotless for gradle according to the docs by copy pasting the Quickstart config. This results in the following error message for each registered spotless task:

```
Some problems were found with the configuration of task ':spotlessMisc' (type 'SpotlessTaskImpl').
> No value has been specified for property 'lineEndingsPolicy'.
> No value has been specified for property 'target'.
```

For the record: simpler configs also don't work, e.g.:

```gradle
spotless {
  java {
    googleJavaFormat('1.8').aosp()
  }
}
```

I am using gradle 6.7.

**Comment by nedtwigg** [comment]
If you add `apply plugin: 'java'` then your example should work, and it will slurp the `target` from the java sourceset. If you don't apply the java plugin, then you have to specify `target 'src/**/*.java'` or something like that.

Each Spotless format needs to have a target. Some of the language-specific formats have defaults based on built-in Gradle features, but some don't. The exact behavior for each language are specified in the docs, e.g. [for java](https://github.com/diffplug/spotless/tree/main/plugin-gradle#java)

> The target is usually inferred automatically from the java source sets. However, Spotless cannot automatically detect android or java-gradle-plugin sources, but you can fix this easily...

**Comment by aloifolia** [comment]
Well, this does not change anything for me.  I tried both "apply..." and setting the target explititly. Also, note that I used the Quickstart solution first, which has a misc task with an explicit target.

Do I need to wrap the spotless configuration somehow? Does spotless have some specific requirements that I might have missed?

**Comment by scott-avery** [comment]
One more situation, when you apply two plugins simultaneously, it shows the same error.
```
plugins {
    id("com.diffplug.spotless") version "6.25.0"
    id("com.palantir.java-format-spotless") version "2.39.0" // NOT REQUIRED
}
```
