### ISSUE TITLE
how to migrate regexp from gradle to maven?

### ISSUE THREAD

**Issue by cal101** [diffplug/spotless#785]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem
- [ ] gradle or maven version
- [ ] spotless version
- [ ] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

How do I translate the following from gradle to maven?

`                replaceRegex 'Remove empty lines at end of block (1)', '\\n[\\n]+(\\s*})(?=\\n)', '\n$1'`

I am not able to translate the newline matches/replacement to mavens XML.

**Comment by nedtwigg** [comment]
Try this: https://stackoverflow.com/questions/10917555/adding-a-new-line-break-tag-in-xml
