### ISSUE TITLE
Argument passed to spotlessIdeHook must be an absolute path

### ISSUE THREAD

**Issue by aloifolia** [diffplug/spotless#790]
I am using spotless in combination with lint-staged in order to have automatically formatted files after each commit. When I trigger spotless manually, everything seems to work als expected:

```
./gradlew spotlessApply -PspotlessIdeHook="D:/path/to/package.json"
```

This results in a new change with perfect formatting. If, however, the exact same command is triggered by lint-staged (which is visible in the logs), I get an error message:

```
ℹ ./gradlew spotlessApply -PspotlessIdeHook="D:/path/to/package.json":
Argument passed to spotlessIdeHook must be an absolute path
```

As you can see, I am working on a Windows machine. Now, since I am combining spotless with lint-staged I might need to consult the lint-staged developers. However, since I see the command in the logs, I am wondering, how spotless resolves paths.

Just in case, this is my lint-staged configuration file:

```js
module.exports = {
    '*.{js,scss,md,ts,json,yml,yaml,html,java}': (filenames) => 
      filenames.map((filename) => `./gradlew spotlessApply -PspotlessIdeHook="${filename}"`),
}
```

**Comment by nedtwigg** [comment]
> ./gradlew spotlessApply -PspotlessIdeHook="D:/path/to/package.json":

Can you copy an actual line, unchanged? I suspect escaping issues. Maybe the quotes need to go to the outside, e.g. `"-PspotlessIdeHook=blah blah blah"`

> how spotless resolves paths

It doesn't, it requires an absolute path:

https://github.com/diffplug/spotless/blob/cd849828bf6548a598c22849271ac74911dc2078/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/IdeHook.java#L37-L42

**Comment by aloifolia** [comment]
Your intuition was on spot. With the slightly changed quotes, lint-staged works as expected. Thanks!
