### ISSUE TITLE
Prettier does not lint and apply XML rules

### ISSUE THREAD

**Issue by bmarwell** [diffplug/spotless#792]
If you are submitting a **bug**, please include the following:

- [X] summary of problem
  Prettier does not lint and apply XML rules
- [X] gradle or maven version
  any, using mvn 3.6.3
- [X] spotless version
  latest, 2.7.0
- [X] operating system and version
  any, Linux mostly
- [X] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
  sure, https://github.com/scms/scms/tree/72-spotless-xml. The config is in the main `pom.xml` which is not nicely indented as well.
  Keep an eye on the `<formats>` section where I configured XML.
  Also tried some recommendations from gitter without any luck.
- [X] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
  none. Thats the problem I am facing!

**Comment by bmarwell** [comment]
Hi @nedtwigg are you sure this is a question and not a bug?

**Comment by nedtwigg** [comment]
Nope, not sure! I suspect that it is not a bug, but it could be, and I'm happy to mark it as such :)

**Comment by nedtwigg** [comment]
There are two places the problem can be.

1) Spotless might not be formatting the files you expect
2) The prettier xml formatter might not be doing what you expect

The easiest way to test theory is 1 is to add the [`replace`](https://github.com/diffplug/spotless/tree/main/plugin-maven#generic-steps) step. For example, you could replace space with `X`, and then you can see which files changed.  This proves that Spotless is applying to the files you expect.

If you know that Spotless is applying to the files you want, then you will be able to tell if prettier does what you want. If it doesn't, then that is an issue for prettier or prettier-xml. But you want to dig in to the Spotless part of the code, it is [here](https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/npm/PrettierFormatterStep.java).

**Comment by bmarwell** [comment]
Thanks for not helping. I asked a few times in gitter how to debug (i.e. see) which files are actually touched and handled over to the javascript plugin. I never received a reply. Too bad.

But if adding random chars is your preferred method of debugging, this plugin is not the right tool for me anyway. Sorry to say that. I usually take other people's example projects and turn them into ITs. Would have loved to help  you with that. But when noone ever replies, this is hard to contribute.

That said, thanks anyway. If this plugin works, it works like a charm. Will look for something else for XML then.
