### ISSUE TITLE
spotless diverges after x steps

### ISSUE THREAD

**Issue by benzen** [diffplug/spotless#793]
Using eclipse formatter, spotless 5.9.0, gradle 6.5 on macos.

For some html files spotless complains that it diverge after 10 steps.

I have no clue what is ment by diverge.

Here is my config for elicpse formatter

```
eclipse.preferences.version=1
indentationChar=space
indentationSize=4

alignEndBracket=false
# inlineElements=small,big,sub,img,strong,basefont,title,sup,br,abbr,b,acronym,strike,em,i,label,td,input,q,s,th,u,cite,li,font,
inlineElements=
lineWidth=100
splitMultiAttrs=true
```

**Comment by benzen** [comment]
What should i do next ?

**Comment by nedtwigg** [comment]
It means this: https://github.com/diffplug/spotless/blob/main/PADDEDCELL.md

You could file a bug with the eclipse HTML formatter, or you could workaround by ignoring the warning, or changing the file so that it doesn't trigger the divergence.

**Comment by snimavat** [comment]
I am facing the same issue with IntelliJ and groovy files.
The above comments doesnt give clue on how "changing the file" could fix it... what needs to be changed ?
