### ISSUE TITLE
Spotless Gradle plugin breaks the `clean` task when Gradle's configuration cache is enabled

### ISSUE THREAD

**Issue by eskatos** [diffplug/spotless#796]
Using the project at execution time is not allowed when Gradle's configuration cache is enabled.

The spotless plugin registers a `doLast` task action on the `clean` task that accesses the project at execution time. The effect
of this is to break using the `clean` task on all builds that have the spotless plugin applied when Gradle's configuration cache is enabled.

Also see https://github.com/diffplug/spotless/issues/644 which is about having full support of Gradle's configuration cache in the Spotless plugin. This issue is only about not preventing to use the `clean` tasks on builds that have the Spotless plugin applied.

**Comment by nedtwigg** [comment]
Thanks for the issue and PR! Fixed in `5.10.1`.

**Comment by eskatos** [comment]
Thank you for the quick turnaround!
