### ISSUE TITLE
The POM project URLs are broken and 404s

### ISSUE THREAD

**Issue by davidburstrom** [diffplug/spotless#798]
The published POMs have broken project URLs as they refer to `<url>https://github.com/diffplug/project</url>` instead of `<url>https://github.com/diffplug/spotless</url>`, e.g. [POM for Gradle plugin 5.10.1](https://repo1.maven.org/maven2/com/diffplug/spotless/spotless-plugin-gradle/5.10.1/spotless-plugin-gradle-5.10.1.pom). This also applies for the SCM entry in each POM.

The problem arises because the `rootProject` name is deduced by the parent directory name and is then referenced from https://github.com/diffplug/spotless/blob/e3a35d89a73fec7f378769a9950b5f689359449e/gradle/java-publish.gradle#L84. Since CircleCI [by default](https://circleci.com/docs/2.0/configuration-reference/#job_name) checks out the repo in a directory called `project`, Gradle picks that up as the default root project name. It's easily circumvented by setting the explicit root project name to `spotless` in `settings.gradle`. I've raised a related ticket [here](https://github.com/gradle/gradle/issues/15655) on Gradle.

**Comment by pzygielo** [comment]
Almost reported duplicate for this. This scm url is also used by dependabot in PR description. It results in

> Bumps [spotless-maven-plugin](https://github.com/diffplug/project) from 2.10.2 to 2.10.3.
> <details>
> <summary>Commits</summary>
> <ul>
> <li>See full diff in <a href="https://github.com/diffplug/project/commits">compare view</a></li>
> </ul>
> </details>
> <br />
