### ISSUE TITLE
[Gradle] Disable spotless for comments

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [diffplug/spotless#807]
Hi,

How I can disable spotless for any comment in my code?
Version: Gradle plugin

**Comment by nedtwigg** [comment]
Some formatters (e.g. eclipse) have settings which disable comment formatting, you'll have to look at the docs of the formatter itself (Spotless just acts as a switchboard).

One option is to use [`toggleOffOn('/*', '*/')`](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson), which would preserve everything between multiline C-style comments. You could adapt this to your language.
