### ISSUE TITLE
indentWithTabs removes leading single space

### ISSUE THREAD

**Issue by sormuras** [diffplug/spotless#81]
Having standard Javadoc comments, like:
```
/**
 * <h3>Logging Configuration</h3>
 *
...
```

After running...
```
spotless {
	java {
		googleJavaFormat('1.3') // indents with 2 spaces
		indentWithTabs(2)
	}
}
```
All Javadoc stars are in the fly-on-the-left-wall position:
```
/**
* <h3>Logging Configuration</h3>
*
...
```

See https://github.com/junit-team/junit5/compare/google_java_format#diff-65f0a88c2a9307f19525f2d3c03dc8f3 for a complete example.

**Comment by sormuras** [comment]
Remainding spaces are discarded here: https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/generic/IndentStep.java#L102

**Comment by jbduncan** [comment]
As a short term measure, how about a custom lazy Spotless task that applies `IndentStep` to all lines except those that start with ` *`.

**Comment by jbduncan** [comment]
Of course, this feature addition would be nice to have in the medium term. :)

**Comment by nedtwigg** [comment]
A short term fix is

```gradle
...
    indentWithTabs(2)
    replaceRegex 'Javadoc space indent', '^\\*', ' *'  // this regex might not be exactly right, but it's close
```

I'm hesitant to change IndentStep.  It is a possibly-breaking change in one of the oldest rules we've got.  The current implementation can catch bugs of the following sort:

```
\t    \t    Good
\t    \t    Good
\t    \t    _Oops (where _ = a space)
\t    \t    Good
```

The suggested change would break this case.  Given how easy the regex fix is, I'm inclined to not alter the behavior of IndentStep.

**Comment by jbduncan** [comment]
The regex `\n\*` seems to work when I use Ctrl+F in IntelliJ IDEA to find non-indented `*` in Javadoc comments. So maybe something like the following custom rule would work instead:
```gradle
indentWithTabs(2)
replaceRegex 'Javadoc space indent', '\n\*', ' *'
```

**Comment by jbduncan** [comment]
Oh no never mind, looks like JUnit 5's build.gradle actually already has a `replaceRegex` step that can do this and which you can steal @sormuras. :)

```gradle
replaceRegex 'class-level Javadoc indentation fix', /^\*/, ' *'
```

**Comment by jbduncan** [comment]
I've realised that the regex I mentioned above doesn't work for method javadocs (or other javadocs that are intended as a whole). The following steps seem to solve all problems:
```gradle
    googleJavaFormat '1.3'
    indentWithTabs 2
    replaceRegex 'class-level javadoc indentation fix', /^\*/, ' *'
    replaceRegex 'method-level javadoc indentation fix', /\t\*/, '\t *'
```

**Comment by MahatmaFatalError** [comment]
will there be an official fix anytime?

**Comment by vpavic** [comment]
@nedtwigg This really feels like something that should work out of the box. Virtually everyone who wants to use `indentWithTabs` and writes javadocs needs to configure those two `replaceRegex` statements.

**Comment by nedtwigg** [comment]
## Proposal 1 (bad idea, probably wouldn't merge a PR)

We have a mechanism for implicitly modifying license steps based on context, e.g. this is how we keep the license step from messing up `package-info.java`

https://github.com/diffplug/spotless/blob/3a845e9c1d8992b12636d680c4aa2e3949d71436/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java#L219-L225

You could add something like:

```java
if (steps.contains(::isGoogleJavaFormatStep) && steps.contains(::isIdentWithTabsStep)) {
  steps.add(replaceRegex 'class-level javadoc indentation fix', /^\*/, ' *')
  steps.add(replaceRegex 'method-level javadoc indentation fix', /\t\*/, '\t *')
}
```

I think that's okay, but not great because it's hard for users to opt out of.

## Proposal 2 (okay idea, would happily merge a PR)

A better solution would be to support something like this: `googleJavaFormat().indentWithTabs()`, which I would add roughly here

https://github.com/diffplug/spotless/blob/3a845e9c1d8992b12636d680c4aa2e3949d71436/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java#L154-L156

and it would look something like this

```java
public void indentWithTabs() {
  // needs to be terminal (returns void) because unlike the other methods in GoogleJavaFormatConfig, this is hard to undo. */
  indentWithTabs(2)
  replaceRegex 'class-level javadoc indentation fix', /^\*/, ' *'
  replaceRegex 'method-level javadoc indentation fix', /\t\*/, '\t *'
}

**Comment by vpavic** [comment]
Thanks for following up on this.

From the snippets you shared it appears to me that you're somehow conflating this issue with `googleJavaFormat` which shouldn't be the case as the problem is much more general.

Here's a minimal reproducer that only contains a `build.gradle` script:

```groovy
plugins {
	id("com.diffplug.spotless").version("6.1.0")
}

/**
 * A simple greeting task.
 */
abstract class GreetingTask extends DefaultTask {
	@TaskAction
	def greet() {
		println("hello from GreetingTask")
	}
}

tasks.register("hello", GreetingTask)

spotless {
	groovyGradle {
		indentWithTabs()
	}
}
```

```bash
$ ./gradlew spotlessCheck
> Task :spotlessGroovyGradleCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessGroovyGradleCheck'.
> The following files had format violations:
      build.gradle
          @@ -3,8 +3,8 @@
           }
           
           /**
          -·*·A·simple·greeting·task.
          -·*/
          +*·A·simple·greeting·task.
          +*/
           abstract·class·GreetingTask·extends·DefaultTask·{
           \t@TaskAction
           \tdef·greet()·{
  Run './gradlew :spotlessApply' to fix these violations.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 888ms
3 actionable tasks: 3 executed
```

Also, could you reopen the issue and label it as `bug` instead of `question`?

**Comment by jbduncan** [comment]
@vpavic, I could be wrong, but I interpreted @nedtwigg's **Proposal 2** as saying, "all Java/Groovy formatters, including 'google-java-format', which I'm just using as an example here". Or am I barking up the wrong tree, Ned? :)

**Comment by vpavic** [comment]
I see, thanks.

Hopefully that's the case - admittedly, I haven't been too much into the Spotless internals.

**Comment by jbduncan** [comment]
@vpavic I hope so too. I don't imagine it would be that hard to make a new `indentWithTabs()` method for all the Java/Groovy/Kotlin formatters that use a fixed number of spaces for indentation, like how google-java-format predictably uses either 2 spaces or 4 spaces depending on which mode it's using. But I'm not sure about more flexible formatters like Eclipse.

I'm also assuming that implementing an `indentWithTabs` method like this would work, and that `numberOfSpacesUsedForIndentation` is easy enough to calculate:

```java
public void indentWithTabs() {
  int numberOfSpacesUsedForIndentation = ...;
  indentWithTabs(numberOfSpaces)
  replaceRegex 'class-level javadoc indentation fix', /^\*/, ' *'
  replaceRegex 'method-level javadoc indentation fix', /\t\*/, '\t *'
}
```

**Comment by nedtwigg** [comment]
>  conflating this issue with googleJavaFormat ... the problem is much more general.

Most of the other formatters (or at least eclipse and greclipse) allow you to configure indentation to use tabs in the first place, so I did see this as a GJF-specific usecase.

But you raise a good point, C-style multiline comments are not unusual, we should "just work" for that case. I'm going to open another issue for that.

**Comment by nedtwigg** [comment]
I don't plan to implement #1070, but happy to merge a PR that does.
