### ISSUE TITLE
Spotlesscheck failing on linux pipeline

### ISSUE THREAD

**Issue by matte23n** [diffplug/spotless#818]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem:
- I just switched from gradle version 3.24.2 to 3.24.3 to get the fixed paddedCell problem. Now, i have my problem solved but i have another problem. On my local machine everything is working fine but on the pipeline from gitlab it fails, telling me that all files have format violations. This wasn't happening before version update.
- [ ] gradle or maven version
- gradle
- [ ] spotless version
- 3.24.2
- [ ] copy-paste your full Spotless configuration block(s)
```
 java {
                target project.fileTree(project.rootDir) {
                    include '**/*.java'
                    exclude '**/generated/**', '**/generated-src/**'
                }
                trimTrailingWhitespace()
                indentWithSpaces()
                endWithNewline()
                removeUnusedImports()
                importOrder 'java', 'javax', 'org', 'com', 'it'
                eclipse().configFile("${project.rootProject.buildDir}/conf/javafmt.xml")
            }
```
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
```
Execution failed for task ':war-servizi-desk:spotlessJava'.
> The following files had format violations
Violations also present in 66 other files.
Run 'gradlew spotlessApply' to fix these violations.
```

**Comment by matte23n** [comment]
Oh yes, i've tried it, i've tried using version 4.5.1 because i'm using gradle 4.10, but with that version i'm getting this error on my local machine when i try to do spotlessApply and i don't know ho to solve that, can you help me so i can try upgrade and make things work well?

```
Spotless error! All target files must be within the project root. In project X
root dir: X
target: Y\build\spotless\spotlessJava\... .java
```
where X and Y stands for the two gradle subproject names he is trying to format.

Thanks

**Comment by nedtwigg** [comment]
Look at the build.gradle in project X. It must have a target along the lines of `target rootProject.files('**/*.java')`, which means that Project X is trying to format files which are inside Project Y. Only Project Y is allowed to format files inside Project Y.

Hint: might need to change `**/*.java` into `src/**/*.java`. Will result in a big speedup.

**Comment by matte23n** [comment]
Maybe can it be because in my project X build.gradle i have this?
```
dependencies {
    compile project('Y')
}
```
And if so, how can i tell spotless to not format files inside that project? My config is the one i posted at the beginning, and it is generic because i have it in a library so all projects can reuse it.

Oh, i've also tried changing `**/*.java` into `src/**/*.java` but it's not working, i think that's because of the subproject structure, in fact when i run the spotlessCheck (using `**/*.java`) directly from the subproject it says me:

```
The following files had format violations:
      :subprojectname\src\
```
and not directly `src\`.

Do i need to configure something for subprojects in spotless or is it kind of a bug?

**Comment by matte23n** [comment]
I think i've managed to do it, i've changed this

```
target project.fileTree(project.rootDir) {
            include '**/*.java'
            exclude '**/generated/**', '**/generated-src/**'
 }
```

to just this `targetExclude '**/generated/**', '**/generated-src/**'`. Is it correct? I think the problem was in `project.fileTree(project.rootDir)`

**Comment by nedtwigg** [comment]
Great! Last tip: you can do `target 'blah'` and also `targetExclude 'blah'`. So if you just want the default target, all you need to do is `targetExclude '**/generated/**'`
