### ISSUE TITLE
spotlessJavaCheck passes even if a file clearly violates the rules

### ISSUE THREAD

**Issue by hakanai** [diffplug/spotless#819]
Summary of problem:

1. We configured Spotless initially with just some basic rules to trim trailing whitespace. (Config below)
2. I edited one of our .java files so that it definitely had trailing whitespace not trimmed.
3. When I run `./gradlew spotlessJavaCheck`, the task _succeeds_, but I expected it to fail.

Tried so far:
- I tried reordering imports to the wrong order as well, and get more or less the same result.
- I tried adding `--debug` but don't see anything interesting in the output.
- Since it's a multi-project build, I tried wrapping allprojects around the spotless config, but it just gives me an error about defining `importOrder` more than once.
- I tried adding the exact same config to a single project build, and that _did_ work. So **whatever is going on here is definitely to do with it being a multi-project build.**

Versions:
- Gradle 6.8
- Spotless 5.11.0
- macOS 10.15.7 (Catalina)

Configuration:

```
% cat ../shared/gradle/spotless.gradle
buildscript {
    repositories {
        maven {
            url "${artifactory_contextUrl}/plugins-release"
            credentials {
                username = artifactory_user
                password = artifactory_password
            }
        }
    }
    dependencies {
        classpath 'com.diffplug.spotless:spotless-plugin-gradle:5.11.0'
    }
}

// Because we put the configuration in a separate file to the main build,
// we have to apply the plugin using the classname instead of the ID.
apply plugin: com.diffplug.gradle.spotless.SpotlessPlugin

spotless {
    // TODO: We want to use this too, but some other bug related to git worktrees prevents it
    // ratchetFrom 'origin/master'

    java {
        importOrder('java', 'javax', '', 'com.acme')
        removeUnusedImports()
        trimTrailingWhitespace()

        // To set up next: prettier()
    }
}
```

**Comment by nedtwigg** [comment]
You need to tell Spotless which files to format with `target 'src/**/*.java'` or something like that. If you applied the `java` plugin then Spotless can pick up the sources from that, but maybe you're using android or some other non-vanilla setup.

**Comment by hakanai** [comment]
Although we are just using the java plugin at the moment, I think it being a multi-project is probably enough to trip it up, and perhaps it might even have to be `'*/src/**/*.java'` to match the files in the subprojects.

**Comment by hakanai** [comment]
Condensed setup: https://github.com/hakanai/spotless-819-repro

**Comment by nedtwigg** [comment]
https://github.com/hakanai/spotless-819-repro/blob/70ea887ba3007ca15ba219501d49389dc5c4cc40/build.gradle#L8-L12

You aren't applying Spotless to any subprojects. Move the "apply spotless" into the `allprojects`.
