### ISSUE TITLE
Sonarqube ceTaskUrl from report-task.txt status "PENDING"

### ISSUE THREAD

**Issue by compilead** [diffplug/spotless#820]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
Using ceTaskUrl from report-task.txt status of sonar file to check whether api of quality gate is updated or not.
- [x] gradle or maven version
gradle-5.6
- [x] spotless version
spotless_version = '5.9.2'
- [ ] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
.
.
.
.
.
.
16:12:31  "PENDING"
16:12:33    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
16:12:33                                   Dload  Upload   Total   Spent    Left  Speed
16:12:33  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   369  100   369    0     0   2648      0 --:--:-- --:--:-- --:--:--  2654
16:12:33  "PENDING"
16:12:35    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
16:12:35                                   Dload  Upload   Total   Spent    Left  Speed
16:12:35  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   369  100   369    0     0   2698      0 --:--:-- --:--:-- --:--:--  2713
16:12:35  "PENDING"
16:12:37    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
16:12:37                                   Dload  Upload   Total   Spent    Left  Speed
16:12:37  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   369  100   369    0     0   2732      0 --:--:-- --:--:-- --:--:--  2753
16:12:37  "PENDING"
16:12:38  Cancelling nested steps due to timeout

- [x] copy-paste your code block:

source build/sonar/report-task.txt
--
  | curl -u "$TOKEN": "$ceTaskUrl" > current_run_status.json
  | status=$(jq .task.status current_run_status.json) \|\| ( echo "Not a json file, please check. Exiting.." && exit 1 )
  | while [ "$status" != '"SUCCESS"' ]
  | do
  | curl -u "$TOKEN": "$ceTaskUrl" > current_run_status.json
  | status=$(jq .task.status current_run_status.json)
  | echo "$status"
  | sleep 2
  | done

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment]
Spotless doesn't have anything to do with `build/sonar/report-task.txt`. Did you open issue on wrong repo?
