### ISSUE TITLE
Noticeable performance regression after adding targetExclude filtering

### ISSUE THREAD

**Issue by Egorand** [diffplug/spotless#833]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] gradle or maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

Gradle: 6.8.3
Spotless: 5.7.0
OS: macOS 11.2.3 (20D91)

I'm running `spotlessJavaCheck` task in a large Gradle project. With the following configuration, the task executes in around 30s on my machine:

```groovy
spotless {
  java {
    target("**/*.java")
    licenseHeader '// Copyright Square, Inc.'
  }
}
```

To filter out generated code under `build` directories, the configuration has been updated to the following, and the execution time jumped to around 5m:

```groovy
spotless {
  java {
    target("**/*.java")
    targetExclude(
      "**/build/**/*.java",
      "**/build/tmp/**/*.java",
    )
    licenseHeader '// Copyright Square, Inc.'
  }
}
```

I also tried the following configuration but the result is similar:

```groovy
spotless {
  java {
    target("**/src/**/*.java")
    licenseHeader '// Copyright Square, Inc.'
  }
}
```

So it seems that directory filtering slows down the task significantly. I'm curious if there's a proper way to configure the plugin to only look for files under `src` directories.

**Comment by Egorand** [comment]
It's also worth mentioning that our `kotlin` part of the configuration includes filters for specific directories:

```groovy
spotless {
  kotlin {
    target("**/*.kt")
    targetExclude(
      "protos/src/**/*.kt",
      ...
    )
  }
}
```

Which doesn't seem to affect performance. The issue seems to be specifically with wildcard excludes, such as `**/build/**/*.kt`.

**Comment by nedtwigg** [comment]
I highly recommend nuking `**/*.blah` and instead using `src/**/*.blah`. In very old Spotless versions, our example code showed how the root project could format files for the entire multiproject build. That was a bad idea, and interacts very badly with caching. Making each project responsible formatting only itself works much better. With `**/*`, you have one project accidentally or intentionally formatting files in child projects, which is bad for performance.

**Comment by Egorand** [comment]
That's a good idea, thanks!
