### ISSUE TITLE
Show scalafmt configuration errors

### ISSUE THREAD

**Issue by loveleif** [diffplug/spotless#837]
Errors in scalafmt configuration files cause an exception in spotless that does does not contain any information about what went wrong. Scalafmt provides this information and this is a request to bubble it up in spotless.

For example, a scalafmt configuration that contains an invalid field will result in an exception in spotless like this:

 ```
java.lang.reflect.InvocationTargetException
    ...
Caused by: java.util.NoSuchElementException: Either.right.value on Left
    at scala.util.Either$RightProjection.get(Either.scala:453
    ...
```

**Comment by nedtwigg** [comment]
Released in `plugin-maven 2.10.0` and `plugin-gradle 5.12.0`.
