### ISSUE TITLE
[Question] : How to allow annotation in multiple lines?

### ISSUE THREAD

**Issue by tivrfoa** [diffplug/spotless#839]
Hi,

If this is not the place to ask this question, could you please point me to the right place?

I would like to use annotation in multiple lines, like the example below, but it's complaining that it should be on the same line.
````java
	@ApiOperation(value = "Lista transações, bla bla bla bla bla bla bla blabla bla bla blabla bla bl.",
			notes = "Lista transações, bla bla bla blabla bla bla blabla bla .",
			protocols = "Http,Https", httpMethod = "Post", response = ItemTimeline.class, responseContainer = "List")
````

I'm using eclipse:
````xml
						<eclipse>
							<version>4.13.0</version>
							<file>${basedir}/eclipse-formatter.xml</file>
						</eclipse>
````

And I have this in settings:
````xml
        <setting id="org.eclipse.jdt.core.formatter.keep_annotation_declaration_on_one_line" value="one_line_if_empty"/>
````

I also tried with `one_line_never` and without this setting, but no success.

Full settings: https://gist.github.com/tivrfoa/95b1b13cc3ec9c59f97dab2b4dbefc47

**Comment by nedtwigg** [comment]
I don't know the answer, you might need to dig around the eclipse.org website or sourcecode. Spotless is just a switchboard for other formatters.
