### ISSUE TITLE
Add JVM-based JSON formatter

### ISSUE THREAD

**Issue by jamietanna** [diffplug/spotless#850]
It would be good to have a JVM-only version of JSON formatters, without needing to have `prettier` installed.

I'd be happy to contribute this, for Gradle - would it be best to raise a PR to add this formatter, or shall I create it as a separate project?

**Comment by nedtwigg** [comment]
JVM-only json formatter is very welcome! If you can implement it without any third-party dependencies, then it can live in `lib` like [the sql formatter](https://github.com/diffplug/spotless/tree/main/lib/src/main/java/com/diffplug/spotless/sql).

If it needs just third-party dependencies then it should live in lib-extra.

https://github.com/diffplug/spotless/blob/59173b055ed132b9df05445909db248f4415c1d8/lib-extra/build.gradle#L11-L18

If the dependencies you need cause a lot of conflicts (ala #587), then we can always pull it out into a third-party lib later on.
