### ISSUE TITLE
2 empty lines on java google import

### ISSUE THREAD

**Issue by clembo590** [diffplug/spotless#875]
Spotless maven plugin, does not format the import section correctly: it adds an empty line.

- [ 2.11.1] gradle or maven version
- [mac os ] operating system and version

I have created a github repo that is formatted with the google 1.10.0 formatter to reproduce/show the issue.
This is the command line I used to format the code in the repo. (which has nothing to do with spotless)
> java   --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED   --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED   --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED   --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED   --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED  -jar /PATH_TO_YOUR_GOOGLE_JAR/google-java-format-1.10.0-all-deps.jar -r $(git ls-files|grep \.java$)

this is the url of my repo: (and the code is formatted by the google-java-format-1.10.0-all-deps.jar)
https://github.com/clembo590/issue_spotless.git

if you `git clone` the repo and then run 

> mvn com.diffplug.spotless:spotless-maven-plugin:2.11.1:apply

An additional line is added at the top of the file.

Is this a bug ? is there any configuration of the plugin that will produce the exact same result as the real google-java-format-1.10.0-all-deps.jar ?

<img width="1106" alt="Screenshot 2021-06-08 at 07 23 30" src="https://user-images.githubusercontent.com/10899818/121128021-ff292400-c82a-11eb-8fc3-79b75baaad61.png">

**Comment by nedtwigg** [comment]
> Is this a bug?

Maybe, but regardless it is probably not worth fixing. We've had the GJF integration for a very long time, we just call the library's public methods:

https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java

It could be that if we call them in a different order, then we would get the same behavior. If so, then that's what we should do. But at this point with thousands of spotless users using GJF, I would consider it a regression if all of their files had to change newlines. The point of Spotless is to spend less time on formatting, not more.

> is there any configuration of the plugin that will produce the exact same result

It is *definitely* a bug from the perspective of "I'm using GJF via commandline, and I want to switch to Spotless and get the same result. One way to maybe get this is to add the `removeUnusedImports` step. That also uses GJF under the hood, it's possible that the jar method does the import thing by default. 

You could also use a [regex rule](https://github.com/diffplug/spotless/tree/main/plugin-maven#generic-steps), something simple like `replace('\n\n', '\n')`, or something more complicated like `replaceRegex('^package (.+);\n\n', 'package $1;\n')`.
