### ISSUE TITLE
Gradle 7 error

### ISSUE THREAD

**Issue by hannesa2** [diffplug/spotless#880]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem **You must declare outputs or use `TaskOutputs.upToDateWhen()` when using the incremental task API**
- [ ] gradle or maven version **7.0.2**
- [ ] spotless version **3.24.2**
- [ ] operating system and version **macOS** on Github actions
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible https://github.com/hannesa2/appactions-common-biis-kotlin/pull/1/checks?check_run_id=2863510472
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/3314607/122631983-f6104080-d0cf-11eb-8fcc-8a544c83d691.png">

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment]
Update to latest Spotless.

**Comment by nedtwigg** [comment]
https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md

**Comment by Ritesh9828** [comment]
> Update to latest Spotless.

Thank you so much.
