### ISSUE TITLE
search upwards for prettierrc

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#887]
I tried doing `prettier().configFile(".prettierrc.yml")` but because I'm using a `buildSrc` plugin for a bunch of modules with varying depths it does find it. So it would be convenient if this could search upwards until it does, or maybe load the default one without a `configFile` call, this works in a kotlin file

```kt
    prettier().configFile(rootDir.toPath().resolve(".prettierrc.yml"))
 ```

**Comment by nedtwigg** [comment]
You can also do `rootProject.file('blah')`. Scanning the filesystem takes time, builds are faster if the user specifies exactly what they want. They are also more repeatable, in case a build later becomes checkout as a submodule of some other build, it would be frustrating for the formatting to change based on a parent directory outside of the repository.

This can be implemented outside of Spotless if you still want it `.configFile(searchUpDirectoryTreeFor(project, '. prettierrc.yml'))`

**Comment by xenoterracide** [comment]
could maybe use an example in the documentation of how to deal with a multimodule build with one config file.
