### ISSUE TITLE
Scala: detect unused imports

### ISSUE THREAD

**Issue by jduan** [diffplug/spotless#892]
AFAICT, "spotlessCheck" doesn't fail if there are unused imports for Scala code. Can this be supported?

**Comment by nedtwigg** [comment]
I believe ScalaFmt does not support this: https://github.com/scalameta/scalafmt/issues/722

ScalaFix does support removing unused imports, and there is an abandoned PR which adds ScalaFix support for Spotless: #591.

**Comment by jduan** [comment]
Thank you for your quick response. I'll wait for #591 then. I don't have the chops to add ScalaFix support.
