### ISSUE TITLE
Spotless and Kotlin 1.5.21

### ISSUE THREAD

**Issue by evertsmits** [diffplug/spotless#896]
Hello, it seems like Kotlin 1.5.21 breaks the following task:
./gradlew spotlessApply (at least for me). 

The console output remains stuck at :spotlessJava or :spotlessKotlin. Thus the task never completes

**gradle version**
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
**spotless version**
const val spotless = "5.12.5"
**operating system and version**
macOS Catelina
Version 10.15.7
**spotless block**
apply plugin: "com.diffplug.spotless"
//Make sure to also apply spotlessCheck to your CI build

spotless {
    java {
        target '**/*.java'
        targetExclude "caches/**", "wrapper/**"
        googleJavaFormat().aosp()
    }
    kotlin {
        target '**/*.kt'
        targetExclude "caches/**", "wrapper/**"
        ktlint()
    }
    kotlinGradle {
        target '**/*.gradle.kts'
        targetExclude "caches/**", "wrapper/**"
        ktlint()
    }
    groovyGradle {
        target "**/*.gradle"
        targetExclude "caches/**", "wrapper/**"
        trimTrailingWhitespace()
        endWithNewline()
    }
    format 'misc', {
        target '**/*.md', '**/.gitignore'
        targetExclude "caches/**", "wrapper/**"
        indentWithSpaces()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

// Adds spotlessCheck before your commit
task installGitHooks(type: Copy) {
    from new File(rootProject.rootDir, 'pre-commit')
    into { new File(rootProject.rootDir, '.git/hooks') }
    fileMode 0777
}

build.dependsOn installGitHooks

Sorry I am not in a position to share the code base. This is under NDA.

**Comment by nedtwigg** [comment]
You are using `ktlint()` which uses the default version, which might be old. Try looking up the latest version of ktlint, then doing `ktlint('1.2.3')`.

**Comment by evertsmits** [comment]
Will do tomorrow!

**Comment by evertsmits** [comment]
Issue remains. I changed ktlint() to ktlint("0.41.0").

**Comment by evertsmits** [comment]
Also running ./gradlew spotlessKotlin does not give any issue. The issue only appears if I run spotlessApply.

**Comment by nedtwigg** [comment]
I just updated your question with "triple-tick code fences"  ` ``` ` which makes it easier to read.

Doing `target '**/*.blah'` is very slow. It will be much faster if you do `target 'src/**/*.blah'`. If it's multi-module, put it all in `spotless.gradle` and do `apply from: rootProject.file('gradle/spotless.gradle')`
