### ISSUE TITLE
Remove *.java files from default Maven Groovy formatting

### ISSUE THREAD

**Issue by Slooz** [diffplug/spotless#902]
This is the default `includes` of Maven Groovy:
```xml
<includes>
  <include>src/main/groovy/**/*.groovy</include>
  <include>src/test/groovy/**/*.groovy</include>
  <include>src/main/java/**/*.java</include>
  <include>src/test/java/**/*.java</include>
</includes>
```

I'm not sure why Maven Groovy is configured to format .java files. At first, it stripped all the semicolons from my .java files. Next, I couldn't figure out why `mvn spotless:apply` wasn't working, when it turned out that Groovy formatting kept overwriting the .java files immediately after Java formatting.

**Comment by nedtwigg** [comment]
Fixed in `2.19.0`.
