### ISSUE TITLE
User blocked and issue closed for bad language

### ISSUE THREAD

**Issue by shihongDeng** [diffplug/spotless#914]
If you are submitting a **bug**, please include the following:

- [ ] summary of problem
- [ ] gradle or maven version
- [ ] spotless version
- [ ] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

**Comment by jbduncan** [comment]
Hi @shihongDeng,

Is there a problem with Spotless that you're suffering from? We'd be more than happy to help of you'd be willing to provide us with more info.

**Comment by jbduncan** [comment]
Thank you, @nedtwigg. 👍
