### ISSUE TITLE
Provide rule being violated when check fails (mvn spotless:check)

### ISSUE THREAD

**Issue by philipwhiuk** [diffplug/spotless#938]
Here's the output I get running `spotless:check`

```
Caused by: org.apache.maven.plugin.MojoExecutionException: The following files had format violations:
    src/main/java/company/package/File.java
        @@ -1,201 +1,201 @@
        -package company.package.file;\r\n
        -\r\n
        -import java.util.zip.CRC32;\r\n
        -import java.util.zip.DataFormatException;\r\n
        -import java.util.zip.Inflater;\r\n
        -\r\n
        [....]
        ... (354 more lines that didn't fit)
Violations also present in:
       ....
```

The problem is that this doesn't tell me *why* it failed. The snippet is useful, but it's still not telling you what rule is being tripped up on (as tools like `eslint` do).

This is a problem because currently when I run: `spotless:check` locally it passes. But ran on my CI server it fails. Knowing the actual check causing the issue would be very useful.

**Comment by nedtwigg** [comment]
> doesn't tell me why it failed.

Spotless doesn't and won't. Spotless is just a list of `Function<String, String>` which turn a file into its formatted form. That's all. You run `spotless:apply` and it will fix it. The snippet it is showing you is a diff, and because it's such a long diff I'm betting the problem is line-endings - the file has `\r\n` in your WC and your Spotless config is defining `\n` to be the correct line ending.

> locally it passes. But ran on my CI server it fails

I'm guessing this is going to be a line-ending issue. Post your configuration block and we can help.

**Comment by cmohankumar** [comment]
@nedtwigg - I am having a similar issue. 
Local Windows PC Spotless apply would succeed with no issues.
However when i run thru CI pipeline its failing with similar error as posted by the OP.

Here's my spotless config

` <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.43.0</version>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>compile</phase>
          </execution>
        </executions>
        <configuration>
          <java>
            <includes>
              <include>src/main/java/**/*.java</include>
              <include>src/test/java/**/*.java</include>
            </includes>
            <removeUnusedImports/>
            <googleJavaFormat>
              <version>1.17.0</version>
              <style>GOOGLE</style>
              <reflowLongStrings>true</reflowLongStrings>
            </googleJavaFormat>
            
            <endWithNewline/>
            <lineEndings>UNIX</lineEndings>
            <indent>
              <tabs>true</tabs>
              <spacesPerTab>2</spacesPerTab>
            </indent>
          </java>
        </configuration>
      </plugin>`

pls suggest how to resolve my CI spotless format error issue.
