### ISSUE TITLE
Allow multiple calls to `target` or `targetExclude`

### ISSUE THREAD

**Issue by RinOrz** [diffplug/spotless#939]
Sometimes I need to set up all projects in buildSrc or elsewhere, and then override these settings in the project.

Maybe `addTarget`, maybe save the parameters in the list, and then handle them uniformly in `FormatExtension.setupTask`

**Comment by nedtwigg** [comment]
Happy to discuss this further, but probably a wontfix.

You can do a per-project `target` or `targetExclude` already. We have gotten *so many* feature requests and user confusion around target over the years.  It simplifies things greatly to remove mutable state, and it complicates them to add mutable state.  Very unlikely that we will add more state.
