### ISSUE TITLE
spotless loads dependency from project dependencies

### ISSUE THREAD

**Issue by cal101** [diffplug/spotless#99]
The following dependency spotless-ext-eclipse-jdt-4.6.1.jar is loaded from the projects repositories
instead of the buildscript repositories when using the java formatter.

Is that expected behavior?
I expected not having to change the project repositories.

**Comment by nedtwigg** [comment]
I think that is the expected behavior, but I agree that it is probably a bug.  This is the code in question:

https://github.com/diffplug/spotless/blob/master/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleProvisioner.java

Happy to merge a PR from anyone which addresses this issue.

**Comment by cal101** [comment]
Sure that this is the place? I can't check better at the moment but this looks like your place is adding the project dependencies to whatever. 
My problem seems more related to some place requesting the extra dependency from the wrong repositories list. Or do you consider your place one side and the requesting place the other side that both needs to be fixed?

**Comment by nedtwigg** [comment]
Yep, that's definitely the place.  In your spotless config block, you're building up a set of steps that you need to format your code.  Those steps then tell Spotless "I need these maven coordinates to do my job", through the [`Provisioner`](https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/Provisioner.java) API, which is implemented by `GradleProvisioner`.  The only place that needs to be changed is definitely GradleProvisioner, but I'm not sure how it should be changed.

**Comment by cal101** [comment]
I take a look at it tomorrow.

**Comment by cal101** [comment]
Anything missing?

**Comment by cal101** [comment]
Fixed with merge.

**Comment by nedtwigg** [comment]
Published in 3.3.0
